### ISSUE TITLE
duplicate user tile in IOS device 

### ISSUE THREAD

**Issue by vivekMss** [jitsi/jitsi-meet#12159] opened 2022-09-12 10:48 UTC
### Description:

when IOS device user enter's in room n there is two user's already inside the room on android user n another web.

### Steps to reproduce:

1.  open the android app n create one fresh room n enter 
2.  open web url jitsimeet n enter new user
3.  now lastly open the ios device n when the user enter then anyone user tile would be duplicated.

### Expected behavior:
show only 3 user's tile

### Actual behavior:
show's four tiles while only 3 user's are there.
attaching the screenshot as well

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: Code version from 2.0.7648 version code n web url https://meet.jit.si/
- Operating System:

while in web:

### Additional information:
![Screenshot 2022-09-12 at 4 17 43 PM](https://user-images.githubusercontent.com/112181946/189635371-11507ab3-f3ba-4062-80b2-c11bc4537994.png)

in IOS device:

![image](https://user-images.githubusercontent.com/112181946/189635239-d00bb26e-8ca1-4c8e-a332-e9132241004d.png)

**Comment by saghul** [comment] 2022-09-12 11:08
Thanks for the report! Do you have steps to reliably reproduce this?

**Comment by vivekMss** [comment] 2022-09-12 11:12
> Thanks for the report! Do you have steps to reliably reproduce this?

yeah the main requirement is android phone user should be entered first n one more apart from the ios 
and then on 3rd position iOS device user should enter

**Comment by vivekMss** [comment] 2022-09-13 11:49
> Thanks for the report! Do you have steps to reliably reproduce this?

can i get the fix on urgent basis or jitsi team is thinking of new updated release as well

**Comment by saghul** [comment] 2022-09-13 14:21
We haven't fixed this ourselves yet.

**Comment by saghul** [comment] 2022-09-13 14:26
I tried to reproduce this just now, but I couldn't. This is what I did:

- Enter a meeting on Android
- Enter the same meeting on web
- Enter the same meeting on iOS

I did not get a duplicated tile.

Can you reproduce this every time?

I am using the latest iOS and Android versions (22.5.1) and meet.jit.si as the server.

**Comment by tmoldovan8x8** [comment] 2022-09-14 07:42
Hi  @vivekMss I have been trying to reproduce this issue, but nothing so far. Are you using the latest iOS/Android apps from the store? Not sure what 2.0.7648 is. The latest betas should be 22.5.1.

**Comment by vivekMss** [comment] 2022-09-15 06:00
> I tried to reproduce this just now, but I couldn't. This is what I did:
> 
> * Enter a meeting on Android
> * Enter the same meeting on web
> * Enter the same meeting on iOS
> 
> I did not get a duplicated tile.
>  avoid using the playstore apps
> Can you reproduce this every time?
> Yes
> I am using the latest iOS and Android versions (22.5.1) and meet.jit.si as the server.
i'm reporting regarding this
https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_7648
release n installing n running the application on both platforms

**Comment by saghul** [comment] 2022-09-15 07:24
> i'm reporting regarding this
> https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_7648
> release n installing n running the application on both platforms

You are running that on the server or also on the mobile clients? That is NOT a mobile release tag.

**Comment by vivekMss** [comment] 2022-09-15 07:37
> > i'm reporting regarding this
> > https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_7648
> > release n installing n running the application on both platforms
> 
> You are running that on the server or also on the mobile clients? That is NOT a mobile release tag.

can you please share the latest stable version. for the mobile and web

**Comment by saghul** [comment] 2022-09-15 08:34
https://jitsi.github.io/handbook/docs/releases

**Comment by vivekMss** [comment] 2022-09-15 09:12
Hi, @saghul @tmoldovan8x8 
I tried with release version 2.0.7648 and i am able to reproduce the issue in this again and again. 

Steps are : 
1. Join the room from with url: https://meet.jit.si/jtest1
2. Install the Release version build 2.0.7648 Android and iOS apps in respective devices. 
3. After that same room "jtest1" from Android
4. And At last when i join the same room "jtest1" with iOS device, show

https://user-images.githubusercontent.com/112181946/190364809-dff3d1c7-9eda-48fe-a008-ee576f90362c.mp4

ing me 2 android users on all platforms. 

Video for reference : 

We are using the Release version 2.0.7648 and getting the duplicate tile issue every time.

**Comment by saghul** [comment] 2022-09-15 09:20
Sorry, it looks like we are not understanding each other. 



> 2\. Install the Release version build 2.0.7648 Android and iOS apps in respective devices.

DO NOT DO THIS.

"2.0.7648" is NOT a mobile release. You can find links to mobile app releases here: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-APPS.md and sdks here: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md

You are taking a WEB release tag and testing mobile apps with the same commit. While this should generally work, it need not be the case, you have to build a proper mobile release tag.

**Comment by vivekMss** [comment] 2022-09-15 16:41
> 

Thank you so much but there are two different sdks but i want both in react-native so can i choose anyone ..?

**Comment by vivekMss** [comment] 2022-09-15 16:46
> Sorry, it looks like we are not understanding each other.
> 
> > 2. Install the Release version build 2.0.7648 Android and iOS apps in respective devices.
> 
> DO NOT DO THIS.
> 
> "2.0.7648" is NOT a mobile release. You can find links to mobile app releases here: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-APPS.md and sdks here: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md
> 
> You are taking a WEB release tag and testing mobile apps with the same commit. While this should generally work, it need not be the case, you have to build a proper mobile release tag.

same issue persist with these sdk build as well

steps:
1. Android user creates room 
2.  web user enters
3.  iOS user enter n android user or web user's tile got duplicated

**Comment by vivekMss** [comment] 2022-09-16 04:46
Hi,
@saghul  @tmoldovan8x8 
there something i noticed something while going into participant screen
screenshot attached:


![1663303482493](https://user-images.githubusercontent.com/112181946/190558584-c484e8d8-300c-46b7-8a48-a22d695a251b.JPEG)

**Comment by saghul** [comment] 2022-09-16 05:39
We have not been able to reproduce this with the provided steps, sorry.

**Comment by vivekMss** [comment] 2022-09-19 11:38
> We have not been able to reproduce this with the provided steps, sorry.

Can you help me giving me the file name or function name so that i can debug it n will report you back

**Comment by vivekMss** [comment] 2022-09-20 07:41
@saghul  && @tmoldovan8x8 
Hello,

I have debugged something n found that 
react/features/filmstrip/actions.any.js
/**
 * Sets the list of the reordered remote participants based on which the visible participants in the filmstrip will be
 * determined.
 *
 * @param {Array<string>} participants - The list of the remote participant endpoint IDs.
 * @returns {{
        type: SET_REMOTE_PARTICIPANTS,
        participants: Array<string>
    }}
 */
export function setRemoteParticipants(participants: Array<string>) {
    console.log("setRemoteParticipants ::::", participants);
    return {
        type: SET_REMOTE_PARTICIPANTS,
        participants
    };
}

through this the participants are getting duplicated at some point

so What i have done id:

export function setRemoteParticipants(participantsParam: Array<string>) {
    let participants = Array.from(new Set(participantsParam))
    return {
        type: SET_REMOTE_PARTICIPANTS,
        participants
    };
}

**Comment by saghul** [comment] 2022-09-20 08:02
Interesting find! Have you managed to track down where `setRemoteParticipants` is dispatched with the duplicate? That fix / hack will only masquerade the issue...

**Comment by vivekMss** [comment] 2022-09-20 09:53
> Interesting find! Have you managed to track down where `setRemoteParticipants` is dispatched with the duplicate? That fix / hack will only masquerade the issue...

sort of :

react/features/filmstrip/functions.any.js

this is the file where this action has been dispatched so don't know whether something is happening in any of these functions or it's getting the prop from some other state which make the duplicate tiles

**Comment by vivekMss** [comment] 2022-09-22 13:17
@saghul   can i get to know when will be the next update coming..
but please do point out this issue or apply my solution or some other way :)
Thank you

**Comment by saghul** [comment] 2022-10-25 10:24
This has been fixed in SDK 6.2.2.

**Closed by saghul** 2022-10-25 10:24 UTC
