### ISSUE TITLE
Screen sharing in Chrome doesn't work if more then 2 users in a room

### ISSUE THREAD

**Issue by contentadore** [jitsi/jitsi-meet#3878] opened 2019-02-09 18:28 UTC
Our team has been using Jitsy Meet for 7 months. And we like it. It's great!
But for the last 3 weeks, screen sharing in Chrome doesn't work if more then 2 users in a room.
Could you help me?

Chrome extension - https://github.com/jitsi/jidesha were upload to Google Web Store
It worked before, but the last 3 weeks we see this error https://i.imgur.com/1zF0GEk.jpg instead of screen sharing

Server:
Amazon AWS EC2
Ubuntu 16.04

Firewall Amazon
Custom UDP Rule | UDP | 10000 - 20000 | 0.0.0.0/0 |  
Custom UDP Rule | UDP | 10000 - 20000 | ::/0
HTTPS | TCP | 443 | 0.0.0.0/0 |  
HTTPS | TCP | 443 | ::/0
HTTP | TCP | 80 | 0.0.0.0/0 | 
HTTP | TCP | 80 | ::/0

Logs:
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/2848135/jicofo.log)

**Comment by damencho** [comment] 2019-02-09 22:01
Are you using latest stable? Did you test the same scenario on meet.jit.si?

**Comment by damencho** [comment] 2019-02-10 11:20
@virtuacoplenny was able to reproduce it and gave me steps to reproduce it and I was able to do so on meet and beta. Seems there is a bug in the bridge we will be looking at it.

There is a workaround though, at least in the steps we follow to reproduce it. The problem is if the participant that will screenshare had never turned on video before screensharing. If the participant turns on the camera for a brief moment and then start screensharing it works.

Thank you for the report.

**Comment by contentadore** [comment] 2019-02-10 21:13
Ok. Thanks for the answer.

> Are you using latest stable?

Yes, it's stable. I followed by the instruction https://jitsi.org/downloads/ubuntu-debian-installations-instructions/

> Did you test the same scenario on meet.jit.si?
> If the participant turns on the camera for a brief moment and then start screensharing it works.

We'll try it. Hope it helps.

**Comment by webintoit** [comment] 2019-02-11 13:53
![image](https://user-images.githubusercontent.com/5518513/52567500-274c1800-2e15-11e9-8a71-2d8c2af0a207.png)
Screensharing -> video onversion is error prone.

**Comment by damencho** [comment] 2019-02-11 14:00
@webintoit is this with the latest stable? I'm not able to repro any of these on meet.jit.si?

**Comment by webintoit** [comment] 2019-02-11 14:12
There is local deployment with `jvb 1095 / ljm latest`. Seems like error is happening randomly (unable to determine the case) when switch between `screensharing ( new getDisplayMedia flow )` / and standard camera. Sometimes some users unable to see screensharing / camera, sometimes this error can be catched. Also, by some test reports, It is not reproducible with 'extension based screensharing'.

**Comment by gpolitis** [comment] 2019-02-11 15:28
Most likely screen-sharing will be fixed by https://github.com/jitsi/jitsi-videobridge/pull/755

**Comment by insightsan** [comment] 2019-02-14 02:37
Seems to be mostly fixed now, I can start a screensharing session with 3 people without having problems anymore. Thanks for your hard work @gpolitis.

**Closed** 2019-02-14 09:55 UTC
