### ISSUE TITLE
Could not get BatchedBridge, make sure your bundle is packaged correctly

### ISSUE THREAD

**Issue by subsub** [jitsi/jitsi-meet#1800] opened 2017-07-19 05:58 UTC
I recently pull the updates from master branch and try to build. But I get the error `Could not get BatchedBridge, make sure your bundle is packaged correctly` when trying to run both on emulator and real device. I run emulator Android 6.0 and real device Android 5.0.2. After searching for awhile, I then try to run `react-native start --reset-cache` and I get these error:
```
jest-haste-map: @providesModule naming collision:
  Duplicate module name: bytes
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/bytes/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/raw-body/node_modules/bytes/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: escape-html
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/escape-html/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/serve-static/node_modules/escape-html/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: escape-html
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/serve-index/node_modules/escape-html/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/escape-html/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: debug
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/serve-index/node_modules/debug/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/body-parser/node_modules/debug/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: iconv-lite
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/iconv-lite/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/raw-body/node_modules/iconv-lite/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: debug
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/finalhandler/node_modules/debug/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/serve-index/node_modules/debug/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: escape-html
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/send/node_modules/escape-html/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/serve-index/node_modules/escape-html/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: debug
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/send/node_modules/debug/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/finalhandler/node_modules/debug/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: mime-types
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/mime-types/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/type-is/node_modules/mime-types/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: debug
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/connect/node_modules/debug/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/send/node_modules/debug/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: depd
  Paths: /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/depd/package.json collides with /home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/react-native/node_modules/send/node_modules/depd/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
watch /home/subkhan/Documents/workspace/forks/jitsi-meet ENOSPC
Error: watch /home/subkhan/Documents/workspace/forks/jitsi-meet ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at NodeWatcher.watchdir (/home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/sane/src/node_watcher.js:45:8)
    at createWatcher (/home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/jest-haste-map/build/index.js:536:23)
    at Array.map (native)
    at HasteMap._watch (/home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/jest-haste-map/build/index.js:654:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/home/subkhan/Documents/workspace/forks/jitsi-meet/node_modules/jest-haste-map/build/index.js:250:21)
```

Does anyone know how to fix this?
Thank you

**Comment by saghul** [comment] 2017-07-19 08:04
Try to wipe your node_modules directory and run `npm install` again. Then do `watchman watch-del-all` and try to run the app again.

**Comment by rashidmv** [comment] 2017-10-11 12:55
Run react-native start in one terminal and once the server is ready build it in another terminal

**Comment by saghul** [comment] 2017-10-11 14:07
I'm closing this since there has been no follow-up and we cannot reproduce it.

**Closed by saghul** 2017-10-11 14:07 UTC
Labels: project:react-native, type:support

**Comment by db-007** [comment] 2017-11-28 19:52
I am seeing this on Windows 10, simple steps

1. Clone this repo [https://github.com/JamesMarino/Firebase-ReactNative](https://github.com/JamesMarino/Firebase-ReactNative)
2. Saw the issue so I dropped node_modules completelly and from proj dir, issued npm i
3. Open Android emulator
4. do react-native run-android
5. project builds successfully, app is started on emulator and error shows
![batchedbridge](https://user-images.githubusercontent.com/17257073/33341073-a1ccf3f8-d432-11e7-9f1b-3716b7b1ceab.png)
