### ISSUE TITLE
[iOS] App going to crash

### ISSUE THREAD

**Issue by ParvendraSingh** [jitsi/jitsi-meet#3003] opened 2018-05-21 10:41 UTC
Hey All,

I implement JitsiMeet in iOS application before.
But i am going to  implement JitsiMeet in another iOS application.
I got an error when i run the application 

Error - Unknown class JitsiMeetView in Interface Builder file.

And app going to crash 

My Steps-

1- Download your demo code from Git.
2- Install all React Native dependencies.
3- Move on jitsi-meet-master folder and run the commands 
    a- npm install -g ios-deploy
    b- npm install . (I can find the node_modules folder after this command)
4- Then move in jitsi-meet-master/ios
5- Run install pods command
Then i am going to build the app for ios by using this commend 

xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

and now  i can find the both frameworks
WebRTC.framework and JitsiMeet.framework 

6- Using both framework in my project 
7- Run the application 
8- getting error and app crash 

Errors - 
1- Unknown class JitsiMeetView in Interface Builder file.
2- -[UIView setDelegate:]: unrecognized selector sent to instance 0x133d0de10

my UIView in interface builder does not taking the JitsiMeetView reference.

Please help me to solve this error.

**Comment by saghul** [comment] 2018-05-21 13:59
Are you importing `<JitsiMeet/JitsiMeet.h>` in your project?

**Comment by ParvendraSingh** [comment] 2018-05-22 11:41
@saghul 
Problem is in updated JitsiMeet.framework 
I think it is not creating properly.

I tried with old one code is working fine.

So let me know something about Updated JitsiMeet.framework

**Comment by saghul** [comment] 2018-05-22 13:00
> I think it is not creating properly.

What is not being created properly? The Jitsi Meet app (which uses the SDK) builds just fine, so I don't know what to tell you :-/

We recently added Swift, I wonder if that has anything to do with it...

**Comment by kishorb005** [comment] 2018-06-04 12:51
we have same problem,,   
when we import JitsiMeet in ViewController (Swift) giving error like

Module file's minimum deployment target is ios10.0 v10.0: /Users/mac2/Desktop/Development/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm.swiftmodule

we included both framework in project 
is Jitsi-Meet.framework  support version>=9?

**Comment by saghul** [comment] 2018-06-05 13:42
Can you try current master? This should be fixed now: https://github.com/jitsi/jitsi-meet/commit/c62809d91052fc45dc2a969b2f6770d727b936fb

**Comment by kishorb005** [comment] 2018-06-06 12:30
Yes, it is working on IOS 9.3 version no error
but getting blank/black video? 

while it is running well on IOS 11.2 version

**Comment by saghul** [comment] 2018-06-06 13:14
@kishorb005 same device? what devices are you testing on?

**Comment by kishorb005** [comment] 2018-06-07 04:30
on Ipad version 9.3.5  it is showing blank screen
and on Ipad version 11.2 it is working well with same configuration.

**Comment by saghul** [comment] 2018-06-07 05:52
What iPad models are those? Is it the same model?

**Comment by kishorb005** [comment] 2018-06-07 06:10
No. not same model,

Issue is with ipad 2 model number MC774HN/A

**Comment by saghul** [comment] 2018-06-07 09:31
Hum, I was hoping the problem would be due to the camera resolution on older iPads... Thanks for letting us know. TBH I don't know what the problem is and I have seen posts in the WebRTC bugtracker about iOS9 not being very well supported, I'm afraid.

**Comment by zy885137** [comment] 2018-06-11 11:22
we have same problem,
Errors -
1- Unknown class JitsiMeetView in Interface Builder file.
2- -[UIView setDelegate:]: unrecognized selector sent to instance 0x133d0de10

my UIView in interface builder does not taking the JitsiMeetView reference.

Please help me to solve this error.

**Comment by saghul** [comment] 2018-06-11 12:06
That’s not the same problem. Please open a new issue for it.

**Closed** 2018-06-20 09:59 UTC
