### ISSUE TITLE
After the third person enters the room, all people can only see their own video, can't see other people's

### ISSUE THREAD

**Issue by liukun28** [jitsi/jitsi-meet#8301] opened 2020-12-23 08:30 UTC
Before using the old version of Chrome browser, everything was normal. After upgrading to version 87, when three or more people enter the room, everyone can only see themselves, not others

**Comment by saghul** [comment] 2020-12-23 09:04
Are you using meet.jit.si or your own deployment? What do you see in the browser console?

**Comment by liukun28** [comment] 2020-12-24 01:19
I used meet.jit.si, the browser console report no errors and some warnings, 
the warnings
`[JitsiConference.js] <e.sendMessage>:  Failed to send a ping request or response.`
`[modules/UI/videolayout/VideoLayout.js] <Object.changeUserAvatar>:  Missed avatar update - no small video yet for undefined`
`[JitsiMeetJS.js] <Object.init>:  Analytics disabled, disposing.`
`[modules/statistics/AnalyticsAdapter.js] <e.value>:  Disposing of analytics adapter.`

**Comment by a2583941969** [comment] 2021-03-02 02:36
Have you solved the problem?

**Comment by saghul** [comment] 2021-03-02 08:18
We cannot reproduce this problem, closing.

If you are still able to, please open a new issue, DO FILL the template and provide the entire console logs.

**Closed by saghul** 2021-03-02 08:18 UTC
Labels: info:feedback-needed, quality, ui/ux
