### ISSUE TITLE
Need the feature to play audio along with video when shared from Application Window

### ISSUE THREAD

**Issue by krishnanvs11** [jitsi/jitsi-meet#6931] opened 2020-06-01 12:58 UTC
**Is your feature request related to a problem you are facing?**
This is a duplicate of Feature request 6909 - https://github.com/jitsi/jitsi-meet/issues/6909 Created this as the other one was closed but the issue remains.
We conduct online trainings and are planning to use Jitsi for our sessions. However, we face a serious constraint that the audio is not shared along with our training videos. I tried now with latest Chrome version 83.0.4103.61 (Official Build) (64-bit) but I don't see the checkbox to share audio when I choose the video to share in "Application window". Please check the attached screenshot.
![jitsi_share_app_window](https://user-images.githubusercontent.com/42645307/83411276-8cc27e80-a435-11ea-8a2b-842488241a09.png)

**Describe the solution you'd like**
We would love to be able to play the audio along with the video that is shared through Application window. It is essential to make our online session effective.

**Describe alternatives you've considered**
The alternative we have considered is to share the whole screen and play the video but the limitation is that the presenter cannot access any other window till the video is played out.

**Comment by damencho** [comment] 2020-06-01 14:05
What is the windows version

**Comment by damencho** [comment] 2020-06-01 14:17
Do you see it under `Your Entire Screen` and `Chrome Tab`?

**Comment by damencho** [comment] 2020-06-01 14:20
@andrei-gavrilescu Can you help? When is `Share audio` supposed to be shown for Applications?

**Comment by damencho** [comment] 2020-06-01 14:22
According to https://bugs.chromium.org/p/chromium/issues/detail?id=896333 that should be available on Windows.

**Comment by krishnanvs11** [comment] 2020-06-01 17:12
> 
> 
> Do you see it under `Your Entire Screen` and `Chrome Tab`?

Yes, I see "Share audio" option under "Entire Screen" and "Chrome Tab".

**Comment by krishnanvs11** [comment] 2020-06-01 18:56
> 
> 
> According to https://bugs.chromium.org/p/chromium/issues/detail?id=896333 that should be available on Windows.

Unfortunately, no.

**Comment by l3d00m** [comment] 2020-06-02 10:15
I can reproduce this. I have the feature under Chrome Tab and Entire Screen, but not for applications, using "Version 83.0.4103.61 (Official Build) (64-bit)"

**Comment by andrei-gavrilescu** [comment] 2020-06-02 11:04
Hello everyone, sorry for my later reply.
AFAIK audio sharing for a specific window isn't available. You can however share audio for a chrome tab if that helps you in any way.

**Comment by saghul** [comment] 2020-06-02 18:25
Closing since this a Chrome limitation, not something we can act upon.

**Closed by saghul** 2020-06-02 18:26 UTC
Labels: browser-support, feature-request
