### ISSUE TITLE
Function to make sketches on shared screen/tab

### ISSUE THREAD

**Issue by heikar** [jitsi/jitsi-meet#7293] opened 2020-07-10 19:34 UTC
**Describe the solution you'd like**
An user should have a function to share the screen/tab and authorize the other participants to use the content as a sketchboard/Whiteboard or to set a mark like an arrow to interact together.

**Comment by TheReal1604** [comment] 2020-07-14 11:34
Take a look at https://github.com/lovasoa/whitebophir/wiki/WBO-Jitsi-integration

**Comment by saghul** [comment] 2020-07-14 11:40
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5295

**Closed by saghul** 2020-07-14 11:40 UTC
Labels: feature-request, ui/ux
