### ISSUE TITLE
React-native-calendar-events issue while building the custom sdk

### ISSUE THREAD

**Issue by GowthamParamasivam** [jitsi/jitsi-meet#5150] opened 2020-03-13 16:36 UTC
while running the release-sdk.sh with the tmp/repo getting the following error

Task :react-native-calendar-events:compileReleaseJavaWithJavac FAILED
/root/jitsi-meet/gowtham-jitsi/jitsi-meet/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:13: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
^
symbol: class ActivityCompat
location: package android.support.v4.app
/root/jitsi-meet/gowtham-jitsi/jitsi-meet/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:14: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
^
/root/jitsi-meet/gowtham-jitsi/jitsi-meet/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:70: error: cannot find symbol
ActivityCompat.requestPermissions(currentActivity, new String[]{
^
symbol: variable ActivityCompat
location: class CalendarEvents
/root/jitsi-meet/gowtham-jitsi/jitsi-meet/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:94: error: cannot find symbol
int writePermission = ContextCompat.checkSelfPermission(reactContext, Manifest.permission.WRITE_CALENDAR);
^
symbol: variable ContextCompat
location: class CalendarEvents
/root/jitsi-meet/gowtham-jitsi/jitsi-meet/node_modules/react-native-calendar-events/android/src/main/java/com/calendarevents/CalendarEvents.java:95: error: cannot find symbol
int readPermission = ContextCompat.checkSelfPermission(reactContext, Manifest.permission.READ_CALENDAR);
^
symbol: variable ContextCompat
location: class CalendarEvents
5 errors

FAILURE: Build failed with an exception.

**Comment by saghul** [comment] 2020-03-13 16:48
What changes have you made to Jitsi Meet? Looks like `jettify` didn't run.

**Comment by GowthamParamasivam** [comment] 2020-03-14 07:35
I was trying to hide the message button on the call screen which is in the react-native application for mobile.

**Comment by saghul** [comment] 2020-03-14 08:41
have you done `npm install` ?

**Comment by Echolon** [comment] 2020-04-10 18:45
@GowthamParamasivam 
Do you have any feedback on this?

**Comment by GowthamParamasivam** [comment] 2020-04-11 03:49
Yes, I have done the npm install. But with the custom SDK am facing few issues. While connecting the video, immediately the video screen gets closed.

**Comment by Echolon** [comment] 2020-08-23 19:40
Hello @GowthamParamasivam please provide steps to reproduce. For the moment I will close this.

**Closed by Echolon** 2020-08-23 19:40 UTC
Labels: quality, wontfix
