### ISSUE TITLE
Firefox : not sound output, and no audio output selection

### ISSUE THREAD

**Issue by piRGoif** [jitsi/jitsi-meet#7669] opened 2020-09-09 09:18 UTC
### Description:

Hello,
I'm using Jitsi in a custom Rocket Chat instance. When creating a call, a new tab is opened on our custom Jitsi instance. If opened with Firefox (80.0.1 64 bits on Windows 10 1909 18363.1016), I cannot hear anyone, but my contact can hear me. Of course permission to use microphone and camera is granted, tab isn't in mute mode.

Here is a screenshot of the the preferences dialog in Firefox :
![image](https://user-images.githubusercontent.com/8947448/92578647-6dd15500-f28c-11ea-8592-d6a2f9be0399.png)

Everything is working fine with Chrome (version 85.0.4183.102) on the same computer.
Preferences dialog screenshot in Chrome :
![image](https://user-images.githubusercontent.com/8947448/92579177-28615780-f28d-11ea-92ae-3789396cb289.png)

I tried disabling tracking protection for the Jitsi URL in Firefox (clicking on the shield icon in the URL bar, and changing the switcher to off) but this didn't change anything.
![image](https://user-images.githubusercontent.com/8947448/92579721-d4a33e00-f28d-11ea-87ce-845efb4cacf5.png)

I'm usually using a bluetooth headset, but when having only the internal mic/hp available I get the same behavior.

### Steps to reproduce:

1. Create a call in Jitsi from Rocket Chat
2. Open the preferences dialog
3. See there are no audio output
4. See that you cannot hear anything from other members of the conference

### Expected behavior:

Should be able to select  an audio source in preferences dialog
Should be able to hear participants

### Actual behavior:

No output selection in mic dropdown and preferences dialog

Nothing heard in the default audio output

Errors in the Firefox console :

11:00:55.672 2020-09-09T09:00:55.673Z [features/analytics] <re/<>:  Error: No analytics handlers created!
    re https://jitsi.combodo.com/libs/app.bundle.min.js?v=4127:1
app.bundle.min.js:126:2379
    i https://jitsi.combodo.com/libs/app.bundle.min.js?v=4127:126
    re https://jitsi.combodo.com/libs/app.bundle.min.js?v=4127:1

11:07:04.762 2020-09-09T09:07:04.763Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: This client does not support P2P connections
    _rejectIncomingCall https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:10
    _onIncomingCallP2P https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:10
    onIncomingCall https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:10
    emit https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:1
    onJingle https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:10
    run https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:1
    _dataRecv https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:1
    forEachChild https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:1
    _dataRecv https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:1
    _onRequestStateChange https://jitsi.combodo.com/libs/lib-jitsi-meet.min.js?v=4127:1
lib-jitsi-meet.min.js:10:26384

### Server information:

- Jitsi Meet version:
ii jitsi-meet 2.0.4627-1 all WebRTC JavaScript video conferences
ii jitsi-meet-prosody 1.0.4127-1 all Prosody configuration for Jitsi Meet
ii jitsi-meet-tokens 1.0.4127-1 all Prosody token authentication plugin for Jitsi Meet
ii jitsi-meet-web 1.0.4127-1 all WebRTC JavaScript video conferences
ii jitsi-meet-web-config 1.0.4127-1 all Configuration for web serving of Jitsi Meet
ii jitsi-videobridge2 2.1-202-g5f9377b9-1 all WebRTC compatible Selective Forwarding Unit (SFU)

- Operating System:
Ubuntu 20.04

### Client information:

- Browser / app version: Firefox 80.0.1 64 bits 
- Operating System: Windows 10 1909 18363.1016

### Additional information:

The issue #2835 might be related ?

**Comment by Echolon** [comment] 2020-09-11 20:39
Hi @piRGoif please dont forget that this forum is public in case you dont want to drop pictures of yourself!

**Comment by piRGoif** [comment] 2020-09-14 07:34
Thanks, you are right, no problem with that for me though.

**Comment by jallamsetty1** [comment] 2020-09-28 18:38
Audio input and output device selection during the call is currently not supported on Firefox because of browser limitation. Firefox does not enumerating and changing audio output devices. Please make sure that your preferred devices are selected at the system level before joining the call. Here is the browser bug -
https://bugzilla.mozilla.org/show_bug.cgi?id=1498512

**Comment by jallamsetty1** [comment] 2020-09-28 18:46
Closing this issue since this is a browser limitation.

**Closed by jallamsetty1** 2020-09-28 18:46 UTC
Labels: browser-support, quality

**Comment by mark-orion** [comment] 2020-10-24 16:50
I had the same problem and it is actually possible to select the audio output device on Firefox. The problem is that this option is disabled in the Firefox configuration by default. Here is how to enable it:
- Enter the Firefox config editor by typing about:config in the URL bar.
- Proceed despite the warning message that will come up.
- Enter "media.setsinkid.enabled" in the search field at the top of the page.
- Double click on the entry so that the boolean value switches from "default" or "false" to "true".
- That's it. You can close the config tab. From now on you will have the audio output section in the jitsi-meet configuration.

**Comment by piRGoif** [comment] 2020-10-26 08:05
Many thanks Mark ! I could have understand that reading the bugzilla ticket but I didn't :D
Indeed after switching the pref I get the audio selector !
Many thanks for the tip !

**Comment by eddsaura** [comment] 2021-08-05 11:59
>     * media.setsinkid.enabled

Hey thanks a lot, this was really helpful. Is there anyway to enable this from client with user's permission?

**Comment by saghul** [comment] 2021-08-06 06:46
Not that I'm aware of, unfortunately.

**Comment by inukaze** [comment] 2023-01-10 20:59
Still under Firefox 108.0.2 the users can't select diferent audio device, i had a full custom GNU/Linux distribution i not have nothing related with PulseAudio, but Firefox requiere specifically that for Audio Output. in the Preferences / Options. Firefox still don't have a simple option to select a Output Device.

i remember i make that suggestion to put «Audio Device» for select when Firefox reach version 59. trying to found if possible use some env varible or option inside about:config, the unique line i had read on some site of mozilla about that, was the answer "Select Audio Device Output : That is not relevant for the web browser" ¬¬
