### ISSUE TITLE
Can I convert rtmp stream to jitsi-meet jvb and play it?

### ISSUE THREAD

**Issue by zsinba** [jitsi/jitsi-meet#7925] opened 2020-10-17 09:07 UTC
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.
I want to discuss some device images through the conference, which are sent to my server through RTMP via hardware capture card.
I am now playing the images of these devices through the Web player, although it is streaming in RTMP, and I can play it in FLV format.It is now embedded in the JITSI session and allows you to draw freely.
I wonder if I can transfer RTMP to JVB and then call these images directly from the JITSI conference?

**Describe the solution you'd like**
Please describe the desired behavior.
Like access to a user, access to a device image, the device image is via hardware (such as OBS) upload RTMP data stream to the server

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

I developed some features myself to fulfill these requirements.
But it's not connected to JVB.

**Comment by Echolon** [comment] 2020-10-18 19:13
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-10-18 19:13 UTC
Labels: question
