### ISSUE TITLE
Suggest participants to set their name

### ISSUE THREAD

**Issue by vlsi** [jitsi/jitsi-meet#4552] opened 2019-08-19 15:57 UTC
Currently users join with a default name of "Fellow Jitster".

It looks like everybody misses that they can really have a name.

I suggest:
1) Make "rename me" user-visible.
2) Randomize default usernames so user names look funny

**Comment by ankathiriya** [comment] 2019-10-04 07:20
Hello,

is there any solution for above I'm also looking for some solution for this.
Looking forward to hear from you.

Thanks,
Ankit

**Comment by saghul** [comment] 2019-10-04 07:47
If you are using your own deployment you can toggle this option: https://github.com/jitsi/jitsi-meet/blob/bb0036fdabd0cb8f4fc127acd50d98a17f06d894/config.js#L248

It's unlikely we ever turn it on for meet.jit.si, since we want people to remain anonymous, should they want to.

**Comment by ankathiriya** [comment] 2019-10-04 08:12
Thanks for your reply.

But is there any way to do in iOS SDk?
As we are going to use Jitsi for native android and iOS app.

Looking forward to hear from you.

**Comment by saghul** [comment] 2019-10-04 08:23
This is not a web thing. It's part of the deployment. The mobile app will read config.js and act accordingly.

**Comment by ankathiriya** [comment] 2019-10-04 08:28
Thanks @saghul for quick response.
Is there any doc for same . So I can follow same.and how can I read config.js file  in my app ?

Your response will help full for me.

**Comment by saghul** [comment] 2019-10-04 08:35
Not sure I follow. If you use the SDK as is, it will have https://meet.jit.si as the default server, so https://meet.jit.si/config.js will be used. If you set your own server (check the android and ios READMEs, they show how to change the server) then your own config file will be used and then it's up to you what values to set.

**Comment by ankathiriya** [comment] 2019-10-04 08:48
okay thanks @saghul 

let me apply same to my side and server side.

**Comment by ankathiriya** [comment] 2019-10-15 09:48
Hello @saghul 

as per your suggestion we did update config file to hide text like "Fello Jitster".

But still its not working.You can check my config file from this link
https://video.kanonhealth.com/config.js

Let me know if we need to make any further changes.Looking forward to hear from you.

Thanks.

**Comment by saghul** [comment] 2019-10-15 09:50
I still see requireDisplayName set to false.

**Comment by ankathiriya** [comment] 2019-10-15 09:52
@saghul again I wants to confirm with you that to hide that text we need to set it "true" ?

**Comment by ankathiriya** [comment] 2019-10-15 10:04
Hello @saghul 

I checked it with true and false both and its not working at all.
![Screenshot 2019-10-15 at 3 33 19 PM](https://user-images.githubusercontent.com/22503223/66822119-39142b00-ef61-11e9-8d17-f3d76fa0d009.png)

  let options = JitsiMeetConferenceOptions.fromBuilder { (builder) in
            builder.welcomePageEnabled = false
            builder.serverURL = URL.init(string: "https://video.kanonhealth.com/")
            builder.room = self.strRoomID
            builder.audioOnly = false
            builder.subject = APPNAME
            builder.userInfo?.displayName = UserDefaultManager.getStringFromUserDefaults(key: kAppUserName)
            builder.setFeatureFlag("chat.enabled", withBoolean: false)
        }

please check my code and let me know if I'm making any mistakes in that.

**Comment by saghul** [comment] 2019-10-15 10:11
I think I misunderstood. Setting that to `true` should request the user to enter a name upon joining, it won't magically hide the test.

If you are passing the display name in userInfo, however, that one should be the one used. Is this not working for you?

**Comment by ankathiriya** [comment] 2019-10-15 10:12
@saghul no its not working at all :(

**Comment by saghul** [comment] 2019-10-15 10:19
Can you confirm builder.userInfo is not null? What does `UserDefaultManager.getStringFromUserDefaults(key: kAppUserName` contain? Can you paste the logs when cakll is joined?

**Comment by ankathiriya** [comment] 2019-10-15 10:56
![Screenshot 2019-10-15 at 4 25 55 PM](https://user-images.githubusercontent.com/22503223/66825735-7e882680-ef68-11e9-9256-92ca817a6fa7.png)


Could you please check I pass static string but still its showing nil.

**Comment by saghul** [comment] 2019-10-15 11:10
I thin it's because you need to create a UserInfo object and then assign displayName to it, and assign the userInfo object to build.

**Comment by ankathiriya** [comment] 2019-10-15 11:38
its working after creating UserInfo object.

Thanks for your support. @saghul

**Comment by saghul** [comment] 2019-10-15 12:29
Glad to hear! I'm closing this now then.

**Closed by saghul** 2019-10-15 12:29 UTC

**Comment by pioneer** [comment] 2020-06-11 12:55
I think this could be also implemented on per-meeting base, not only on per-server base.

**Comment by chirayu25** [comment] 2020-08-18 12:25
Here is the code to change the username


```
let userInfo = JitsiMeetUserInfo()
userInfo.displayName = "FirstName LastName"
builder.userInfo = userInfo
```

**Comment by rohitrparsana** [comment] 2022-04-18 07:24
How to change "Fellow Jitster" to "Guest User" in ios SDK.

(https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk)

**Comment by SalihKIR** [comment] 2023-11-22 09:58
Greetings, I am using Jitsi 5.0.0, I have tried every method, jitster friends continue to write, can you share the most current solution?

**Comment by saghul** [comment] 2023-11-22 10:19
That SDK is incredibly old.

**Comment by SalihKIR** [comment] 2023-11-22 10:22
I agree with this, but for now I am using this. I will share my codes with you. I have tried every method, but the fellow jitster text always remains on the screen.

**Comment by SalihKIR** [comment] 2023-11-22 10:23
<img width="1084" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/77065124/706a8223-b01e-4486-9205-e9e0ca1f3314">

**Comment by saghul** [comment] 2023-11-22 10:32
The display name cannot be empty, that's why you see the default.

**Comment by saghul** [comment] 2023-11-22 11:34
Sorry that version is old and unsupported. You need to update to the latest SDK.

**Comment by SalihKIR** [comment] 2023-11-22 12:18
I have one last question: When the user starts a conversation on the phone, there is sound from the phone, but the sound does not come from the speaker. Then when I press the speaker icon, select the speaker, the sound comes from the speaker. There is no problem here, but my expectation is that when the conversation starts, the sound comes from the speaker. How can I set this?

**Comment by saghul** [comment] 2023-11-22 12:40
It's not possible for audio-only calls, that's our default.

**Comment by SalihKIR** [comment] 2023-11-22 12:44
My expectation is that the sound comes from the speaker as soon as the video call starts, isn't this possible?

**Comment by SalihKIR** [comment] 2023-11-22 12:50
<img width="814" alt="image" src="https://github.com/jitsi/jitsi-meet/assets/77065124/667b6cff-5f39-4cf8-926a-96d3bd20b160">


My expectation is that as soon as it starts to be seen, the conversation will start with the speaker turned on.

**Comment by SalihKIR** [comment] 2023-11-22 12:56
But when the conversation starts, the phone is selected. How can I change this situation?

**Comment by saghul** [comment] 2023-11-22 13:09
Did you start in audio-only mode? If not then it's a bug. Can you reproduce it with the Jitsi Meet app?

**Comment by SalihKIR** [comment] 2023-11-22 13:11
Yes, I started directly in audio-only mode.

**Comment by saghul** [comment] 2023-11-22 17:18
Then the earpiece is the default speaker. It's currently y not possible to change this default.

**Comment by niranjanave** [comment] 2023-12-21 17:21
I am trying display logo inside the jitsi meet but it is not showing can any one help me

**Comment by niranjanave** [comment] 2023-12-21 17:21
I am using ionic angular
