### ISSUE TITLE
Android craches with pre-build SDK

### ISSUE THREAD

**Issue by california257** [jitsi/jitsi-meet#4257] opened 2019-05-23 04:05 UTC
I use macOS to build SDK
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/18181704/58224959-010a1280-7d4a-11e9-8120-28d6c4de0dcf.png">

Project build.gradle
`
buildscript {
    ext.kotlin_version = '1.3.31'
    repositories {
        maven { url "file:/tmp/repo" }
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "file:/tmp/repo" }
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

App build.gradle
`
....
// Jitsi Meet
    implementation('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true }
....
`
But it got crash while I start jitsi view
Here is the log:
`
2019-05-23 11:03:47.472 30276-30316/com.calling.talk.red.debug E/ReactNativeJS: null is not an object (evaluating 'l.SIGN_IN_CANCELLED')
2019-05-23 11:03:47.478 30276-30316/com.calling.talk.red.debug E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
    
    --------- beginning of crash
2019-05-23 11:03:47.483 30276-30317/com.calling.talk.red.debug E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.calling.talk.red.debug, PID: 30276
    com.facebook.react.common.JavascriptException: null is not an object (evaluating 'l.SIGN_IN_CANCELLED'), stack:
    <unknown>@1084:2367
    h@2:1670
    <unknown>@1083:386
    h@2:1670
    <unknown>@1082:142
    h@2:1670
    <unknown>@1050:2426
    h@2:1670
    <unknown>@1049:206
    h@2:1670
    <unknown>@1019:278
    h@2:1670
    <unknown>@1018:85
    h@2:1670
    <unknown>@371:240
    h@2:1670
    <unknown>@12:156
    h@2:1670
    <unknown>@11:30
    h@2:1670
    d@2:868
    global code@1490:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
`
Please help me! Thank you very much!

**Comment by saghul** [comment] 2019-05-23 07:32
Your maven URL points to a Maven repo of your own, so did you build the SDK or did you use the prebuilt artifacts? Contrary to the issue title, it seems like the former. And it looks like a dependency is missing.

**Comment by california257** [comment] 2019-05-23 07:58
I used the release script as described here: https://github.com/jitsi/jitsi-meet/blob/master/android/README.md#build-and-use-your-own-sdk-artifactsbinaries

**Comment by saghul** [comment] 2019-05-23 08:39
What are you trying to accomplish? What are the contents of `/tmp/repo` ?

**Comment by california257** [comment] 2019-05-23 08:49
I run "./android/scripts/release-sdk.sh /tmp/repo"
Result:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/18181704/58238716-f95e6400-7d71-11e9-806b-d696d6659267.png">
After do like above steps.

**Comment by saghul** [comment] 2019-05-23 08:52
Did you make any changed to the SDK? I have never seen this issue before :-/

**Comment by california257** [comment] 2019-05-23 09:18
I do not make any changes to the SDK :(

**Comment by saghul** [comment] 2019-05-23 09:53
I suggest youi first start with the prebuilt binaries, then build your own.

**Comment by california257** [comment] 2019-05-23 09:56
I will try it! Thank you

**Comment by MeghsP** [comment] 2019-05-23 15:27
Hi
I am using same code in my android app and calling that code from React Native file. When JitsyMeetActivity is being called, app is being crashed with the same error saying:

```
null is not an object (evaluating 'M.Aspect')
2019-05-23 19:42:17.169 9640-9722/com.telecare E/ReactNativeJS: Module 

AppRegistry is not a registered callable module (calling runApplication)
2019-05-23 19:42:17.174 9640-9723/com.telecare E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.telecare , PID: 9640
    com.facebook.react.common.JavascriptException: null is not an object (evaluating 'M.Aspect'), stack:
    <unknown>@944:6009
    h@2:1670
    <unknown>@943:292
    h@2:1670
    <unknown>@942:280
    h@2:1670
    <unknown>@11:743
    h@2:1670
    d@2:868
    global code@1008:4

        at 
com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at 

com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at 
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at 

com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
```

Please help. I am trying from whole day and no luck! Also please check my question [here ](https://stackoverflow.com/questions/56277357/module-appregistry-is-not-a-registered-callable-module-calling-runapplication)where you find my code.

**Comment by saghul** [comment] 2019-05-23 17:11
@MeghsP are you using react-native-firebase on your project?

**Comment by california257** [comment] 2019-05-24 04:26
@saghul Sorry, this is my mistake. Because my project use old file "index.android.bundle". I rebuild new file  "index.android.bundle" from Jitsi-meet after add it into my project and it worked ok. Thank you!

**Comment by MeghsP** [comment] 2019-05-24 05:25
@saghul ,Thanks for your reply. I am not using react-native-firebase in my project. Here are the dependencies I am using in my app:

```
"react-native-calendars": "^1.21.0",
    "react-native-camera": "^1.8.0",
    "react-native-card-stack-swiper": "^1.1.0",
    "react-native-cardview": "^2.0.2",
    "react-native-circular-action-menu": "^0.5.0",
    "react-native-contacts": "^2.2.4",
    "react-native-datepicker-dialog": "0.0.9",
    "react-native-elements": "^1.0.0-beta7",
    "react-native-expandable-section-list": "^1.0.7",
    "react-native-loader": "^1.2.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-material-textfield": "^0.12.0",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-parallax-scroll-view": "^0.21.3",
    "react-native-swipeout": "^2.3.6",
    "react-native-switch": "^1.5.0",
    "react-native-tab-view": "^1.3.1",
    "react-native-table-component": "^1.2.0",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^2.18.2",
    "toggle-switch-react-native": "^2.0.2"
```

**Comment by MeghsP** [comment] 2019-05-24 05:43
@california257 Hi, glad you resolved your issue. Can you please tell me how to reproduce index.android.bundle file from jitsi meet?

**Comment by california257** [comment] 2019-05-24 06:32
@MeghsP 
From your jitsi-meet project directory:
$ cd android
$ react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
Finally, navigate back to the root directory and check

**Comment by MeghsP** [comment] 2019-05-24 06:38
@california257 , thanks for your reply. Actually I am using jitsi-meet as a dependency not using jitsi-meet sdk itself. so how can I follow above steps?

**Comment by california257** [comment] 2019-05-24 07:18
@saghul Because my project use old file "index.android.bundle". I rebuild new file "index.android.bundle". Your project may not need to use it, now if I remove file "index.android.bundle" from my project, It still works well, not crash. I think our problem is not the same

**Comment by saghul** [comment] 2019-05-24 07:52
@california257 Thanks for confirming. I'm going to close this then. @MeghsP please open a new issue since your is different.

**Closed by saghul** 2019-05-24 07:52 UTC

**Comment by ngoctan95** [comment] 2019-06-11 02:33
@california257 @saghul ,
I have an issue like this but I could not know how to build release.
- In debug mode, the app use the index.android.bundle which generated by 
```
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
```
- When I run in debug mode, it not work and crash after open jitsi activity. If I delete index.android.bundle in assets directory, it works. 
- But when I wanna release signed apk, react native let me do command above for generating bundle assets or it will be crash on the startup even build successfully. If I still keep it in assets directory, in release mode, the app will be crash while I click onto open jitsi activity. 
- I think it is conflict bundle in react native app and bundle of jitsi in release mode.
How can I combine them or use one of them for both app bundle and jitsi bundle? 
Have you tried to build release mode bundle js asset? Please help me out this issue :(

**Comment by darktheft** [comment] 2019-12-19 13:11
When i build apk jitsi is crash and when i debuge app it's worked if you have any solution plz tell me about this
