### ISSUE TITLE
Hide insecure circle icon and notice from guests

### ISSUE THREAD

**Issue by kjcole** [jitsi/jitsi-meet#6962] opened 2020-06-04 21:17 UTC
## Background

On our self-hosted instance some users insist -- against my better judgement -- in using insecure room names, and have asked for the notification to be turned off, because it makes the room appear to be "buggy" to anonymous guests.

## Suggestion / Solution

An option to show the warning only to the registered host / moderator who initiates the meeting.  Or possibly to all registered non-anonymous users.

## Bad idea that I was out-voted on

It was decided that we set the CSS to hide the icon and warning. Bleah! :stuck_out_tongue_closed_eyes:

**Comment by luixxiul** [comment] 2020-06-05 01:57
Duplicate of https://github.com/jitsi/jitsi-meet/issues/6801

**Closed by luixxiul** 2020-06-05 01:57 UTC
