### ISSUE TITLE
Can't Find recording of my lesson

### ISSUE THREAD

**Issue by kifur** [jitsi/jitsi-meet#5231] opened 2020-03-18 15:20 UTC
Good morning, today I did a webinar, recorded it, but can't find on dropbox? what happened? sorry for this, it's my first time using this product. 
Regards
Salvatore

**Comment by Echolon** [comment] 2020-04-10 21:16
duplicate of

meet.jit.si recording - no audio recorded #5403 

@damencho

**Comment by l3d00m** [comment] 2020-05-12 13:42
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affliated with the Jitsi team.*

**Closed by l3d00m** 2020-05-12 13:42 UTC
