### ISSUE TITLE
Jitsi doesn't recognize the browser's locale settings

### ISSUE THREAD

**Issue by asereze** [jitsi/jitsi-meet#6736] opened 2020-05-16 20:23 UTC
##  Description
Jitsi doesn't automatically opens in my browser's locale for website pages.

## Current behavior
When I start a new meeting on https://meet.jit.si/, the interface is always in English, and I have to manually change the language to the one I use (Sardinian, ISO 639-1 code: "sc") every time. I use Firefox, with Sardinian as the first language for visualizing the pages, but while that works on many other sites (ex. Wikipedia or Facebook), it doesn't work on Jitsi meetings right now.

## Expected Behavior
To have my Jitsi meetings interface automatically in Sardinian while I open it.

**Comment by saghul** [comment] 2020-05-17 06:08
I believe this is fixed in master already, but hasn’t been deployed to meet.jit.si yet.

**Comment by JohnProv** [comment] 2020-06-20 08:25
I think this hasn't been fixed in master already, because this is a configuration option. Thus maybe a fresh installation has standard LANG_DETECTION: true. But on https://meet.jit.si/ the configuration is set to LANG_DETECTION: false.
Please change this configuration option, so translations are enabled.

**Comment by JohnProv** [comment] 2020-07-06 15:17
Some research: the concerning fix is https://github.com/jitsi/jitsi-meet/commit/1aba57e6bb92e66f92e10341191b5553e2b4dc0c
Can someone explain what the problem is? Is it a configuration option that is set to _false_ instead of _true_, or has the fix not released to meet.jit.si?
How can we get translations on meet.jit.si? Maybe this pull request is also related? https://github.com/jitsi/jitsi-meet/pull/5641

**Comment by damencho** [comment] 2020-07-06 16:08
This had not been deployed to meet.jit.si, I will take note about that.

**Comment by JohnProv** [comment] 2020-07-18 14:57
I think this has been solved: translations are enabled when visiting https://meet.jit.si/.
Can the status of this ticket now change from _open_ to _closed_?

**Closed** 2020-07-18 21:03 UTC
Labels: localization
