### ISSUE TITLE
"Jingle error" messages

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#265] opened 2015-04-09 13:55 UTC
"Jingle error" messages are often logged (as errors), without apparent ill effects.

**Comment by luistduarte** [comment] 2015-06-05 14:58
localhost environment?

**Comment by luistduarte** [comment] 2015-06-05 15:14
I have the same messages in the browser, but i cant get audio/video from other participants because,
on jitsi-videobridge i get messages like ice failed

**Comment by paweldomas** [comment] 2015-07-06 11:25
This is caused by strophe.js bug which no longer exists in the latest version. First 'on result' callback was called for 'session-accept' IQ and then after timeout limit expired Strophe trigerred error callback again.

**Comment by paweldomas** [comment] 2015-07-21 06:23
Fixed in https://github.com/jitsi/jitsi-meet/commit/b5135c455efa9a46c7403dc1a8984d0df0f6eb80

**Closed by paweldomas** 2015-07-21 06:23 UTC
