### ISSUE TITLE
Quality for screensharing + camera is bad

### ISSUE THREAD

**Issue by puckipedia** [jitsi/jitsi-meet#7923] opened 2020-10-16 15:03 UTC
### Description:

For some people with low-resolution webcams, screensharing is high-resolution, but the moment that someone toggles their webcam, the resolution of the combined stream turns unreadable.

### Steps to reproduce:

1. Enable the webcam, see a low quality image
2. Start screensharing, see that the resolution is good
3. Enable the webcam while screensharing, and see that the resolution is bad.

### Expected behavior:
The resolution of the whole screenshare is not bad.

### Actual behavior:
The resolution of the whole screenshare is bad.

### Server information:

- Jitsi Meet version: 1.0.4127
- Operating System: NixOS

### Client information:

- Browser / app version: Firefox various, e.g. 78
- Operating System: NixOS

**Comment by paweldomas** [comment] 2020-10-16 16:51
can you try with the latest version? there was recently a change which should make screenshare in the presenter mode more readable: https://github.com/jitsi/jitsi-meet/pull/7836

**Comment by jallamsetty1** [comment] 2020-10-23 13:44
Does this happen only on Firefox or are you able to reproduce this on Chromium as well ?

**Comment by amsnek** [comment] 2020-10-27 13:33
i am not the person in question, but i observed the same behaviour (screenshare + presenter mode reduced screenshare quality)
-> this is fixed for me in latest release (2.0.5142) as far as i can tell.

**Comment by jallamsetty1** [comment] 2020-11-09 16:04
The firefox issue should have been resolved on meet.jit.si now. It will be available in the stable builds once the version running meet.jit.si gets pushed there. I am closing the issue, please feel free to re-open if you still see the issue.

**Closed by jallamsetty1** 2020-11-09 16:04 UTC
Labels: info:feedback-needed, quality, web

**Comment by neehalsaal** [comment] 2020-12-10 16:12
Hi @jallamsetty1, 
Sorry to be commenting over a closed issue. 
I just checked this on meet.jit.si and found that the screen share quality wasn't good. 

![image](https://user-images.githubusercontent.com/42176363/101796933-e9100480-3b22-11eb-9695-1da42c564ad8.png)

This happens only when someone is doing a screen share with their camera ON from firefox (v83.0, this is what I tried on)
The recipient's browser didnt matter. I am using chrome v86.0.4240.111 here.

Thank you

**Comment by jallamsetty1** [comment] 2020-12-10 19:25
> Hi @jallamsetty1,
> Sorry to be commenting over a closed issue.
> I just checked this on meet.jit.si and found that the screen share quality wasn't good.
> 
> ![image](https://user-images.githubusercontent.com/42176363/101796933-e9100480-3b22-11eb-9695-1da42c564ad8.png)
> 
> This happens only when someone is doing a screen share with their camera ON from firefox (v83.0, this is what I tried on)
> The recipient's browser didnt matter. I am using chrome v86.0.4240.111 here.
> 
> Thank you

We have a limitation on Firefox with presenter because FF doesn't report the width/height of desktop tracks. So we have to resize a given desktop track to 720p to be able to create a composite video stream that includes the desktop and camera. If the screen you have chosen to share is of much higher resolution, then FF doesn't do a good job when it gives us a resized stream of 720p. Unfortunately we cannot do anything about it for now. Can you try with a low resolution screen and check if you see the same issue ? Also please give the browser about a min to adjust the upload bitrate .

**Comment by neehalsaal** [comment] 2020-12-13 05:58
Yes, that's right. If we share something that has a lower resolution, then things are fine.

**Comment by JLuc** [comment] 2021-02-12 17:57
It looks like i had the same issue with both Firefox 85.0.1 and Chromium 88.0 
We were 2 in the same room. I had VDO on (low res or hi res didnt change). My partner had Screen Sharing + Small VDO on and his screen was very low res here.
He then switched to "screen sharing only" (video off) and i could receive his screen with high resolution.
