### ISSUE TITLE
Android app crashes on Android 12 due to some PendingIntent usage requirements

### ISSUE THREAD

**Issue by justmax437** [jitsi/jitsi-meet#12506] opened 2022-11-03 14:37 UTC
Description:

I am using Jitsi Meet Android app, latest build from google play store as of now, on a Samsung Galaxy Fold 4 running OneUI 4.1.1, Android 12. Jitsi Meet app crashes immediately after I launch it with an exception like the one below in logcat.

```
11-03 17:22:26.119  1241  1328 W FA      : Service disabled
11-03 17:22:26.120  1241  1241 D MainActivity: LIBRE_BUILD=false
11-03 17:22:26.120  1241  1241 D MainActivity: Initializing Google Services
11-03 17:22:26.121  1467  1467 I SurfaceFlinger: [7ce7790 org.jitsi.meet/org.jitsi.meet.MainActivity#0] FrameRatePriority: 1
11-03 17:22:26.121  1467  1467 I Layer   : id=21969 removedFromDrawingState Surface(name=4fbc713 StatusBar)/@0x4584c0c - animation-leash of insets_animation#0 (158)
11-03 17:22:26.121  1467  1467 I Layer   : id=21970 removedFromDrawingState Surface(name=3f04d40 NavigationBar0)/@0x26445be - animation-leash of insets_animation#0 (158)
11-03 17:22:26.121  3576  3576 W AppTransitionAnimatorImpl: onAnimationStart - APP IN
11-03 17:22:26.121  1467  1467 I Layer   : id=21971 removedFromDrawingState Surface(name=b433f5f Taskbar)/@0xc5ee20c - animation-leash of insets_animation#0 (158)
11-03 17:22:26.121  1467  1467 I SurfaceFlinger: id=21969 Removed Surface(name=4fbc713 StatusBar)/@0x4584c0c - animation-leash of insets_animation#0 (158)
11-03 17:22:26.121  1467  1467 I SurfaceFlinger: id=21970 Removed Surface(name=3f04d40 NavigationBar0)/@0x26445be - animation-leash of insets_animation#0 (158)
11-03 17:22:26.121  1467  1467 I SurfaceFlinger: id=21971 Removed Surface(name=b433f5f Taskbar)/@0xc5ee20c - animation-leash of insets_animation#0 (158)
11-03 17:22:26.121  1467  1467 I Layer   : id=21969 Destroyed Surface(name=4fbc713 StatusBar)/@0x4584c0c - animation-leash of insets_animation#0
11-03 17:22:26.122  1467  1467 I Layer   : id=21970 Destroyed Surface(name=3f04d40 NavigationBar0)/@0x26445be - animation-leash of insets_animation#0
11-03 17:22:26.122  1467  1467 I Layer   : id=21971 Destroyed Surface(name=b433f5f Taskbar)/@0xc5ee20c - animation-leash of insets_animation#0
11-03 17:22:26.122  1241  1337 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10383; state: ENABLED
11-03 17:22:26.122  1467  1467 W Scheduler: No mode changed params found, not dispatching cached mode.
11-03 17:22:26.122  1241  1337 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
11-03 17:22:26.122  1241  1337 E AndroidRuntime: Process: org.jitsi.meet, PID: 1241
11-03 17:22:26.122  1241  1337 E AndroidRuntime: java.lang.IllegalArgumentException: org.jitsi.meet: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
11-03 17:22:26.122  1241  1337 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at android.app.PendingIntent.getActivity(PendingIntent.java:451)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at android.app.PendingIntent.getActivity(PendingIntent.java:415)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at ma.f.f(Unknown Source:2)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at ma.f.e(Unknown Source:1)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at ma.e.e(Unknown Source:1)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at ma.e.q(Unknown Source:3)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at ma.e.B(Unknown Source:1)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.e.r(Unknown Source:1)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.e$a.h(Unknown Source:12)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.e$a.a(Unknown Source:5)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.e$a.m(Unknown Source:10)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.e.handleMessage(Unknown Source:50)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at bb.h.dispatchMessage(Unknown Source:1)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-03 17:22:26.122  1241  1337 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
11-03 17:22:26.122  3576  6391 I ViewRootImpl@9c27a97[LauncherActivity]: mWNT: t = android.view.SurfaceControl$Transaction@6f2e512 fn = 34 com.android.systemui.shared.system.ViewRootImplCompat.mergeWithNextTransaction:2 com.android.quickstep.util.SurfaceTransactionApplier.lambda$scheduleApply$0:9 com.android.quickstep.util.SurfaceTransactionApplier.a:0
11-03 17:22:26.122  3576  6391 I ViewRootImpl@9c27a97[LauncherActivity]: mWNT: merge t to BBQ
11-03 17:22:26.123  1241  1337 E JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
```

**Comment by saghul** [comment] 2022-11-03 15:37
What exact version and build number are you running?

**Comment by saghul** [comment] 2022-11-03 22:00
So weird! I'm aunable to reproduce it on a Pixel 3a XL, running Android 12 too. Is there something special about that device?

**Comment by justmax437** [comment] 2022-11-04 12:36
Weird indeed, was pretty surprised to see this too, on my Poco X3 Pro running 12 it was ok too.

Not sure about "special", it's completely stock, just bought it a week ago, only installed latest updates, no unlocks or other rom trickery. Maybe I missed something else in logs and this intent exception is not the root cause. I may try different builds, like fdroid or build myself and see if I can reproduce it there.

**Comment by justmax437** [comment] 2022-11-04 12:38
22.5.1 from f-droid works, it that a regression?

**Comment by saghul** [comment] 2022-11-04 14:46
> 22.5.1 from f-droid works, it that a regression?

I don't think we have made changed things regarding intents... maybe a transitive dependency.

Any chance you can pinpoint the offending code / library?

**Comment by justmax437** [comment] 2022-11-06 09:19
22.6.1 from google play is obfuscated, so probably no

**Comment by saghul** [comment] 2022-11-07 09:28
@tmoldovan8x8 do you have any ideas here?

**Comment by mehul4795** [comment] 2022-11-22 09:14
I faced the same error. The issue occurs when I integrate the Jitsi Meet SDK in my app and set the `compileSdk` &  `targetSdk` version of my app to `32` or above. The error is caused due to the [new requirement introduced in Android 12](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability) where a `PendingIntent` needs to be explicitly set to Mutable or Non Mutable. 

I hope the Jitsi Meet SDK is updated with support for setting the `compileSdk` & `targetSdk` to `32`. 

As of now, I think the only workaround is to set the `compileSdk` & `targetSdk` of your app to `31`.

**Comment by saghul** [comment] 2022-11-22 09:51
I don't think we have a dependency on `WorkManager`. I tried bumping our compile and target SDKs to 32 and got no crash. Any chance that dependency comes from your app?

**Comment by mehul4795** [comment] 2022-11-22 10:23
Sorry, I forgot to mention. Yes, the dependency of `WorkManager` comes from another library in my app. I think @justmax437 must be having the same issue.

**Comment by saghul** [comment] 2022-11-22 10:38
Thanks for confirming! I'm going to tentatively close this then.

**Closed by saghul** 2022-11-22 10:38 UTC
