### ISSUE TITLE
Login screen doesn't log in (on iPad, Jitsi Meet 23.0.0)

### ISSUE THREAD

**Issue by snan** [jitsi/jitsi-meet#13270] opened 2023-04-26 13:02 UTC
Today on iPad there was a new version of Jitsi Meet installed (23.0.0) and I can no longer log into be the host of rooms on my self-hosted server. After putting in name & password, the first time I press the login window's blue "OK" button, it flickers grey briefly as if it was successfully pressed but then it turns blue again and completely unclickable. Cancel still works. But I can't authenticate the rooms (and therefore can't join them).

**Comment by saghul** [comment] 2023-04-26 14:08
The latest release unfortunately contains a regression in the authentication flow.

We are currently working on a fix and a new release.

**Comment by snan** [comment] 2023-04-26 14:36
Since the app didn't work I upgraded the server—which was a huge mistake because now I can't authenticate in the browser either. (I thought that might be a workaround, auth on Linux Firefox and then connect from the iPad.)

**Comment by himpierre** [comment] 2023-04-27 14:21
> The latest release unfortunately contains a regression in the authentication flow.
> 
> We are currently working on a fix and a new release.

Well I was hit by that bug today on android. Unable to login on self-hosted `authentication = "internal_hashed"` enabled machine. Good to know you guys working on it.

cheers, t.

**Comment by saghul** [comment] 2023-04-27 14:26
A new release (23.1.0) is now rolling out. Sorry everyone!

**Comment by himpierre** [comment] 2023-04-27 14:37
Thanks!

Am 27. April 2023 16:27:05 MESZ schrieb "Saúl Ibarra Corretgé" ***@***.***>:
>A new release (23.1.0) is now rolling out. Sorry everyone!
>

**Comment by saghul** [comment] 2023-04-27 19:13
23.1.0 has been released on the App Store and it's rolling out on the Play Store.

**Comment by rrgeorge** [comment] 2024-01-25 22:22
This issue appears have resurfaced in the current version of the iOS app (23.6.1).

**Comment by saghul** [comment] 2024-01-26 05:52
What behavior do you observe?

Can you enroll in the beta program and check with the latest beta?

**Comment by rrgeorge** [comment] 2024-01-26 06:04
> What behavior do you observe?
Same as described above. The OK button on the login window is completely unresponsive, but the Cancel button works fine.
It's also worth noting that the meeting never prompts you to login like the (unstable) web ui does. Instead, it continually spins like it's still connecting. The only way to get the Login window is to tap the ..., tap settings, tap your name, and then tap the Log-In button in the upper right corner.  

> Can you enroll in the beta program and check with the latest beta?
The behavior is unchanged in the Tesflight beta.

**Comment by saghul** [comment] 2024-01-26 07:59
What versions of the server side components are you using?

**Comment by rrgeorge** [comment] 2024-01-26 15:30
> What versions of the server side components are you using?

I had to switch to the nightly branch because of the same behavior on the web ui on the stable branch.

```
ii  jitsi-meet                            2.0.9230-1                             all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                    1.0.7767-1                             all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver                 1.0.7767-1                             all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                        1.0.7767-1                             all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                 1.0.7767-1                             all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                    2.3-71-g573abcdf-1                     all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  lua-basexx                            0.4.1-jitsi1                           all          baseXX encoding/decoding library for Lua
ii  lua-cjson:amd64                       2.1.0.10-jitsi1                        amd64        JSON parser/encoder for Lua
```

**Comment by saghul** [comment] 2024-01-26 15:37
So is it working on the unstable branch?

**Comment by rrgeorge** [comment] 2024-01-26 15:37
Only on the web ui

**Comment by saghul** [comment] 2024-01-26 15:38
Oh, I see.

**Comment by Calinteodor** [comment] 2024-02-08 14:27
@rrgeorge We merged a fix regarding standard authentication and it's available on TestFlight, latest beta. 
Can you check if this is still reproducible? Thank you.

**Comment by rrgeorge** [comment] 2024-02-08 15:07
> @rrgeorge We merged a fix regarding standard authentication and it's available on TestFlight, latest beta. 
> 
> Can you check if this is still reproducible? Thank you.

No changes. Creating a meeting still spins indefinitely, and attempts to login manually:  
1. Press `...`
2. Press `Settings`
3. Press <name>
4. Press Log-in
5. Enter username/password
6. `OK` button does not respond at all

**Comment by saghul** [comment] 2024-02-08 15:08
What build do you have installed?

**Comment by rrgeorge** [comment] 2024-02-08 15:18
If I create a meeting on the web, I am immediately greeted with a "Waiting for Moderator" pop up with a log-in button where I can successfully log in and start the meeting.
To clarify, this only works on the nightly release of jitsi-meet. 
(Currently `jitsi-meet 2.0.9270-1` & `jitsi-meet-web 1.0.7802-1`
When I was using the stable release, the web ui behaved the same way as the app (it would spin indefinitely, and provided no prompts to login)

**Comment by saghul** [comment] 2024-02-08 15:19
I mean the mobile app, you need the latest mobile app beta tgo test this.

**Comment by rrgeorge** [comment] 2024-02-08 15:21
> I mean the mobile app, you need the latest mobile app beta tgo test this.

I understood, I was just trying to provide more context. There is no change in the latest TestFlight (version 24.0.0 build 1707296466).

**Comment by saghul** [comment] 2024-02-09 11:58
I wasn not able to reproduce the problem with the latest TestFlight version + a vanilla Docker setup with auth enabled. Is you instance available so we can run a test?

**Comment by rrgeorge** [comment] 2024-02-09 16:43
Sure. https://meet.rrgeorge.direct

**Comment by rrgeorge** [comment] 2024-02-09 20:35
Upon further investigation, it seems that the issue is due to mod_bosh crashing in prosody. It turns out that it is mere coincidence that it's presenting the same way as this bug. Forcing the use of the websocket by setting testing.mobileXmppWsThreshold to 100 seems to resolve the issue.

**Comment by saghul** [comment] 2024-02-09 20:42
Interesting. What logs do you see? What prosody version is that?

**Comment by rrgeorge** [comment] 2024-02-09 20:48
> Interesting. What logs do you see? What prosody version is that?
prosody-trunk 1nightly1868-1~bookworm
```
Feb 09 12:17:55 mod_bosh        error   Traceback[bosh]: /usr/lib/prosody/modules/mod_saslauth.lua:94: attempt to concatenate a nil value (field 'base_type')
        stack traceback:        /usr/lib/prosody/modules/mod_saslauth.lua:94: in function </usr/lib/prosody/modules/mod_saslauth.lua:80>
        (...tail calls...)
        /usr/share/lua/5.4/prosody/util/events.lua:81: in function </usr/share/lua/5.4/prosody/util/events.lua:77>
        (...tail calls...)
        /usr/share/lua/5.4/prosody/core/stanza_router.lua:143: in method 'dispatch_stanza'
        /usr/lib/prosody/modules/mod_bosh.lua:340: in upvalue 'func'
        /usr/share/lua/5.4/prosody/util/async.lua:149: in function </usr/share/lua/5.4/prosody/util/async.lua:147>
        stack traceback:        /usr/share/lua/5.4/prosody/util/async.lua:244: in method 'run'
        /usr/lib/prosody/modules/mod_bosh.lua:484: in upvalue 'cb_handlestanza'
        /usr/share/lua/5.4/prosody/util/xmppstream.lua:188: in function </usr/share/lua/5.4/prosody/util/xmppstream.lua:165>
        [C]: in upvalue 'parse'
        /usr/share/lua/5.4/prosody/util/xmppstream.lua:290: in method 'feed'
        /usr/lib/prosody/modules/mod_bosh.lua:137: in function </usr/lib/prosody/modules/mod_bosh.lua:118>
        (...tail calls...)        /usr/share/lua/5.4/prosody/util/events.lua:81: in function </usr/share/lua/5.4/prosody/util/events.lua:77>
        (...tail calls...)
        /usr/share/lua/5.4/prosody/net/http/server.lua:297: in upvalue 'handle_request'
        /usr/share/lua/5.4/prosody/net/http/server.lua:134: in upvalue 'func'
        /usr/share/lua/5.4/prosody/util/async.lua:149: in function </usr/share/lua/5.4/prosody/util/async.lua:147>
        
```

**Comment by saghul** [comment] 2024-02-10 06:56
Can you try prosody 0.22? Is there a reason why you run trunk?

**Comment by rrgeorge** [comment] 2024-02-10 16:54
I was able to fix it by patching mod_bosh.lua and adding base_type to the session declaration line 327 from:
```
local session = {
			type = "c2s_unauthed", conn = request.conn, sid = sid, host = attr.to,
			rid = rid - 1, -- Hack for initial session setup, "previous" rid was $current_request - 1
			bosh_version = attr.ver, bosh_wait = wait, streamid = sid,
			bosh_max_inactive = bosh_max_inactivity, bosh_responses = cache.new(BOSH_HOLD+1):table();
			requests = { }, send_buffer = {}, reset_stream = bosh_reset_stream,
			close = bosh_close_stream, dispatch_stanza = core_process_stanza, notopen = true,
			log = logger.init("bosh"..sid),	secure = consider_bosh_secure or request.secure,
			ip = request.ip;
		};
```
To:
```
local session = {
			type = "c2s_unauthed", conn = request.conn, sid = sid, host = attr.to,
			type = "c2s",
			rid = rid - 1, -- Hack for initial session setup, "previous" rid was $current_request - 1
			bosh_version = attr.ver, bosh_wait = wait, streamid = sid,
			bosh_max_inactive = bosh_max_inactivity, bosh_responses = cache.new(BOSH_HOLD+1):table();
			requests = { }, send_buffer = {}, reset_stream = bosh_reset_stream,
			close = bosh_close_stream, dispatch_stanza = core_process_stanza, notopen = true,
			log = logger.init("bosh"..sid),	secure = consider_bosh_secure or request.secure,
			ip = request.ip;
		};
```

**Comment by saghul** [comment] 2024-02-10 17:39
Good to hear!

**Closed by saghul** 2024-02-10 17:39 UTC
