### ISSUE TITLE
Couldnot connect to jitsi live video stream,  Network request failed getting

### ISSUE THREAD

**Issue by anjanabnath** [jitsi/jitsi-meet#7443] opened 2020-08-03 10:07 UTC
Hi Jitsi team, 

When I connect to jitsi activity, Reconnect now  window  showing and a white blank screens appears after.Log error report is as follows
JitsiMeetSDK: [features/base/lib-jitsi-meet] Failed to load configError(TypeError){"message":"Network request failed","stack":"TypeError: Network request failed\n    at anonymous (index.android.bundle:137:7285)\n    at call (native)\n    at dispatchEvent (index.android.bundle:128:5676)\n    at value (index.android.bundle:123:6095)\n    at value (index.android.bundle:123:2835)\n    at apply (native)\n    at anonymous (index.android.bundle:123:5024)\n    at apply (native)\n    at value (index.android.bundle:49:1280)\n    at apply (native)\n    at value (index.android.bundle:36:3685)\n    at anonymous (index.android.bundle:36:841)\n    at value (index.android.bundle:36:2939)\n    at value (index.android.bundle:36:813)"}
 E/com.amplitude.api.AmplitudeClient: context cannot be null, set context with initialize() before calling logEvent()
/JitsiMeetSDK: [features/overlay] The conference will be reloaded after 10 seconds.
/JitsiMeetSDK: ExternalAPI Sending event: CONFERENCE_TERMINATED with data: { NativeMap: {"error":"TypeError: Network request failed"} }
I/JitsiMeetSDK: Conference terminated: {error=TypeError: Network request failed}

Please help me

**Comment by Echolon** [comment] 2020-08-03 15:44
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed** 2020-08-03 15:44 UTC
Labels: question

**Comment by anjanabnath** [comment] 2020-08-04 06:46
Hi,

This is not a question. Its an issue that happened while connecting to live streaming in jitsi. Please have a look at this issue and help me pls

**Comment by Echolon** [comment] 2020-08-04 07:56
Then please fill out the issue template first and replace it in your first message. Ping me and I will reopen
