### ISSUE TITLE
Cannot change audio output volume/mute in Android (loudspeaker mode)

### ISSUE THREAD

**Issue by rugk** [jitsi/jitsi-meet#7998] opened 2020-10-28 22:28 UTC
### Description:
In Android the system audio output settings do have no effect when you use the volume sliders in the loude speaker mode.

### Steps to reproduce:

1. Get into a call.
2. Use loud speaker.
3. Frantically press "volume down" keys, so you do not need to hear the output.

By default you change the "call volume", which is correct IMHO. But you can also try to change the media volume.

### Expected behavior:

If the call volume is 0, I should hear nothing.

### Actual behavior:

No matter what I do, I always hear the same volume.

### Server information:

Does not matter.

### Client information:

- Browser / app version: 20.4.1
- Operating System: Android 10

### Additional information:

If you use Bluetooth headphones or earpiece.

**Comment by saghul** [comment] 2020-11-27 15:01
Please test the latest beta (20.6.0, just rolled out) and let us know how it goes.

Closing as a duplicate of https://github.com/jitsi/jitsi-meet/issues/6399

**Closed by saghul** 2020-11-27 15:01 UTC
Labels: android, mobile, ui/ux

**Comment by rugk** [comment] 2020-11-27 22:21
Yeah thanks, AFAIK/IIRC (When I last tested it) it does indeed work now.
