### ISSUE TITLE
Failed to load remote config.js in iOS app

### ISSUE THREAD

**Issue by lwz7512** [jitsi/jitsi-meet#2193] opened 2017-11-18 01:05 UTC
hi, my site has deployed successfully, I'm testing ios client, but it cannot connect to conference:
```
[error][tid:com.facebook.react.JavaScript] 'Failed to load config from https://xxxx.com/config.js?room=anxioustreesabandonnowhere'
```
Yet the url is available from browser and response returned, what's the problem?
I added my site domain to app.entitlements.

any other missed config?

**Comment by lyubomir** [comment] 2017-11-18 05:39
I get NET::ERR_CERT_COMMON_NAME_INVALID from Google Chrome for https://xxxx.com/config.js?room=anxioustreesabandonnowhere. Probably you're getting the same on iOS. You need a valid certificate for your deployment in order for the iOS client to work.

**Comment by lwz7512** [comment] 2017-11-18 08:27
@lyubomir hi, I commented the domain with xxx for privacy, the original error is:

```
'Failed to load config from https://runbytech.com/config.js?room=hardfungihurryhigh', 
{ [TypeError: Network request failed]
  line: 94,
  column: 6987,
  sourceURL: 'file:///var/containers/Bundle/Application/70F0539C-C910-4DA7-BEBF-E5CCCD9EFE64/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle' }
```

what's wrong?

**Comment by lyubomir** [comment] 2017-11-20 04:59
I successfully created a conference at https://runbytech.com/lmarinov between Jitsi Meet for Android 1.12.63 on Samsung S8 with Android 7 and Google Chrome on MacBook with macOS High Sierra. I'll test on iOS tomorrow as well but, in the meantime, what's the version of iOS on which you get the `Network request failed` please?

**Comment by lwz7512** [comment] 2017-11-20 06:55
I'm running the iOS version in my iPad mini, os version is 9.3.5

**Comment by saghul** [comment] 2017-11-20 09:57
I cannot connect to your server using Safari on macOS or iOS 0.3.5 or 11. Are you able to connect with regular Safari? Given the server cuts the connection, I wonder if it has to with TLS parameter incompatibilities. FTR, here is the error I also get with curl:

~~~
curl -vvi https://runbytech.com/lmarinov
*   Trying 121.52.229.241...
* TCP_NODELAY set
* Connected to runbytech.com (121.52.229.241) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: runbytech.com
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /lmarinov HTTP/1.1
> Host: runbytech.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* SSLRead() return error -9806
* Closing connection 0
curl: (56) SSLRead() return error -9806
~~~

**Comment by lwz7512** [comment] 2017-11-20 11:41
@saghul I cannot open the url with safari too....

**Comment by saghul** [comment] 2017-11-20 12:45
There is your problem then. Maybe check if you are sending the intermediate CA certs, I've seen problems related to this...

**Comment by lwz7512** [comment] 2017-11-21 05:21
what shall I do next?

**Comment by lwz7512** [comment] 2017-11-22 03:22
@saghul I solved the certificate problem for disordered configuration, then safari can visit the site.

but when I'm joining the room, the iOS client turned to black screen, the Xcode console report:

```
2017-11-22 11:13:36.928 [error][tid:com.facebook.react.JavaScript] Error: Provided an image that is available locally already.

This error is located at:
    in t
    in t
    in RCTView
    in t
    in t
    in Connect(t)
    in RCTView
    in RCTView
    in TouchableHighlight
    in t
    in t
    in Connect(t)
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in RCTView
    in t
    in t
    in r
    in Connect(r)
    in Connect(Connect(r))
    in RCTView
    in RCTView
    in TouchableWithoutFeedback
    in t
    in o
    in Connect(o)
    in RCTView
    in t
    in Connect(t)
    in r
    in t
    in n
    in t
    in RCTView
    in RCTView
    in t
2017-11-22 11:13:37.034 [error][tid:com.facebook.react.JavaScript] '[modules/xmpp/strophe.util.js]', '<r>: ', 'Strophe: value@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:502:3253\nvalue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:502:3407\nl@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:59:10696\nc@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:59:11326\nc@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:59:14216\nT@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:59:17029\nl@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:60:81\nd@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:60:641\nh@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:60:1584\nT@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:60:4353\nP@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:60:3717\nenqueueSetState@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:59:12480\nsetState@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:16:2511\nonStateChange@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:537:3920\n[native code]\nnotify@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:540:245\nnotifyNestedSubs@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:540:763\n[native code]\nonStateChange@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:537:3946\n[native code]\nc@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:457:739\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:853:174\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:961:776\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:955:1299\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:951:576\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:920:150\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:898:466\ni@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:906:74\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:906:2308\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:860:628\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:850:449\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:848:220\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:846:554\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:843:329\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:841:703\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:833:798\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:829:596\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:815:1596\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:804:1031\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:634:345\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:581:2895\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:577:200\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:483:847\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:573:794\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:570:1688\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:567:1533\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:530:659\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:487:1157\ndispatch@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:474:295\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:311:1627\nemit@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:412:1082\nonMemberJoined@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:420:22216\n[native code]\nemit@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:412:969\nvalue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:428:9758\nvalue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:428:2201\n[native code]\nrun@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:409:27913\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:410:4171\nforEachChild@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:409:19678\n_dataRecv@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:410:4013\n[native code]\n_onRequestStateChange@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:410:22813\n[native code]\n[native code]\nvalue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:82:1502\nvalue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:81:6214\nvalue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:81:2969\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:81:5303\nvalue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:48:1281\nvalue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:29:2853\nfile:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:29:280\nvalue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:29:2304\ncallFunctionReturnFlushedQueue@file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:29:252'
2017-11-22 11:13:37.059 [error][tid:com.facebook.react.JavaScript] '[modules/xmpp/strophe.util.js]', '<r>: ', 'Strophe: error: undefined file:///var/containers/Bundle/Application/63DF5413-4A04-4B47-BF32-F178BBEECE92/kpmg-meet.app/Frameworks/JitsiMeet.framework/main.jsbundle:502 - Error: Error: Provided an image that is available locally already.\n\nThis error is located at:\n    in t\n    in t\n    in RCTView\n    in t\n    in t\n    in Connect(t)\n    in RCTView\n    in RCTView\n    in TouchableHighlight\n    in t\n    in t\n    in Connect(t)\n    in RCTScrollContentView\n    in RCTScrollView\n    in ScrollView\n    in RCTView\n    in t\n    in t\n    in r\n    in Connect(r)\n    in Connect(Connect(r))\n    in RCTView\n    in RCTView\n    in TouchableWithoutFeedback\n    in t\n    in o\n    in Connect(o)\n    in RCTView\n    in t\n    in Connect(t)\n    in r\n    in t\n    in n\n    in t\n    in RCTView\n    in RCTView\n    in t'

```

is it a bug?

**Comment by saghul** [comment] 2017-11-22 07:40
I'm sorry, I have never seen such an error so I don't know :-S

**Comment by paweldomas** [comment] 2017-11-22 13:36
Sounds like it could be fixed by this commit ? https://github.com/jitsi/jitsi-meet/commit/78bc8121fff6c8791b6dde1ca9f6164ab69187c9

**Comment by lwz7512** [comment] 2017-11-23 11:00
updated but still not works...

```
Invariant Violation: View config not found for name span

This error is located at:
    in span (at PageReloadOverlay.js:28)
    in div (at PageReloadOverlay.js:27)
    in div (at OverlayFrame.js:72)
    in div (at OverlayFrame.js:69)
    in OverlayFrame (at PageReloadOverlay.js:26)
    in PageReloadOverlay (created by Connect(PageReloadOverlay))
    in Connect(PageReloadOverlay) (created by Translate(Connect(PageReloadOverlay)))
    in Translate(Connect(PageReloadOverlay)) (created by OverlayContainer)
    in OverlayContainer (created by Connect(OverlayContainer))
    in Connect(OverlayContainer) (at Conference.native.js:191)
    in RCTView (at View.js:113)
    in View (created by Container)
    in TouchableWithoutFeedback (created by Container)
    in Container (at Conference.native.js:177)
    in Conference (created by Connect(Conference))
    in Connect(Conference) (created by AbstractApp)
    in RCTView (at View.js:113)
    in View (at AspectRatioDetector.native.js:38)
    in AspectRatioDetector (created by Connect(AspectRatioDetector))
    in Connect(AspectRatioDetector) (at App.native.js:99)
    in Provider (at AbstractApp.js:203)
    in I18nextProvider (at AbstractApp.js:202)
    in AbstractApp (at index.native.js:124)
    in Root (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:126)
    in AppContainer (at renderApplication.js:34)

get
    ReactNativeFiber-dev.js:3033:29
createInstance
    ReactNativeFiber-dev.js:3112:110
completeWork
    ReactNativeFiber-dev.js:1965:55
completeUnitOfWork
    ReactNativeFiber-dev.js:2548:76
performUnitOfWork
    ReactNativeFiber-dev.js:2571:56
workLoop
    ReactNativeFiber-dev.js:2595:141
_invokeGuardedCallback
    ReactNativeFiber-dev.js:75:23
invokeGuardedCallback
    ReactNativeFiber-dev.js:49:40
performWork
    ReactNativeFiber-dev.js:2634:41
scheduleUpdateImpl
    ReactNativeFiber-dev.js:2768:101
scheduleUpdate
    ReactNativeFiber-dev.js:2751:38
enqueueSetState
    ReactNativeFiber-dev.js:1569:90
setState
    react.development.js:218:31
onStateChange
    connectAdvanced.js:222:24
dispatch
    createStore.js:186:6
<unknown>
    index.js:14:20
<unknown>
    middleware.js:25:16
<unknown>
    middleware.js:54:16
<unknown>
    middleware.js:24:16
<unknown>
    middleware.js:27:24
<unknown>
    middleware.js:36:16
_maybeSetCallOverlayVisible
    middleware.js:77:24
<unknown>
    middleware.js:43:43
<unknown>
    middleware.js:21:24
<unknown>
    middleware.js:38:16
<unknown>
    middleware.js:21:24
<unknown>
    middleware.js:18:24
<unknown>
    middleware.js:29:24
<unknown>
    middleware.js:25:24
<unknown>
    middleware.js:64:16
<unknown>
    middleware.js:56:16
<unknown>
    middleware.js:133:16
<unknown>
    middleware.js:57:16
<unknown>
    middleware.js:21:16
_conferenceFailedOrLeft
    middleware.js:124:24
<unknown>
    middleware.js:55:39
<unknown>
    middleware.js:21:16
<unknown>
    middleware.js:39:16
<unknown>
    middleware.js:64:16
<unknown>
    middleware.js:35:16
<unknown>
    middleware.js:127:16
<unknown>
    middleware.js:84:16
<unknown>
    middleware.js:34:16
dispatch
    applyMiddleware.js:45:27
<unknown>
    actions.js:61:30
emit
    lib-jitsi-meet.min.js:2:98367
emit
    lib-jitsi-meet.min.js:2:98615
value
    lib-jitsi-meet.min.js:2:639156
value
    lib-jitsi-meet.min.js:2:630999
run
    lib-jitsi-meet.min.js:2:27832
<unknown>
    lib-jitsi-meet.min.js:2:36113
forEachChild
    lib-jitsi-meet.min.js:2:19599
_dataRecv
    lib-jitsi-meet.min.js:2:35955
_onRequestStateChange
    lib-jitsi-meet.min.js:2:54739
dispatchEvent
    event-target.js:172:43
setReadyState
    XMLHttpRequest.js:540:23
__didCompleteResponse
    XMLHttpRequest.js:381:25
<unknown>
    XMLHttpRequest.js:487:16
emit
    EventEmitter.js:182:12
__callFunction
    MessageQueue.js:306:47
<unknown>
    MessageQueue.js:108:26
__guard
    MessageQueue.js:269:6
callFunctionReturnFlushedQueue
    MessageQueue.js:107:17
```

**Comment by saghul** [comment] 2017-11-23 13:54
Ah, you are on mobile and there is an error which is trying to show the page reload overlay, which is not currently implemented.

The problem is that your video bridge is down. Test your installation with a browser and you'll see a " CONFERENCE FAILED: conference.videobridgeNotAvailable" error.

**Comment by saghul** [comment] 2017-11-23 13:55
I'm going to close this since it's not a problem in the app but a problem in the deployment.

**Closed by saghul** 2017-11-23 13:55 UTC
Labels: project:react-native

**Comment by lwz7512** [comment] 2017-11-24 07:46
@saghul how do i fix the problem? i din't see the CONFERENCE FAILED error, can u give some clues to restart the bridge?

**Comment by saghul** [comment] 2017-11-24 09:43
I saw the problem when testing with 2 browsers. You can restart the jvb by doing this: `sudo systemctl restart jitsi-videobridge.service`

**Comment by lwz7512** [comment] 2017-11-25 06:08
i use ubuntu14.04, it has not systemctl, so i use service cmd, but the bridge service not found:
```
$ service jitsi-videobridge.service restart
jitsi-videobridge.service: unrecognized service
```
then i found the jvb process:
```
root@agfqrkix:/home/nono# ps -ef|grep video
jvb      13223     1  0 Nov16 ?        00:41:47 java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.library.path=/usr/share/jitsi-videobridge/lib/native/linux-64 ...
```
i didn't find any instructions to manage the process in https://github.com/jitsi/jitsi-videobridge/tree/master/doc , is it missed?

**Comment by saghul** [comment] 2017-11-25 20:03
If you are not using systemd then you can do it via `/etc/init.d/jisti-videobridge restart`. Even if its running it may have gotten stuck.

**Comment by saghul** [comment] 2017-11-25 20:04
> i didn't find any instructions to manage the process in https://github.com/jitsi/jitsi-videobridge/tree/master/doc , is it missed?

There is no need to do anything special.
