### ISSUE TITLE
Multiple Avatars are created

### ISSUE THREAD

**Issue by ijoshivaibhav** [jitsi/jitsi-meet#7200] opened 2020-06-30 10:04 UTC
### Description:
When participant left the meeting and rejoins previous avatar remains in Jitsi Meet View

### Steps to reproduce:

1.  Join Room
2. Leave the room without pressing Hang up button 
3.  Launch Application Rejoin Same Room again 
4. Now there are two Avatars  of same person

### Expected behavior:
Multiple avatars should not be shown

### Actual behavior:
Multiple Avatars of same participant are shown

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

### Additional information:
Using SDK 2.9.0 for android

**Comment by ijoshivaibhav** [comment] 2020-06-30 13:08
@saghul Please help

**Comment by ijoshivaibhav** [comment] 2020-06-30 13:09
![Screenshot_20200630-183446_illumnus](https://user-images.githubusercontent.com/45067950/86129884-fef3b500-bb00-11ea-9f4f-800a6d0c5a5e.jpg)

**Comment by l3d00m** [comment] 2020-06-30 16:21
Please do not ping individual members of the team, this'll definitely not get you faster support and is kinda rude for a free product.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by l3d00m** [comment] 2020-06-30 16:22
Is this happening on other OS than android as well?

**Comment by Echolon** [comment] 2020-06-30 21:47
@ijoshivaibhav please be reminded that this is a public service, as you uploaded private pictures.

**Comment by ijoshivaibhav** [comment] 2020-07-01 03:52
Yes i will take care of that.
Thanks for pointing out.

**Comment by ijoshivaibhav** [comment] 2020-07-01 03:53
I am so sorry if i disturbed you guys.
I will not make it happen again.

**Comment by ijoshivaibhav** [comment] 2020-07-01 03:54
We are developing on android so i am not aware of that.

**Comment by ijoshivaibhav** [comment] 2020-07-02 06:00
> 
> 
> Is this happening on other OS than android as well?

Any suggetions?.. I am stuck here..

**Comment by saghul** [comment] 2020-07-02 06:33
Are you actually leaving the conference. The avatar would remain there if the user left the conference abruptly, then it would be detected after a timeout.

**Comment by ijoshivaibhav** [comment] 2020-07-02 06:37
> 
> 
> Are you actually leaving the conference. The avatar would remain there if the user left the conference abruptly, then it would be detected after a timeout.

Thank you  for your response.
Yes i am leaving the conference. after what time it detects that user left the conference?

**Comment by l3d00m** [comment] 2020-07-12 21:05
Btw, this is a duplicate of #7084. Please use that issue for further comments.

**Closed by l3d00m** 2020-07-12 21:05 UTC
Labels: android, mobile, ui/ux
