### ISSUE TITLE
error in jitsi-meet installation in ubuntu 18

### ISSUE THREAD

**Issue by TivanDev** [jitsi/jitsi-meet#6919] opened 2020-05-30 18:59 UTC
i have this error in ubuntu 18
`root@conference:~# sudo apt-get update
Hit:1 http://mirror.hetzner.de/ubuntu/packages bionic InRelease
Hit:2 http://mirror.hetzner.de/ubuntu/packages bionic-updates InRelease
Hit:3 http://mirror.hetzner.de/ubuntu/packages bionic-backports InRelease
Hit:4 http://mirror.hetzner.de/ubuntu/packages bionic-security InRelease
Ign:5 https://download.jitsi.org stable/ InRelease
Err:6 https://download.jitsi.org stable/ Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2001:660:2402::22 443]
Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:8 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists... Done
E: The repository 'https://download.jitsi.org stable/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by luixxiul** [comment] 2020-05-30 19:11
Duplicate of https://github.com/jitsi/jitsi-meet/issues/6918

**Closed by luixxiul** 2020-05-30 19:11 UTC
Labels: duplicate
