### ISSUE TITLE
Require moderator to admit waiting attendees on secure domain to prevent lobby bypass

### ISSUE THREAD

**Issue by Shotster** [jitsi/jitsi-meet#7676] opened 2020-09-10 03:19 UTC
**Is your feature request related to a problem you are facing?**
As described [here](https://community.jitsi.org/t/lobby-easily-bypassed-by-arriving-early/77787/3?u=shotster), the new lobby feature, while a great concept, is trivial to bypass on a secure domain by simply arriving early. This is because anyone who is waiting is automatically admitted to the room once the moderator authenticates and enters the room. A room “bomber” would simply have to know the room name, arrive early, and wait for the moderator to log in.

**Describe the solution you'd like**
If, after authenticating, the moderator still had to admit each waiting participant, the problem would be solved. There could be an "Admit all" option to expedite the process if need be.

**Describe alternatives you've considered**
Another way to think about it is, if there is one or more attendees waiting when the moderator arrives, then they should have to be explicitly admitted by the moderator.

**Comment by rickgoud** [comment] 2020-09-10 03:33
Great suggestion! Indeed a quite serious issue that could be solved by the approach above. Isn't it possible to turn on lobby by default (on server for all, or for specific room with URL parameter)? That would be a short term fix?

**Comment by Shotster** [comment] 2020-09-10 05:15
Yeah, my use case is for an online tutoring service, mostly adults tutoring young children - usually small groups or one-to-one. The same room name/URL would be reused on an ongoing basis, and I don’t want to mess with passwords. (That‘s just something else to remember and to have to change periodically.)

Especially when it comes to kids, privacy and security are of paramount importance. If no one could get in until the instructor let them in, that would be ideal. Were it not for the bypass issue, the lobby feature would be perfect.

I don’t know if there’s a default setting or URL parameter, but I haven’t run across any such documentation. If there is such a feature, I would like to try it out.

**Comment by saghul** [comment] 2020-09-10 06:35
There currently is no way to turn on lobby by default with a URL parameter. Marking this as a feature request.

**Comment by Shotster** [comment] 2020-09-10 15:13
> Marking this as a feature request.

Sounds good.

I would suggest, though, that the fact the lobby can be so easily bypassed is - at the very least - an oversight.

**Comment by heikar** [comment] 2020-09-17 19:23
This feature would be nice for rooms without lobby but with password protection.
Like in #7641 the host can send the invitations to the guests and each guest needs the password to enter the room.

**Closed** 2020-12-29 15:11 UTC
Labels: feature-request, wontfix

**Comment by khorben** [comment] 2021-02-05 00:56
The issue is still there and a fix would be great.
