### ISSUE TITLE
(ANDROİD) Cannot get property 'mavenRepo' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by gokhanakcam** [jitsi/jitsi-meet#4895] opened 2019-11-26 07:30 UTC
I get this error when trying to get build for Android on MacOS.

Android Studio 3.5.2
---------------------------------
  dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'io.fabric.tools:gradle:1.27.0'
    }

---------------------------------
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
--------------------------------

<img width="1679" alt="Ekran Resmi 2019-11-26 10 23 59" src="https://user-images.githubusercontent.com/39699114/69607757-01f06980-1037-11ea-971f-28408efaa48f.png">

**Comment by saghul** [comment] 2019-11-26 08:43
Have you made changes to the code? We don't use Gradle 5: https://github.com/jitsi/jitsi-meet/blob/fb3a832a52065f13d6b2f05fe0c221e27e313528/android/gradle/wrapper/gradle-wrapper.properties#L6

**Comment by gokhanakcam** [comment] 2019-11-26 09:20
Dear Saghul,
Thank you very much for todo point answer. We passed Maven error. Now we are getting the following error what could be the reason for that and how can we correct it.


<img width="1679" alt="Ekran Resmi 2019-11-26 12 18 00" src="https://user-images.githubusercontent.com/39699114/69615974-decdb600-1046-11ea-9b76-6223bfda8939.png">

**Comment by saghul** [comment] 2019-11-26 10:05
Ok, then I'm closing this one.

**Closed by saghul** 2019-11-26 10:05 UTC

**Comment by thiagobrez** [comment] 2019-12-16 12:49
@saghul I'm having the same `Cannot get property 'mavenRepo' on extra properties extension as it does not exist` error. Changing `distributionUrl` to gradle 4 warns me that minimum version is gradle 5.4.1.

graddle-wrapper.properties
```
#Mon Dec 16 10:02:21 BRST 2019
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```

Project build.gradle
```
    if (project.name.startsWith('react-native-')) {
        apply plugin: 'maven-publish'
        publishing {
            publications {}
            repositories {
                maven {
                    url rootProject.ext.mavenRepo
                    if (!rootProject.ext.mavenRepo.startsWith("file")) {
                        credentials {
                            username rootProject.ext.mavenUser
                            password rootProject.ext.mavenPassword
                        }
                    }
                }
            }
        }
    }

...

ext {
    buildToolsVersion = "28.0.3"
    compileSdkVersion = 28
    minSdkVersion    = 21
    targetSdkVersion = 28
    supportLibVersion = "28.0.0"

    // The Maven artifact groupdId of the third-party react-native modules which
    // Jitsi Meet SDK for Android depends on and which are not available in
    // third-party Maven repositories so we have to deploy to a Maven repository
    // of ours.
    moduleGroupId = 'com.facebook.react'

    // Maven repo where artifacts will be published
    mavenRepo = System.env.MVN_REPO ?: ""
    mavenUser = System.env.MVN_USER ?: ""
    mavenPassword = System.env.MVN_PASSWORD ?: ""

    // Libre build
    libreBuild = (System.env.LIBRE_BUILD ?: "false").toBoolean()
}
```

**Comment by thiagobrez** [comment] 2019-12-16 12:50
@gokhanakcam How did you solve the maven error?

**Comment by saghul** [comment] 2019-12-16 12:58
That’s not correct, you can use Gradle 4 just fine.

**Comment by thiagobrez** [comment] 2019-12-16 13:04
@saghul Please look:

![image](https://user-images.githubusercontent.com/26878038/70909010-51e59f00-1feb-11ea-9f3c-3ee732dfdb8b.png)

**Comment by thiagobrez** [comment] 2019-12-16 13:48
Managed to make it work by changing distributionUrl to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` and dependency`classpath 'com.android.tools.build:gradle:3.5.1'` to `classpath 'com.android.tools.build:gradle:3.3.2'` in project build.gradle.

**Comment by saghul** [comment] 2019-12-16 15:57
Isn’t that how we already have it in master? Is have never seen AS complain about a minimum required Gradle version unless you had raised the plugin version.

There are issues with 3.5, so don’t update to that. Also there is no need AFAICT.

**Comment by developerashish01** [comment] 2020-06-12 16:43
Caused by: groovy.lang.MissingPropertyException: Cannot get property 'mavenRepo' on extra properties extension as it does not exist

I am getting same error, any solution?

**Comment by ccs1428** [comment] 2020-06-15 03:05
> Caused by: groovy.lang.MissingPropertyException: Cannot get property 'mavenRepo' on extra properties extension as it does not exist
> 
> I am getting same error, any solution?

Please confirm gradle confirguration.

distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip and dependency

classpath 'com.android.tools.build:gradle:3.3.2' in project build.gradle.

Please change this and build.

**Comment by AbhisekhD** [comment] 2020-06-16 06:40
> > Caused by: groovy.lang.MissingPropertyException: Cannot get property 'mavenRepo' on extra properties extension as it does not exist
> > I am getting same error, any solution?
> 
> Please confirm gradle confirguration.
> 
> distributionUrl=https://services.gradle.org/distributions/gradle-4.10.2-all.zip and dependency
> 
> classpath 'com.android.tools.build:gradle:3.3.2' in project build.gradle.
> 
> Please change this and build.

I have  the above confriguration and I'm still getting the  error!

**Cannot get property 'mavenRepo' on extra properties extension as it does not exist**

**Comment by AbhisekhD** [comment] 2020-06-16 06:42
@thiagobrez How did you solved the : 
 Cannot get property 'mavenRepo' on extra properties extension as it does not exist.

**Comment by ccs1428** [comment] 2020-06-16 07:15
> @thiagobrez How did you solved the :
> Cannot get property 'mavenRepo' on extra properties extension as it does not exist.
Please update and gradle sync

distributionUrl=https://services.gradle.org/distributions/gradle-4.10.1-all.zip and dependency

classpath 'com.android.tools.build:gradle:3.3.2' in project build.gradle.

**Comment by gayankalhara** [comment] 2020-06-19 23:08
This worked for me...

**gradle-wrapper.properties**
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`

**build.gradle**
`classpath 'com.android.tools.build:gradle:3.3.2'`

After updating this, run Build -> Clean Project and then Build -> Rebuild Project. It should work!

**Comment by ngdlmk** [comment] 2020-06-28 10:42
what if need to use higher version of gradle. For example I want to embed jitsi app to my native app. But my native app min gradle version is 5.4.1 but jitsi project is using 4.10.1 so how I can I increase jitsi's gradle version

**Comment by htcheng** [comment] 2020-07-02 03:36
@ngdlmk - Found this in Stackoverflow: https://stackoverflow.com/questions/53498161/unsupported-method-androidproject-getvariantnames-in-android-studio-3-4/53511998#53511998

You need to disable this setting in Android Studio:

File > Settings(or Preferences for previous versions) > Experimental > Only sync active variant

and then follow what @gayankalhara said above. This should solve your problem on minimum Gradle versions. Fixed the problem for me.
