### ISSUE TITLE
Safari: Video freezes when activating camera while screen sharing

### ISSUE THREAD

**Issue by git-teufel** [jitsi/jitsi-meet#7720] opened 2020-09-18 09:51 UTC
Device: MacBook Pro
OS: MacOS Catalina
Browser: Safari Version 13.05.5

Problem: On Safari, when sharing the screen and starting the camera the video freezes, so screen sharing with camera is not working. Reproducible on https://meet.jit.si and our custom deployment.

Steps to reproduce:
1. Share Screen
2. Share Camera

Is this something Jitsi can fix or has it to be fixed by Safari?
Since Firefox has still so many bugs with Screen Sharing, I would be sad if the only two reliable options are Chrome and Edge.

**Comment by pgenderson** [comment] 2020-09-19 20:37
You mean when the sharer ends their screenshare and their camera reactivates (or is supposed to reactivate)? I have the same problem with Mac when the sharer's browser isn't Chrom(e/ium) (and the Mac can't be using Safari because at least on my end, screenshare doesn't work at all when a recipient is using Safari (if I recall correctly)).

**Comment by git-teufel** [comment] 2020-09-25 11:45
No you do not describe the same problem as me.
It is possible for one person to share the screen and at the same time share the camera. By first sharing the screen and then activating the camera, wich is displayed as an overlay in the corner of the shared content. This only works in Chrome and Edge. In safari as soon as the camera is enabled while sharing, the video freezes.

**Comment by pgenderson** [comment] 2020-09-29 20:29
@git-teufel that's probably a browser issue, as the Jitsi devs develop for Chromium-based browsers first and then fix bugs occurring on other browsers.

**Comment by jallamsetty1** [comment] 2020-09-29 21:34
> @git-teufel that's probably a browser issue, as the Jitsi devs develop for Chromium-based browsers first and then fix bugs occurring on other browsers.

I agree with this. This is a browser limitation on Safari. We will have to disable presenter mode on Safari until it is properly supported there.

**Comment by jallamsetty1** [comment] 2020-09-29 22:00
@git-teufel you mentioned that Firefox still has so many bugs with screensharing ? Is it what @pgenderson mentioned or is it a different issue ? I will be actively working on fixing the pending FF/Safari screensharing issues, so if you see any new issue please bring it to my attention. Also please note that we have received reports of bandwidth estimation issue with FF80 which we are actively investigating so if you haven't upgraded already, please continue to use FF79 and older versions and not upgrade the browser.

**Comment by git-teufel** [comment] 2020-10-02 14:36
@jallamsetty1  Thank you for your reply. On Firefox we encountered several issues, that is why we currently do not advise our conference guests to use it, tested was 2-3 weeks ago on mac and windows. Among them:

- Often when joining a conference where a screensharing takes place, it was not visible for the newly entered firefox user. The synchronisation seems to be missing here. Also sometimes there were just artifacts instead of the video signal.

- When sharing the screen on firefox, the browser does not detect changes like when a power point presentation is entering "presentation/full screen" mode, the other users would not see the power point presentation but instead the power point program in the background, wich is why the users thinks the stream is frozen. Only way around this is to stop and start screensharing after applications entered full screen mode.

**Comment by jallamsetty1** [comment] 2020-10-02 20:36
> @jallamsetty1 Thank you for your reply. On Firefox we encountered several issues, that is why we currently do not advise our conference guests to use it, tested was 2-3 weeks ago on mac and windows. Among them:
> 
> * Often when joining a conference where a screensharing takes place, it was not visible for the newly entered firefox user. The synchronisation seems to be missing here. Also sometimes there were just artifacts instead of the video signal.

This shouldn't be happening, I will try to reproduce it and check whats going wrong there.

> * When sharing the screen on firefox, the browser does not detect changes like when a power point presentation is entering "presentation/full screen" mode, the other users would not see the power point presentation but instead the power point program in the background, wich is why the users thinks the stream is frozen. Only way around this is to stop and start screensharing after applications entered full screen mode.

Sounds like this issue is already being tracked here - https://bugzilla.mozilla.org/show_bug.cgi?id=1663286

**Comment by jallamsetty1** [comment] 2021-01-13 20:52
This has been fixed in the latest version of the client that has been deployed on meet.jit.si now.

**Closed by jallamsetty1** 2021-01-13 20:52 UTC
Labels: browser-support, meet.jit.si, quality, wontfix
