### ISSUE TITLE
screen control share 

### ISSUE THREAD

**Issue by TapanKumarBarik** [jitsi/jitsi-meet#8351] opened 2021-01-07 11:24 UTC
\how can i give my scrren control to otherone in call same as zoom oe microsoft teams

**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by TapanKumarBarik** [comment] 2021-01-07 11:28
> Is co-browsing available ? something similar like together js or how can i give my scrren control to otherone in call same as zoom oe microsoft teams
> 
> **Is your feature request related to a problem you are facing?**
> Please describe the problem you are trying to solve.
> 
> **Describe the solution you'd like**
> Please describe the desired behavior.
> 
> **Describe alternatives you've considered**
> Please describe alternative solutions or features you have considered.

**Comment by md-work** [comment] 2021-03-04 10:22
Probably a duplicate of: [jitsi-meet-electron: Remote control return #483](https://github.com/jitsi/jitsi-meet-electron/issues/483)

**Comment by saghul** [comment] 2021-03-04 10:54
Yep.

**Closed by saghul** 2021-03-04 10:54 UTC
Labels: feature-request
