### ISSUE TITLE
Second firefox jitsi meet instance on a machine via gecko driver fails

### ISSUE THREAD

**Issue by sajidcosmo** [jitsi/jitsi-meet#3387] opened 2018-08-20 11:21 UTC
We are doing interoperability test automation and using jitsi meet web application for that. The specific scenerio where our test fails is while invoking two firefox browsers to connect to the same room from a single machine. We are met with the following exception in our test code:

```
org.openqa.selenium.WebDriverException: Failed to decode response from marionette
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'Sajids-Mac-Pro.local', ip: 'fe80:0:0:0:18f4:c972:815f:b869%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_162'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 61.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 28971, moz:profile: /var/folders/dw/6jfw81sx0h3..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 17.7.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, webdriver.remote.sessionid: e4a15ade-a3b6-ec41-8a7e-256...}
Session ID: e4a15ade-a3b6-ec41-8a7e-256cbdecbb9d

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:482)
```

We are merely trying to execute 'navigator.appVersion;'. We have experienced that it fails with the same exception no matter what we execute.

We have tried Selenium version 3.10 to 3.14 and geckodriver version 0.19.1 to 0.21.0

Any help would be appreciated!

**Comment by damencho** [comment] 2018-08-20 15:14
Recently I had tried to upgrade our grid with latest Firefox and was facing the same issue, this is not a problem of selenium or geckodriver, the problem is Firefox crashing.
Also I had reported the problem in https://bugzilla.mozilla.org/show_bug.cgi?id=1473983 and there are some thoughts on the subject at the end of the comments in: https://bugzilla.mozilla.org/show_bug.cgi?id=1472321

The only solution, for now, is to stick with Firefox 57. 

Firefox 58 to 60 was not an option for us because of: https://bugzilla.mozilla.org/show_bug.cgi?id=1434477, and this was fixed in Firefox 61, but it now randomly crashes with bug 1409167.

Hope this helps.

**Closed by damencho** 2018-08-20 15:14 UTC
