### ISSUE TITLE
(iOS only) Black empty screen in conference on repeated change of participants list

### ISSUE THREAD

**Issue by iospro** [jitsi/jitsi-meet#9823] opened 2021-08-28 17:22 UTC
iOS SDK (3.8.1 and earlier) gives black screen when I try to re-enter in the existing conference with 2 participants (I'm the third one).

In the log we have
`TypeError: undefined is not an object (evaluating 'A.id')`
It is from Thumbnail.js, line 130

It seems that sometimes `participant` is `undefined` in the context of `function Thumbnail(props: props)`.

If we start SDK the first time then it's OK. But if we exit from conference and back again then we can get the black empty screen. It may even occur if some one from other participants exit and enter again (black screens will appear on iPhones in conference).

Also systematically after every re-enter to any conference iOS has multiplication of other participants.
At the same time in web in android we have current participants list.

All of this seems to be local iOS sdk problem, maybe due to local cache.

This problem arises only with token authorisation.
There are no problems with guest access.

**Comment by saghul** [comment] 2021-08-28 18:04
Thanks for the report!

**Comment by saghul** [comment] 2021-08-28 18:05
cc @hristoterezov @damencho I think this is fixed in master, but I'll take a look none the less.

**Comment by damencho** [comment] 2021-08-28 18:13
@saghul Nope, I had two PRs of avoiding those undefined, then I found out the problem is actually mixing selectors and connect function and fixed that on the web, by moving the problem component to use connect, so I would guess same is happening and there and needs to be fixed the same way by not mixing both approaches when the components are looking up participants by id. 

https://github.com/jitsi/jitsi-meet/commit/bcc326c1505423d8184a56712edfd64257b428e2

**Comment by iospro** [comment] 2021-08-28 21:23
Thanks, hope to get working solution ASAP.
Web works fine, Android as well.
Looks strange that iOS has this problem on the common js level

**Comment by saghul** [comment] 2021-08-29 07:12
Indeed. Just to make sure, what steps are you following to reproduce this?

**Comment by iospro** [comment] 2021-08-29 11:56
You can try three users. Two of them are from web, one is from iOS 3.8.1 sdk.

all of them should enter with token (we have the problem only in auth mode).

Conference starts in the room of any web participant. Another web user and iOS user enter that room.

then iOS user and web user leave the room.
Then iOS user re-enter the room.
And finally web user come back to the room and iOS catches black screen and the error described earlier.

I’ve described one of the possible scenirio

**Comment by iospro** [comment] 2021-08-29 12:19
The very close issue is described here
https://github.com/jitsi/jitsi-meet/issues/9784

**Comment by saghul** [comment] 2021-08-30 07:30
> the main thing is that iOS user must re enter the room (without relaunch mobile app, jitsi shared object should be alive during the experiment)

This is how the JItsi Meet app in the store does it, for example. Can you reproduce the problem with the latest beta?

**Comment by iospro** [comment] 2021-08-30 19:28
What do you mean by the latest beta?

I built Framework manually from branch fix-participants-pane-list and it seems to work much better.
No empty screen and no Thumbnail multiplication after re-enter.

As I see this commit is now in master branch and I can rebuild it from master.

Cocoa pod still gives 3.8.1 (11 days ago) without patch.

**Comment by saghul** [comment] 2021-08-30 21:46
I meant the Jitsi Meet beta app. But yeah, if you built master this should've been fixed.

**Comment by iospro** [comment] 2021-09-04 17:42
In the last lib version on App Store upload we get the following:

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK: addStream:, channelId, initWithBuffer:rotation:timeStampNs:, initWithURLStrings:, isBinary, isPassthrough, localDescription, onSuccess:, sdp, sendData:, setCategoryID:, setChannelId:, setColor:animated:, setConfiguration:error:, streamId, typeForString:, vibrate:, videoSource. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. 

We managed to publish our new app version with this SDK, but it may result in problems in future.

**Comment by saghul** [comment] 2021-09-05 07:16
Not it won't. That's a known false positive on the Apple checks side. Nothing to worry about.

**Closed** 2022-04-30 08:34 UTC
Labels: wontfix
