### ISSUE TITLE
Jitsi crashes with "Unfortunately something went wrong" the moment any second user joins

### ISSUE THREAD

**Issue by youthpolicy** [jitsi/jitsi-meet#5706] opened 2020-04-06 09:43 UTC
## Description
Whenever a second user tries to join a session, Jitsi crashed for both users (initial hosting and second joining) with "Unfortunately something went wrong". This behaviour is persistent across browsers, apps and operating systems.

## Current behavior
Jitsi crashes when second user joins.

## Expected Behavior
Jitsi works when second user joins.

## Possible Solution
Unknown

## Steps to reproduce
---

# Environment details
Jitsi on Debian 10, worked flawlessly until update this morning.

/var/log/jitsi/jvb.log shows 
```
warning "2020-04-06 11:28:36.550 WARNING: [27] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#643: [MucClient id=shard hostname=localhost] error connecting
org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS
```

/var/log/jitsi/jicofo.log shows 
```
WARNING: [32] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
```
and 
```
SEVERE: [32] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
```

And finally /var/log/prosody/prosody.log shows
```
callcontrol.lulu.youthpolicylabs.org:component  warn    Component not connected, bouncing error for: <iq to='callcontrol.lulu.youthpolicylabs.org' id='3QU5N-39596' from='focus@auth.lulu.youthpolicylabs.org/focus4353663369260066' type='get'>
```
and
```
jitsi-videobridge.lulu.youthpolicylabs.org:component    warn    Component not connected, bouncing error for: <iq to='jitsi-videobridge.lulu.youthpolicylabs.org' id='3QU5N-39598' from='focus@auth.lulu.youthpolicylabs.org/focus4353663369260066' type='get'>
```

**Comment by funkyfuture** [comment] 2020-04-06 16:30
are you using https://github.com/jitsi/docker-jitsi-meet for your deployment?

**Comment by funkyfuture** [comment] 2020-04-06 16:32
actually, this is duplicate of #5696

**Comment by youthpolicy** [comment] 2020-04-06 16:58
> actually, this is duplicate of #5696

How so? The log messages are different, unless I am overlooking something?

**Comment by richb-hanover** [comment] 2020-04-06 22:38
I don't know if this will solve the problem, but I am now avoiding the crash with "Unfortunately..." using these steps... https://github.com/jitsi/jitsi-meet/issues/5696#issuecomment-609527186

I'm still not convinced that it's working, but I just did the install a few minutes ago, and have gotten farther.

**Comment by ageekhere** [comment] 2020-04-07 00:19
I have had this problem, everything was working for weeks then i get this connection issue. Restart the server, check if it works, restart the server again check if it works. Sometimes it can take a few restarts to fix this issue. Then it works again.

**Comment by funkyfuture** [comment] 2020-04-07 17:23
> > actually, this is duplicate of #5696
> 
> How so? The log messages are different, unless I am overlooking something?

sorry, i just focused on the issue summary / title.

> Sometimes it can take a few restarts to fix this issue.

actually, in my case a server restart is causing an issue. but again, it's another it's another issue with just the same resulting behaviour.

**Comment by youthpolicy** [comment] 2020-04-07 17:31
> sorry, i just focused on the issue summary / title.
No worries at all! Was just curious whether I had overlooked an aspect or detail.

> actually, in my case a server restart is causing an issue.
Restarting doesn't help at all here

**Comment by youthpolicy** [comment] 2020-04-07 17:33
> I don't know if this will solve the problem, but I am now avoiding the crash with "Unfortunately..." using these steps... [#5696 (comment)](https://github.com/jitsi/jitsi-meet/issues/5696#issuecomment-609527186)

Purging the entire existing installation including all configurations and reinstalling from scratch should fix the issue, but I was hoping to avoid that nuclear option… Ah well.

**Comment by bocasaythebert** [comment] 2020-04-16 12:50
Hi ! 
I got exactly the same behavior, same error logs with my fresh quick install.
Have you got news about a fix ?
@youthpolicy , did you try the purge and reinstalling from scratch ?

**Comment by youthpolicy** [comment] 2020-04-16 12:58
> @youthpolicy , did you try the purge and reinstalling from scratch ?

@bocasaythebert yes that works. From my Jitsi install notes:

# If necessary to uninstall and start over
`apt purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge2`
`apt autoremove`
`apt -y install jitsi-meet`

**Comment by bocasaythebert** [comment] 2020-04-16 13:29
@youthpolicy , thanks, it works now

I was following the uninstall guide here : https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md
They miss the "apt autoremove" command, with this command it works now

**Comment by rboba** [comment] 2020-04-16 21:25
I am getting the same error message when using the meet.jit.si web service. I get disconnected from any existing discussion rooms immediately after joining, or I get kicked out when someone else connects. I tried with various security configuration on Firefow, to no avail.

Please let me know if this is the wrong place to report.

**Comment by richb-hanover** [comment] 2020-04-17 02:16
You should try the **uninstall and start over** commands (just copy-paste the three commands) in the note above (https://github.com/jitsi/jitsi-meet/issues/5706#issuecomment-614636484)

Several people (including me) have reported that this fixed the problem. Let us know

**Comment by rboba** [comment] 2020-04-18 03:34
Sorry, I was not clear enough: this happened while I was trying to use the _remote instance_ of Jitsi Meet at meet.jit.si. I have absolutely no management rights on that instance.

Could the origin of the problem be related to the fact that I am using Firefox to connect?

**Comment by richb-hanover** [comment] 2020-04-18 11:37
My apologies. I didn't read your note carefully enough - you did mention *meet.jit.si*  I would recommend opening a new issue because this one is tied up with people who are trying to install their own server.

Note: a new version that works better with Firefox was just released. If this is still a problem (that is, tested within the last 24 hours) use a subject line like: **meet.jit.si session crashes when second user joins** to attract attention.

Provide browsers and version numbers, any other messages you see/notice, and exactly what you see when it crashes. Good luck.

**Comment by rboba** [comment] 2020-04-18 20:36
Thank you @richb-hanover for your advice. I was able to succesfully use another public instance today (with the same browser, same config) but will still report as suggested if the problem persists on the meet.jit.si instance.

**Closed** 2020-05-26 10:24 UTC

**Comment by julian70400** [comment] 2020-06-03 14:30
Hello, got exactly same problem, in same conditions (update).. Please, have a look to my thread : https://community.jitsi.org/t/can-not-invite-participant-no-bridge-available-since-last-update-debian-10/63046

**Comment by nafil-gigsboard** [comment] 2020-11-13 16:25
> ow avoiding the crash with "Unfor

this solution is without jwt auth. We need to lock the meeting creator for our own host. otherwise anyone can come and create meeting
