### ISSUE TITLE
when using Android SDK, will call 4887763385474123456??

### ISSUE THREAD

**Issue by BreakerSAMA** [jitsi/jitsi-meet#7407] opened 2020-07-27 06:48 UTC
when using Android SDK, will call number:4887763385474123456

https://github.com/jitsi/jitsi-meet-sdk-samples/

I just want to use video conferencing. Don't want to use the phone dialing . What should I do?

**Comment by Echolon** [comment] 2020-07-27 17:35
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by Echolon** [comment] 2020-07-27 17:36
@saghul

**Closed by Echolon** 2020-07-27 17:35 UTC
Labels: android, mobile, question, ui/ux
