### ISSUE TITLE
Jitsi doesn't work in Firefox-based browsers

### ISSUE THREAD

**Issue by RedSteel-1** [jitsi/jitsi-meet#13839] opened 2023-09-16 19:22 UTC
### Description:

Jitsi doesn't work in Firefox-based browsers.
Meanwhile, it works in Chromium-based browsers.

### Steps to reproduce:

1. Install Mullvad and/or Librewolf.
2. Start a conference.

### Expected behavior:

Everything works.

### Actual behavior:

When I start a conference in Jitsi (with camera and mic enabled ofc), the situation is as follows:

- I can see my local video and the mic levels on Jitsi in the browser.
- The participants don't see me and likely don't hear me.
- I don't see/hear the participants either.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version: Mullvad v12.5.4 (latest), Librewolf v116 (latest)
- Operating System: Windows 7

**Comment by damencho** [comment] 2023-09-16 20:10
Do you experience the same on meet.jit.si?

Upload js console logs from the browser

**Comment by damencho** [comment] 2023-09-17 02:32
> > Do you experience the same on [meet.jit.si](http://meet.jit.si/)?
> 
> I have no idea how it is on [meet.jit.si](http://meet.jit.si/), it requires some weird login so I am not able to use it.

Then what is the jitsi-meet version you use?


> 2023-09-16T21:35:34.398Z [modules/browser/BrowserCapabilities.js] This appears to be firefox, ver: 102.0 Logger.js:154:22

That is a pretty old version of Firefox, were you able to try something more recent?

**Comment by saghul** [comment] 2023-09-17 11:14
That link doesn't tell us what server version they installed.

It would be best if you could test with meet.jit.si since it always runs the latest.

**Comment by saghul** [comment] 2023-09-17 13:57
Once you click on login you'll be presented with a site which allows you to login with either Google, Facebook or GitHub. After logging in you'll be redirected to the meeting, but authenticated.

You only need to do this for the first participant which joins the meeting.

**Comment by saghul** [comment] 2023-09-17 14:28
You are using GitHub right now.

**Comment by HERCLLC** [comment] 2023-09-21 18:55
"Once you click on login you'll be presented with a site which allows you to login with either Google, Facebook or GitHub. After logging in you'll be redirected to the meeting, but authenticated.

You only need to do this for the first participant which joins the meeting."

This is terrible, buggy, and inefficient. Change it back to what it was before.

**Comment by Codeshark-NET** [comment] 2023-09-24 11:12
I just tested the issue using MullVad on Windows, together with Firefox/Chrome too, specifically on meet.jit.si.

Apart from a few bandwidth drops, which seem unrelated, both the microphone and camera worked as expected. I did notice that Firefox performed slightly better compared to Mullvad, which could be due to some requests being blocked by the VPN.

If you're not using meet.jit.si and have customized your installation, could you please provide more details? It's possible that the issue isn't directly related to Jitsi but rather due to specific security settings in your environment.

Otherwise, I think we should close this one.

**Comment by saghul** [comment] 2023-09-24 12:18
I'll reopen if you can provide logs of a failed meeting, otherwise theee is nothing actionable here.

**Comment by Codeshark-NET** [comment] 2023-09-24 12:23
> > I just tested the issue using MullVad on Windows, together with Firefox/Chrome too
> 
> Wait, was it Mullvad Browser, or Mullvad the VPN thing?

Mullvad browser. 

> You mean the meeting participants could see and hear you, and you could see and hear them?

Yep! 

> Which VPN do you mean, there is no VPN, Mullvad is basically Tor browser without the Tor component

That's my mistake, I was referring to the browser and its security features.

**Comment by Codeshark-NET** [comment] 2023-09-24 12:38
> Anyway, this is very strange that you got it work in Mullvad Browser, did you alter any default parameters or was it a fresh vanilla profile?

No, I installed it fresh to check this exact issue. Couldn't replicate. I'm afraid you may have to be open to it being something on your end. 

I'll keep an eye out for your further testing here, but until then, @saghul is right that there's not much we can do outside of this.

**Comment by saghul** [comment] 2023-11-15 11:30
I don't think the operating system is the problem but the version, can you confirm?

**Comment by Knudch** [comment] 2023-11-15 12:34
Fedora 37 kernel 6.5.7-100, Firefox 118.0.2  --- works ok
Fedora 37 kernel 6.5.7-100, Firefox 106.0.1  --- not working
Fedora 36 kernel 6.2.15.100, Firefox 112.0.1 ---- not working
Fedora 32 kernel 5.11.22-100, Firefox 88.0.1---- not working
OpenSuse tumbleweed kernel 6.5.9-1, Firefox 119.0 --- ok

So maybe Firefox 115 => works

**Comment by saghul** [comment] 2023-11-15 14:07
Ping @jallamsetty1

**Comment by jallamsetty1** [comment] 2023-11-15 14:20
Thanks @damencho, I will try with FF 102 ESR.

**Closed** 2023-11-15 15:54 UTC

**Comment by Knudch** [comment] 2023-11-17 09:47
When will this fix float into meet.jit.si ?

**Comment by jallamsetty1** [comment] 2023-11-20 15:16
Hopefully sometime this week.

**Comment by BlueOwlet** [comment] 2024-01-30 20:21
My jitsi installation completely started crashing every single meeting on EVERY browser yesterday. I did a clean installation of jitsi and after much configuration I managed to get it back to work. However; I has completely stopped working with firefox and firefox related browsers.

I will admit I had not updated any packages since it's initial installation back in August. Moreover, I checked my traffic and found that 30% of my users are on firefox.

Is there something that changed or that could have gotten misconfigured somehow?

In between all the debugging I saw a very quick message about firefox and it doing something new maybe having to do with websockets. I've since looked for that message again but have not been able to locate it in my logs.

Any help is appreciated

**Comment by jallamsetty1** [comment] 2024-01-30 20:58
> However; I has completely stopped working with firefox and firefox related browsers.

What version of Firefox are you seeing this on? Are you seeing the same behavior on meet.jit.si as well?

**Comment by cpot** [comment] 2024-05-05 08:03
I have no more information for now but some customer using Firefox started to tell us that Jitsi (on prem) is not working anymore : continuous deconnexion . We will provide more details when we have them

**Comment by guemi** [comment] 2024-07-22 14:35
Can confirm, firefox doesn't work. Tried on multiple systems. 

Will fetch all the logs from my containers tomorrow, I've been troubleshooting this for a few hours now and didn't for ONCE think it could be the damn browser so I'mma just take the L and go home to my dog to make up. 

Be back in ~18 hours.

**Comment by jallamsetty1** [comment] 2024-07-22 14:53
@guemi Are you able to reproduce this issue on meet.jit.si? If you are not able to reproduce it there, we suggest you to update your deployments and test it again.

**Comment by guemi** [comment] 2024-07-22 14:56
I'll try, I updated to latest stable like a week ago as part of major update of infra. But I'll verify tomorrow and let you know.

Any specific things you want from the browser, or only the container logs?

I can connect, chat is working but no video or audio is coming through or received by other user.

// Emil
IT-Infrastruktur & Driftansvarig
Direkt: 019 20 63 08
Mobil: 070 532 09 18
________________________________

**Comment by jallamsetty1** [comment] 2024-07-22 15:01
Please try to reproduce the issue on meet.jit.si first. If you reproduce it there, please share the browser console logs.

**Comment by jallamsetty1** [comment] 2024-07-22 16:12
See https://github.com/jitsi/jitsi-meet/issues/5230#issuecomment-2243228897

**Comment by guemi** [comment] 2024-07-23 06:27
Just tried, I deleted all the images off the docker host and ran the stack again so it 100% pulled the images:

![bild](https://github.com/user-attachments/assets/cb5974b4-047d-4176-ba91-9ddd929abcfc)


But no dice. Firefox does not work, picture is available until someone joins, then it disappears. If I join the same meeting in Edge, it works flawlessly. Chat message from client1 and client2 works splendid.

Attached is the console output from Firefox 
. 
[jitsi console.txt](https://github.com/user-attachments/files/16344549/jitsi.console.txt)

**Comment by IliaIdakiev** [comment] 2024-07-23 10:48
> meet.jit.si works splendid with the same systems, same browsers but not on the on premises solution.
> 
> Just tried, I deleted all the images off the docker host and ran the stack again so it 100% pulled the images:
> 
> ![bild](https://private-user-images.githubusercontent.com/151639949/351209721-cb5974b4-047d-4176-ba91-9ddd929abcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzE4ODYsIm5iZiI6MTcyMTczMTU4NiwicGF0aCI6Ii8xNTE2Mzk5NDkvMzUxMjA5NzIxLWNiNTk3NGI0LTA0N2QtNDE3Ni1iYTkxLTlkZGQ5MjlhYmNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QxMDQ2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGZmYjViYTJkMTg2M2IyYzEzMzgxYjQxM2Q5Njg5NDlmODMyZDg2NTNlZDBmODAzY2M0YzhhYzEzZTU5ZGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vfi8v_USTXN_0-bf5-NRliYR9w2sTqau7a1pvtHueN4)
> 
> But no dice. Firefox does not work, picture is available until someone joins, then it disappears. If I join the same meeting in Edge, it works flawlessly. Chat message from client1 and client2 works splendid.
> 
> Attached is the console output from Firefox . [jitsi console.txt](https://github.com/user-attachments/files/16344549/jitsi.console.txt)

same here

**Comment by jallamsetty1** [comment] 2024-07-23 20:33
Can you pls compare meet.jit.si settings at https://meet.jit.si/config.js with that of your deployment and see what is different?

**Comment by guemi** [comment] 2024-07-23 20:41
These files are extremely different, the variable names and what not are not the same -is that to be expected? 

Here's a snippetof the on prem solution;


`/ Jitsi Meet configuration.
var config = {};

if (!config.hasOwnProperty('hosts')) config.hosts = {};

config.hosts.domain = 'meet.jitsi';
config.focusUserJid = 'focus@auth.meet.jitsi';

var subdir = '';
var subdomain = "";
if (subdir.startsWith('<!--')) {
    subdir = '';
}
if (subdomain) {
    subdomain = subdomain.substring(0,subdomain.length-1).split('.').join('_').toLowerCase() + '.';
}
config.hosts.muc = 'muc.' + subdomain + 'meet.jitsi';
config.bosh = '/' + subdir + 'http-bind';

// Video configuration.
//

if (!config.hasOwnProperty('constraints')) config.constraints = {};
if (!config.constraints.hasOwnProperty('video')) config.constraints.video = {};

config.resolution = 720;
config.constraints.video.height = { ideal: 720, max: 720, min: 180 };
config.constraints.video.width = { ideal: 1280, max: 1280, min: 320};
config.disableSimulcast = false;
config.startVideoMuted = 10;
config.startWithVideoMuted = false;

if (!config.hasOwnProperty('flags')) config.flags = {};
config.flags.sourceNameSignaling = true;
config.flags.sendMultipleVideoStreams = true;
config.flags.receiveMultipleVideoStreams = true;


// ScreenShare Configuration.
//

config.desktopSharingFrameRate = { min: 5, max: 5 };

// Audio configuration.
//

config.enableNoAudioDetection = true;
config.enableTalkWhileMuted = false;
config.disableAP = false;

if (!config.hasOwnProperty('audioQuality')) config.audioQuality = {};
config.audioQuality.stereo = false;

config.startAudioOnly = false;
config.startAudioMuted = 10;
config.startWithAudioMuted = false;
config.startSilent = false;
config.enableOpusRed = false;
config.disableAudioLevels = false;
config.enableNoisyMicDetection = true;`


Is that correct?

Many if statements seem completely missing from SaaS JITSI, but is present on on-premises.

**Comment by jallamsetty1** [comment] 2024-07-23 21:53
Can you pls add

```
config.bridgeChannel = { preferSctp: true };
config.flags.ssrcRewritingEnabled = true;
```

and check if that makes any difference?

**Comment by BanuRekhaVarun** [comment] 2024-07-25 12:29
Hi
We are using latest jitsi js library (https://web-cdn.jitsi.net/meetjitsi_8077.4968/libs/lib-jitsi-meet.min.js?v=8077.4968).
Facing an issue with Firefox version 127 and above, 
1) Call connected but audio is not audible.
2) Screen share not working.

Checked the solution
'config.bridgeChannel = { preferSctp: true };
 config.flags.ssrcRewritingEnabled = true;' 
but it did not fix the issue.

Observation:
When p2p is enabled, then one-to-one call between chrome user and firefox user (OR) both firefox users, call gets connected and voice is audible but screenshare is still not working.

Is there any specific config setting for latest version of firefox to fix the issue?

Thanks!

Note: Firefox version that tested up to 124 is working fine.

**Comment by jallamsetty1** [comment] 2024-07-25 17:31
Can someone please share the JVB log from their deployment? I am unable to reproduce the issue on meet.jit.si

**Comment by jallamsetty1** [comment] 2024-07-25 18:06
> meet.jit.si works splendid with the same systems, same browsers but not on the on premises solution.
> 
> Just tried, I deleted all the images off the docker host and ran the stack again so it 100% pulled the images:
> 
> ![bild](https://private-user-images.githubusercontent.com/151639949/351209721-cb5974b4-047d-4176-ba91-9ddd929abcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzA0ODUsIm5iZiI6MTcyMTkzMDE4NSwicGF0aCI6Ii8xNTE2Mzk5NDkvMzUxMjA5NzIxLWNiNTk3NGI0LTA0N2QtNDE3Ni1iYTkxLTlkZGQ5MjlhYmNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNzU2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGUwYzNiNzg5ZTdhMzRlYzBhMWZlYjM1ZGQ2NTE4NWU5ODJhZGIyOWUzMDkxOTJhOTMxY2I5N2FiOTRlMzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fVKOQU4UqQEtPNcKIilh4-Kx5As_lvNNKda6iPEJ6yY)
> 
> But no dice. Firefox does not work, picture is available until someone joins, then it disappears. If I join the same meeting in Edge, it works flawlessly. Chat message from client1 and client2 works splendid.
> 
> Attached is the console output from Firefox . [jitsi console.txt](https://github.com/user-attachments/files/16344549/jitsi.console.txt)

Are these logs from the latest stable? There seems to be some mixup with the upgrade process, as per the logs you are running a much older version of the client.

**Comment by jallamsetty1** [comment] 2024-07-25 18:09
> Hi We are using latest jitsi js library (https://web-cdn.jitsi.net/meetjitsi_8077.4968/libs/lib-jitsi-meet.min.js?v=8077.4968). Facing an issue with Firefox version 127 and above,
> 
> 1. Call connected but audio is not audible.
> 2. Screen share not working.
> 
> Checked the solution 'config.bridgeChannel = { preferSctp: true }; config.flags.ssrcRewritingEnabled = true;' but it did not fix the issue.
> 
> Observation: When p2p is enabled, then one-to-one call between chrome user and firefox user (OR) both firefox users, call gets connected and voice is audible but screenshare is still not working.
> 
> Is there any specific config setting for latest version of firefox to fix the issue?
> 
> Thanks!
> 
> Note: Firefox version that tested up to 124 is working fine.

What backend version are you using?

**Comment by guemi** [comment] 2024-07-26 06:52
> > meet.jit.si works splendid with the same systems, same browsers but not on the on premises solution.
> > Just tried, I deleted all the images off the docker host and ran the stack again so it 100% pulled the images:
> > ![bild](https://private-user-images.githubusercontent.com/151639949/351209721-cb5974b4-047d-4176-ba91-9ddd929abcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzA0ODUsIm5iZiI6MTcyMTkzMDE4NSwicGF0aCI6Ii8xNTE2Mzk5NDkvMzUxMjA5NzIxLWNiNTk3NGI0LTA0N2QtNDE3Ni1iYTkxLTlkZGQ5MjlhYmNmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNzU2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGUwYzNiNzg5ZTdhMzRlYzBhMWZlYjM1ZGQ2NTE4NWU5ODJhZGIyOWUzMDkxOTJhOTMxY2I5N2FiOTRlMzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fVKOQU4UqQEtPNcKIilh4-Kx5As_lvNNKda6iPEJ6yY)
> > But no dice. Firefox does not work, picture is available until someone joins, then it disappears. If I join the same meeting in Edge, it works flawlessly. Chat message from client1 and client2 works splendid.
> > Attached is the console output from Firefox . [jitsi console.txt](https://github.com/user-attachments/files/16344549/jitsi.console.txt)
> 
> Are these logs from the latest stable? There seems to be some mixup with the upgrade process, as per the logs you are running a much older version of the client. Release 8252 is from Jan 2023 which explains the issue that you are seeing.

Ugh, apparently the version variable in the docker compose was set to -stable-8252 rather than -stable. Fixed that now. And you're right, Firefox worked. 

I recommend the rest of you checking the same, I'm not sure why you'd specify a specific version but recommend you configure your docker-compose like this;

```
services:
    # Frontend
    web:
        image: jitsi/web:${JITSI_IMAGE_VERSION:-stable}

    # XMPP server
    prosody:
        image: jitsi/prosody:${JITSI_IMAGE_VERSION:-stable}


    # Focus component
    jicofo:
        image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-stable}
        
            # Video bridge
    jvb:
        image: jitsi/jvb:${JITSI_IMAGE_VERSION:-stable}
```



Rather than what I had before;


```
services:
    # Frontend
    web:
        image: jitsi/web:${JITSI_IMAGE_VERSION:-stable-8252}

    # XMPP server
    prosody:
        image: jitsi/prosody:${JITSI_IMAGE_VERSION:-stable-8252}


    # Focus component
    jicofo:
        image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-stable-8252}
        
            # Video bridge
    jvb:
        image: jitsi/jvb:${JITSI_IMAGE_VERSION:-stable-8252}
```

**Comment by BanuRekhaVarun** [comment] 2024-07-29 08:02
> > Hi We are using latest jitsi js library (https://web-cdn.jitsi.net/meetjitsi_8077.4968/libs/lib-jitsi-meet.min.js?v=8077.4968). Facing an issue with Firefox version 127 and above,
> > 
> > 1. Call connected but audio is not audible.
> > 2. Screen share not working.
> > 
> > Checked the solution 'config.bridgeChannel = { preferSctp: true }; config.flags.ssrcRewritingEnabled = true;' but it did not fix the issue.
> > Observation: When p2p is enabled, then one-to-one call between chrome user and firefox user (OR) both firefox users, call gets connected and voice is audible but screenshare is still not working.
> > Is there any specific config setting for latest version of firefox to fix the issue?
> > Thanks!
> > Note: Firefox version that tested up to 124 is working fine.
> 
> What backend version are you using?

Hi,
I have two backends and the issue happens in both.
Attaching both backend versions for your reference....

[Jitsi-backend.txt](https://github.com/user-attachments/files/16409363/Jitsi-backend.txt)
[Jitsi-backend-wm.txt](https://github.com/user-attachments/files/16409375/Jitsi-backend-wm.txt)

**Comment by BanuRekhaVarun** [comment] 2024-07-30 11:29
Hi jallamsetty1,

Any update on my above comment.

Thanks

**Comment by jallamsetty1** [comment] 2024-07-30 14:17
> Hi jallamsetty1,
> 
> Any update on my above comment.
> 
> Thanks

Both the versions are old, one is an year old and the other one is 6 months old. We suggest upgrading to the latest stable from July 2nd for the issue to be fixed.

**Comment by BanuRekhaVarun** [comment] 2024-08-05 04:08
> Both the versions are old, one is an year old and the other one is 6 months old. We suggest upgrading to the latest stable from July 2nd for the issue to be fixed.

Thanks. Upgrade fix the issue.
Thanks again!

**Comment by BanuRekhaVarun** [comment] 2024-08-06 04:53
> Both the versions are old, one is an year old and the other one is 6 months old. We suggest upgrading to the latest stable from July 2nd for the issue to be fixed.

Hi,
Thanks.  Upgrade fix the issue.
Thanks again Jallamsetty

**Comment by umstek** [comment] 2024-09-06 03:00
Does anyone have any idea what change/commit fixes this issue?

Thanks.

**Comment by jallamsetty1** [comment] 2024-09-06 13:06
> Does anyone have any idea what change/commit fixes this issue?

I believe it is this bridge commit - https://github.com/jitsi/jitsi-videobridge/commit/573abcdf4c7b3f17493d30550811ad7a8fd27a64
