### ISSUE TITLE
Camera only works the first time on iOS safari. (Alpha release)

### ISSUE THREAD

**Issue by muditjuneja** [jitsi/jitsi-meet#6903] opened 2020-05-29 04:23 UTC
I am trying to connect to a meeting from iOS safari browser. It works fine the first time I start the camera. But if I switch it off and then try turning it on again, it doesn't start.

On browser console I can see the following warning :
`2020-05-29T04:16:11.316Z [modules/RTC/RTCUtils.js] Failed to get access to local media. Error: Invalid constraint [object Object]`

And the following error :
`[native code]:1 2020-05-29T04:16:11.320Z [features/base/tracks] set track unmute failed s {gum: Object, name: "gum.general", message: "Invalid constraint", stack: "s@https://alpha.jitsi.net/libs/lib-jitsi-meet.min.…s?v=4163:1:92377↵promiseReactionJob@[native code]", constructor: function}`

I am using the alpha version to test this because the current stable version doesn't even start the camera not even the first time.

Can anyone help? Is it the web thing or something related to the video bridge?

### Steps to reproduce:

1. Open the web version of alpha.jitsi.net on iOS safari.
2. Grant access to camera
3. Open the camera by clicking the camera icon: It will open up your camera
4. Stop the camera by clicking again on the same button
5. Then click on the button to start again : Camera won't start and it will give the above error in the browser console.

### Client information:

- Browser / app version: Safari/ Safari 12
- Operating System: iOS

### Expected behavior:
The camera should start again after clicking the button.

**Comment by luixxiul** [comment] 2020-05-29 04:28
Please follow the template to provide information. It should greatly help developers to troubleshoot. Thanks!

````
### Steps to reproduce:

1. <!-- Open '...' -->
2. <!-- Click on '...' -->
3. <!-- and so on... -->

### Expected behavior:

<!-- Please describe what should happen. -->

### Actual behavior:

<!-- Please describe what actually happens. -->
<!-- Please attach screenshot if possible. -->

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:
````

**Comment by muditjuneja** [comment] 2020-05-29 04:47
Updated the description of the ticket.

**Comment by jallamsetty1** [comment] 2020-05-29 14:41
Can you pls add more details about the device and the iOS version that is running on this specific device ? Also, can you please elaborate on what you mean by "opening the camera by clicking on camera icon" ? Are you referring to the camera icon on the browser tab or the camera button on the bottom ?

**Comment by muditjuneja** [comment] 2020-05-29 22:05
I am using ios safari version 12. I am talking about the camera tool icon on the jitsi web which is used to switch the camera state.

**Comment by nathankurtyka** [comment] 2020-06-09 19:46
@jallamsetty1 Hello! Note that alpha.jitsi.net isn't usable on **any** iOS or iPhone version (eg. camera starts off/freezes, local user video is a frozen image, "Enter your name" button is off the screen, etc).

There are a few iOS issues floating around here referencing different bugs, but I get the impression that the team might think the latest Jitsi works on iOS? If iOS is still a work-in-progress, then this issue be disregarded. But if not, then there are probably a bunch of redundant issues about to appear when the latest release goes live on meet.jit.si.

**Comment by jallamsetty1** [comment] 2020-06-09 19:55
> @jallamsetty1 Hello! Note that alpha.jitsi.net isn't usable on **any** iOS or iPhone version (eg. camera starts off/freezes, local user video is a frozen image, "Enter your name" button is off the screen, etc).
> 
> There are a few iOS issues floating around here referencing different bugs, but I get the impression that the team might think the latest Jitsi works on iOS? If iOS is still a work-in-progress, then this issue be disregarded. But if not, then there are probably a bunch of redundant issues about to appear when the latest release goes live on meet.jit.si.

Hey there, we are aware of the issue with Safari and alpha.jitsi.net. This has something to do with Safari and callstats integration which we are trying to resolve but please be assured that these issues won't appear when the latest release goes live on meet.jit.si since callstats integration is disabled there. If you wan't to try the latest fixes, please try out beta.meet.jit.si.

**Comment by jallamsetty1** [comment] 2020-06-09 19:57
> I am using ios safari version 12 on iphone >=8. I am talking about the camera tool icon on the jitsi web which is used to switch the camera state.

I am not able to reproduce the issue with muting and unmuting the camera, can you please provide the console logs ?

**Comment by jallamsetty1** [comment] 2020-06-09 19:58
> I am using ios safari version 12 on iphone >=8. I am talking about the camera tool icon on the jitsi web which is used to switch the camera state.

Can you please try against https://beta.meet.jit.si and see if you can reproduce the issue ? If so, can you please provide the full console log ?

**Comment by nathankurtyka** [comment] 2020-06-10 01:09
@jallamsetty1 Thank you for the reply! beta.meet has the same problems.

I'm happy to pull console logs, but I believe the iOS problems are a tad broader than miscellaneous JS or connection errors.  For example, loading any room on iOS (on the beta site) displays the local video in some Apple media player completely on top of Safari (Jitsi isn't even visible any longer).  

Does this genuinely work for anyone else on iOS? Maybe I'm crazy, but I can't fathom anybody can complete a meeting on iOS at the moment.

**Comment by muditjuneja** [comment] 2020-06-10 06:46
Which branches are pointing to beta.meet.ji.si. I would like to build the entire beta stack myself. Guide me!

**Comment by saghul** [comment] 2020-06-10 07:13
> I'm happy to pull console logs, but I believe the iOS problems are a tad broader than miscellaneous JS or connection errors. For example, loading any room on iOS (on the beta site) displays the local video in some Apple media player completely on top of Safari (Jitsi isn't even visible any longer).

@jallamsetty1 Maybe we need those CSS classes to hide the inline media controls?

```
    video::-webkit-media-controls-overlay-play-button {
      display: none;
    }
```

And maybe some more...

**Comment by jallamsetty1** [comment] 2020-06-12 15:12
@nathankurtyka, I have committed a fix for the local video starting in full screen. This should be available in nightly soon. 
@muditjuneja, I will be closing this issue since your issue seems to be fixed.

**Closed by jallamsetty1** 2020-06-12 15:12 UTC
Labels: browser-support, devices, ios

**Comment by nathankurtyka** [comment] 2020-06-13 19:59
@jallamsetty1 - I can't even imagine how tricky it must have been to bring this feature to life..  great job!

**Comment by muditjuneja** [comment] 2020-06-15 04:39
@jallamsetty1 I don't think it is related to the fix that you pushed. Why are you closing this?

**Comment by l3d00m** [comment] 2020-06-15 09:16
Could you try out the newest version and see if it is fixed? Otherwise feel free to reopen the issue.
