### ISSUE TITLE
Live streaming failed to start

### ISSUE THREAD

**Issue by goatchild** [jitsi/jitsi-meet#3188] opened 2018-06-23 12:11 UTC
Hello
I'm trying to livestream to my youtube account but an error message keeps poping up:
"Livestream failed to start
Livestream failed. Pease try again."
I try again but it doesn't work.
What can be done?
Thanks

**Comment by saghul** [comment] 2018-06-23 14:11
Hi!

Is this happening in meet.jit.si or your own deployment?

**Comment by mckaygerhard** [comment] 2018-07-27 13:58
i have same problem, using debian jessie, quick instsall not modify nothing.. the today guide are very poor explicit about custon configs and documentation are poor explicit

**Comment by supun19** [comment] 2018-09-18 13:46
i also have a same issue (recording is working)

**Comment by mckaygerhard** [comment] 2018-09-18 14:01
of course are happened in own deployment @saghul what we can provided as information to help to solve this problem, please post steps to provide the info, some one to help to solve this info? @lyubomir, @virtuacoplenny , @damencho ? the documentation are very poor and ambiguous!

**Comment by virtuacoplenny** [comment] 2018-09-18 15:19
I'd check https://community.jitsi.org/. That's where this topic comes up every once in a while and I overheard the issue is normally due to configuration (I think due to all the custom configs stuff people have to set up). You can try asking bbaldino but not sure he can do much help if it's a configuration issue; make sure to include jibri logs and point out and logged errors. I myself don't have any knowledge on the setup and deployment of jibri.

**Comment by supun19** [comment] 2018-09-18 15:32
thank you your response @virtuacoplenny

**Comment by mckaygerhard** [comment] 2018-09-18 15:46
ok 'ill setup again a environment and report feedback when i get free ... thanks

**Comment by supun19** [comment] 2018-09-18 15:49
Recording is working but streaming not

I got this log in ffmpeg.0.txt

2018-09-18 15:41:33.700 INFO: [61] ffmpeg.call()   libpostproc    53.  3.100 / 53.  3.100
2018-09-18 15:41:33.700 INFO: [61] ffmpeg.call() Input #0, x11grab, from ':0.0+0,0':
2018-09-18 15:41:33.700 INFO: [61] ffmpeg.call()   Duration: N/A, start: 1537285293.690534, bitrate: N/A
2018-09-18 15:41:33.700 INFO: [61] ffmpeg.call()     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1280x720, 30 fps, 30 tbr, 1000k tbn, 30 tbc
2018-09-18 15:41:33.700 INFO: [61] ffmpeg.call() Guessed Channel Layout for  Input Stream #1.0 : stereo
2018-09-18 15:41:33.700 INFO: [61] ffmpeg.call() Input #1, alsa, from 'hw:0,1,0':
2018-09-18 15:41:33.700 INFO: [61] ffmpeg.call()   Duration: N/A, start: 1537285293.695302, bitrate: 1536 kb/s
2018-09-18 15:41:34.132 INFO: [61] ffmpeg.call()     Stream #1:0: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
2018-09-18 15:41:34.132 INFO: [61] ffmpeg.call() RTMP_ReadPacket, failed to read RTMP packet header
2018-09-18 15:41:34.133 INFO: [61] ffmpeg.call() rtmp://a.rtmp.youtube.com/live2/https://www.youtube.com/channel/UCoMoI7CAwX8_LjQHig: Unknown error occurred

this is a log.0.txt


2018-09-18 15:47:04.799 FINE: [39] org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.<init>() Detected os as OS: LINUX
2018-09-18 15:47:05.433 INFO: [39] org.openqa.selenium.remote.ProtocolHandshake.createSession() Detected dialect: OSS
2018-09-18 15:47:05.434 FINE: [39] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: start:live_stream
2018-09-18 15:47:05.435 INFO: [39] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Jibri reports its status is now busy, publishing presence to connection prod environment
2018-09-18 15:47:05.907 FINE: [39] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Visiting url https://meet.micasatuiglesia.com/12344#config.iAmRecorder=true&config.externalConnectUrl=null&config.startWithAudioMuted=true&config.startWithVideoMuted=true&interfaceConfig.APP_NAME="Jibri"
2018-09-18 15:47:07.836 INFO: [39] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Waited 525 milliseconds for call page to load
2018-09-18 15:47:07.847 INFO: [39] org.jitsi.jibri.service.impl.StreamingJibriService.start() Selenium joined the call
2018-09-18 15:47:07.848 INFO: [39] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.launchFfmpeg() Starting ffmpeg with command [ffmpeg, -y, -v, info, -f, x11grab, -draw_mouse, 0, -r, 30, -s, 1280x720, -thread_queue_size, 4096, -i, :0.0+0,0, -f, alsa, -thread_queue_size, 4096, -i, hw:0,1,0, -acodec, aac, -strict, -2, -ar, 44100, -c:v, libx264, -preset, veryfast, -maxrate, 2976k, -bufsize, 5952k, -pix_fmt, yuv420p, -r, 30, -crf, 25, -g, 60, -tune, zerolatency, -f, flv, rtmp://a.rtmp.youtube.com/live2/https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig]
2018-09-18 15:47:07.871 SEVERE: [39] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.isFfmpegHealthy() Ffmpeg is running but doesn't appear to be encoding: 
2018-09-18 15:47:08.872 SEVERE: [39] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.isFfmpegHealthy() Ffmpeg exited with code 1.  Its most recent output was rtmp://a.rtmp.youtube.com/live2/https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig: Unknown error occurred
2018-09-18 15:47:08.873 SEVERE: [39] org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.start() Ffmpeg already exited
2018-09-18 15:47:08.873 SEVERE: [39] org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.start() Ffmpeg started up but did not start encoding after 15 tries, giving up
2018-09-18 15:47:08.873 SEVERE: [39] org.jitsi.jibri.service.impl.StreamingJibriService.start() Capturer failed to start
2018-09-18 15:47:08.874 FINE: [39] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: stop:live_stream
2018-09-18 15:47:08.874 INFO: [39] org.jitsi.jibri.JibriManager.stopService() Stopping the current service
2018-09-18 15:47:08.875 INFO: [39] org.jitsi.jibri.service.impl.StreamingJibriService.stop() Stopping capturer
2018-09-18 15:47:08.875 INFO: [39] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.stopFfmpeg() Stopping ffmpeg process
2018-09-18 15:47:08.876 INFO: [39] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.stopFfmpeg() Ffmpeg exited with value 1
2018-09-18 15:47:08.876 INFO: [39] org.jitsi.jibri.service.impl.StreamingJibriService.stop() Stopped capturer
2018-09-18 15:47:08.876 INFO: [39] org.jitsi.jibri.service.impl.StreamingJibriService.stop() Quitting selenium
2018-09-18 15:47:08.888 INFO: [39] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 8 log entries for type browser
2018-09-18 15:47:08.935 INFO: [39] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 395 log entries for type driver
2018-09-18 15:47:08.998 INFO: [39] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 0 log entries for type client
2018-09-18 15:47:08.999 INFO: [39] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Leaving web call

2018-09-18 15:47:09.027 INFO: [39] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Quitting chrome driver
2018-09-18 15:47:09.107 INFO: [39] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Chrome driver quit
2018-09-18 15:47:09.108 INFO: [39] org.jitsi.jibri.service.impl.StreamingJibriService.stop() Quit selenium
2018-09-18 15:47:09.108 INFO: [39] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Jibri reports its status is now idle, publishing presence to connection prod environment
2018-09-18 15:47:09.109 FINE: [39] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: error:live_stream
2018-09-18 15:47:09.110 INFO: [39] org.jitsi.jibri.api.xmpp.XmppApi.run() Sending start service response iq: <iq to='jibribrewery@internal.auth.meet.micasatuiglesia.com/focus' id='GLHmp-69' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error'/></iq>

**Comment by supun19** [comment] 2018-09-19 02:51
thanks @bbaldino

**Comment by mckaygerhard** [comment] 2018-09-19 03:05
umm thaks seems one solved, i could not setuo my environment yet due i am not at home for a while.. ill post later in those days my problem, thanks any way...

**Comment by mckaygerhard** [comment] 2018-12-18 12:22
it's not resolved yet

**Comment by saghul** [comment] 2018-12-18 14:13
@mckaygerhard Is there any new information on this though? What is the specific problem now?

**Comment by mckaygerhard** [comment] 2018-12-18 17:00
i not have time now, ok close it but i'll back later then, i cannot configure to live stream, i tried all the only two ways in the net and does not work, there's no info about detailed confighurations and the docs are very limited!

**Comment by rasos** [comment] 2018-12-20 12:43
Entering entering the live stream key also fails here every time.

**Comment by mateolan** [comment] 2019-02-24 00:09
having the same problem on meet.jit.si

**Comment by mckaygerhard** [comment] 2019-02-25 00:07
well it's definitivelly that live stream does not work due many many reasons...

**Comment by mckaygerhard** [comment] 2019-05-27 04:57
well it's definitivelly that live stream does not work due many many reasons... comment added to remove staled

**Comment by saghul** [comment] 2019-05-28 06:54
Liove Streaming does work. Please feel free to open a new issue where specific issues are mentioned. If the servic e is not available at times on meet.jit.si, do note that we do not make any SLA promises.

**Closed by saghul** 2019-05-28 06:54 UTC

**Comment by jmurphree77** [comment] 2024-03-20 04:30
Had a horrible experience on meet.jit.si earlier tonight - we've been planning this interview for several years now and every few minutes it would drop connection: https://www.youtube.com/watch?v=91H1Ug8Jqyc

It was so embarrassing for the people watching. Here's the room we used if that helps to debug the problem: https://meet.jit.si/graphiccontractorsgrantway

I've streamed to YouTube with Jitsi for years now and never experienced anything like this until tonight unfortunately. :-(
