### ISSUE TITLE
Delete chat and others options

### ISSUE THREAD

**Issue by alfredorods** [jitsi/jitsi-meet#1863] opened 2017-08-04 16:35 UTC
Hi, i've a client with an chat, this chats work properly and i don't wanna use the jitsi-meet chat.

can the api a remove this chat? in the documentation i saw a option to toggle the chat but this option only change the object's display.

I just wanna remove the chat's icon and call to number.

Greetings to everyone.

thanks for build jitsi-meet.

greetings from Venezuela.

**Comment by RuudBurger** [comment] 2017-08-09 12:11
I have a similar issue but with all the buttons in the menus. I see https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js and can change some buttons. But if I remove a button it either doesn't do anything, or it gets moved to the other menu..
I want to remove as much as possible, something like the `filmStripOnly` option does, but with the large video feed.

**Comment by damencho** [comment] 2017-08-09 12:39
Have you tried removing the button from both MAIN_TOOLBAR_BUTTONS and
TOOLBAR_BUTTONS?

On Aug 9, 2017 15:11, "Ruud Burger" <notifications@github.com> wrote:

I have a similar issue but with all the buttons in the menus. I see
https://github.com/jitsi/jitsi-meet/blob/master/interface_config.js and can
change some buttons. But if I remove a button it either doesn't do
anything, or it gets moved to the other menu..
I want to remove as much as possible, something like the filmStripOnly
option does, but with the large video feed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jitsi/jitsi-meet/issues/1863#issuecomment-321237060>,
or mute the thread

**Comment by RuudBurger** [comment] 2017-08-09 14:31
Yeah that doesn't work. I would expect if both MAIN_TOOLBAR_BUTTONS and TOOLBAR_BUTTONS are empty arrays no buttons are shown. But that is not the case.

**Comment by yourcelf** [comment] 2017-08-17 16:44
We're also impacted by this, using the [jitsi meet external API](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md) and `interfaceConfigOverwrite` to replace `TOOLBAR_BUTTONS` and `MAIN_TOOLBAR_BUTTONS`.  Not all of buttons go away, even when they're not present in `TOOLBAR_BUTTONS` and `MAIN_TOOLBAR_BUTTONS`.  We're initializing with these values for those settings:
```
          TOOLBAR_BUTTONS: [
            "microphone", "camera", "desktop",
            "chat", "filmstrip",
            "sharedvideo","settings",
            "recording"
          ],
          MAIN_TOOLBAR_BUTTONS: ['microphone', 'camera', 'desktop'],
```
and getting these toolbar buttons:

![image](https://user-images.githubusercontent.com/21318/29421516-8e8fb0e2-8332-11e7-95ab-d57d6d303720.png)

We've wanted to eliminate "etherpad", "raisehand", "invite", "addtocall", but eliminating them from *TOOLBAR_BUTTONS doesn't seem to work.  Some of the other controls ("profile", "hangup", "fullscreen", etc) do seem to respect the TOOLBAR_BUTTONS settings.

**Comment by virtuacoplenny** [comment] 2017-08-17 17:16
I think this line is causing the problem: https://github.com/jitsi/jitsi-meet/blob/4e5bc172c909c694ac1b81f18d04043a1bf308d7/react/features/base/config/functions.js#L180. By design, lodash ignores merging of empty arrays (https://github.com/lodash/lodash/issues/1313).

**Comment by yourcelf** [comment] 2017-08-17 17:20
@virtuacoplenny that might impact the case @RuudBurger mentioned of trying to pass in empty arrays. But both @alfredorods and I are talking about passing in non-empty arrays, but having buttons missing from those arrays still show up.

I know the arrays are getting merged, because *some* of the buttons go away, and adding/removing things from `MAIN_TOOLBAR_BUTTONS` works to move them from the sidebar to top bar.  But some buttons (e.g. "etherpad", "raisehand", "invite", "addtocall", "chat") remain even when missing from both arrays.

**Comment by alfredorods** [comment] 2017-08-17 17:33
Yesss, you have reason, these are my options:

     var options = {

      roomName: 'myroomtest',
      parentNode: document.querySelector('#meet'),
      interfaceConfigOverwrite: { MAIN_TOOLBAR_BUTTONS: ['microphone']},


    }

and later i:

`   var api = new JitsiMeetExternalAPI(domain, options);`

But this is not work for me, i try with all the options and i can't remove the options.

**Comment by virtuacoplenny** [comment] 2017-08-17 17:39
I think due to the recursive merging of _.merge, indexes are replaced instead of the array being replaced completely. I haven't look at its implementation but I've played with it in console.

**Closed** 2017-08-21 12:41 UTC

**Comment by KindYAK** [comment] 2020-04-02 14:14
> ```
>  var options = {
> 
>   roomName: 'myroomtest',
>   parentNode: document.querySelector('#meet'),
>   interfaceConfigOverwrite: { MAIN_TOOLBAR_BUTTONS: ['microphone']},
> 
> 
> }
> ```
> 
> 
> and later i:
> 
> `   var api = new JitsiMeetExternalAPI(domain, options);`
> 
> But this is not work for me, i try with all the options and i can't remove the options.

This method does work for me, but it is not TOOLBAR_BUTTONS, not MAIN_TOOLBAR_BUTTONS
