### ISSUE TITLE
Raised hand remains after disconnecting-reconnecting the video conf call.

### ISSUE THREAD

**Issue by mhamdihajer1** [jitsi/jitsi-meet#13872] opened 2023-09-25 16:04 UTC
Hi team,

Brief description of the issue 

The raised hand remains after disconnecting-reconnecting the video conf call.

Preconditions/test setup:

jitsiMeetSdk = "6.0.0"
jitsiMeetSdkSw = "5.1.0-sw-r7"

Android device 13

Connect to a video conf session 

Steps to reproduce:

1- Generate a video conference URL.

2- connect the video conference from the Android

3- Connect another user from the web for example.

4- Android raise the hand

5- Everybody leaves the video conf

6- Generate a new video conference URL 

7- Same Android user connect the video conference from the new URL 

Actual result or description of the tests done:

The raised hand remains on Android (not for the user connected from web)

Expected result:

The raised hand should not remain after disconnecting-reconnecting the video conf session.

More info: 
same behavior on iOS.

**Comment by saghul** [comment] 2023-09-25 16:58
Duplicate of https://github.com/jitsi/jitsi-meet/issues/13830

**Closed by saghul** 2023-09-25 16:58 UTC
