### ISSUE TITLE
Clarification: "Jitsi Meet is a fully encrypted, "

### ISSUE THREAD

**Issue by jcalfee** [jitsi/jitsi-meet#7368] opened 2020-07-21 14:22 UTC
### Description:

Can you please clarify:

On "https://jitsi.org/jitsi-meet/" I see "**Jitsi Meet is a fully encrypted,**"

I am not sure which is true, but I would suggest that full disclosure is better.  For example, one of the following:

1) "Self-hosted Jitsi Meets are end-to-end encrypted, "
OR:
2) "All Jitsi Meets, self-hosted or web-hosted, are end-to-end encrypted, "

It is not clear to me which one.  My understanding of WebRTC is that an end-to-end encrypted video session in the browser would involve writing native JavaScript encoders and decoders.  Please correct me on this, but I did not find code like this and I don't see how you could pull this off as a web-hosted solution without doing your own encoding and encrypting.

### Additional information:

In any event, it would be very helpful to have clarification so people can plan accordingly: decide if they should use self-hosted solutions sooner or use the free service.  It is very important that if the web-hosted video sessions are not encrypted from the free servers that this information be disclosed.

Thank you...

**Comment by saghul** [comment] 2020-07-21 14:30
This is a duplicate of: https://github.com/jitsi/jitsi-meet/issues/7270

All meetings are encrypted hop-by-hop. On supported devices, E2EE can be enabled too. This applies to any deployment.

**Closed by saghul** 2020-07-21 14:30 UTC
