### ISSUE TITLE
The name of the room is in random format

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3122] opened 2018-06-11 09:13 UTC
After the name of the room is scrambled, the mobile terminal cannot enter.How?

for https://domain/%E8%A7%86%E9%A2%91%E4%BC%9A%E8%AE%AE

**Comment by lyubomir** [comment] 2018-08-27 14:31
This issue sounds like a duplicate of https://github.com/jitsi/jitsi-meet/issues/3107 to me.

**Closed by lyubomir** 2018-08-27 14:31 UTC
Labels: project:react-native
