### ISSUE TITLE
Feature request: provide update-proof configuration of the layout

### ISSUE THREAD

**Issue by scroom** [jitsi/jitsi-meet#6200] opened 2020-04-19 18:54 UTC
**Is your feature request related to a problem you are facing?**
I have set up a Jitsi Meet server for our school. I replaced the Jitsi logo with a school's own logo and edited the text on the start page. Unfortunately I have to repeat all these changes after each update.

**Describe the solution you'd like**
It would be great if there was a config in which I could set e.g. the path for my logo and the text that appears on the start page, which will not be overwritten during an update.

Considering how many forum entries there are that deal with changing the text etc., this seems to be something that many admins would like to see and which certainly leads to a better feeling among the users.

**Comment by MagicFab** [comment] 2020-05-25 13:55
Marking as duplicate of  #6279, it describes workarounds and has devs involved.

**Closed** 2020-05-26 10:22 UTC
Labels: duplicate, feature-request, meta
