### ISSUE TITLE
Low fps video camera upload chrome 126 vp9 

### ISSUE THREAD

**Issue by javierckr** [jitsi/jitsi-meet#14937] opened 2024-07-22 15:20 UTC
### What happened?

When on a meeting with 3 or more participants the cameras of the participants using chrome are between 3 and 8 fps, tested on our own instance and on meet.jit.si, for testing on meet.jit.si you need to 1 participant on firefox to fall on vp9 codec instead of av1.
It is not happening on chrome 115.

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chromium and Google Chrome 126

### Reproducibility

- [X] The problem is reproducible on meet.jit.si

**Comment by pbirkants** [comment] 2024-07-23 10:53
Hi, I've also come across this weird behavior, and can contribute details on some observations.

I did some testing with various clients, and the issue was always present for VP9 video sources coming from Chrome/-ium 126 + Windows, and never occurred when downgrading to Chrome 124, or when using Chromium 126 on Linux, or when using AV1.

Additionally, when looking at details in `chrome://webrtc-internals`, I saw that the outbound-rtp stream is reported as having full, stable framerate (25 or 30fps), meanwhile receivers' inbound-rtp shows 4x less (6-7fps or 8fps respectively) and the video is choppy. Audio is always fine. Configuring a higher target bitrate also did not change anything.

initially noticed in an older version of Jitsi, but also reproducible both on a freshly deployed docker-jitsi-meet instance with default settings (AV1 not enabled) in a LAN environment, and on meet.jit.si (by joining also with Firefox, as mentioned by OP).

**Comment by cyrilfl** [comment] 2024-08-18 00:58
No update from anyone on this? Experiencing the same issue and do not know what to do.

**Comment by saghul** [comment] 2024-08-19 08:09
Ping @jallamsetty1

**Comment by jallamsetty1** [comment] 2024-08-20 14:34
This was fixed on the bridge and the fix has been deployed to meet.jit.si already but I suspect it hasn't made to stable yet. We are planning to release new stable builds soon.

**Closed by jallamsetty1** 2024-08-20 14:34 UTC

**Comment by Stromduster** [comment] 2025-03-03 13:41
Has it been added to the stable release ? Got the same problem on  
jitsi-meet                       2.0.10078-1
jitsi-meet-prosody               1.0.8448-1
jitsi-meet-turnserver            1.0.8448-1
jitsi-meet-web                   1.0.8448-1
jitsi-meet-web-config            1.0.8448-1
jitsi-videobridge2               2.3-209-gb5fbe618-1

**Comment by saghul** [comment] 2025-03-03 14:19
A lot has changed since, we now default to AV1, for example.

**Comment by Stromduster** [comment] 2025-03-03 17:26
Of course, but most of our devices still use vp8 or vp9 (can't say why some won't ever use AV1), and so reproduce the issue on the version I mentioned.

**Comment by saghul** [comment] 2025-03-03 18:25
Please share your config.js

**Comment by Stromduster** [comment] 2025-03-04 16:52
In attachment. Thanks in advance for your feedback.

[config.zip](https://github.com/user-attachments/files/19074621/config.zip)

**Comment by saghul** [comment] 2025-03-06 09:39
@Stromduster Youa re using 1080, which I bet is why things are not going well, as it can be very resource intensive. You are also configuring codecs with AV1 being the first on mobile, but not on web, you may want to review your config.

At any rate, I doubt the original issue is related, feel free to open a new one. If you do, please provide console logs for the user(s) with the problem.

**Comment by Stromduster** [comment] 2025-03-06 09:49
I'll review the codecs order. However, I suppose the issue is due to chrome variants, since I don't experience it with Firefox.
