### ISSUE TITLE
Screen sharing "Permission Denied" message.

### ISSUE THREAD

**Issue by jacq0123** [jitsi/jitsi-meet#1575] opened 2017-05-16 09:02 UTC
Hello,
We created the screen sharing extension and published it in chrome. But when we I click on the "screen sharing" tab, it will display the permission to install the extension. When I tried to install the extension, I'm getting a this pop up message: "Permission denied. failed to install desktop sharing extension"
Please help.
Thanks!

**Comment by saghul** [comment] 2017-05-16 11:06
Hi there! Can you open the console and paste the output here? Hopefully we can see something in there.

**Comment by jacq0123** [comment] 2017-05-16 20:19
Thank you, below is the output. I'm attaching the screenshoot and the txt file as well:


Object {message: "Could not establish connection. Receiving end does not exist."}
r @ lib-jitsi-meet.min.js?v=1592:6
(anonymous) @ lib-jitsi-meet.min.js?v=1592:24
sendResponseAndClearCallback @ extensions::messaging:345
disconnectListener @ extensions::messaging:363
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnDisconnect @ extensions::messaging:306
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/ScreenObtainer.js] <>:  Extension not installed?:  Object {message: "Could not establish connection. Receiving end does not exist."}
r @ lib-jitsi-meet.min.js?v=1592:6
(anonymous) @ lib-jitsi-meet.min.js?v=1592:24
sendResponseAndClearCallback @ extensions::messaging:345
disconnectListener @ extensions::messaging:363
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnDisconnect @ extensions::messaging:306
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/ScreenObtainer.js] <>:  Extension not installed?:  Object {message: "Could not establish connection. Receiving end does not exist."}
r @ lib-jitsi-meet.min.js?v=1592:6
(anonymous) @ lib-jitsi-meet.min.js?v=1592:24
sendResponseAndClearCallback @ extensions::messaging:345
disconnectListener @ extensions::messaging:363
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnDisconnect @ extensions::messaging:306
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/ScreenObtainer.js] <>:  Extension not installed?:  Object {message: "Could not establish connection. Receiving end does not exist."}
r @ lib-jitsi-meet.min.js?v=1592:6
(anonymous) @ lib-jitsi-meet.min.js?v=1592:24
sendResponseAndClearCallback @ extensions::messaging:345
disconnectListener @ extensions::messaging:363
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnDisconnect @ extensions::messaging:306
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/ScreenObtainer.js] <>:  Extension not installed?:  Object {message: "Could not establish connection. Receiving end does not exist."}
r @ lib-jitsi-meet.min.js?v=1592:6
(anonymous) @ lib-jitsi-meet.min.js?v=1592:24
sendResponseAndClearCallback @ extensions::messaging:345
disconnectListener @ extensions::messaging:363
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnDisconnect @ extensions::messaging:306
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/ScreenObtainer.js] <>:  Extension not installed?:  Object {message: "Could not establish connection. Receiving end does not exist."}
r @ lib-jitsi-meet.min.js?v=1592:6
(anonymous) @ lib-jitsi-meet.min.js?v=1592:24
sendResponseAndClearCallback @ extensions::messaging:345
disconnectListener @ extensions::messaging:363
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnDisconnect @ extensions::messaging:306
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/ScreenObtainer.js] <>:  Extension not installed?:  Object {message: "Could not establish connection. Receiving end does not exist."}
r @ lib-jitsi-meet.min.js?v=1592:6
(anonymous) @ lib-jitsi-meet.min.js?v=1592:24
sendResponseAndClearCallback @ extensions::messaging:345
disconnectListener @ extensions::messaging:363
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnDisconnect @ extensions::messaging:306
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/ScreenObtainer.js] <>:  Extension not installed?:  Object {message: "Could not establish connection. Receiving end does not exist."}
r @ lib-jitsi-meet.min.js?v=1592:6
(anonymous) @ lib-jitsi-meet.min.js?v=1592:24
sendResponseAndClearCallback @ extensions::messaging:345
disconnectListener @ extensions::messaging:363
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnDisconnect @ extensions::messaging:306
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/ScreenObtainer.js] <>:  Extension not installed?:  Object {message: "Could not establish connection. Receiving end does not exist."}
r @ lib-jitsi-meet.min.js?v=1592:6
(anonymous) @ lib-jitsi-meet.min.js?v=1592:24
sendResponseAndClearCallback @ extensions::messaging:345
disconnectListener @ extensions::messaging:363
EventImpl.dispatchToListener @ extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ extensions::utils:149
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ extensions::utils:149
dispatchOnDisconnect @ extensions::messaging:306
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/ScreenObtainer.js] <Object.handleExtensionInstallationError>:  Failed to install the extension from https://chrome.google.com/webstore/detail/jcaafjdimkdhappfncjebmbphkklklkh undefined
app.bundle.min.js?v=1592:sourcemap:31 [conference.js] <>:  failed to create local tracks ["desktop"] i {name: "gum.chrome_extension_installation_error", message: "Failed to install the extension from https://chrom…/webstore/detail/jcaafjdimkdhappfncjebmbphkklklkh", stack: "Error↵    at new i (https://meet.uproom.net/libs/l…om.net/libs/lib-jitsi-meet.min.js?v=1592:24:12938"}
i @ app.bundle.min.js?v=1592:sourcemap:31
(anonymous) @ app.bundle.min.js?v=1592:sourcemap:70
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/RTCUtils.js] <t.value>:  Get media constraints Object {audio: false, video: Object}
app.bundle.min.js?v=1592:sourcemap:31 [conference.js] <>:  failed to share local desktop i {name: "gum.chrome_extension_installation_error", message: "Failed to install the extension from https://chrom…/webstore/detail/jcaafjdimkdhappfncjebmbphkklklkh", stack: "Error↵    at new i (https://meet.uproom.net/libs/l…om.net/libs/lib-jitsi-meet.min.js?v=1592:24:12938"}
i @ app.bundle.min.js?v=1592:sourcemap:31
(anonymous) @ app.bundle.min.js?v=1592:sourcemap:70
lib-jitsi-meet.min.js?v=1592:6 [modules/RTC/RTCUtils.js] <>:  onUserMediaSuccess
lib-jitsi-meet.min.js?v=1592:6 [modules/xmpp/ChatRoom.js] <t.value>:  No conference handler or conference not started yet
r @ lib-jitsi-meet.min.js?v=1592:6
value @ lib-jitsi-meet.min.js?v=1592:26
(anonymous) @ lib-jitsi-meet.min.js?v=1592:22
o.addTrack @ lib-jitsi-meet.min.js?v=1592:22
(anonymous) @ app.bundle.min.js?v=1592:sourcemap:70
app.bundle.min.js?v=1592:sourcemap:31 [modules/UI/videolayout/LargeVideoManager.js] <>:  hover in %s b20137ed
app.bundle.min.js?v=1592:sourcemap:31 [conference.js] <>:  sharing local video





________________________________

**Comment by saghul** [comment] 2017-05-17 12:21
I could reproduce the issue on your deployment, but not on ours. Are you running the latest version of jitsi-meet?

**Comment by virtuacoplenny** [comment] 2017-05-17 16:23
I installed your extension and checked its background page (from chrome://extensions) and noticed a script error. Could resolving the error also resolve your issues?

**Comment by cpot** [comment] 2017-05-19 21:55
We have also the issue that appeared recently. Is it possible that it is since a Chrome updrade?

**Comment by IvanMarkovic** [comment] 2017-07-26 12:02
Hi, I am also having the same issue. If I have installed google chrome extension everything works perfectly, but when I don't have installed I get "Permission denied. failed to install desktop sharing extension" and in browser console: gum.chrome_extension_installation_error", message: "Failed to install the extension from https://chrom…/webstore/detail/bejdagalpcfnmlocdbedgpghciceokcp.

I will appreciate any help. Thanks!

**Comment by thekyriarchy** [comment] 2017-10-03 02:34
is this a duplicate of #747 ?

**Comment by Do33o** [comment] 2017-11-16 17:15
I had this problem and solved it after some head scratching,  hopefully this helps others.

Inline install is required for clicking desktop sharing to trigger an install of your extension.   Verified site is required for inline install to be allowed.

You have to follow a few steps.  First,  you must have a verified site (I used our Jitsi server) added in webmaster tools.

Once your site is verified, edit your extension profile and you will see an option to associate your verified site with your extension.   You must do this.

Once you've associated a verified site,  you must then enable the "Inline install" option.

Having done both of these there can be a delay of a few minutes,  so allow time for this.   Then it should work.

**Closed** 2018-12-11 05:41 UTC
Labels: wontfix
