### ISSUE TITLE
Add option to talk over YouTube video without the video being muted

### ISSUE THREAD

**Issue by omer-g** [jitsi/jitsi-meet#8720] opened 2021-03-03 21:16 UTC
**Is your feature request related to a problem you are facing?**
When a YouTube video is playing, as soon as someone unmutes himself, the video is muted (and continues playing). In certain cases it is useful to be able to talk as the video's audio continues.

**Describe the solution you'd like**
It would be nice to have the option to either mute the video, or to talk while the video continues to play unmuted.

**Describe alternatives you've considered**
When user unmutes himself while a video plays, to prompt him if he would like to also mute the video.

**Comment by sbruder** [comment] 2021-03-04 22:03
Probably a duplicate of https://github.com/jitsi/jitsi-meet/issues/6390 and https://github.com/jitsi/jitsi-meet/issues/2540

**Closed** 2021-07-21 13:41 UTC
Labels: feature-request, wontfix

**Comment by alemoh1234** [comment] 2021-10-04 20:13
I think this should be reviewed when possible, It is really annoying to have this happen when everyone is wearing headphones.

**Comment by saghul** [comment] 2021-10-05 05:36
We have no plans to change how this feature works at this time.

**Comment by o-miller** [comment] 2021-11-05 22:29
> We have no plans to change how this feature works at this time.

Can we at least get a reason? Most of the folks asking are aware of the dreaded feedback loops that are mentioned but using that as justification to not even provide an option despite many people clearly wanting this is incredibly frustrating.

**Comment by jbg** [comment] 2021-11-06 01:05
> Can we at least get a reason? Most of the folks asking are aware of the dreaded feedback loops that are mentioned but using that as justification to not even provide an option despite many people clearly wanting this is incredibly frustrating.

It's a bit unreasonable to expect the core developers to add any given feature just because some people ask for it. Like everyone, they have limited time and should prioritise it toward things with a bigger impact (and can prioritise it however they want!). By definition anything that forces headphone use is a bit niche.

If this feature is important to you, it's not difficult to add it yourself or hire a developer to add it for you. If it's behind a default-off config option maybe you can even send a PR and try to get it merged.
