### ISSUE TITLE
New camera device control blocks camera

### ISSUE THREAD

**Issue by mjg** [jitsi/jitsi-meet#6540] opened 2020-05-02 12:04 UTC
## Description
The camera device controls (right at the camera icon) apparantly block all available cameras. This makes it impossible to record from a camera to a postprocessor (such as obs) and feed the postprocessor output to jitsi, because the postprocessor cannot access the camera.

## Current behavior
Virtual camera stream stalls as soon as Jitsi display the camera device controls.

## Expected Behavior
Jitsi grabs only the camera stream which is selected.

## Possible Solution
Release the camera unless the popup is displayed.
Note that this never happened with the menu settings for camera devices, only with the new controls.

## Steps to reproduce
Have to camera streams, enter Jitsi and select one camera. Observe that the other one is blocked for all other applications,

# Environment details
Linux: Fedora 31
Chrome: chrome-stable-81.0.4044
Cameras: video4linux devices (camera, obs)

**Comment by Echolon** [comment] 2020-05-13 19:24
Hi,
first question, is this a duplicate of #5425?

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by mjg** [comment] 2020-05-13 19:31
> Hi @mjg,
> first question, is this a duplicate of #5425?
> 
I don't see how. That one is a meta bug which claims to have fixes in current Jitsi.

This one here is about a regression in current Jitsi. My camera is working, in Jitsi and outside. The point is that Jitsi's new device control drop down grabs all cameras so that they don't work outside of Jitsi any more. This is different from what the preferences dialog is doing which in turn causes no problems.

**Closed** 2020-12-06 05:39 UTC
Labels: devices, wontfix
