### ISSUE TITLE
Broken startWithVideoMuted and startWithAudioMuted

### ISSUE THREAD

**Issue by mrin** [jitsi/jitsi-meet#8016] opened 2020-10-30 16:17 UTC
This update breaks startWithVideoMuted and startWithAudioMuted config settings.

https://github.com/jitsi/jitsi-meet/blob/9fbb35b6e18536a85fc608b0685c71744880a651/conference.js#L736
https://github.com/jitsi/jitsi-meet/blob/9fbb35b6e18536a85fc608b0685c71744880a651/conference.js#L739
https://github.com/jitsi/jitsi-meet/commit/9c10ac3028548c3e8535d35789b23492b194e9fd

**Comment by AyushmanChatterjee** [comment] 2020-11-20 12:37
Hello,

Is this issue going to be fixed soon?

Regards,

**Comment by kiliankoller** [comment] 2021-01-19 07:00
Same Problem here, conflicts with GDPR, so quite important. Thanks!

**Comment by saghul** [comment] 2021-01-19 13:10
Closing as a duplicate of https://github.com/jitsi/jitsi-meet/issues/8144, which has more context in it. Please follow that issue.

**Closed by saghul** 2021-01-19 13:10 UTC
Labels: confirmed
