### ISSUE TITLE
Error connecting with live stream YouTube

### ISSUE THREAD

**Issue by anlemaco** [jitsi/jitsi-meet#5970] opened 2020-04-13 22:23 UTC
An error occurred while accesing your YouTube broadcasts. Please try logging in again. All streamers are currently busy We're working on freeing streaming resources. Please try again in a few minutes.

**Comment by RedCore161** [comment] 2020-04-13 22:47
can you please give more context?

**Comment by anlemaco** [comment] 2020-04-13 23:37
Sure, I'm tryin https://meet.jit.si/ with the option to "Start live stream", It shows me a button with text "Sign in with Google", I tryied to login with my Google Account, and it shows me the error "An error occurred while accesing your YouTube broadcasts. Please try logging in again.".
Also it shows a textbox to enter a live stream key. When I try to put my live stream key, it shows the error "All streamers are currently busy We're working on freeing streaming resources. Please try again in a few minutes."
So I was not able to use live stream feature.

**Comment by luixxiul** [comment] 2020-04-15 14:39
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5266?

**Comment by Yaco** [comment] 2020-04-15 18:46
I have the same issue here. I think is not duplicate, because this error is related with the option "Live stream" (that is different than "Start recording"). 

I was able to make "Live streaming" via YouTube when running the 8x8 implementation of Jitsi Meet, but not on https://meet.jit.si.

Any clue?

**Comment by lucasdaiki** [comment] 2020-04-16 23:35
Im having the same issue. I tried with 2 different Google Accounts and it throws the same error.

**Comment by Echolon** [comment] 2020-05-13 20:21
I will close this with reference to this: #5146
See also: #5403

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-05-13 20:21 UTC
Labels: duplicate
