### ISSUE TITLE
Room password could be send as URL parameter

### ISSUE THREAD

**Issue by mzaman-19** [jitsi/jitsi-meet#6601] opened 2020-05-07 08:59 UTC
I'm trying to create rooms using a set password could be send as URL parameter.
Please see bellow example for more details.
https://meet.sangoma.com/room1234#45678
How can I do this anyone help please.

Regards

**Comment by jespino** [comment] 2020-05-18 11:42
I would like to give this a try.

**Comment by luixxiul** [comment] 2020-05-22 14:44
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5902

**Closed by luixxiul** 2020-05-22 14:44 UTC
Labels: feature-request
