### ISSUE TITLE
Video shoudn't start automatically when joining a meeting.

### ISSUE THREAD

**Issue by da-edra** [jitsi/jitsi-meet#5045] opened 2020-02-05 22:08 UTC
**Is your feature request related to a problem you are facing?**
When you join a Jitsi meeting the video from your webcam is started automatically, this can be pretty annoying if you're not using a web cam cover.

**Describe the solution you'd like**
I'd like Jitsi to have video disabled by default when joining a meeting so users can enable it manually in case the users want to share video from their webcams, this would also be helpful as on all the meeting I join I need to disable my video and most users do.

**Describe alternatives you've considered**
Covering the webcam (I already do that but not all users do).

**Comment by saghul** [comment] 2020-02-06 09:20
Hi there @da-edra ! Thanks for your feedback! Your concern is valid and shared by some, and we have plams to address this in the short term.

The plan is to add a "hair check" screen where you could decide if you want video / audio / etc *before* joining the meeting.

If you are using your own Jitsi Meet deployment, here is what you can do in the interim: set this option to `true`, so all participants join the conference with the video muted by default. https://github.com/jitsi/jitsi-meet/blob/9855fac8059091c9863c5075cf1fd057dea33ded/config.js#L139

If you are using a public instance like meet.jit.si, you can enfore this locally by appending `#config.startWithVideoMuted=true` to the URL, like so: `https://meet.jit.si/test123#config.startWithVideoMuted=true` I know it's not ideal, but you can think of it as a stopgap while we implement the aforementioned feature.

**Comment by da-edra** [comment] 2020-02-06 16:50
Hello @saghul , thanks for the quick reply.

I'm sadly not using my one Jitsi Meet deployment so resorting to the URL seems like the only option to me.

I'm not sure if we should let this issue open until the feature is implemented or closing it as there's a workaround, but I'll let it up to you.

Thanks! :smile:

**Comment by saghul** [comment] 2020-02-06 18:17
Let's keep it open until the feautre is implemented, as a reminder. Cheers!

**Comment by siku4** [comment] 2020-04-01 21:20
> If you are using your own Jitsi Meet deployment, here is what you can do in the interim: set this option to `true`, so all participants join the conference with the video muted by default.
> 
> https://github.com/jitsi/jitsi-meet/blob/9855fac8059091c9863c5075cf1fd057dea33ded/config.js#L139
> 

Hey @saghul,

may it be possible that `startWithVideoMuted: true` is overwritten by the corresponding app setting when joining a conference via Jitsi Meet app? I have made the experience that the video is just muted on start when joining via browser.

What is really confusing here: When opening a conference and choosing option "Everyone starts hidden" in the conference settings window then also participant joining via Jitsi Meet app are video muted - even if "join without video" is disabled.

Do have any suggestions here?

**Comment by saghul** [comment] 2020-04-01 21:23
> may it be possible that `startWithVideoMuted: true` is overwritten by the corresponding app setting when joining a conference via Jitsi Meet app? I have made the experience that the video is just muted on start when joining via browser.

Might be... we do have a setting for it, but IIRC it shoud only apply when we set to to yes, that is, to mute.



> When opening a conference and choosing option "Everyone starts hidden" in the conference settings window then also participant joining via Jitsi Meet app are video muted - even if "join without video" is disabled.

I'm confused. Are all participants joining with video muted or now, when you enable "Everyone starts hidden"? Note that it will only apply to new participants.

**Comment by siku4** [comment] 2020-04-01 21:37
> I'm confused. Are all participants joining with video muted or now, when you enable "Everyone starts hidden"? Note that it will only apply to new participants.

All participants have configured their app to join with video **enabled** (join without video = false). When I (as moderator) create a new conference room via browser, go to settings and enable "Everyone starts hidden", all participants join - as I expect - without video. Exactly this is the behavior I would like to configure for all new conferences with `startWithVideoMuted: true` globally in the config file.

**Comment by saghul** [comment] 2020-04-01 21:57
Got it. Mobile devices should honor `startWithVideoMuted: true ` if set in your server config. If not it's a bug we should address.

**Comment by siku4** [comment] 2020-04-01 22:50
> Got it. Mobile devices should honor `startWithVideoMuted: true ` if set in your server config. If not it's a bug we should address.

It should be a bug. Tested it on three iOS devices with Jitsi Meet 20.1.0 build 63. Unfortunately I don‘t have a Android device for testing. On server side anything should be correctly configured: Verified the config has been applied by opening <server-url>/config.json and via web client (chrome) participants successfully join without video.

**Comment by hasgar** [comment] 2020-05-08 05:44
same issue here. in both ios and android. @siku4 any fix?

**Comment by siku4** [comment] 2020-05-09 15:45
No fix yet @hasgar. I will create a separate issue for that.

**Comment by saghul** [comment] 2020-05-10 06:22
Thanks for testing and creating an issue, we’ll take a look ASAP.

**Comment by l3d00m** [comment] 2020-05-16 09:29
Linking this to #2737, as the issue is quite similar.

**Comment by Echolon** [comment] 2020-05-22 18:57
And also this: **make "start audio/video muted" web setting configurable in user's browser side preferences (like name and email)** #4913

I think this is a duplicate of the mentioned one.

**Comment by l3d00m** [comment] 2020-06-17 19:46
See the last linked issues for more details.

**Closed by l3d00m** 2020-06-17 19:46 UTC
Labels: duplicate, feature-request

**Comment by alexandredoein** [comment] 2020-07-14 13:36
Hi,
I think my issue is related to this case:

I saw that very recently (like this week), jitisi api now opens a screen before video with invitation link as showed on image attached.

I want the contrary: I am dealing with lots of people who are not used with technology (they are on their 50s or 60s). Also I am in Brazil and jitisi api is not in portuguese. So any click is very hard for people to understand and get it. A new screen makes things very worse for my application.

Also, it is bad to show invitation link since my system it is not supposed to add people using invitation link.

My question is: is there a way for api open video directly without this "join button"? (I mean skip this screen and go straght to talking part as before). It would be awesome a way to simply return to old version which was awesome in my application.

![old](https://user-images.githubusercontent.com/68284601/87431158-a28e9c00-c5bc-11ea-880f-94855a43230e.JPG)

Thanks in advance
Alex

**Comment by saghul** [comment] 2020-07-14 13:57
You can override the `prejoinPageEnabled` config option to disable that screen.

PS: The app is translated to Brazilian Portuguese. We used to have some bug matching the user's browser locale to select it automatically, but AFAIK that was resolved.

**Comment by alexandredoein** [comment] 2020-07-14 14:21
@saghul thanks for the quick answer. 
I tried to make a quick search on google but i couldn't find a coded example of how to set prejoinPageEnabled using jitsi api. Do you have some piece of code as example?

The way I see I was expecting to change something on "const options" parameters as below. I tried to insert prejoinPageEnabled 
as another parameter (but unfortunatelly it did not work):
	const domain = 'meet.jit.si';
	const options = {
		roomName: 'b66540d0-9565-11ea-bb37-0242ac130002',
		width: 600,
		height: 600,
		prejoinPageEnabled: true, //also tried: prejoinPageEnabled //also tried: prejoinPage: 'Enabled'
		parentNode: document.querySelector(objName)
	};
	const api = new JitsiMeetExternalAPI(domain, options);

Do you have any ideas?

(Also, my browser is in Portuguese but jitsi is still in English. please let me know if I need to set something)

**Comment by damencho** [comment] 2020-07-14 14:36
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe is your documentation link.
You need to pass it in configOverwrite. 

const options = {
....
configOverwrite: { prejoinPageEnabled: false }
...

**Comment by alexandredoein** [comment] 2020-07-14 14:40
@damencho thanks for the quick and precise answer. 
It worked perfectly. 
Also thanks for the docs!
