### ISSUE TITLE
CONFERENCE_TERMINATED  {error=connection.otherError, url=https://meet.xxx}  in Android

### ISSUE THREAD

**Issue by houxinlin** [jitsi/jitsi-meet#8907] opened 2021-03-29 12:39 UTC
Hello，I frequently receive the following errors in Android，After that, a dialog box will pop up for reconnection
```
CONFERENCE_TERMINATED  {error=connection.otherError, url=https://meet.xxx}  
```
But in the first few seconds he was normal,

How can I solve it？

**Comment by saghul** [comment] 2021-03-29 15:25
Do you see any other log lines before that?

**Comment by houxinlin** [comment] 2021-03-29 15:35
> 在此之前，您还看到其他任何日志行吗？

No other logs，This log received by broadcast，But it's normal in web pages

**Comment by saghul** [comment] 2021-03-29 17:30
Check the JitsiMeetSDK tag, and paste all the logs please.

**Comment by houxinlin** [comment] 2021-03-29 23:23
> Check the JitsiMeetSDK tag, and paste all the logs please.

Ok，This is all the logs after the connection。
```java
2021-03-30 07:16:16.472 1127-1622/com.example.hxl.healthy I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
2021-03-30 07:16:17.398 1127-1269/com.example.hxl.healthy I/JitsiMeetSDK: [modules/xmpp/xmpp.js] (TIME) Strophe connfail[item-not-found]:	 1617059777394
2021-03-30 07:16:17.402 1127-1269/com.example.hxl.healthy I/JitsiMeetSDK: [modules/xmpp/strophe.ping.js] Ping interval cleared
2021-03-30 07:16:17.408 1127-1269/com.example.hxl.healthy I/JitsiMeetSDK: [modules/xmpp/xmpp.js] (TIME) Strophe disconnected[item-not-found]:	 1617059777403
2021-03-30 07:16:17.408 1127-1269/com.example.hxl.healthy I/JitsiMeetSDK: [modules/statistics/statistics.js] {"type":"operational","action":"connection.failed","attributes":{"error_type":"connection.otherError","error_message":"item-not-found","suspend_time":10,"time_since_last_success":11}}
2021-03-30 07:16:17.480 1127-1269/com.example.hxl.healthy I/JitsiMeetSDK: [features/overlay] The conference will be reloaded after 27 seconds.
2021-03-30 07:16:17.567 1127-1269/com.example.hxl.healthy D/JitsiMeetSDK: [features/base/lastn] There is no active conference, not updating last N
2021-03-30 07:16:17.567 1127-1269/com.example.hxl.healthy I/JitsiMeetSDK: [modules/e2eping/e2eping.js] Stopping e2eping
2021-03-30 07:16:17.574 1127-1269/com.example.hxl.healthy I/JitsiMeetSDK: [modules/xmpp/ChatRoom.js] do leave 4d92730c-ef19-4b8e-8d80-34863e3951ff@conference.meet.xxx.com/1e59cfbc
2021-03-30 07:16:17.575 1127-1269/com.example.hxl.healthy D/JitsiMeetSDK: ExternalAPI Sending event: CONFERENCE_TERMINATED with data: { NativeMap: {"error":"connection.otherError","url":"https://meet.xxx.com/4d92730c-ef19-4b8e-8d80-34863e3951ff"} }
2021-03-30 07:16:17.575 1127-1127/com.example.hxl.healthy I/QX: onBroadcastReceived: CONFERENCE_TERMINATED  {error=connection.otherError, url=https://meet.xxx.com/4d92730c-ef19-4b8e-8d80-34863e3951ff}
2021-03-30 07:16:17.580 1127-1269/com.example.hxl.healthy D/JitsiMeetSDK: JitsiConnectionService reportCallFailed 9C4E7B92-09CF-4263-93F1-C0FC8E6AC20D
2021-03-30 07:16:17.581 1127-1269/com.example.hxl.healthy D/JitsiMeetSDK: JitsiConnectionService onStateChanged: DISCONNECTED 9C4E7B92-09CF-4263-93F1-C0FC8E6AC20D
2021-03-30 07:16:17.591 1127-1381/com.example.hxl.healthy I/JitsiMeetSDK: AudioMode Update audio route for mode: 0
2021-03-30 07:16:17.591 1127-1381/com.example.hxl.healthy I/JitsiMeetSDK: AudioMode Updating audio device list
2021-03-30 07:16:17.592 1127-1269/com.example.hxl.healthy D/JitsiMeetSDK: ExternalAPI Sending event: CONFERENCE_TERMINATED with data: { NativeMap: {"url":"https://meet.xxx.com/4d92730c-ef19-4b8e-8d80-34863e3951ff","error":"connection.otherError"} }
2021-03-30 07:16:17.593 1127-1269/com.example.hxl.healthy I/JitsiMeetSDK: [features/base/conference] JitsiConference.leave() rejected with: Error(Error){"message":"Not connected"}
2021-03-30 07:16:17.593 1127-1127/com.example.hxl.healthy I/QX: onBroadcastReceived: CONFERENCE_TERMINATED  {error=connection.otherError, url=https://meet.xxx.com/4d92730c-ef19-4b8e-8d80-34863e3951ff}
2021-03-30 07:16:18.332 1127-1629/com.example.hxl.healthy I/org.webrtc.Logging: EglRenderer: Duration: 4003 ms. Frames received: 119. Dropped: 0. Rendered: 119. Render fps: 29.7. Average render time: 3149 us. Average swapBuffer time: 1474 us.
2021-03-30 07:16:18.474 1127-1622/com.example.hxl.healthy I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
2021-03-30 07:16:18.785 1127-1127/com.example.hxl.healthy D/AlarmPingSender: Sending Ping at:1617059778785
2021-03-30 07:16:18.789 1127-1127/com.example.hxl.healthy D/AlarmPingSender: Schedule next alarm at 1617059783789
2021-03-30 07:16:18.789 1127-1127/com.example.hxl.healthy D/AlarmPingSender: Alarm scheule using setExactAndAllowWhileIdle, next: 5000
2021-03-30 07:16:18.842 1127-1252/com.example.hxl.healthy D/AlarmPingSender: Success. Release lock(MqttService.client.1135Id):1617059778842
2021-03-30 07:16:20.475 1127-1622/com.example.hxl.healthy I/org.webrtc.Logging: CameraStatistics: Camera fps: 30.
2021-03-30 07:16:21.805 1127-1629/com.example.hxl.healthy I/org.webrtc.Logging: EglRenderer: Dropping frame - No surface
2021-03-30 07:16:21.837 1127-1629/com.example.hxl.healthy I/org.webrtc.Logging: EglRenderer: Dropping frame - No surface
2021-03-30 07:16:21.850 1127-1269/com.example.hxl.healthy D/JitsiMeetSDK: [features/base/lastn] There is no active conference, not updating last N
2021-03-30 07:16:21.859 1127-1269/com.example.hxl.healthy I/JitsiMeetSDK: [modules/RTC/JitsiLocalTrack.js] Mute LocalTrack[2,video]: true
2021-03-30 07:16:21.860 1127-1266/com.example.hxl.healthy I/org.webrtc.Logging: CameraCapturer: Stop capture
2021-03-30 07:16:21.861 1127-1266/com.example.hxl.healthy I/org.webrtc.Logging: CameraCapturer: Stop capture: Nulling session
2021-03-30 07:16:21.861 1127-1266/com.example.hxl.healthy I/org.webrtc.Logging: CameraCapturer: Stop capture done
2021-03-30 07:16:21.861 1127-1622/com.example.hxl.healthy I/org.webrtc.Logging: Camera2Session: Stop camera2 session on camera 1
2021-03-30 07:16:21.861 1127-1622/com.example.hxl.healthy I/org.webrtc.Logging: Camera2Session: Stop internal
2021-03-30 07:16:21.861 1127-1622/com.example.hxl.healthy I/org.webrtc.Logging: SurfaceTextureHelper: stopListening()
2021-03-30 07:16:21.886 1127-1127/com.example.hxl.healthy I/org.webrtc.Logging: EglRenderer: Releasing.
2021-03-30 07:16:21.887 1127-1629/com.example.hxl.healthy E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
2021-03-30 07:16:21.887 1127-1629/com.example.hxl.healthy I/org.webrtc.Logging: GlShader: Deleting shader.
2021-03-30 07:16:21.887 1127-1629/com.example.hxl.healthy I/org.webrtc.Logging: EglRenderer: eglBase detach and release.
2021-03-30 07:16:21.888 1127-1127/com.example.hxl.healthy I/org.webrtc.Logging: EglRenderer: Releasing done.
2021-03-30 07:16:21.888 1127-1629/com.example.hxl.healthy I/org.webrtc.Logging: EglRenderer: Quitting render thread.
2021-03-30 07:16:22.105 1127-1177/com.example.hxl.healthy E/libc: Access denied finding property "camera.aux.packagelist"
2021-03-30 07:16:22.108 1127-1177/com.example.hxl.healthy E/libc: Access denied finding property "camera.aux.packagelist"
2021-03-30 07:16:22.111 1127-1622/com.example.hxl.healthy W/BpBinder: Slow Binder: BpBinder transact took 246 ms, interface=android.hardware.camera2.ICameraDeviceUser, code=1 oneway=false
2021-03-30 07:16:22.111 1127-1364/com.example.hxl.healthy W/ple.hxl.health: Long monitor contention with owner CaptureThread (1622) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(BinderProxy.java:-2) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onDeviceError(int, android.hardware.camera2.impl.CaptureResultExtras) for 238ms
2021-03-30 07:16:22.111 1127-1622/com.example.hxl.healthy I/org.webrtc.Logging: Camera2Session: Stop done
2021-03-30 07:16:22.111 1127-1622/com.example.hxl.healthy I/org.webrtc.Logging: Camera2Session: Camera device closed.
2021-03-30 07:16:22.111 1127-1622/com.example.hxl.healthy D/com.oney.WebRTCModule.WebRTCModule: CameraEventsHandler.onFirstFrameAvailable

```

But it will pop up in a few seconds

![微信图片_20210330072018](https://user-images.githubusercontent.com/38684327/112911609-65594280-9128-11eb-8241-68390f70f7d3.jpg)

**Comment by houxinlin** [comment] 2021-03-31 02:03
Please solve my problem

**Comment by houxinlin** [comment] 2021-03-31 05:58
> stock

I use my own server. Is it related to the server configuration？

**Comment by houxinlin** [comment] 2021-03-31 06:09
Yes，It works normally in the browser

**Comment by houxinlin** [comment] 2021-03-31 06:16
This is my server，https://meet.houxinlin.com

**Comment by houxinlin** [comment] 2021-03-31 06:28
May be my server problem，Because I use https://meet.jit.si without any problems，But where is the problem

**Comment by saghul** [comment] 2021-03-31 07:18
So start with, it uses a self-signed certificate, which won't work on mobile.

**Comment by saghul** [comment] 2021-03-31 07:18
I am going to close this since it's not a bug in the software. Please feel free to ask questions in our community.

**Closed by saghul** 2021-03-31 07:18 UTC
