### ISSUE TITLE
[iOS] App crashes after calling jitsiMeetView?.retrieveParticipantsInfo()

### ISSUE THREAD

**Issue by jsearle** [jitsi/jitsi-meet#8578] opened 2021-02-07 13:06 UTC
### Description:

I have upgraded to v3.1.0 in order to get the new SDK feature retrieveParticipantsInfo(), but the app crashes after being called.

### Steps to reproduce:

1. Create and join a conference:
```Swift
let jitsiMeetView = JitsiMeetView(frame: CGRect(x: 0, y: 0, width: 300, height: 200))
jitsiMeetView.delegate = self
let ui = JitsiMeetUserInfo(displayName: "my name", andEmail:"my@email.com", andAvatar: nil)
let options = JitsiMeetConferenceOptions.fromBuilder({ builder in
    builder.serverURL = URL(string: "https://meet.jit.si")
    builder.room = "my_personal_room_3"
    builder.subject = "Room"
    builder.token = nil
    builder.audioMuted = false
    builder.videoMuted = false
    builder.setFeatureFlag("chat.enabled", withBoolean: true)
    builder.setFeatureFlag("invite.enabled", withBoolean: true)
    builder.setFeatureFlag("JMCallKitProxy.enabled", withBoolean: false)
    builder.userInfo = ui
})
jitsiMeetView.join(options)
```
2. Wait for the meeting for setting up...
3. Try to get the participants array
```Swift
jitsiMeetView?.retrieveParticipantsInfo({ (d:[Any]?) in
            print("Retrieved!")
})
```
### Expected behavior:

It should output the message "Retrieved!" in the debug log

### Actual behavior:

App crashes with no message (AppDelegate)
<img width="1324" alt="Captura de pantalla 2021-02-07 a las 14 02 09" src="https://user-images.githubusercontent.com/1092275/107147311-9a79bd80-694d-11eb-945e-0024bfd9853b.png">

### Client information:

- Jitsi Meet version: iOS SDK 3.1.0
- Crashes on iOS simulator and on iPhone X device. iOS versions 13.2 and 14.3

**Comment by saghul** [comment] 2021-02-07 13:18
Ping @tmoldovan8x8

**Comment by tmoldovan8x8** [comment] 2021-02-09 16:04
Thanks @jsearle for signalling this. There was a problem with the way the completion blocks are handled on Swift. Merged the fix and we'll release a new SDK asap.

**Comment by jsearle** [comment] 2021-02-09 16:17
Great news you managed to fix it. Thank you for your help and keep improving this great project!

**Comment by ahmed-classtra** [comment] 2021-06-15 19:47
Did anyone manage to get this working, we're still seeing this problem in SDK 3.6.0. Is there a workaround in the meantime?
@tmoldovan8x8 @jsearle ?

**Comment by tmoldovan8x8** [comment] 2021-06-16 05:43
Hi @ahmed-classtra. In what situation are you still reproducing this? I've just tested it on SDK 3.6.0 and it seems to be working fine.

**Comment by AlvaroBro** [comment] 2021-10-04 16:44
Hi!
I'm having trouble using retrieveParticipantsInfo.
In my case, I don't see any crash, but the callback is not called, some times.
I don't know what it depends on but sometimes the callback is called and I get the participants info, and other times it does not. Is there anything I'm missing regarding the use of retrieveParticipantsInfo? I mean, it should work always regardless of who the creator of the conference is, or any other aspect of it right?

**Comment by AlvaroBro** [comment] 2021-10-05 09:16
Sorry to bother you guys! @saghul @tmoldovan8x8 @ahmed-classtra do you have any thoughts or new info regarding this issue retrieving participants?
Regards!

**Closed** 2022-04-30 22:34 UTC
Labels: mobile, wontfix, ios

**Comment by maulikgoyanidbc** [comment] 2024-06-06 13:46
I am getting same issue on iOS
SDK version: 8.5.0
![Screenshot 2024-06-06 at 7 15 13 PM](https://github.com/jitsi/jitsi-meet/assets/137482703/fa3a1221-ac7e-4c1a-8294-266d9946406e)

can any one help me?
