### ISSUE TITLE
Audio problems

### ISSUE THREAD

**Issue by kinnla** [jitsi/jitsi-meet#1278] opened 2017-01-31 11:13 UTC
We are using a self-hosted instance of jitsi meet for conference calls (<10 people). In most of the calls we experience audio problems: some people can not hear each other. Then they disconnect and reconnect, but sometimes the problem remains and we fall back to skype. We recently hat upgraded to 1.0.1592, but it seems to be even worse, so we rolled back to 1.0.1575.

How can we debug or mitigate the problem? Some ideas what might cause the trouble:

- our installation or server configuration might be flawed
- people connect with a variety of OSs and browsers that not all might play well together
- firewalls cut of audio streams

Thanks in advance

**Comment by saghul** [comment] 2017-01-31 12:53
Hi there,

Is it an option for you to test using meet.jit.si?  If so, do you observe any difference?  As for the participants who see their connections failing, can you spot a patter?  Say, they use the same browser, for example.

Cheers,

**Comment by edi9999** [comment] 2017-02-01 18:02
We have the same issue, it also happens on meet.jit.si . We haven't found any pattern , but it seems to be that if we have 5 people connected : A, B, C, D, E

A can hear everyone
B can hear everyone
C can hear everyone but D
D can hear everyone but C
E can hear everyone

If C and D reconnect, they can hear everyone.

**Comment by edi9999** [comment] 2017-02-01 18:05
We are using Fedora (3 persons), Fedora with xfce(1 person), MacOs(1 person),  and are all using Chrome (I assume latest, since it auto updates).

From memory, it seems to happen both between 2 persons using Fedora, or with MacOs and Fedora, and with all possible cases in general.

**Comment by saghul** [comment] 2017-02-02 10:06
That's really weird. Are C and D consistently the same people?  Checking the Chrome versions of those who fail might be a good start.

**Comment by edi9999** [comment] 2017-02-02 13:05
No we don't all have the same Chrome version, some of us have the version 55, some of them version 56.

However, it didn't seem to happen always with the same people, I mean, it has happened between users of 55 and 56, 55 and 55 , 56 and 56.

**Comment by gpolitis** [comment] 2017-02-02 16:18
@edi9999 in the above example, have D and C enabled their cameras?

**Comment by edi9999** [comment] 2017-02-02 17:53
I'm 90% sure that C and D were **not using the camera at that point**, since the way we found out that there is a bug was because two people started talking simultaneously without being aware that someone else speaks.

**Comment by gpolitis** [comment] 2017-02-02 22:08
Unfortunately, this is a valid bug; we know what's causing and we've implemented a workaround that doesn't always work. We're working on a more proper fix. I understand it's really annoying and frustrating. In the meantime, you can unmute your video for a few seconds and then mute again. This should fix the issue.

**Comment by cdtapay** [comment] 2017-02-06 14:30
Just a few minutes ago, one of guys on my team, found out another workaround: the person that cannot be heard, just put the camera on and off, and everybody can hear him/her.

@gpolitis, **is there an ETA for the fix?** Jitsi looks nice, but team got frustated with this issue. Thanks.

**Comment by gpolitis** [comment] 2017-02-08 18:13
One other workaround is to disable lipsync. On your own deployment you can set `disableLipSync: true` in config.js and on meet.jit.si you can append `#config.disableLipSync=true` in the URL.

@cdtapay we're going to give a fix a try next week.

**Comment by gpolitis** [comment] 2017-02-10 19:26
We're hoping this https://github.com/jitsi/jitsi-videobridge/pull/418 will fix this issue. Once it's merged it will get deployed on our staging environment. I'll write here when it's released on https://meet.jit.si/

**Comment by bamms** [comment] 2017-05-10 12:38
My experience was, I installed latest Jitsi in March, and it was working well across. 
All of a sudden, audio just stopped across all browsers. Installed the newest jitisi meet but still experiencing same. Any guides by now please?

**Comment by gpolitis** [comment] 2017-05-14 20:43
@bamms can you please describe a little bit how you're testing and what you're seeing?

**Comment by psaavedra** [comment] 2018-08-01 20:49
> One other workaround is to disable lipsync. On your own deployment you can set disableLipSync: true > in config.js and on meet.jit.si you can append #config.disableLipSync=true in the URL.
>
> @cdtapay we're going to give a fix a try next week.

@gpolitis I don't see `disableLipSync` option in jitsi-meet code. Is it still a valid option ?

We have the same audio issues described in this issue in

```
ii  jicofo                             1.0-417-1                          amd64        JItsi Meet COnference FOcus
ii  jigasi                             1.0-175                            amd64        Jitsi Gateway for SIP
ii  jitsi-archive-keyring              1.0.1                              all          The public key for the Jitsi packages repository
ii  jitsi-meet                         1.0.3135-1                         all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                 1.0.2866-1                         all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                     1.0.2866-1                         all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config              1.0.2866-1                         all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge                  1066-1                             amd64        WebRTC compatible Selective Forwarding Unit (SFU)
```

**Comment by psaavedra** [comment] 2018-08-01 21:01
Maybe I can reply myself with this: `enableLipSync: false`, right?

**Comment by sylvainlb** [comment] 2018-09-25 09:37
Fyi, We're experiencing the same issues on meet.jit.si

**Comment by Gallaecio** [comment] 2018-12-07 12:19
May this be a duplicate of #641?

**Comment by cathalgarvey** [comment] 2018-12-07 12:20
Just another FYI, we started using meet.jit.si for a team call, and have started experiencing the above issues. I've used this server a lot for smaller calls, and have never had the "A can hear everyone but D" issue, but now that we're having calls of 10+ people it's happening _every time_. We're currently looking at switching to Mumble, but it's a shame we can't use this FLOSS video-conferencing system. It would be great to use screenshare sometimes and we'll lose that with Mumble.

**Comment by damencho** [comment] 2018-12-07 12:33
And browser versions especially.

**Comment by Gallaecio** [comment] 2018-12-07 12:39
The issue does not seem to be specific to a browser or OS. The people in the meetings @cathalgarvey mentions are using a variety of both (at least Linux and OS X, also Firefox and Chrome/Chromium). And affected people does not seem to use a given combination of those. Also, refreshing the browser page when audio stops brings it back; if you are lucky until the end of the call, otherwise for a short time.

From my experience, it might have something to do with joins (as new people join in I might stop hearing someone currently speaking), but I am not really sure it always happened surrounding a join or departure.

**Comment by edi9999** [comment] 2018-12-07 12:53
@Gallaecio totally share the same feeling about this issue. I'm not so sure that this has anything to do with joins however, I think this happens quite randomly, and it never comes back by itself, someone has to reload the browser tab to make it work.

**Comment by cathalgarvey** [comment] 2018-12-07 13:19
A sampling from our call, with a little feedback from each:

* OSX Sierra 10.12.6 / Chrome v70.0.3538.110 / _Freezes sometimes_
* Ubuntu Gnome 16.04 /, Firefox 63.0.3 (64-bit) / got lots audio loss problem with this browser.
* (Unknown OS) / Chrome 70.0.3538.110 (64-bit) / only got the audio problem once.
* Linux Mint 19 / Chrome Version 71.0.3578.80 (Official Build) (64-bit) / OK, except few problems with the sound for several minutes
* OSX Mojave 10.14.1 / Chrome 70.0.3538.110 / Works fine
* Ubuntu 18.04 Linux 4.15.0-42-generic / Firefox 63.0.3 (64-bit) / Others could not always hear me, I cannot always hear others
* Ubuntu 18.04 Linux 4.15.0-42-generic / Chromium 70.0.3538.110 (Official Build) (64-bit) / Same user as above. No issues yet, but tested late in call when few coming/leaving. Strongly prefer Firefox. :)

Hope that helps!

**Comment by chamerling** [comment] 2019-02-04 13:41
Hello,

Can we have a status on this issue? 
Thx a lot

**Comment by saghul** [comment] 2019-02-05 09:05
Hi there! We released a new stable build last week, can you check if you still have issues?

**Comment by pabelenda** [comment] 2019-03-06 11:43
> Hi there! We released a new stable build last week, can you check if you still have issues?

@saghul which version do you refer to on your comment?

I have a couple of deployments, one is running jitsi-meet 1.0.3508-1 and jitsi-videobridge 1104-1 (etc) and the other running jitsi-meet 1.0.3548-1 and jitsi-videobridge 1109-1 (etc),

The former one has audio issues, the latter is being tested, but it's been running for just a couple of days so I cannot confirm if it has audio issues.

Just for completeness, these are the versions running on both deployments:

A
```
jicofo:
  Installed: 1.0-451-1
jitsi-meet:
  Installed: 1.0.3508-1
jitsi-meet-prosody:
  Installed: 1.0.3186-1
jitsi-meet-web:
  Installed: 1.0.3186-1
jitsi-meet-web-config:
  Installed: 1.0.3186-1
jitsi-videobridge:
  Installed: 1104-1
```
B
```
jicofo:
  Installed: 1.0-458-1
jitsi-meet:
  Installed: 1.0.3548-1
jitsi-meet-prosody:
  Installed: 1.0.3216-1
jitsi-meet-web:
  Installed: 1.0.3216-1
jitsi-meet-web-config:
  Installed: 1.0.3216-1
jitsi-videobridge:
  Installed: 1109-1
```

**Comment by saghul** [comment] 2019-03-06 13:21
Yep, B looks like it's running the latest components.

**Comment by pabelenda** [comment] 2019-03-06 13:29
Many thanks for the quick response @saghul , we will try this version out and see if things have improved.

**Comment by chamerling** [comment] 2019-03-12 08:54
Hi @saghul,

I just updated to latest release yesterday and for now it looks really better.

**Comment by psaavedra** [comment] 2019-03-12 10:08
Which version @chamerling?

**Comment by chamerling** [comment] 2019-03-12 10:13
According to https://github.com/jitsi/docker-jitsi-meet/issues/72, I am using this one https://github.com/jitsi/jitsi-meet/releases/tag/stable/jitsi-meet_3548

**Comment by saghul** [comment] 2019-03-12 11:58
> I just updated to latest release yesterday and for now it looks really better.

Thanks for letting us know!

**Comment by johnxie** [comment] 2019-04-10 03:05
We are experiencing something similar with meet jitsi.

**Comment by saghul** [comment] 2019-04-10 08:16
@johnxie What devices were involved and what was the exact problem you were facing?

**Comment by johnxie** [comment] 2019-04-10 13:39
All running on Chrome + macOS Mojave.

**Closed** 2019-07-16 14:26 UTC
Labels: wontfix

**Comment by pabelenda** [comment] 2019-07-16 16:20
I would like to say that we are still experiencing this audio problems.

**Comment by saghul** [comment] 2019-07-16 16:34
@pabelenda Please open a new issue. This one was opened too long ago and "audio issues" ends up being too generic. Thank you!

**Comment by jonnius** [comment] 2020-03-18 10:27
We still hit this issue and I think it has been described well enough in the discussion. Do you want me to summarize it in a new issue?

**Comment by saghul** [comment] 2020-03-18 10:39
Please do!
