### ISSUE TITLE
Add inbuilt whiteboard collaboration with annotation facility for participants too

### ISSUE THREAD

**Issue by jagadish-pattanaik** [jitsi/jitsi-meet#8279] opened 2020-12-18 17:42 UTC
The jitsi meet would be far better than other platforms if it had a real-time whiteboard and other documents sharing the facility with annotation for participants too like it is zoom meetings.

**Comment by saghul** [comment] 2020-12-18 19:32
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5295

**Closed by saghul** 2020-12-18 19:32 UTC
Labels: feature-request
