### ISSUE TITLE
Streaming issues on Jit.si

### ISSUE THREAD

**Issue by lcanavarro** [jitsi/jitsi-meet#6138] opened 2020-04-17 13:24 UTC
Hello, Im trying to start a live on YouTube using Jitsi Meet but it says all streamers are busy. I have now 3500 people waiting for the live to start and Im kind of worried. Could you help me?

**Comment by luixxiul** [comment] 2020-04-17 13:26
@saghul

**Comment by l3d00m** [comment] 2020-04-17 13:48
Duplicate of #6128 and #5403

**Comment by luixxiul** [comment] 2020-04-17 13:59
@lcanavarro I would recommend you to alternative- it may get too late to make this fixed.

**Comment by lcanavarro** [comment] 2020-04-17 14:13
It's all good now, thanks. Does Jit.si often have difficulties finding a streaming server for YouTube lives? Do you know any alternatives?

**Comment by luixxiul** [comment] 2020-04-17 14:21
> It's all good now, thanks.

I see, I'm relieved. Lately I see a lot of people report the issue.

>  Do you know any alternatives?

Sorry I'm not quite sure.

**Comment by lcanavarro** [comment] 2020-04-17 15:13
Thanks, @luixxiul

**Closed** 2020-05-13 11:02 UTC
