### ISSUE TITLE
Screen sharing doesn't work properly with Firefox 80

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet#7642] opened 2020-09-05 21:17 UTC
### Steps to reproduce:

1. Open Firefox
1. Open LibreOffice Impress presentation
1. Menu Bar → Slide Show → Start from First Slide F5
1. Alt+Tab to switch to Firefox, open a room on [Jitsi Meet](https://meet.jit.si/) and share the screen `Presenting: …`
1. When the presentation slides are changed, the other person with Firefox 80.0 (64-bit) only sees one slide, the slides do not change.

### Expected behavior:

Screen share should work with Firefox.

### Actual behavior:

Screen share does not show slide changes.

### Server information:

- Jitsi Meet version: [Jitsi Meet](https://meet.jit.si/)
- Operating System: 5th September 2020

### Client information:

- Screen share program: LibreOffice 7.0.1.2 [Linux (64-bit) (deb)](https://www.libreoffice.org/download/download/)
- Browser / app version: [Firefox](https://www.mozilla.org/firefox/new/) 80.0 (64-bit)
- Operating System: [Linux Mint 20 Cinnamon](https://www.linuxmint.com/edition.php?id=281)

### Additional information:

* All the participants in the Jitsi Meet Room were hidden, i.e. their video was turned off. Does this help to reproduce?
* Is this a bug introduced with the updated Jitsi Meet program?
* Is this a feature missing in Firefox 80 which the updated Jitsi Meet program requires? https://github.com/jitsi/jitsi-meet/issues/4758
* Also didn't work when we shared a screen from a different program.
* Worked when Chrome was used by the presenter and the view was using Firefox. However, the sound was not good for the Firefox viewers when their microphones were muted. When the viewer unmuted their microphones, then the sound from the presenter (on Chrome) was fine.

Thank you

**Comment by damencho** [comment] 2020-09-05 22:49
I believe there is nothing we can do for this issue, as this is entirely on the browser side. Search their bugzilla for a similar report and report it there.
Does it work with Firefox 79 or any other version?

**Comment by ovari** [comment] 2020-09-05 23:23
Yes, Jitsi Meet worked with Firefox 79 and lower when we last used Jitsi Meet.

Since the last time we used Jitsi Meet:
* Firefox updated to 80
* Jitsi Meet now:
a) has the Settings → More → Enable pre meeting screen
b) no longer has the `Tile view` when `You are the only one in the meeting`

With Chrome, there was a delay of about 5 seconds from when the slide was changed by the presenter to the change being seen by the viewer.

**Comment by ovari** [comment] 2020-09-05 23:43
> Search their bugzilla for a similar report and report it there.

https://bugzilla.mozilla.org/show_bug.cgi?id=1663286

**Comment by saghul** [comment] 2020-09-09 13:23
>     * Jitsi Meet now:
>       a) has the Settings → More → Enable pre meeting screen
>       b) no longer has the `Tile view` when `You are the only one in the meeting`

This is not related to screen-sharing.

**Comment by ovari** [comment] 2020-09-10 20:49
Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1663286 has also been confirmed on Windows 10 with Firefox Release 80.0 (64-bit) and Firefox Nightly 82.0a1 (2020-09-10) (64-bit).. Thank you

**Comment by ovari** [comment] 2020-09-19 11:00
> Tried again today with 6 people (including us) in a Jitsi Meet room. They couldn't see our screen share. We were using Linux Mint 20 Cinnamon 64-bit with Firefox 80.0.1 64-bit. The Jitsi Meet room in our Firefox browser showed the screen share.
> 
> A person using Firefox 32-bit on Windows 7 (32-bit) could only see the screen share once we stopped sharing the screen. It showed them the screen which was shared after we stopped screen sharing!?
> 
> There was a person on our local area network (Linux Mint 19.3 Cinnamon 64-bit with Firefox 80.0.1 64-bit) that also couldn't see the screen share. Perhaps Firefox no longer works when there a someone in the Jitsi Meet room on the local area network?

https://bugzilla.mozilla.org/show_bug.cgi?id=1663286#c20

**Comment by awlx** [comment] 2021-01-08 21:04
Firefox 84.0.2 seems not to fix this issue as it happened again on https://meet.ffmuc.net ... we had to remove the following stanza to make it work again:

https://github.com/jitsi/jitsi-meet/issues/4758#issuecomment-756991405

**Comment by awlx** [comment] 2021-01-09 12:36
Ok, I tried to reproduce it and on Firefox 84 it immediately fails with 78 it's working just fine. Here are the screenshots. Everytime I just share the screen from one window and have a look with 5 others.

working FF78:
![Screenshot 2021-01-09 at 13 29 42](https://user-images.githubusercontent.com/6527744/104091730-9475bb80-527f-11eb-9c0b-5f72f6ce86f0.png)

Not working ff84.0.2:
![Screenshot 2021-01-09 at 13 33 34](https://user-images.githubusercontent.com/6527744/104091739-9f305080-527f-11eb-8c46-cfb9b8d50150.png)

As you can see the screensharing window appears but no video is transmitted

**Comment by awlx** [comment] 2021-01-09 14:16
It seems the disableRTX Patch was missing on our plattform and now it works ...
https://github.com/jitsi/lib-jitsi-meet/commit/0cffc064e644ad87ff381cc6c4df1c1a9f2c73ff

**Comment by pierreozoux** [comment] 2021-07-27 09:10
I think it will be improved/fix by https://github.com/jitsi/jitsi-meet/issues/7369#event-4948152557

**Comment by saghul** [comment] 2021-07-27 09:28
Oops, looks like we forgot to close this one.

**Closed by saghul** 2021-07-27 09:28 UTC
Labels: browser-support
