### ISSUE TITLE
Chat panel moves the video out of the screen

### ISSUE THREAD

**Issue by GLM-NormandNadon** [jitsi/jitsi-meet#7889] opened 2020-10-08 00:44 UTC
This affects only our docker instance (for now)
When we pop-out the chat panel, the video slides to the right instead of the panel covering the video.
When chat is closed, Video does not return to its original location.
A resize of the window is necessary to trigger the "re-centering" of the video

Video Settings are the same on both of our instances (bare metal, updated few weeks ago and docker installs) but it affects only the docker instance we have…

Issue seems to affect all browsers.

Zooming factor makes no difference

Resolution makes no difference

**Comment by saghul** [comment] 2020-10-13 07:15
@muscat1 Mihai can you please take a look here? Looks related to your chat panel move changes.

**Comment by pugelarouge** [comment] 2020-10-14 09:00
Seeing this issue on my latest stable (deb not docker) / meet.jit.si and beta.meet.jit.si (in chrome)

From what I can see the problem is that the chat is still animating it's close when it's width is measured ... so the video is left with that much gap on the left ( css::left ), and the same amount is chopped form the right (by virtue of being pushed beyond the view-port). It fixes with any trigger to recalculate (such as a browser resize), so possibly it just requires a delay (or callback) until after the chat has finished closing (visually).

**Comment by fipski** [comment] 2020-10-14 10:46
Removing the line I mentioned seems to fix it for me, I build from sources to do some changes. In the commit the line was added it is mentioned: "This is needed when custom styling is configured on the large video container through the iFrame API" . I don't know what it would break if you run jitsi in a iFrame.

        /**
         * If chat state is open, we re-compute the container width by subtracting the default width of
         * the chat. We re-compute the width again after the chat window is closed. This is needed when
         * custom styling is configured on the large video container through the iFrame API.
         */
        if (isOpen && !this.resizedForChat) {
            widthToUse -= CHAT_SIZE;
            this.resizedForChat = true;
        } else if (this.resizedForChat) {
            this.resizedForChat = false;
            widthToUse += CHAT_SIZE;
        }

**Comment by muscat1** [comment] 2020-10-14 11:02
Thanks for looking further into it, @fipski ! I've also reached the same conclusion. The line you mention adds the chat width on top of `window.innerWidth` that didn't take chat size into consideration in the first place, thus increasing the window size beyond its boundaries. As you've mentioned, the line was placed there for a reason and I'm not too sure of it either but I think @jallamsetty1 did some work there regarding the Large Video Manager. Jaya, do you think you could please take a look? :D

**Comment by pugelarouge** [comment] 2020-10-14 11:56
Yep - working here to - the code seems to presume the widthToUse had persisted since chat was opened so needed to add back - which of course it didn't need to as is calculated within the method...

```
    if (isOpen && !this.resizedForChat) {
        widthToUse -= CHAT_SIZE;
        this.resizedForChat = true;
    } else if (this.resizedForChat) {
        this.resizedForChat = false;
        widthToUse += CHAT_SIZE;
    }
```
could just revert to 
```
    if (isOpen) {
        widthToUse -= CHAT_SIZE;
}
```
right? as custom width height added for iframe is still taken in to account above ... maybe someone using API/IFrame needs to test ??

**Comment by jallamsetty1** [comment] 2020-10-14 13:04
> Yep - working here too - the code seems to presume the widthToUse had persisted since chat was opened so needed to add back - which of course it didn't need to as is calculated within the method...
> 
> ```
>     if (isOpen && !this.resizedForChat) {
>         widthToUse -= CHAT_SIZE;
>         this.resizedForChat = true;
>     } else if (this.resizedForChat) {
>         this.resizedForChat = false;
>         widthToUse += CHAT_SIZE;
>     }
> ```
> 
> could just revert to
> 
> ```
>     if (isOpen) {
>         widthToUse -= CHAT_SIZE;
> }
> ```
> 
> right? as custom width height added for iframe is still taken in to account above ... maybe someone using API/IFrame needs to test ??

Thanks for the explanation, yep looks like we don’t need to add the chat width back. I will open a PR after testing the IFrame case.

**Closed** 2020-10-15 14:00 UTC
Labels: quality, web

**Comment by GLM-NormandNadon** [comment] 2020-10-20 14:36
Hello, I am pretty new to github and the like... I have not even noticed that my issue was answered!
Could someone please tell me if the issue is fixed in Jitsi-Meet-Docker also?
I use Jitsi-Latest for all images... Do I need to do something to pull-up the new version?

Thanks for taking the time :)
