### ISSUE TITLE
Pin Button Videolayout/smallVideo.js

### ISSUE THREAD

**Issue by ketak** [jitsi/jitsi-meet#7441] opened 2020-08-03 09:42 UTC
hi all,
As i am new to this can any 1 help me  
i have copied code from below path in jitsi-meet source code to check the behaviour 
https://github.com/jitsi/jitsi-meet/pull/3649/files
in below path i got error can any one help me plzz
![image](https://user-images.githubusercontent.com/25436037/89169200-8c607400-d59b-11ea-8320-26a9eb3bd287.png)
code error :-
      755 |     * @returns {void}
      756 |    */
    > 757 |     SmallVideo.prototype._onContainerDoubleClick = function(event) {
          |               ^
      758 |     if (this._pinningRequiresDoubleClick() && this._shouldTriggerPin                                                                                                             (event)) {
      759 |         APP.store.dispatch(pinParticipant(this.id));
      760 |     }
 
modules/UI/videolayout/SmallVideo.js

**Comment by Echolon** [comment] 2020-08-03 15:42
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-08-03 15:42 UTC
Labels: packaging, question
