### ISSUE TITLE
How to debug UI changes for iOS and Android? 

### ISSUE THREAD

**Issue by mohdsafadsaal** [jitsi/jitsi-meet#7406] opened 2020-07-26 12:26 UTC
Is there any way to debug UI changes for mobile apps? I can make changes in react native component and then i need build framework and test it in ios and android app. Is there any easier way to make changes and debug?

**Comment by Echolon** [comment] 2020-07-27 17:38
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-07-27 17:38 UTC
Labels: android, ios, mobile, question
