### ISSUE TITLE
brandingDataUrl not working - Url not requested

### ISSUE THREAD

**Issue by spprod35** [jitsi/jitsi-meet#8183] opened 2020-11-29 15:11 UTC
Hello,

I tried to integrate the branding API in my instance.
I tested all possible formats, with " ' " or " " " on values and indexes, nothing works, the url is never requested by the jitsi.
My code : 

BRANDING_DATA_URL=https://run.mocky.io/v3/b3f29922-5314-497f-8da2-xxxxxxxxx

This URL return :

```
{
    backgroundColor: '#FF14F3',
    backgroundImageUrl: 'https://xxxx/test/background.png',
    logoClickUrl: 'https://ifconfig.me',
    logoImageUrl: 'https://xxxx/test/logo.png'
}
```

Thanks for the help

**Comment by spprod35** [comment] 2020-12-03 11:25
do you have a idea or documentation?

**Comment by kachar** [comment] 2020-12-08 09:19
Not working for us either, the endpoint is never requested from what the console is showing.

**Comment by saghul** [comment] 2020-12-08 20:07
Ping @vp8x8

**Comment by vp8x8** [comment] 2020-12-09 07:39
This works only for meetings which have a tenant e.g. https://example.com/**tenant**/MyMeeting.

**Comment by saghul** [comment] 2020-12-09 10:03
Why though? Can't we make it work for all of them?

**Comment by vp8x8** [comment] 2020-12-09 11:07
That was the requirement back then. I'll take a look and make it work as soon as I have some bandwidth.

**Comment by rasos** [comment] 2021-02-01 13:57
Confirmed, `BRANDING_DATA_URL` works in the standard Jitsi setup, but you need to address a room with a tenant like `https://myjistsiserver.net/tenant/roomname`.  Would be nice to use this feature without tenant, for which there is no standard procedure to call from within the Jitsi web interface afaiks, only from another service such as Rocket.Chat, where you can define a URL prefix.

**Comment by spprod35** [comment] 2021-02-01 14:45
> Confirmed, `BRANDING_DATA_URL` works in the standard Jitsi setup, but you need to address a room with a tenant like `https://myjistsiserver.net/tenant/roomname`. Would be nice to use this feature without tenant, for which there is no standard procedure to call from within the Jitsi web interface afaiks, only from another service such as Rocket.Chat, where you can define a URL prefix.

@vp8x8 made the changes in this commit:
https://github.com/jitsi/jitsi-meet/commit/33e4324f6de7b4360182d39669b8095bd0dff43a

This commit is well included in the 5390 release of jitsi meet.
I didn't have time to test it though.

**Comment by rasos** [comment] 2021-02-01 15:26
We are on 5830: no, the branding url seems to have no grip yet in single tenant mode. Only if you use a prefix as tenant it works.

**Comment by ludovicm67** [comment] 2021-02-03 16:31
Commit https://github.com/jitsi/jitsi-meet/commit/33e4324f6de7b4360182d39669b8095bd0dff43a changed the name of the key in the configuration file (`brandingDataUrl` to `dynamicBrandingUrl`).

I created a PR https://github.com/jitsi/docker-jitsi-meet/pull/937 to update the key and update the name of the environment variable (`BRANDING_DATA_URL` will be `DYNAMIC_BRANDING_URL` to be consistent with the configuration file).

**Comment by ludovicm67** [comment] 2021-02-05 15:09
I tested on my Jitsi Meet instance (using `stable-5390-3`) since my PR https://github.com/jitsi/docker-jitsi-meet/pull/937 was merged.
Using `DYNAMIC_BRANDING_URL` pointing to an HTTP endpoint serving valid JSON is now working as expected.

@spprod35 you asked about the format, here is an example of valid JSON which is working:

```json
{
  "backgroundColor": "#fff",
  "backgroundImageUrl": "https://example.com/background-img.png",
  "logoClickUrl": "https://example-company.org",
  "logoImageUrl": "https://example.com/logo-img.png"
}
```

**Closed** 2021-02-05 15:11 UTC
Labels: api

**Comment by prayagsingh** [comment] 2021-06-17 13:27
Hello @ludovicm67
Is it working fine with docker? 
Below is the JSON I'm using. The logo isn't showing on the screen(background image and invite domain are working fine).

set `DYNAMIC_BRANDING_URL: "https://raw.githubusercontent.com/prayagsingh/mockserver/main/bloquelabs/jitsibrand.json"`
```
{
          "inviteDomain":"test.example.com",
          "backgroundColor":"#fff",
          "backgroundImageUrl":"https://i2.wp.com/www.freeconference.com/wp-content/uploads/2017/11/video-template-2635532_640-2.jpg",
          "logoClickUrl":"https://www.bloquelabs.com",
          "logoImageUrl":"https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png"   
}
```

**Comment by ludovicm67** [comment] 2021-06-17 13:41
Hello @prayagsingh!

Yes, it is working fine with Docker.
I just tried following steps just now:
1. clone https://github.com/jitsi/docker-jitsi-meet
2. cp env.example .env
3. ./gen-passwords.sh
4. echo 'DYNAMIC_BRANDING_URL=https://raw.githubusercontent.com/prayagsingh/mockserver/main/bloquelabs/jitsibrand.json' >> .env
5. docker-compose up
6. open https://localhost:8443/test

And I can see the logo in the call. Can you confirm that when you follow those steps you have it working also in your side?

**Comment by prayagsingh** [comment] 2021-06-17 14:43
Thanks @ludovicm67 
After removing previous config from ` ~/.jitsi-meet-cfg/web/` directory it's working now.

**Comment by RyanJit** [comment] 2021-10-13 03:45
@ludovicm67 no, I make mistake put coma here but I no put comma for me json. And I try make with two quote already he no worke. Inside config.js he no put two quote he put one quote like I poste. But I try put two quote too because I see people are do like that and he still no worke. I think two quote are for docker people.

**Comment by remyBerrebi-fi** [comment] 2022-03-09 08:44
Any solution and complete example of how to use it ?
thanks
