### ISSUE TITLE
Coturn fallback to JVB closes the connexion after 30-40 sec and restart

### ISSUE THREAD

**Issue by jlemangarin** [jitsi/jitsi-meet#11888] opened 2022-07-20 09:59 UTC
### Steps to reproduce:

1. Close output 10000 port
2. Fallback to coturn => JVB
3. Wait 40 sec

### Expected behavior:

No interruptions

### Actual behavior:

The connexion between me and JVB using coturn is interrupted after approximately 30-40 sec and restart automatically a few sec later, it seems to be the result of a timeout or something like this.
We are using coturn to fallback to 443 using a nginx reverse proxy and we already tried all the timeout configurations in nginx.

**Browser** : 
![image](https://user-images.githubusercontent.com/22454938/179953534-8a7f8a0f-8d2e-4e08-a8e0-61b53b3b8f56.png)
09:42:52 : Last log of the connexion, all is good after this and we are connected to JVB
09:43:20 : Browser detect it losts connexion to JVB, no video/audio is available anymore. Nothing unusual in server logs, no errir
09:43:22 : Browser initiate restart and we can see it in coturn logs (REFRESH packet sent)

Coturn logs : 
![image](https://user-images.githubusercontent.com/22454938/179954181-e83ddf96-46d4-4645-9b3c-54f60b425a8a.png)
We just see at 11:43:22 the refresh request after the connexion has been lost (2h shift but it's the same request).

Our suspicions is a missing 'heartbeat' to maintain the connexion as described here : https://github.com/coturn/coturn/issues/457 

![image](https://user-images.githubusercontent.com/22454938/179954493-692e2f6a-f1dc-4f73-ab83-3be151ab3e30.png)

So maybe somthing between my computer and coturn closes the connexion but I can't manage to configure something like a heartbeat in coturn or nginx and I'm not sure this is the issue here.

We don't have this issue when 10000/UDP is open.

If you want to try you can use https://gofast-preprod-comm.ceo-vision.com/jitsi-meet

### Server information:

- Jitsi Meet version: 1.0.5913
- Operating System:CentOS

### Client information:

- Browser / app version: Chrome latest
- Operating System: Any

### Additional information:

Thanks for your help !

**Comment by damencho** [comment] 2022-07-20 10:13
Please, when you have questions or problems use the community forum before opening new issues, thank you.

How do you close the 10000 port, with what conditions?
Coturn is also using it.

**Comment by damencho** [comment] 2022-07-20 11:50
Do you have set some large buffer size in your nginx config like 
https://github.com/jitsi/jitsi-meet/blob/ac2af798073f12c35554bb177c467650ec6565b8/doc/debian/jitsi-meet/jitsi-meet.conf#L32

**Comment by jlemangarin** [comment] 2022-07-20 11:58
Yes absolutly
![image](https://user-images.githubusercontent.com/22454938/179976264-5cabf93b-e907-41a1-889c-71d0c29bc054.png)

**Comment by jlemangarin** [comment] 2022-07-26 10:37
Hello @damencho,

Do you have any idea I can try about this issue ? We're kind of feared to do Jitsi videoconferences with partners now..

Thank you !

**Comment by damencho** [comment] 2022-07-26 17:19
Are you using the template config for coturn provided by jitsi-meet packages?

**Comment by damencho** [comment] 2022-07-26 17:20
It is also worth checking whether the coturn machine has these settings https://github.com/jitsi/jitsi-videobridge/blob/master/config/20-jvb-udp-buffers.conf

**Comment by jlemangarin** [comment] 2022-07-28 13:46
@damencho I tried both these modifications without any effect on the result

Here is what our turnserver file looks like compared to yours (yours left) : 

![image](https://user-images.githubusercontent.com/22454938/181520849-6d77b298-97d0-4aa5-bc07-ca7ba5e02310.png)

Also we want to use tcp in the final configuration as this is our point to use coturn but that's another thing as it doesn't seems to change anything

Thank you in advance for your help !

**Comment by damencho** [comment] 2022-08-01 11:24
That uses the internal address to connect to the bridge ... Not sure how will that work with the denied peer. Try disabling the external-ip config and see whether that changes anything.

**Comment by jlemangarin** [comment] 2022-08-01 13:18
@damencho It doesn't works and actually in production we don't have these denied-peer lines :S

**Comment by damencho** [comment] 2022-08-01 13:57
> @damencho It doesn't works and actually in production we don't have these denied-peer lines :S

Those denied peer addresses are there to protect your network from being available to the public by relaying traffic through the cotrun server. 
You say it is not working at all, or you are hitting the same problem with working just for 40 seconds?

**Comment by damencho** [comment] 2022-08-01 17:07
Why you set the udp and tcp port to be the same?

**Comment by damencho** [comment] 2022-08-01 17:08
Have you tried setting it different port and make both accessible from outside?

**Comment by jlemangarin** [comment] 2022-08-02 08:22
Hello @damencho, port 9443 is used internally and is reverse proxified using nginx so the point is to not make this port accessible from outside.

Actually I think if there was a port binding issue the service would just not start and throw an error, not have this 40 sec behavior.

But I can try different configurations and see what it does (change the ports, make them temporarily accessible from outside etc)

**Comment by jlemangarin** [comment] 2022-08-03 10:10
@damencho I tried all the configurations I can think of but nothing changed (except when a configuration I made broke the connexion entierly).

In webrtc-internals we can clearly see the connexion fails after 40 seconds for absolutly no reason and nothing in logs...

![Screenshot_1391](https://user-images.githubusercontent.com/22454938/182583346-8d42700c-2c9c-4aa1-9e50-88b78a93f63e.png)
![Screenshot_1390](https://user-images.githubusercontent.com/22454938/182583361-e0ea69b4-6af4-4acd-b07d-f547efd0d18a.png)

**Comment by damencho** [comment] 2022-08-03 10:50
With the same clients that are failing, if you try it with meet.jit.si it works?

**Comment by jlemangarin** [comment] 2022-08-03 11:05
Yes it doesn't timeout, and it also says it uses turn to communicate with the bridge.

So it should be server-side or we have a different front configuration / different js file between you and us. 

But actually we track all your changes in jitsi front configuration and releases to adapt so I'm not sure. Also it's not related to my computer as we experienced this issue with dozen of external people with port 10000/udp closed

**Comment by damencho** [comment] 2022-08-03 11:14
And during these 40 seconds there is media in both direction between the client and the turnserver?

**Comment by jlemangarin** [comment] 2022-08-03 11:17
If by media you mean video/audio yes absolutely. Client-side all works but after 40 sec we have a brief interruption for 1-2 sec each 40 sec.

Actually we're doing in production a lot of meetings with multiple hundreds of people spitted in multiple jitsi servers, rooms etc and it works pretty well, but when we fallback to 443 using coturn we have this issue.

**Comment by damencho** [comment] 2022-08-03 11:36
I'm out of ideas ... I would try removing nginx from the picture and expose coturn to be directly reached by clients and see whether that changes anything.

**Comment by jlemangarin** [comment] 2022-08-03 11:41
Ok I try and get back to you, thank you for your help anyway

**Comment by jlemangarin** [comment] 2022-08-03 11:48
No it's not nginx.. I'm binding directly to 9443 which is coturn listening port : 

![image](https://user-images.githubusercontent.com/22454938/182600254-654c637b-bc04-44a0-9a9c-d704fc986051.png)

And it fails after exactly 40 sec..

![image](https://user-images.githubusercontent.com/22454938/182600333-dad255cf-ca2a-465c-9e89-9593dbe801d1.png)

I also tried to edit all timers-related configurations in coturn

Do you know if it's the Jitsi js code that change the state of the ICE connexion to disconnected / failed or the browser ? I have to say I don't understand exactly how webrtc works (Is it websockets or something else ?)

**Comment by damencho** [comment] 2022-08-03 11:54
Nope this is inside the browser implementation.

**Comment by damencho** [comment] 2022-08-03 11:56
Is there a reason to add the `fingerprint` option to coturn? This is the only significant difference I see in your config.

**Comment by jlemangarin** [comment] 2022-08-03 12:15
I'm not sure, as far as I remember I didn't initiated the work on this configuration file. Also as you can imagine I just tried but it doesn't change anything

Some member of my team thinks we didn't had this issue in our first implementation in a previous version of jitsi meet but I'm absolutely not sure of this information, maybe I will try with previous versions and see.

**Comment by damencho** [comment] 2022-08-03 12:17
Do you see the same with Firefox and Chrome?

**Comment by jlemangarin** [comment] 2022-08-03 12:43
We may have something, with firefox the connexion fails and nothing happens + no trace in firefox webrtc debug.

I have here a screenshot with : 

- Left screen : Chrome with console
- Middle screen : Firefox with console
- Right screen : Coturn logs of firefox failing

Both console start with the same message to be easy to debug (messages before are pretty the same and the connection seems to fail with traces at my scroll point).

We don't use or recommend to use firefox because of this issue (https://github.com/jitsi/jitsi-meet/issues/2835). Also firefox works with 10000/UDP.

I remember an old chrome issue where we wasn't able to use 443/TCP to fallback (something internal to chrome because this port is usually used for HTTPS) but they fixed it like 2-3 years ago. Also it works on your jitsi so it should be something else.

I really don't understand what happens..

If I remember you are using Debian (or Ubuntu) for your instances so I'm starting to wonder if there is a coturn issue in CentOS not happening in other distributions

**Comment by damencho** [comment] 2022-08-03 13:04
Another thing you can play with is chrome://net-internals/ maybe there is something when the socket is closed that can give you a clue ...

**Comment by jlemangarin** [comment] 2022-08-03 13:29
I exported a file and tried to open it in a viewer (https://netlog-viewer.appspot.com/) but not knowing exactly for what I'm looking for I didn't find anything suspicious.

Do you want me to send this file ? If you have an email address or sth

**Comment by jlemangarin** [comment] 2022-08-10 09:57
Hi @damencho,

We analyzed, TCP dumped, debugged all we can think of and there is where we are now : 

- Changing turn server version or provider doesn't change anything
- Using or not using JVB websocket doesn't change anything
- Using your live (meet.jit.si) built library and the latest version doesn't change anything
- Debugging your code makes clear that the connection is interrupted by the browser itself and not by your code (The stack trace only shows the oniceconnectionstatechange event and I assume this is sent by the browser)
- Preventing Jitsi from doing anything when the connection cuts, the browser seems to re establish the connection itselfs

![Screenshot_1447](https://user-images.githubusercontent.com/22454938/183872277-daf69d13-5c31-432c-ba01-77a70d4357d5.png)
![Screenshot_1448](https://user-images.githubusercontent.com/22454938/183872293-6ce62073-338b-4aaf-83e2-e896408702e5.png)

- It takes 3 seconds before the browser establish the connection again (And I wonder the connection isn't re established by jitsi but by the browser, am I right ?)

![Screenshot_1449](https://user-images.githubusercontent.com/22454938/183873074-b9e9d7a5-5445-4fb7-9eec-c36e238d5e47.png)

Well it's clear that jitsi isn't involved in this issue and my last thought is that the OS could be involved and cut the connection (we already removed nginx from the equation using direct connection from coturn and already try to change coturn and jitsi versions).

If you have no idea I will try to request help on CentOS forums I guess

**Comment by damencho** [comment] 2022-08-10 11:20
No idea sorry. The net internals may give some clue, but it is very hard to locate the correct socket there in timely manner.
For example that helped me long time ago to find that the certificate on the coturn side was missing the full chain of certs.

**Comment by jbg** [comment] 2023-01-06 00:52
Wouldn't this be because `enableIceRestart` is disabled by default (due to the TCC sequence bug)? So Jitsi is unable to do an ICE restart when the connection to JVB fails.

**Comment by jlemangarin** [comment] 2023-01-06 14:02
Hello @jbg 

No I already tried, when I force enableIceRestart to true it just throw an error saying the connexion is closed and does nothing

**Comment by katequynh** [comment] 2023-03-05 19:25
> Hello @jbg
> 
> No I already tried, when I force enableIceRestart to true it just throw an error saying the connexion is closed and does nothing

I am in this case, have you overcome it?

**Comment by jlemangarin** [comment] 2023-03-07 07:46
> > No this issue is still blocking us, it seems to be related to RHEL environnements, are you in this situation @katequynh ?
> 
> I still haven't found a solution, exactly 42 seconds will be frozen for about 2 seconds, I think there is some configuration.

What is your OS environment ?

**Comment by katequynh** [comment] 2023-03-07 13:17
> What is your OS environment ?
I installed coturn on ubuntu, I am looking for an alternative solution.

**Comment by katequynh** [comment] 2023-06-16 09:11
> Hey @katequynh, by chance do you have find any solution ? :S

I used pion turn on ubuntu and it worked fine for me, you can try it:

1: Create a new directory (optional):

mkdir pions
cd pions

2: Download the TURN server's source: wget -q https://github.com/pions/turn/releases/download/1.0.3/simple-turn-linux-amd64

3: Give read-write permissions to the DIR:
chmod +x simple-turn-linux-amd64

4: Set username, password and port: (using EXPORT commands)
export USERS='username=password'
export REALM=turn.domain.com
export UDP_PORT=3478

5: Now run the pions turn server:
./simple-turn-linux-amd64

# or use nohup
nohup ./simple-turn-linux-amd64 &

**Comment by jlemangarin** [comment] 2023-06-16 09:33
Thanks a lot for your answer @katequynh, we'll look at this project and see if it works for us !

**Comment by saghul** [comment] 2023-07-07 09:56
Closing since it doesn't seem to be related to a bug in the software but a deployment specific issue.

**Closed by saghul** 2023-07-07 09:56 UTC

**Comment by jlemangarin** [comment] 2023-08-11 08:40
@katequynh I confirmed changing the TURN server resolves the issue, thanks a lot for your help

@saghul The best I can do is to encourage you to not bury this issue which is now confirmed for multiple users (cf. https://community.jitsi.org/t/paid-support-fix-issue-11888-connection-close-after-40-seconds/120171/5).

The "deployment specific issue" is concerning the default TURN server with the default configuration provided in Jitsi packages

**Comment by saghul** [comment] 2023-08-11 10:26
What would you expect us to do here?

**Comment by jlemangarin** [comment] 2023-08-16 09:47
@saghul I tried to find a solution for a long time but I wasn't able to, so I can't tell you for now.. 

But my point is that the issue exists and is a problem for some users, so even if we can't resolve it for now it shouldn't be abandonned (even for tracking purpose)

**Comment by saghul** [comment] 2023-08-16 13:35
Unless there is an avenue for reproducing it, we don't know it's an issue with our software of coturn or the specific deployment.

The issue is closed, not deleted, so people can still find it and it can be reopened if new evidence arises.

**Comment by ishjayursaleo** [comment] 2024-06-20 05:42
We are facing this right now. Any updated solution? @jlemangarin  :(

**Comment by jlemangarin** [comment] 2024-06-20 07:56
@ishjayursaleo Yes, use pion-turn instead of coturn.

You can also read https://community.jitsi.org/t/paid-support-fix-issue-11888-connection-close-after-40-seconds/120171/13

**Comment by ishjayursaleo** [comment] 2024-07-01 08:30
@jlemangarin did you try adding the below 2 parameters in coturn conf?

user=<username>:<pwd>
lt-cred-mech

This did the trick for us.

**Comment by jlemangarin** [comment] 2024-07-19 17:40
@ishjayursaleo 

We don't use coturn anymore so I won't be able to tell you ;)

But yes I remember those parameters, it was properly configured

**Comment by pumelotea** [comment] 2025-01-16 08:59
> 您是否尝试在 Coturn conf 中添加以下 2 个参数？
> 
> 用户=用户名：pwd lt-cred-mech
> 
> 这对我们来说起到了作用。

i try it ,  work well!!!
