### ISSUE TITLE
tile view witout selfie

### ISSUE THREAD

**Issue by mcantsin** [jitsi/jitsi-meet#9517] opened 2021-07-07 23:23 UTC
**Is your feature request related to a problem you are facing?**
There is no *problem*. My *feature request* concerns a *nice to have*.

**Describe the solution you'd like**
In the "tile view" seeing others without one-self would be an enhancement to the "tile view".

**Describe alternatives you've considered**
as I said, it's just a "nice to have", I don't have an alternative at hand.

P.S. thanks for your awesome software!

**Comment by jbg** [comment] 2021-12-01 07:04
Duplicate of #8477

**Closed** 2021-12-02 12:40 UTC
Labels: feature-request
