### ISSUE TITLE
Authenticated Moderator [secured domain] re-joining a meeting creates a 2nd, separate instance of profile with trimmed down moderator rights

### ISSUE THREAD

**Issue by fremzy** [jitsi/jitsi-meet#7588] opened 2020-08-27 04:25 UTC
### Description:

1. If an authenticated Moderator enables the lobby room feature after creating a meeting but gets disconnected for ANY reason (internet interruption, need to correct unrelated audio problems, camera malfunction e.t.c..), that same Moderator cannot get back into the room. So they are 'permanently' locked out - at least, until everyone else leaves the room and the room name becomes available again. **This has already been reported.**

2. If in trying to remedy issue above, the Moderator sets a password upon creating the room in addition to enabling the lobby feature, they are indeed able to get back into the room if they're disconnected or step out for any reason. HOWEVER, what the system appears to do is create a NEW instance of the same Moderator in that same room. The new [instance of the] Moderator can go in and remove the password they initially set (which would show up as "password set by another user"), but they do not regain moderator rights over the lobby feature. So, in essence, if someone else tries to get in after the Moderator successfully re-enters the room, the Moderator doesn't get the join-request notification. They are able to turn off the lobby feature entirely, but they do not receive requests to join the room if the lobby feature remains turned on (even if they turn it off and turn it back on). 

### Steps to reproduce:

1. Create a new meeting
2. Turn on Lobby feature
3. Add a password as a fallback
4. Disconnect from meeting
5. Try to get back into meeting
6. Request to join
7. Use password to get back in
8. New user requests to join meeting

### Expected behavior:

An authenticated moderator should never be locked out of a meeting they created. Even if they get disconnected for any reason, they should be able to get back in (without needing to fallback to a password) and when they get back in, should immediately have all room administrative rights without being set as a second instance. Moderator should be able to approve join requests after rejoining the meeting.

### Actual behavior:

Moderator cannot join a meeting they created with no one else in the meeting having moderator status. If Moderator uses fallback password, they still cannot approve new join requests. 

### Server information:

- Jitsi Meet version: 2.3.1
- Operating System: Ubuntu Server 20.04 LTS

### Client information:

- Browser / app version: Version 78.0.3904.108 (Official Build) (64-bit), Firefox 79.0 (64 bit), Brave (1.11.104),
 Safari (13.1.2) 
- Operating System: Mac OSX 10.13.6, Windows 10

**Comment by damencho** [comment] 2020-08-27 13:26
Duplicate of https://github.com/jitsi/jitsi-meet/issues/7561

**Closed by damencho** 2020-08-27 13:26 UTC
