### ISSUE TITLE
On calling JitsiMeetActivity second time starts pip mode Android

### ISSUE THREAD

**Issue by maheshgelani** [jitsi/jitsi-meet#4718] opened 2019-10-07 09:15 UTC
Hi, i am implementing jitsi for our health care app , when i start activity for first time it opens properly and on second call it automatically minimize to PIP mode and then close popup , "placing this call will end your ... call.

If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.

**Comment by saghul** [comment] 2019-10-08 09:13
How are you terminating the first call? Programatically or by pressing the hangup button? Please share the adb logcat output when you make the test.

**Comment by maheshgelani** [comment] 2019-10-10 08:30
by pressing the hangup button. 

now i started getting crash the below is the log .

org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView (JitsiMeetActivity.java:106)
org.jitsi.meet.sdk.JitsiMeetActivity.leave (JitsiMeetActivity.java:122)
org.jitsi.meet.sdk.JitsiMeetActivity.finish (JitsiMeetActivity.java:95)
org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated (JitsiMeetActivity.java:220)
java.lang.reflect.Method.invoke (Method.java)
org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread (ListenerUtils.java:135)
org.jitsi.meet.sdk.ListenerUtils.access$000 (ListenerUtils.java:35)
org.jitsi.meet.sdk.ListenerUtils$1.run (ListenerUtils.java:114)

**Comment by saghul** [comment] 2019-10-10 08:33
Can yopu please share how you are integrating the activity? It's very hard to tell what can be going wrrong from just a partial backtrace.

**Comment by maheshgelani** [comment] 2019-10-10 09:13
i am extending JitsiMeetActivity as below 

class CallActivity() : JitsiMeetActivity() {

    var roomId = ""
    var avtar = ""
    var fullname = ""
    var counter = 1

    override fun initialize() {

        val bundle = this.intent.extras
        if (bundle != null) {
            if (bundle.containsKey("roomId")) {
                roomId = bundle.getString("roomId")
            } else return
        } else {
            finish()
        }

        val defaultOptions = JitsiMeetConferenceOptions.Builder()
            .setWelcomePageEnabled(true)
            .setServerURL(buildURL("https://meet.jit.si"))
            .setRoom(roomId)
            .setSubject("kanon")
            .setAudioMuted(false)
            .setVideoMuted(false)
            .setAudioOnly(false)
            .setWelcomePageEnabled(false)
//            .setFeatureFlag("pip.enabled", false)
//            .setFeatureFlag("chat.enabled", false)
            .build()
        // Set default options

        JitsiMeet.setDefaultConferenceOptions(defaultOptions)

        super.initialize()
    }


    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        if (requestCode == OVERLAY_PERMISSION_REQUEST_CODE) {

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {

                if (Settings.canDrawOverlays(applicationContext)) {
                    initialize()
                } else {
                    throw RuntimeException("Overlay permission is required when running in Debug mode.")
                }

            } else {
                initialize()
            }

        }

        super.onActivityResult(requestCode, resultCode, data)
    }


    override fun onKeyUp(keyCode: Int, event: KeyEvent): Boolean {
        if (BuildConfig.DEBUG && keyCode == KeyEvent.KEYCODE_MENU) {
            JitsiMeet.showDevOptions()
            return true
        }

        return super.onKeyUp(keyCode, event)
    }

    // Helper methods
    //

    private fun buildURL(urlStr: String): URL? {
        try {
            return URL(urlStr)
        } catch (e: MalformedURLException) {
            return null
        }

    }

    override fun onConferenceTerminated(data: MutableMap<String, Any>?) {
        super.onConferenceTerminated(data)
        finish()
    }

    override fun onDestroy() {
        super.onDestroy()

    }

    companion object {

        private val OVERLAY_PERMISSION_REQUEST_CODE =
            (Math.random() * java.lang.Short.MAX_VALUE).toInt()
    }
}


// calling start activity from activity
 val intent = Intent(this@ActivityNewPrivateChat, CallActivity::class.java)
            intent.putExtra("roomId", roomID)
            intent.putExtra("avtar", currentUser?.userProfile?.avatar)
            intent.putExtra("fullname", currentUser?.userProfile?.fullName)
            startActivityForResult(intent, 3000)

**Comment by maheshgelani** [comment] 2019-10-10 09:16
on call in some device i am getting crash and below is the log 

Fatal Exception: java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.kanonhealth-w7Tx1LOSfgdv_18ANNogkw==/base.apk!classes5.dex)
       at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
       at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
       at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java:89)
       at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:165)
       at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$2$WebRTCModule(WebRTCModule.java:485)
       at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$C_Gitx4KOYySlWXaI1K4M1yoJoA.run(:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**Comment by saghul** [comment] 2019-10-10 09:19
> on call in some device i am getting crash and below is the log
> 
> Fatal Exception: java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.kanonhealth-w7Tx1LOSfgdv_18ANNogkw==/base.apk!classes5.dex)
> at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
> at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
> at com.oney.WebRTCModule.GetUserMediaImpl.createVideoTrack(GetUserMediaImpl.java:89)
> at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:165)
> at com.oney.WebRTCModule.WebRTCModule.lambda$getUserMedia$2$WebRTCModule(WebRTCModule.java:485)
> at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$C_Gitx4KOYySlWXaI1K4M1yoJoA.run(:8)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:764)

What gradle plugin version are you using?

**Comment by maheshgelani** [comment] 2019-10-10 10:35
classpath 'com.android.tools.build:gradle:3.5.1'

**Comment by saghul** [comment] 2019-10-10 10:36
Can you lower it to 3.4 or 3.3? I've seen this problem with 3.5 only, and I think it's a bug in the plugin itself, since those classes are there.

**Comment by maheshgelani** [comment] 2019-10-10 10:36
ok let us try

**Comment by maheshgelani** [comment] 2019-10-11 03:06
lowering the gradle to  classpath 'com.android.tools.build:gradle:3.4.1' did worked. but it crashes on hangup the call in jitsimeet activity. I have override the method to finish the activity after hangup.

 override fun onConferenceTerminated(data: MutableMap<String, Any>?) {
        super.onConferenceTerminated(data)
        finish()
    }

below is the error log 

Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:139)
       at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35)
       at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
       at org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView(JitsiMeetActivity.java:106)
       at org.jitsi.meet.sdk.JitsiMeetActivity.leave(JitsiMeetActivity.java:122)
       at org.jitsi.meet.sdk.JitsiMeetActivity.finish(JitsiMeetActivity.java:95)
       at org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated(JitsiMeetActivity.java:220)
       at 

com.Kanon.Kanonhealth.callSettings.CallActivity.onConferenceTerminated(CallActivity.kt:109)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135)
       at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35)
       at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by maheshgelani** [comment] 2019-10-11 06:10
also after hangup, I am not ablet play music in other apps

W/MediaPlayer-JNI: MediaPlayer finalized without being released,

**Comment by saghul** [comment] 2019-10-11 06:24
> I have override the method to finish the activity after hangup.

That is already done by JitsiMeetActivity: https://github.com/jitsi/jitsi-meet/blob/98698ba89accac8fa707095cbc5020199012686c/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetActivity.java#L220

What SDK version are you using? Did you fix the `defaultConferenceOptions` problem I mentioned earlier? Please paste your entire JitsiMeetActivity subclass.

> also after hangup, I am not ablet play music in other apps
> 
> W/MediaPlayer-JNI: MediaPlayer finalized without being released,

This is likely due to the error, because no proper cleanup was performed.

**Comment by maheshgelani** [comment] 2019-10-11 08:52
class CallActivity() : JitsiMeetActivity() {

    var avtar = ""
    var fullname = ""
    var counter = 1
    var callInfo: CallInfo? = null

    override fun initialize() {

        val policy = StrictMode.ThreadPolicy.Builder().permitAll().build()
        StrictMode.setThreadPolicy(policy)

        val bundle = this.intent.extras
        if (bundle != null) {
            if (bundle.containsKey("callInfo")) {
                callInfo = bundle.getSerializable("callInfo") as CallInfo
            } else return
        } else {
            finish()
        }

        val defaultOptions = JitsiMeetConferenceOptions.Builder()
            .setWelcomePageEnabled(true)
            .setServerURL(buildURL("https://meet.jit.si"))
            .setRoom(callInfo?.roomID)
            .setSubject("kanon")
            .setAudioMuted(false)
            .setVideoMuted(false)
            .setAudioOnly(false)
            .setWelcomePageEnabled(false)
            .setFeatureFlag("pip.enabled", true)
            .setFeatureFlag("chat.enabled", false)
            .build()
        // Set default options

        JitsiMeet.setDefaultConferenceOptions(defaultOptions)

        super.initialize()
    }


    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        if (requestCode == OVERLAY_PERMISSION_REQUEST_CODE) {

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {

                if (Settings.canDrawOverlays(applicationContext)) {
                    initialize()
                } else {
                    throw RuntimeException("Overlay permission is required when running in Debug mode.")
                }

            } else {
                initialize()
            }

        }

        super.onActivityResult(requestCode, resultCode, data)
    }


    override fun onKeyUp(keyCode: Int, event: KeyEvent): Boolean {
        if (BuildConfig.DEBUG && keyCode == KeyEvent.KEYCODE_MENU) {
            JitsiMeet.showDevOptions()
            return true
        }

        return super.onKeyUp(keyCode, event)
    }

    // Helper methods
    //

    private fun buildURL(urlStr: String): URL? {
        try {
            return URL(urlStr)
        } catch (e: MalformedURLException) {
            return null
        }

    }

//    override fun onConferenceTerminated(data: MutableMap<String, Any>?) {
//        super.onConferenceTerminated(data)
//        finish()
//    }

    override fun onDestroy() {
        super.onDestroy()

    }

    companion object {

        private val OVERLAY_PERMISSION_REQUEST_CODE =
            (Math.random() * java.lang.Short.MAX_VALUE).toInt()
    }
}

**Comment by saghul** [comment] 2019-10-11 09:01
You are setting the room on the default options, which is not going to work. In fact, you don't even need to subclass JitsiMeetActivity.

See this example: https://github.com/jitsi/jitsi-meet-sdk-samples/blob/master/android/java/JitsiSDKTest/app/src/main/java/net/jitsi/sdktest/MainActivity.java

The default options (server URL and flags for example, in your case) can be set early on application startup, and conference specific data (the room) is set when launch is called. The SDK will merge both options internally.

**Comment by maheshgelani** [comment] 2019-10-11 09:28
I am creating pending intent on the notification received from the server , on click of notification I want to take user to jitsi call again.  

that's the main reason I created subclass JitsiMeetActivity.

**Comment by saghul** [comment] 2019-10-11 09:39
That's ok, but you don't need to override even half of what you are overriding.

**Comment by maheshgelani** [comment] 2019-10-11 09:44
ok will remove not required overriden methods, is there any option to play sound or ringing ton till call gets connected to another party, I am using it for one to one call

**Comment by saghul** [comment] 2019-10-11 10:01
No, there is no such option.

**Comment by maheshgelani** [comment] 2019-10-11 13:09
thank you for the support

**Comment by saghul** [comment] 2019-10-11 13:12
@maheshgelani So, did it work ok after moving the setRoom then?

**Comment by maheshgelani** [comment] 2019-10-12 05:01
@saghul I used the following code 

var options = JitsiMeetConferenceOptions.Builder()
            .setRoom(callInfo?.roomID!!)
            .build();

        JitsiMeetActivity.launch(this, options);

and removed the subclass of CallActivity it works.

but Another issue I am facing is to terminate ongoing calls when the other party declines. I receive notification from our backend and i should terminate ongoing call.

1) Is there a way to manually terminate call instead of hangup button click?
2) How to get reference to going call activity in another activity or service?

**Comment by saghul** [comment] 2019-10-14 06:53
> and removed the subclass of CallActivity it works.

Great to hear! I'm going to close this since the next 2 question (which I'll briefly answer) are not part of this issue. Also, since these are not bugs in Jitsi, please join our community for asking questions: https://community.jitsi.org

>     1. Is there a way to manually terminate call instead of hangup button click?

Yes, call `activity.leave()`

>     2\. How to get reference to going call activity in another activity or service?

This you are going to need to do yourself. You can have a singleton object which holds a reference to the current conference, for example.

**Closed by saghul** 2019-10-14 06:53 UTC

**Comment by maheshgelani** [comment] 2019-10-14 07:56
thanks

**Comment by aninditasadhukhan** [comment] 2021-03-17 07:33
Hi @saghul  I am not sure whether this is the right thread to discuss this issue I am facing. The issue is I want to terminate the participant when moderator left the call. It is working perfectly when both moderator and participant log in from two browsers.

But it is not working if participant login from android app and moderator log in from browser, our gradle version is 4.1 . Could you please give some light on this. I have tried in many different but unable to terminate participant log in from app. Is there some code modifications required for this in android app side?
