### ISSUE TITLE
Live Stream to YouTube is not working

### ISSUE THREAD

**Issue by netstairs** [jitsi/jitsi-meet#6734] opened 2020-05-16 16:28 UTC
When a screen is popped up and asks for streaming using YouTube Stream Key, it displays error and redirects to GitHub for this text email request for support.

**Comment by l3d00m** [comment] 2020-05-16 17:46
Could you provide more details? What did the error say? Were you using meet.jit.si or your own deployment? What browser and OS are you using?

**Comment by netstairs** [comment] 2020-05-16 17:53
WIN 10 Professional
Chrome 81 Latest
We installed the GitHub code AS IS
We invoked the utility in a room session

[cid:image001.png@01D62B89.39113030]

Asked for stream key.
And after entry, gave an orange display and then proceeded to contact support page

**Comment by l3d00m** [comment] 2020-06-17 19:38
I assume this to be a duplicate of #6714 then.

**Closed by l3d00m** 2020-06-17 19:38 UTC
Labels: info:feedback-needed

**Comment by netstairs** [comment] 2020-06-17 19:46
Did it get resolved?

**Comment by l3d00m** [comment] 2020-06-17 19:47
I'm not a Jitsi dev, just helping out with issue management (and this was a duplicate). Feel free to try it out, this is a rarely reported issue so I assume this is resolved.
