### ISSUE TITLE
Numbers in the room name add too many spaces to the Tab Title

### ISSUE THREAD

**Issue by ineiti** [jitsi/jitsi-meet#6468] opened 2020-04-29 15:21 UTC
**Is your feature request related to a problem you are facing?**

We're working at a place called `C4DT`, and as such we sometimes want to make rooms that include our name, like `PartnerC4DT`. Unfortunately, this renders to `Partner  C  4  DT`, which is quite ugly with the space in between the C, the 4, and the T.

**Describe the solution you'd like**
I would like no spaces around numbers.

**Describe alternatives you've considered**
Using `Partner_C_4_D_T`, but that's also ugly...

**Comment by l3d00m** [comment] 2020-05-16 14:31
Confirmed: Numbers in the room name lead to the **tab title** containing spaces in front and after those numbers. Not sure if this is intentional, but I couldn't guess why.

**Comment by bmorg** [comment] 2021-01-13 13:17
We are facing similar problems with random room ids. E.g. a room id of `UuFZXAoPp` leads to `Uu FZX Ao Pp` in the title.

According to [this comment](https://github.com/jitsi/jitsi-meet/issues/4050#issuecomment-478675386) the room id is beautified before being set as the title (I'm guessing [here](https://github.com/jitsi/jitsi-meet/blob/stable/jitsi-meet_5390/react/features/conference/components/web/Conference.js#L132)), but I couldn't find out where the beautifying is happening. Any pointers?

The feature makes sense when the room ids are a combination of words. Less so when the ids are random.

An option to disable this would be great.

**Comment by saghul** [comment] 2021-01-13 13:26
Here is where that takes place: https://github.com/jitsi/jitsi-meet/blob/1196ede961c17c85c4839194054588b1b2c2be05/react/features/base/conference/functions.js#L166

The function that does the actual "beautifying" is in that same file. Having a config option to disable the beautifying would be acceptable as a PR.

**Comment by ineiti** [comment] 2021-01-13 15:13
Or what about every room that starts with an underscore is only beautified by removing the first underscore?

**Comment by ineiti** [comment] 2021-01-13 15:19
Something like #8407?

**Comment by damencho** [comment] 2021-01-13 15:30
I left a comment in the PR

**Comment by damencho** [comment] 2021-01-13 15:31
I'll move it here

**Comment by damencho** [comment] 2021-01-13 15:31
Can we do some other logic here? @saghul I remember we were discussing this with you at some point.
We have the case of meetings like https://meet.jit.si/sometenant/47a67ee47350faa2802a0a2c2f1c55b6b11c357312a0f1127be93474b5c296c8
And using _ will not catch this.
We know that the room generator uses four words from the dictionary this means 3 spaces. Maybe we can add a logic where if the resulting prettified string contains more than 4 spaces we do not pritify it (give room for one more word to be added to generator) ...
WDYT @saghul @ineiti?

**Comment by bmorg** [comment] 2021-01-13 16:25
> Maybe we can add a logic where if the resulting prettified string contains more than 4 spaces we do not pritify it (give room for one more word to be added to generator) ...

I feel like in the case of relatively short random IDs this will result in somewhat chaotic behaviour:

 * `UuFfZxAoPpF` -> `Uu Ff Zx Ao Pp F` -> 5 spaces -> discard
 * `UufFZXAoPpf` -> `Uuf FZX Ao Ppf` -> 3 spaces -> keep

**Comment by damencho** [comment] 2021-01-13 16:31
I see your point ... but the `_` is very deployment-specific, you see, I came up with another case for the same problem. We need to come up with some generic solution ... 
Or just hide the subject UI component using URL params ... or as @saghul suggested just add a config for disabling the function and use that in the parameters passed.

**Comment by ineiti** [comment] 2021-01-13 17:08
Yes, the '_' suggestion was kind of a hack on top of a hack ;) Configuration parameters are nice, but if I want to use jitsi on the default deployment, I cannot change the configuration.

More possible hacks:
- if more than 3 spaces, skip (already proposed)
- only add spaces in place of underscores
- add a checkbox that is chosen by default `Niceify Room Name`
- add a description for the room that is shown if set
- allow spaces in the room name

**Comment by ineiti** [comment] 2021-01-13 17:09
> I left a comment in the PR

Signed the CLA - just in case you want to go down the easiest path...

**Comment by damencho** [comment] 2021-01-13 17:10
You can change it by passing url params or params to iframe API

**Comment by ineiti** [comment] 2021-01-13 17:13
> You can change it by passing url params or params to iframe API

That's not very user-friendly, is it?

**Comment by damencho** [comment] 2021-01-13 17:19
Are you using iframeAPI? This is one of the main functionalities there.

**Comment by ineiti** [comment] 2021-01-14 07:39
> Are you using iframeAPI? This is one of the main functionalities there.

I'm just a simple user of the tool - all I did was install it on our server in a subdomain. From time to time I point people to https://meet.jit.si, but nothing more.

**Comment by saghul** [comment] 2021-01-14 09:08
> all I did was install it on our server in a subdomain.

Then you could easily change the option in config.js, right?

**Comment by saghul** [comment] 2021-01-14 09:10
> We know that the room generator uses four words from the dictionary this means 3 spaces. Maybe we can add a logic where if the resulting prettified string contains more than 4 spaces we do not pritify it (give room for one more word to be added to generator) ...

-1. Making assumptions always yields bad edge cases. It's easier to reason about consistent behavior. There is a notable exception which would be easy to handle: UUIDs. If the room name is a UUID we could skip beautifying. Since UUIDs have a specific format we could parse and check it.

**Comment by bmorg** [comment] 2021-01-21 11:44
> We know that the room generator uses four words from the dictionary this means 3 spaces. Maybe we can add a logic where if the resulting prettified string contains more than 4 spaces we do not pritify it (give room for one more word to be added to generator) ...

I'm guessing the clean solution here would be to only beautify the title when a room id was actually created by the room name generator. Is it possible to attach the meta information "was created by the room name generator" to the room id? Or store it elsewhere?

**Comment by saibotma** [comment] 2021-11-30 07:51
There is a solution to this problem, I believe. You can just add `config.subject="N4m3WithNumb3ers"`.
However, unfortunately, the title tag of the Jitsi window still displays the “ugly” beautified name. Is there a way to also set the title tag?

**Comment by saghul** [comment] 2021-11-30 08:30
As I mentioned here: https://github.com/jitsi/jitsi-meet/issues/6468#issuecomment-759446916 a setting to disable all beautification would be acceptable. PRs are welcome but it's unlikely we'll work on this ourselves.

That said, and given there has been no actual movement here for well over a year I'm going to close this. If anyone is inclined to work on it please feel free to leave a comment and / or open a PR.

**Closed by saghul** 2021-11-30 08:30 UTC
Labels: confirmed, ui/ux

**Comment by WilliamDEdwards** [comment] 2024-04-16 16:31
Running into this. The UUID `699cbb1e-1ece-4ee1-8df3-da43893a087a` causes the room name `699 Cbb 1 E 1 Ece 4 Ee 1 8 Df 3 Da 43893 A 087 A`. The proposed solution of not beautifying UUIDs would be good.
