### ISSUE TITLE
Jitsi-meet SDK version 9.0.0 giving error related to GiphyUISDK

### ISSUE THREAD

**Issue by Vikrant2411** [jitsi/jitsi-meet#14442] opened 2024-03-07 05:30 UTC
### Description:

Updated Jsitsi-meet sdk to version 9.0.0, Giphy sdk is linked to Jitsi and got installed. Now when I am running the app I am getting error in the app.

dyld[670]: Symbol not found: (_$s10GiphyUISDK0A14ViewControllerC19selectedContentTypeAA010GPHContentG0OvsTj)
  Referenced from: '/private/var/containers/Bundle/Application/CC7664FF-7F3E-497B-8B19-6A68D63F6BA4/CellularBackupContacts.app/Frameworks/JitsiMeetSDK.framework/JitsiMeetSDK'
  Expected in: '/private/var/containers/Bundle/Application/CC7664FF-7F3E-497B-8B19-6A68D63F6BA4/CellularBackupContacts.app/Frameworks/GiphyUISDK.framework/GiphyUISDK'

### Server information:

- Jitsi Meet version: 9.0.0
- Operating System: iOS

**Comment by saghul** [comment] 2024-03-07 06:19
Are you using CocoaPods? If not, are you also including the giphy SDK on your app?

**Comment by Vikrant2411** [comment] 2024-03-07 06:46
Yes I am using cocoa pods.

Issue is when I am running the app on Real device, on simulator it is working fine.

**Comment by saghul** [comment] 2024-03-07 06:53
That's odd! @Calinteodor can you pl update the sample apps and try to repro?

**Comment by Vikrant2411** [comment] 2024-03-07 07:36
In JitsiSDKTest sample app getting the same issue
![Screenshot 2024-03-07 at 13 05 56](https://github.com/jitsi/jitsi-meet/assets/88380070/7f691950-f8f6-4064-8b48-15a20760f39c)

**Comment by saghul** [comment] 2024-03-07 07:51
Thanks for helping investigate! What iOS version are you running?

**Comment by Vikrant2411** [comment] 2024-03-08 04:25
I have tested this on iOS version 17.3.1 & 15.7.6.

**Comment by Zroyal** [comment] 2024-03-08 09:49
I have the same issue on real device.

**Comment by saghul** [comment] 2024-03-08 10:01
We have been able to reproduce it and are working on a fix.

**Comment by Vikrant2411** [comment] 2024-03-08 13:23
Okay,
Thank you, please notify me once it will be fixed.

**Comment by saghul** [comment] 2024-03-08 14:38
I spotted a couple of important problems during the 9.0.0 release. Can you please update to 9.0.1 and try again?

**Comment by Zroyal** [comment] 2024-03-09 18:54
Are you certain that you've published the new version? I'm encountering the following error: 
CocoaPods could not find compatible versions for the 'JitsiMeetSDK' pod:
  In your Podfile:
    JitsiMeetSDK (~> 9.0.1)

**Comment by saghul** [comment] 2024-03-09 19:08
Yes. https://github.com/CocoaPods/Specs/blob/master/Specs/c/0/0/JitsiMeetSDK/9.0.1/JitsiMeetSDK.podspec.json

You may want to try `pod install --repo-update`

**Comment by Zroyal** [comment] 2024-03-10 13:21
I've tested the latest version (9.0.1), and it appears that you've raised the minimum version support to 13.4. The crash has been resolved. Thanks!

**Comment by saghul** [comment] 2024-03-10 14:39
Thanks for confirming!

Yes we've had to because RN has raised it.

The Podfile template was wrong, but it's fixed in 9.0.1

**Comment by Vikrant2411** [comment] 2024-03-11 05:46
Yes 9.0.1 is working fine for me too.
Thanks

**Comment by saghul** [comment] 2024-03-11 06:07
Great to hear!

**Closed by saghul** 2024-03-11 06:07 UTC
