### ISSUE TITLE
Media doesn't work from Russia

### ISSUE THREAD

**Issue by Owirtifo** [jitsi/jitsi-meet#11045] opened 2022-02-28 20:07 UTC
Hello! sound and video via google chrome 98.0.4758.102 and Edge 98.0.1108.62 does not work. It works via Firefox.
I am using Jitsi-Meet on a Debian-based GNU/Linux system version 2.0.6865-2. 3 days ago it worked.
If I use https://meet.jit.si / then there is sound and video, but every 10 seconds the page is reloaded.

**Comment by Owirtifo** [comment] 2022-02-28 20:10
In browser
2022-02-28T20:09:19.383Z [modules/xmpp/JingleSessionPC.js] <Cr.sendIceCandidates>:  JingleSessionPC[session=JVB,initiator=false,sid=fsgk8g9mhcjp8] sendIceCandidates [{"candidate":"candidate:3091507729 1 udp 2122260223 10.254.1.3 54325 typ host generation 0 ufrag hZwT network-id 1","sdpMid":"0","sdpMLineIndex":0},{"candidate":"candidate:1193052247 1 udp 2122194687 192.168.2.65 54326 typ host generation 0 ufrag hZwT network-id 2 network-cost 10","sdpMid":"0","sdpMLineIndex":0}]
In jvb.log:
JVB 2022-02-28 23:09:01.930 INFO: [80] [confId=de3d790bc9702958 gid=7070 stats_id=Noemi-RLa componentId=1 conf_name=12345@conference.conf.infowatch.com ufrag=2rtve1ft0v6m8l name=stream-e380b4bc epId=e380b4bc local_ufrag=2rtve1ft0v6m8l] Component.addUpdateRemoteCandidates#347: Update remote candidate for stream-e380b4bc.RTP: 10.254.1.3:55952/udp
JVB 2022-02-28 23:09:01.930 INFO: [80] [confId=de3d790bc9702958 gid=7070 stats_id=Noemi-RLa componentId=1 conf_name=12345@conference.conf.infowatch.com ufrag=2rtve1ft0v6m8l name=stream-e380b4bc epId=e380b4bc local_ufrag=2rtve1ft0v6m8l] Component.addUpdateRemoteCandidates#347: Update remote candidate for stream-e380b4bc.RTP: 192.168.2.65:55953/udp
JVB 2022-02-28 23:09:01.930 INFO: [80] [confId=de3d790bc9702958 gid=7070 stats_id=Noemi-RLa componentId=1 conf_name=12345@conference.conf.infowatch.com ufrag=2rtve1ft0v6m8l name=stream-e380b4bc epId=e380b4bc local_ufrag=2rtve1ft0v6m8l] Component.updateRemoteCandidates#484: new Pair added: 178.16.25.98:10000/udp/host -> 10.254.1.3:55952/udp/host (stream-e380b4bc.RTP).
JVB 2022-02-28 23:09:01.931 INFO: [80] [confId=de3d790bc9702958 gid=7070 stats_id=Noemi-RLa componentId=1 conf_name=12345@conference.conf.infowatch.com ufrag=2rtve1ft0v6m8l name=stream-e380b4bc epId=e380b4bc local_ufrag=2rtve1ft0v6m8l] Component.updateRemoteCandidates#484: new Pair added: 178.16.25.98:10000/udp/host -> 192.168.2.65:55953/udp/host (stream-e380b4bc.RTP).
JVB 2022-02-28 23:09:01.945 WARNING: [84] [confId=de3d790bc9702958 gid=7070 stats_id=Noemi-RLa conf_name=12345@conference.conf.infowatch.com ufrag=2rtve1ft0v6m8l epId=e380b4bc local_ufrag=2rtve1ft0v6m8l] ConnectivityCheckClient.startCheckForPair#374: Failed to send BINDING-REQUEST(0x1)[attrib.count=6 len=92 tranID=0xF85AF3417F010EC8750E874C]
JVB 2022-02-28 23:09:01.945 INFO: [84] [confId=de3d790bc9702958 gid=7070 stats_id=Noemi-RLa conf_name=12345@conference.conf.infowatch.com ufrag=2rtve1ft0v6m8l epId=e380b4bc local_ufrag=2rtve1ft0v6m8l] ConnectivityCheckClient$PaceMaker.run#942: Pair failed: 178.16.25.98:10000/udp/host -> 10.254.1.3:55952/udp/host (stream-e380b4bc.RTP)
JVB 2022-02-28 23:09:01.946 WARNING: [84] [confId=de3d790bc9702958 gid=7070 stats_id=Noemi-RLa conf_name=12345@conference.conf.infowatch.com ufrag=2rtve1ft0v6m8l epId=e380b4bc local_ufrag=2rtve1ft0v6m8l] ConnectivityCheckClient.startCheckForPair#374: Failed to send BINDING-REQUEST(0x1)[attrib.count=6 len=92 tranID=0xF95AF3417F01E404A3DB99C0]
JVB 2022-02-28 23:09:01.946 INFO: [84] [confId=de3d790bc9702958 gid=7070 stats_id=Noemi-RLa conf_name=12345@conference.conf.infowatch.com ufrag=2rtve1ft0v6m8l epId=e380b4bc local_ufrag=2rtve1ft0v6m8l] ConnectivityCheckClient$PaceMaker.run#942: Pair failed: 178.16.25.98:10000/udp/host -> 192.168.2.65:55953/udp/host (stream-e380b4bc.RTP)

**Comment by saghul** [comment] 2022-03-01 06:20
What error do you get in meet.jit.si when the page reloads?

**Comment by Owirtifo** [comment] 2022-03-01 06:49
I tried it today, the microphone and camera don't turn on. And the sound goes only one way.

2022-03-01T06:46:43.663Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=P2P,initiator=true,sid=f26bb602f856] Replace track error: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

Logger.js:154 2022-03-01T06:46:43.664Z [JitsiConference.js] replaceTrack failed: Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

Logger.js:154 2022-03-01T06:46:43.664Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer. Script: null Line: null Column: null StackTrace:  Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

**Comment by roman04204** [comment] 2022-03-01 07:10
I had the same problem, it also worked and at one point it stopped)
https://github.com/jitsi/jitsi-meet/issues/11043

**Comment by saghul** [comment] 2022-03-01 08:12
> I tried it today, the microphone and camera don't turn on. And the sound goes only one way.
> 
> 2022-03-01T06:46:43.663Z [modules/xmpp/JingleSessionPC.js] <Object.callback>: JingleSessionPC[session=P2P,initiator=true,sid=f26bb602f856] Replace track error: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.
> 
> Logger.js:154 2022-03-01T06:46:43.664Z [JitsiConference.js] replaceTrack failed: Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.
> 
> Logger.js:154 2022-03-01T06:46:43.664Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>: UnhandledError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer. Script: null Line: null Column: null StackTrace: Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.
> 
> Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

That's odd, was this on meet.jit.si ? Also, this doesn't show the real reason for the reload. Can you search your console for CONFERENCE_FAILED?

**Comment by eXeLe** [comment] 2022-03-01 11:55
We are fasing the same issue (for some of our users) with 98.0.4758.102. But for some users it works fine. There are also problems with MS Edge. And it works perfectly in FF and Yandex.Browser.
We fasing this problem on our local installation and on meet.jit.si.
Some of our users, who have this problem, says that it works fine, while they are connected to companys VPN.
As I can see from this post and from another, mentioned above, the common thing here is we are all from Russian companies, probably it could be related in some way.

**Comment by Owirtifo** [comment] 2022-03-01 14:12
Perhaps it's strange that it works through FF, if something was blocked, it didn't work through other browsers either.

**Comment by roman04204** [comment] 2022-03-01 15:20
Seems to be:
https://support.google.com/chrome/thread/149820183/webrtc-not-working-after-chrome-update-to-version-98-0-4758-82?hl=en

**Comment by eXeLe** [comment] 2022-03-01 15:44
> Seems to be: https://support.google.com/chrome/thread/149820183/webrtc-not-working-after-chrome-update-to-version-98-0-4758-82?hl=en

This post is from Feb 7, 2022, but our problem started like a few days ago.

**Comment by jallamsetty1** [comment] 2022-03-01 19:35
It appears that some traffic blocking is happening in your providers network as the ICE connection between the client and the bridge is failing. FYI, google meet also seems to have the same issue. Are you able to verify if you are able to get the media to work on https://meet.google.com/ ? This is the Chrome bug for your reference - https://bugs.chromium.org/p/chromium/issues/detail?id=1301270

**Comment by Owirtifo** [comment] 2022-03-02 06:42
It work on https://meet.google.com/

**Comment by R31N3** [comment] 2022-03-02 12:48
Got the same problem, the same time on docker latest jitsi version. In FF and Yandex Browser it works fine, but in chrome troubles appears when 2+ members use Chrome and 1+ user use other browser. 

Same issue on meet.jit.si and JaaS Dev (tried this for tests too). 
Also tried previous versions of Jitsi, but I think there's some troubles in chrome...

Chrome Version 98.0.4758.102 and 101.0.4919.0

**Comment by saghul** [comment] 2022-03-02 13:00
Any chance you can try to repro with Chrome beta (99) ?

**Comment by roman04204** [comment] 2022-03-02 13:09
Similarly, the issue persists on Chrome beta (99) (

**Comment by chernodub** [comment] 2022-03-03 06:01
We're facing **the same issue on Chrome 98** (although it works fine on Firefox and Safari). This is reliably reproducible on meet.jit.si with 3 participants or more. The users who use Chrome 98, can not see either each other or other people (and others can not see them), also the page reloads automatically for Chrome users (not sure if it's related to #11043).
I'm attaching the logs below, hope it's going to be helpful somehow.

[meet.jit.si-1646287104793.log](https://github.com/jitsi/jitsi-meet/files/8175348/meet.jit.si-1646287104793.log)

**Comment by cinques** [comment] 2022-03-03 07:44
BTW everything works on chrome 94

**Comment by saghul** [comment] 2022-03-03 09:29
> BTW everything works on chrome 94 Seems to be https://bugs.chromium.org/p/chromium/issues/detail?id=1203442

Interesting. How did you reach that conclusion? I cannot reproduce the bug on 99 for instance.

**Comment by wf2020** [comment] 2022-03-06 23:07
I also noticed that the API doesn't request video and  microphone access in Edge and Chrome, Firefox works.
Direct call of meet.xxx.xx works.
Iframe in Edge or Chrome only works when adding allow "video;microphone".

**Comment by wf2020** [comment] 2022-03-06 23:09
I also noticed that the API doesn't request video and microphone access in Edge and Chrome, Firefox works.
Direct call of meet.xxx.xx works in Edge and Chrome.
Iframe in Edge or Chrome only works when adding allow="video;microphone".

**Comment by damencho** [comment] 2022-03-07 00:52
@wf2020 iframe API creates the iframe itself and always uses `allow="video;microphone".`
If you are creating the iframe, that is not the correct way of using the iframeAPI 
https://github.com/jitsi/jitsi-meet/blob/981e96fb6ae459dada2d8bc4fc1feec4f7a9b84d/modules/API/external/external_api.js#L364

https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe

**Comment by wf2020** [comment] 2022-03-07 00:59
> @wf2020 iframe API creates the iframe itself and always uses `allow="video;microphone".` If you are creating the iframe, that is not the correct way of using the iframeAPI

It might be not the correct way - but it only works this way, so when I add allow="video;microphone".

**Comment by abasalaev** [comment] 2022-03-07 06:47
Is there any workaround available?

**Comment by cinques** [comment] 2022-03-07 07:07
> Is there any workaround available?

use relay or vpn

**Comment by R31N3** [comment] 2022-03-16 08:28
At this moment it doesn't work from Russia on any browser, even FF or Yandex Browser. Works Normal with VPN, but Chrome Issue appears again.

**Comment by saghul** [comment] 2022-03-16 12:56
More evidence that filtering is going on in Russia: https://github.com/net4people/bbs/issues/108

I adjusted the issue title too.

**Comment by saghul** [comment] 2022-03-16 21:09
I pinned this issue and I'm closing it since there nothing actionable for us.

**Closed by saghul** 2022-03-16 21:09 UTC

**Comment by umairgillani94** [comment] 2022-03-21 12:15
Having same issue. But not in Russia, I am using on premises deployment and libs/external_api.min.js.

The linux package is update on version 2.0.7001-1

Chrome version is 99

**Comment by saghul** [comment] 2022-03-21 13:34
@umairgillani94 That is a separate problem, please open a new issue.

**Comment by umairgillani94** [comment] 2022-03-22 11:29
> @umairgillani94 That is a separate problem, please open a new issue.

@saghul created. https://github.com/jitsi/jitsi-meet/issues/11192

**Comment by R31N3** [comment] 2022-04-07 06:51
Hello again! As I can see, trafic filtering in Russia now doesn't affect Jitsi, and it works great at self hosted instance and at meet.jit.si too!

**Comment by ValdikSS** [comment] 2022-05-02 17:06
https://ntc.party/t/webrtc/2174
