### ISSUE TITLE
Do you have the SDK developed using Android?

### ISSUE THREAD

**Issue by lizi0588** [jitsi/jitsi-meet#2445] opened 2018-02-01 03:12 UTC
I want to use only Android code to make calls instead of using react native. I want to use the native layout of Android, so that it will be better to maintain the project. Can this be achieved? Do you have the SDK developed using Android?

**Comment by saghul** [comment] 2018-02-01 09:05
Please don't open new issues which have already been answered. Closing a duplicate of #2442

**Closed by saghul** 2018-02-01 09:05 UTC
