### ISSUE TITLE
Does not work if no sound/video detected, or if sound/video access is denied

### ISSUE THREAD

**Issue by mgaunard** [jitsi/jitsi-meet#133] opened 2014-09-18 06:14 UTC
Even if there is no sound or video, the meeting should take place, and this shouldn't prevent things such as chatting or desktop sharing.

**Comment by akuckartz** [comment] 2015-11-01 18:57
Seems to be a duplicate of #271 (which was created later).

**Comment by bgrozev** [comment] 2016-02-17 19:17
This should be fixed now. Please open a new issue if it still happens.

**Closed by bgrozev** 2016-02-17 19:17 UTC
