### ISSUE TITLE
Better issue management

### ISSUE THREAD

**Issue by toby63** [jitsi/jitsi-meet#6306] opened 2020-04-22 14:48 UTC
I know you are probably busy, but I noticed that the issue tracker is flooded with issues right now, and many of them are duplicates, have no content etc.

So I would recommend better issue management.
This can include the following:
* apply more labels and milestones for better seperation between issues
* use an automatic issue labeler, like: https://github.com/github/issue-labeler
* delete empty or nonsense issues
* close duplicates (or even delete them)
* Respond to issues, when they are solved or if you work on them (can also be marked with labels)

Thanks in advance.

**Comment by toby63** [comment] 2020-04-22 14:53
@jitsi @saghul

**Comment by AliKarpuzoglu** [comment] 2020-04-22 17:01
In the last hour there were 3 issues about people not able to open their camera. I strongly agree. Real Bugs in the software get left behind.

**Comment by l3d00m** [comment] 2020-04-23 05:58
Ironically, this is a duplicate of #6164 :P

They are investigating the possibilities for better issue management and my hope is that they add people from the community here, as there seem to be a lot willing to help.

**Comment by saghul** [comment] 2020-04-23 07:08
Pleasse let's continue over on #6164

**Closed by saghul** 2020-04-23 07:08 UTC
