### ISSUE TITLE
unable to acces camera

### ISSUE THREAD

**Issue by brusspi** [jitsi/jitsi-meet#5195] opened 2020-03-16 21:16 UTC
I'm using Riot desktop-app.  When I do a conferencecall with Jitsi and I toggle to tile view, then the camera-function is not working

**Comment by saghul** [comment] 2020-03-17 20:09
Does your camera work when using the Chrome desktop browser?

**Comment by alexanderadam** [comment] 2020-03-25 11:23
Isn't this a duplicate of #5155?

**Comment by Echolon** [comment] 2020-04-10 20:15
@damencho can be closed

**Closed** 2020-04-10 20:20 UTC
