### ISSUE TITLE
error:"Unfortunately something went wrong"

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [jitsi/jitsi-meet#6985] opened 2020-06-08 10:03 UTC
After reading everything that I could find, nothing really helped me to pass "**Unfortunately, something went wrong**" error. Please help me.
-----
Server OS: Debian 10
DOMAIN_NAME: https://meet.chattly.xyz
SSL_CERTIFICATE: Custom ZeroSSL certificate
RAM: 512MB
CPU: 1.00GHz
CPU_ARCHITECTURE: 32Bit
WiFi_SPEED: 50mbps
DNS_TTL: 1min
Memory: 128GB
------
Note that I've got a free SSL cause I couldn't generate one with certbot because of insufficient system resources.

**Comment by Echolon** [comment] 2020-06-08 19:59
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

The report is few of information, please review the forum first, then come back with more information. Until then I will close this.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-06-08 19:59 UTC
