### ISSUE TITLE
ios dominant speaker not being shown with latest app update

### ISSUE THREAD

**Issue by cegnulug** [jitsi/jitsi-meet#7868] opened 2020-10-08 23:04 UTC
### Description:

With the latest ios app (20.4.2 build88), the dominant speaker function doesn't seem to work anymore. The 'blue speaker' icon isn't shown and it doesn't bring to focus the dominant speaker like it used to. This functionality worked fine the previous version. 
FWIW, other participants (using non-ios app) continue to see the dominant speaker and the 'blue speaker' icon. 

### Steps to reproduce:

1. Use latest ios app with self hosted jitsi

### Actual behavior:

Some other tests/clients we ran:
1. App with meet.jit.si -> dominant speaker is shown
2. Safari on the same ipad with self hosted -> dominant speaker is shown
3. Firefox on Linux with self hosted -> dominant speaker is shown

### Server information:

- Jitsi Meet version: 1.0.4428 (also tried 1.0.4370 and 1.0.4289)
- Operating System: debian 10

### Client information:

- Browser / app version: 20.4.2build88
- Operating System: IpadOS13.5.1 and 14.0.1

### Additional information:

Please let me know if there's any other information or tests I could run to help resolve this issue. Thanks.

**Comment by saghul** [comment] 2020-10-09 08:24
I cannot reproduce this with meet.jit.si. This could mean your installation has a broken bridge channel configuration somehow. Can you use Console.app on a Mac computer, select the iPhone and filter by the "JitsiMeetSDK" category. You should see some logs there.

**Comment by cegnulug** [comment] 2020-10-09 16:27
Sure. I'll do the console app and report back.

Just out of curiosity, does the ios client app use a different "bridge channel config" than say a client using Safari or Firefox? The reason I ask is during the same meeting with a self hosted jitsi, all the Safari and Firefox clients do see the dominant speaker while only the participants using the ios app don't see the dominant speaker. 
FWIW, our self hosted server's openBridgeChannel is set 'datachannel' and not websocket. 

Thank you.

**Comment by saghul** [comment] 2020-10-09 17:29
It's the same config, but a different implementation on the WebRTC wrapper we use.

**Comment by cegnulug** [comment] 2020-10-09 19:54
I see. Thanks for the info. 

As for the Console output on a mac. All I see are repeated lines of:
<timestamp> jitsi-meet [modules/RTC/BridgeChannel.js] Bridge Channel send: no opened channel.

Not very familiar with Console and I'm not sure what to make of this.

**Comment by saghul** [comment] 2020-10-10 03:07
That explains why you don't see dominant speaker changes, since that is signaled through the bridge channel.

**Comment by kaymyst** [comment] 2020-10-16 07:41
hi I'm experiencing the same issue but I don't understand how to fix it. @cegnulug did you get anywhere?

**Comment by 10urT** [comment] 2020-10-22 12:10
Yes, I am too.

**Comment by robertogvieira** [comment] 2020-11-12 14:59
Same here 🙁
and also getting the bridge channel log:
![Jitsi dominant speaker issue #7868](https://user-images.githubusercontent.com/7226114/98956217-ab09cb80-24f7-11eb-8c14-c72729169f12.png)

**Comment by kaymyst** [comment] 2020-11-12 15:04
we ended up moving to websockets instead of datachannel  on our server to fix the issue

**Comment by robertogvieira** [comment] 2020-11-12 15:32
@kaymyst cool 👍 

Do you happen to use **JWT token authentication**? Does it still work after the change? 
I'm asking because of the statement [here](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md):
> JWT token authentication currently works only with BOSH connections.

**Comment by saghul** [comment] 2020-11-13 23:04
That's no longer the case.

**Comment by saghul** [comment] 2020-11-15 21:10
Closing since this is an issue with that specific deployment (ie, the broken bridge channel) not a bug in the software itself.

**Closed by saghul** 2020-11-15 21:10 UTC
Labels: ios, meet.jit.si, mobile
