### ISSUE TITLE
lib-jitsi-meet 404 not found when building from source

### ISSUE THREAD

**Issue by luciash** [jitsi/jitsi-meet#694] opened 2016-06-14 22:47 UTC
Hi,
I get the following errors when trying to build using make command on Ubuntu 14.04. It suggest the package does not exist anymore on registry.npmjs.org and the build fails:

$ make
npm install
npm http GET https://registry.npmjs.org/async/0.9.0
npm http GET https://registry.npmjs.org/bootstrap/3.1.1
npm http GET https://registry.npmjs.org/i18next-client/1.7.7
npm http GET https://registry.npmjs.org/events
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/autosize
npm http GET https://registry.npmjs.org/jquery-contextmenu
npm http GET https://registry.npmjs.org/jquery-ui
npm http GET https://registry.npmjs.org/retry/0.6.1
npm http GET https://registry.npmjs.org/strophe
npm http GET https://registry.npmjs.org/jssha/1.5.0
npm http GET https://registry.npmjs.org/strophejs-plugins
npm http GET https://registry.npmjs.org/toastr
npm http GET https://registry.npmjs.org/browserify-shim
npm http GET https://registry.npmjs.org/exorcist
npm http GET https://registry.npmjs.org/browserify
npm http GET https://registry.npmjs.org/jshint/2.8.0
npm http GET https://registry.npmjs.org/uglify-js/2.4.24
npm http GET https://registry.npmjs.org/precommit-hook/3.0.0
npm http GET https://registry.npmjs.org/clean-css
npm http GET https://registry.npmjs.org/babelify
npm http GET https://registry.npmjs.org/babel-preset-es2015
npm http GET https://registry.npmjs.org/babel-polyfill
npm http GET https://registry.npmjs.org/lib-jitsi-meet
npm http 304 https://registry.npmjs.org/bootstrap/3.1.1
npm http 304 https://registry.npmjs.org/autosize
npm http 304 https://registry.npmjs.org/events
npm http 304 https://registry.npmjs.org/i18next-client/1.7.7
npm WARN deprecated i18next-client@1.7.7: you can use npm install i18next from version 2.0.0
npm http 304 https://registry.npmjs.org/jquery-contextmenu
npm http 304 https://registry.npmjs.org/strophe
npm http 304 https://registry.npmjs.org/jquery
npm http 304 https://registry.npmjs.org/jssha/1.5.0
npm WARN deprecated jssha@1.5.0: jsSHA versions < v2.0.0 will no longer receive features
npm http 304 https://registry.npmjs.org/async/0.9.0
npm http 304 https://registry.npmjs.org/strophejs-plugins
npm http 304 https://registry.npmjs.org/retry/0.6.1
npm http 304 https://registry.npmjs.org/exorcist
npm http 304 https://registry.npmjs.org/toastr
npm http 304 https://registry.npmjs.org/jshint/2.8.0
npm http 304 https://registry.npmjs.org/browserify
npm http 304 https://registry.npmjs.org/clean-css
npm http 304 https://registry.npmjs.org/jquery-ui
npm http 304 https://registry.npmjs.org/uglify-js/2.4.24
npm http 304 https://registry.npmjs.org/browserify-shim
npm http 304 https://registry.npmjs.org/precommit-hook/3.0.0
npm http 304 https://registry.npmjs.org/babelify
npm http 304 https://registry.npmjs.org/babel-polyfill
npm http 304 https://registry.npmjs.org/babel-preset-es2015
npm http 404 https://registry.npmjs.org/lib-jitsi-meet
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-88-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/GIT/Marc L/jitsi-meet
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/GIT/Marc L/jitsi-meet/npm-debug.log
npm ERR! not ok code 0
make: *** [update-deps] Error 1

Any ideas?

**Comment by luciash** [comment] 2016-06-15 09:45
Interestingly when I go directly to https://registry.npmjs.org/lib-jitsi-meet in my browser it does not return 404 (as npm wrongly reports) but an empty json array "{}" - is that what it is supposed to return?
Could the problem be the npm version? What is the recommended version to use?

**Comment by luciash** [comment] 2016-06-28 08:27
Ping! Anyone checking this?

**Comment by damencho** [comment] 2016-06-28 14:42
jitsi-meet and lib-jitsi-meet are not uploaded to npmjs.org, so its normal that they are missing there. Not sure though why it searches for them. Do you see this with clean co from github jitsi-meet project? 
A clean clone of jitsi-meet doing npm install and then make, should work fine. lib-jitsi-meet is directly checked out from github inside its dependencies.

**Comment by mbell8903** [comment] 2016-07-14 15:11
Im getting this as well.  The issue is with this line in the `package.json`:  `"lib-jitsi-meet": "jitsi/lib-jitsi-meet",`.  NPM 3.0 looks at https://registry.npmjs.org by default, so it assumes that the package is there.  When changed to `"lib-jitsi-meet": "git+https://github.com/jitsi/lib-jitsi-meet.git",` it works, except that the same issue exists in the lib-jitsi-meet project's `package.json` for the jitsi-meet-logger dependency.

**Comment by damencho** [comment] 2016-07-19 15:52
Fixed by https://github.com/jitsi/jitsi-meet/commit/85d0c62c1dadba0778668cff9037cc8d97eb427e
and https://github.com/jitsi/lib-jitsi-meet/commit/1d57a4550af44d3e28e74a5bfd3e5a82d0904989

**Closed by damencho** 2016-07-19 15:52 UTC

**Comment by luciash** [comment] 2016-07-27 18:25
Awesome! Thanks!

**Comment by luciash** [comment] 2016-07-27 20:04
Looks better, just now it ends with:
```
> lib-jitsi-meet@0.0.0 browserify /var/www/GIT/Marc L/jitsi-meet/node_modules/lib-jitsi-meet
> browserify -d JitsiMeetJS.js -s JitsiMeetJS | exorcist lib-jitsi-meet.js.map > lib-jitsi-meet.js && [ -s lib-jitsi-meet.js ]

sh: 1: exorcist: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0
make: *** [update-deps] Error 1
```

Must be different issue, right?
