### ISSUE TITLE
Turn on lobby by default for each newly created room

### ISSUE THREAD

**Issue by mfts** [jitsi/jitsi-meet#7385] opened 2020-07-23 08:16 UTC
**Is your feature request related to a problem you are facing?**
I differentiate conference participants between moderators and regular participants. I authenticate users with JWT, where I also set a moderator boolean field. To achieve this, I use a custom prosody plugin: https://github.com/mfts/jitsi-token-moderation-plugin/ 

Now I would also like to have lobby turned for each room so only moderators can enter.

**Describe the solution you'd like**
I would like to turn on lobby by default for all newly created rooms and let only moderators join without having to request access.
There will be two scenarios:
1. Moderator is first to enter the room:
   - Can join normally because s/he is a moderator
   - Lobby is not blocking him/her from entering

2. Regular participant is first to enter the room:
   - Cannot join/create the conference, because a lobby is set which requires a moderator to enter first
   - Participant sees a screen, moderator is not present yet, please wait (or come back later)

**Comment by saghul** [comment] 2020-07-23 08:25
We currently don't have a setting for enabling the lobby by default. I guess we'd need that first.

Allowing a moderator to skip the lobby is a bit of a chicken and egg problem, because you can only be a moderator once *inside* a room, and the lobby prevents you from entering.

At a glance I think we'd need some extra info in the token to make it work, thus limiting that functionality only to token based authentication.

**Comment by surfrock66** [comment] 2020-09-25 18:10
This has been determined to be a deal-breaking feature for our organization. One idea I had was to add some small settings to the meeting create screen, a slider on the side for "enable lobby" and if ticked, when you press "go" host authentication pops up before proceeding?  I'm not sure how the back-end works, but it seems it solves the chicken and egg problem before joining the actual meeting.

**Comment by amsnek** [comment] 2020-10-31 22:38
this may be relevant to the discussion: 
https://community.jitsi.org/t/start-a-room-with-lobby-enabled/79279/4

**Comment by qchn** [comment] 2020-12-17 14:20
Hey @saghul 
>We currently don't have a setting for enabling the lobby by default.

any news on this?
I really need this feature! :-)

Best
Robert

**Comment by saghul** [comment] 2020-12-17 14:21
No updates on this, sorry.

**Comment by d3hof** [comment] 2020-12-30 09:18
> Allowing a moderator to skip the lobby is a bit of a chicken and egg problem, because you can only be a moderator once _inside_ a room, and the lobby prevents you from entering.

This makes the lobby-feature basically unuseable if you use authentification on your setup. Because as soon as you disconnect you cannot rejoin the meeting, because there is no moderator left.

**Comment by amsnek** [comment] 2020-12-30 09:54
> > Allowing a moderator to skip the lobby is a bit of a chicken and egg problem, because you can only be a moderator once _inside_ a room, and the lobby prevents you from entering.
> 
> This makes the lobby-feature basically unuseable if you use authentification on your setup. Because as soon as you disconnect you cannot rejoin the meeting, if there is no moderator left.

as workaround, one can set a password. that way, anyone who knows the password can re-enter (and then become moderator again). i admit this will not be a workaround for everyone, but may be usefull for some.

**Comment by fritzgithub** [comment] 2021-03-05 18:02
> ...
> Allowing a moderator to skip the lobby is a bit of a chicken and egg problem, because you can only be a moderator once _inside_ a room, and the lobby prevents you from entering.
> 
> At a glance I think we'd need some extra info in the token to make it work, thus limiting that functionality only to token based authentication.

Any updates on this?
Without decent re-entry for moderators the lobby feature is not working for us ...

**Comment by Aldekein** [comment] 2021-05-20 15:24
The lobby function is extremely wanted. I know that there was a progress with it: https://community.jitsi.org/t/how-to-how-do-i-use-the-new-lobby-feature/73100 and https://community.jitsi.org/t/lobby-waiting-room/27752/53 but since it locks out the moderators it's not in a state that could be used. I've read that generally there is nothing in Jitsi-meet to setup special characteristics for rooms, but some rooms have their characteristics and need a way to reflect it in Jitsi.

**Comment by mkofahl** [comment] 2022-01-13 19:00
The lobby can be activated with this hook, but I'm not sure if the event is always processed in time. Should run before the hook defined in [mod_token_verification.lua](https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_token_verification.lua) using default priority.

    module:hook("muc-room-pre-create", function(event)
        if module:get_option_boolean("muc_lobby_default", false) then
                log('debug', 'auto-enabling lobby for room "%s".', roomname);

                local stanza = event.stanza;
                local roomname = jid.split(stanza.attr.to);
                prosody.events.fire_event("create-lobby-room", event);
        end
    end, 5);

Now nobody can create a room with this hook. Everyone goes to the lobby. In mod_muc_lobby_rooms.lua there are several rules to bypass the lobby. One could add a module setting the room password using a database. Or [mod_muc_lobby_rooms.lua](https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_lobby_rooms.lua) may be extended to read the token (copy-paste from [mod_token_moderation.lua](https://github.com/nvonahsen/jitsi-token-moderation-plugin/blob/master/mod_token_moderation.lua)):

    if is_token_room_owner(event.origin) == true then
        whitelistJoin = true;
    end
    
    ...
    
    function is_token_room_owner(origin)
        if origin.auth_token then
                -- Extract token body and decode it
                local dotFirst = origin.auth_token:find("%.");
                if dotFirst then
                        local dotSecond = origin.auth_token:sub(dotFirst + 1):find("%.");
                        if dotSecond then
                                local bodyB64 = origin.auth_token:sub(dotFirst + 1, dotFirst + dotSecond - 1);
                                local body = json.decode(basexx.from_url64(bodyB64));
                                return body["moderator"] == true;
                        end;
                end;
        end;
    end;

**Comment by Tmmon799** [comment] 2022-03-03 00:29
Keeping the thread alive, is Jitsi coming up with the default lobby feature any time soon? Any ETA for it. 
What we are trying to implement as we do not want the client to come in before the moderator, like in Zoom the host automatically becomes host even after it joined late in the meeting with no lobby. But, in jitsi, the first person to enter the room is moderator and not the one who set the meeting. We would want the client to wait in the lobby until it is accepted by the moderator, but then how will the room know if this is the one who set the meeting, so zoom has personal meeting ID for it, which Jitsi does not. Can someone please help on this one ? Thanks in advance.

**Comment by saghul** [comment] 2022-03-03 06:46
You can use moderated.jitsi.net to create rooms where you decide who the moderator is.

The problem then is that if people wait for the moderator to arrive they are automatically let in before the moderator has the chance to enable the lobby.

Since rooms don't exist until someone joins, we have a chicken and egg problem here, because there is no clear way to decide if the lobby should be enabled for a given room.

**Comment by Tmmon799** [comment] 2022-03-03 16:25
Hey Saghul, thanks for the help. I have self hosted Jitsi on AWS. I know you mentioned the chicken and egg problem, but do you think, would there be a possibility that I can make a solution of default waiting room for all given room for participants like zoom, zoom has the option while scheduling but before the meeting started of enabling the waiting room and can I include the feature for the moderator as who set the meeting would be the only one to bypass the waiting room. would that be a possibility for custom or it jitsi having a solution for this in mind ?

**Comment by saghul** [comment] 2022-03-03 17:08
We currently don't have a solution nor are we working on one at this moment, sorry.

**Comment by Tmmon799** [comment] 2022-03-03 21:04
Thanks for the information.

**Comment by albertoVieiraNeto** [comment] 2022-05-25 19:49
Maybe this could be solved when using the JWT token authentication, currently jitsi considers anyone with a jwt a administrator, therefore, the admins could sort of "skip" the lobby, anyone else, should wait on the lobby for any of the admins to "aprove" of him. 

this could be further "improved" if there was a indicator inside the JWT if that person/user is a admin, to further mitigate any authorization issues.

**Comment by shawnchin** [comment] 2022-08-11 11:27
There is now a prosody plugin in jitsi-contrib to autostart lobby for all rooms -- https://github.com/shawnchin/prosody-plugins/tree/main/lobby_autostart

As mentioned in the discussion above, this is only practical if you have some means for moderators to bypass the lobby.  There's another plugin coming soon that will offer that based on JWT attributes -- https://github.com/jitsi-contrib/prosody-plugins/pull/13

**Comment by amsnek** [comment] 2022-08-11 11:42
this seems to be a nice approach. Though it would be nice to allow authenticated users (Moderators) to inmediately enter the lobby. Is there an "default passwort for room" feature I am unaware about? 
Will have to look at the upcoming JWT token feature, though then I will need to run an JWT Service somewhere for users to authenticate against and get a Token i assume? 

Very nice that this is not forgotten and progress happening. thanks @shawnchin

**Comment by shawnchin** [comment] 2022-08-11 12:15
> Is there an "default password for room" feature I am unaware about?

I don't think there is official support for that, but there are several posts in community with suggestions on how to achieve that. 

> though then I will need to run an JWT Service somewhere for users to authenticate against and get a Token i assume?

Yup.

**Comment by megamaiku** [comment] 2022-09-28 14:04
Would setting MEET_MODERATOR key to true in the .env file address this?

> There is now a prosody plugin in jitsi-contrib to autostart lobby for all rooms -- https://github.com/shawnchin/prosody-plugins/tree/main/lobby_autostart
> 
> As mentioned in the discussion above, this is only practical if you have some means for moderators to bypass the lobby. There's another plugin coming soon that will offer that based on JWT attributes -- [jitsi-contrib/prosody-plugins#13](https://github.com/jitsi-contrib/prosody-plugins/pull/13)
> 
> I've intentionally separate the notion of "moderator" with the ability to bypass lobby. This allows for user cases where you might want to allow certain non-moderators to join without being manually admitted, and perhaps to have some moderators still subject to the lobby.

**Comment by saghul** [comment] 2022-09-28 14:08
> There is now a prosody plugin in jitsi-contrib to autostart lobby for all rooms -- https://github.com/shawnchin/prosody-plugins/tree/main/lobby_autostart
> 
> 
> 
> As mentioned in the discussion above, this is only practical if you have some means for moderators to bypass the lobby.  There's another plugin coming soon that will offer that based on JWT attributes -- https://github.com/jitsi-contrib/prosody-plugins/pull/13
> 
> 
> 
> I've intentionally separate the notion of "moderator" with the ability to bypass lobby. This allows for user cases where you might want to allow certain non-moderators to join without being manually admitted, and perhaps to have some moderators still subject to the lobby. 

Closing since this is now possible. Thanks @shawnchin !

**Comment by amsnek** [comment] 2022-09-28 14:08
> Would setting MEET_MODERATOR key to true in the .env file address this?

Hmm curious, what config file (jicofo?) is influenced by this environment setting?

**Closed by saghul** 2022-09-28 14:08 UTC
Labels: feature-request, ui/ux

**Comment by shawnchin** [comment] 2022-09-28 16:33
AFAIK, there is not such env var so should not influence anything.

**Comment by megamaiku** [comment] 2022-09-29 11:11
> > Would setting MEET_MODERATOR key to true in the .env file address this?
> 
> Hmm curious, what config file (jicofo?) is influenced by this environment setting?

My bad, I'm running a customized version. Although what helped us in our setup was implementing this plugin to use with our tokens: https://github.com/nvonahsen/jitsi-token-moderation-plugin

**Comment by maulikgoyanidbc** [comment] 2024-03-11 11:16
@saghul 
How can I turn on/off lobby when create room using iOS sdk? before create room we are showing our own screen and on that screen user can select lobby option turn on/off.

do we have any function in iOS sdk to handle this?

**Comment by maulikgoyanidbc** [comment] 2024-03-11 11:45
@saghul  We hide jitsi default toolbox as there are lots of option. (toolbox.enabled = false)
So as there is no API function and We are hiding toolbox. we are not able to use this feature. Am I correct?

**Comment by saghul** [comment] 2024-03-11 12:17
> We are hiding toolbox. we are not able to use this feature. Am I correct?

Correct.



> Also we need apis for list of participant who waiting in lobby. moderator can accept and reject their request. (This is also out custome ui)

We provide a UI already, adding extra APIs to recreate a custom UI is not high on our roadmap...

**Comment by brlarini** [comment] 2024-05-24 02:19
Sorry to insist on this topic, but I was wondering if it wouldn't be possible for an authenticated user have the same treatment as someone joining a meeting with JWT.
I have a working instance that uses JWT tokens and it works fine, and now was experimenting with LDAP authentication hoping all authenticated users could join rooms as moderators.

Of course, after the room is opened there would have to be means to keep authenticating users, maybe enabling some small button under the main join button for guests. This would also solve the issue with orphaned rooms, if for some reason the last moderator was disconnected from the room.

**Comment by saghul** [comment] 2024-05-24 07:46
JWT is the most flexible authentication mechanism we support and in fact t we have long term plans to deprecate and remove the test. I'd suggest you stick to JWT.

**Comment by brlarini** [comment] 2024-05-24 14:27
I see.
As I understand, JWT is really useful when integrated with other software and tools that can generate the token, but what if you want to give the moderation powers based on the user instead of the URL containing the token?

For example, with JWT we can create rooms that are not bound to any user, but because of that we have to define an expiration time for that room. If eventually the user quits our organization, the user can't get into that room after that period of time.

If the control is based on user, let's say with LDAP, this user can have a room for an indefinite amount time, and as soon as this person quits the organization we can disable their account.

I still can see user accounts as an useful choice for user control on Jitsi Meet, but maybe I don't completely understand all the applications for JWT. Maybe there's a way to achieve a similar setup for user control?

**Comment by damencho** [comment] 2024-05-24 14:35
You can have your LDAP login page which generates jwt tokens. It is recommended to generate tokens with an expiration date, and let them be valid for 12 or 24h. 
In a few months when you decide not to use LDAP, but some other identity provider, it is easy to switch as you change only the login page and continue using the JWT tokens and you do not touch the jitsi-meet deployment.

**Comment by damencho** [comment] 2024-05-24 14:36
> If the control is based on user, let's say with LDAP, this user can have a room for an indefinite amount time, and as soon as this person quits the organization we can disable their account.

I don't see how this cannot be achieved when using jwt tokens?

**Comment by brlarini** [comment] 2024-05-24 14:42
Yeah, I probably should research more on it then.
Thanks!

**Comment by amsnek** [comment] 2025-02-20 07:03
> > There is now a prosody plugin in jitsi-contrib to autostart lobby for all rooms -- https://github.com/shawnchin/prosody-plugins/tree/main/lobby_autostart
> > As mentioned in the discussion above, this is only practical if you have some means for moderators to bypass the lobby.  There's another plugin coming soon that will offer that based on JWT attributes -- [jitsi-contrib/prosody-plugins#13](https://github.com/jitsi-contrib/prosody-plugins/pull/13)
> > I've intentionally separate the notion of "moderator" with the ability to bypass lobby. This allows for user cases where you might want to allow certain non-moderators to join without being manually admitted, and perhaps to have some moderators still subject to the lobby.
> 
> Closing since this is now possible. Thanks [@shawnchin](https://github.com/shawnchin) !

I just realised, that when using lobby_autostart + token_moderation + token_lobby_bypass that "non moderators" (using JWT token but without lobby bypass enabled) can still bypass the lobby (when being first) by selecting "enter password" and just leaving it blank. I assume this is because the room has no password set and the guest is authenticating with JWT. Is this is intended behaviour however?

**Comment by shawnchin** [comment] 2025-02-21 09:29
@amsnek Hmm... That really shouldn't happen. Can you repro the same issue when you start the lobby manually? So:
1. Disable lobby_autostart and token_lobby_bypass (keep token_moderation)
2. Join with moderator token
3. Manually start lobby from the UI
4. Join with non-moderator token. Can you still bypass lobby with empty password?

**Comment by amsnek** [comment] 2025-02-21 10:08
@shawnchin 
I would have expected this to not work, but yes... it still allows me to enter. As long as I have a valid token (moderator: false), this seems possible. Without a token -> it results in "invalid password"

**Comment by shawnchin** [comment] 2025-02-21 10:29
Sounds like a misconfiguration on your end. If lobby is enabled, users should not be able to bypass lobby with empty password even if they have JWT token. 

If you can't work out the issue, perhaps open a topic on the forum? I don't think this closed issue is the best place to start off a new conversation thread.

**Comment by amsnek** [comment] 2025-02-21 10:49
thanks @shawnchin I guess I will do that, its already good to know that this is not intended though I fail to see any (obvious) misconfig so far.

**Comment by tomhughes** [comment] 2025-03-16 12:27
So I get how the combination of `lobby_autostart` and `token_lobby_bypass` is supposed to work but as soon as I enable `lobby_autostart` the  "wait for moderator or login" dialog stops appearing and I just get asked for a meeting password so there's no way for anybody to login and become a moderator?

**Comment by amsnek** [comment] 2025-03-17 07:41
hmm the following works for me (token moderation plugin did not). i have the following modules in use:
```
        "token_affiliation";
        "lobby_autostart";
        "token_lobby_bypass";
```

with the following token structure (role and bypass need to be in context with token_lobby_bypass), adjust as needed. 
example (long expire time)
```
{
  "sub": "meet.example.domain",
  "iss": "meet",
  "aud": "jitsijwt",
  "exp": 1839895100,
  "room": "lobybypasstestroom",
  "context": {
    "user": {
      "id": "5f03e918-e29b-2edf-8199-e252463291f2",
      "name": "Moderator",
      "moderator": true,
      "lobby_bypass": true
    }
  }
}
```

**Comment by tomhughes** [comment] 2025-03-17 08:20
My problem is that jitsi never sees the token because I never get a chance to login - normally this is what I get:

![Image](https://github.com/user-attachments/assets/f08a1b80-d441-43a2-a141-020fbe482aef)

but once I enable `lobby_autostart` that dialog stops appearing and instead the sidebar asks for a meeting password.

**Comment by amsnek** [comment] 2025-03-17 09:29
afaik the (encoded) token can only be provided in the url, like 
https://meet.example.com/lobybypasstestroom?jwt=eyJhbGciOiJIUzI1NiIs.....

without a provided token the above would be expected.

**Comment by kiber-io** [comment] 2025-04-25 22:28
Hi everyone! I also needed to automatically enable the lobby, so I put together this solution — https://github.com/jitsi-contrib/prosody-plugins/pull/42.
It doesn't require any tokens or additional mechanisms — the lobby is activated automatically after the first moderator joins the room.
