### ISSUE TITLE
A different video/audio input

### ISSUE THREAD

**Issue by Tenorio4** [jitsi/jitsi-meet#7430] opened 2020-07-31 09:24 UTC
I am developing a project in which you need to use a different video / audio input than the one that comes from default (webcam, microphone, etc). Could a file be set as a video / audio input? This file could be a video file for example.
I am using jitsi-meet and lib-jitsi-meet for the project.

**Comment by Echolon** [comment] 2020-07-31 12:43
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-07-31 12:43 UTC
Labels: quality, question
