### ISSUE TITLE
all streamers are currently busy contact support

### ISSUE THREAD

**Issue by ecappadona** [jitsi/jitsi-meet#5954] opened 2020-04-13 14:22 UTC

**Comment by luixxiul** [comment] 2020-04-15 14:38
duplicate of https://github.com/jitsi/jitsi-meet/issues/5266 ?

**Comment by Echolon** [comment] 2020-05-13 20:11
Hi,
The team is aware of recording issues. Any reports are now grouped in the pinned issue #5403.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-05-13 20:11 UTC
