### ISSUE TITLE
App crash on startup - android release build null is not an object

### ISSUE THREAD

**Issue by Rajivyadav** [jitsi/jitsi-meet#4574] opened 2019-08-25 18:50 UTC
application crash on every startup - release build only 
there are some dependency issues in latest SDK 2.2.2 
can you guys please help

---Crash logs
2019-08-26 00:13:09.434 20933-21024/? E/ReactNativeJS: null is not an object (evaluating 'n.IsAndroid')
2019-08-26 00:13:09.444 20933-21024/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
2019-08-26 00:13:09.446 20933-21024/? E/ReactNativeJS: null is not an object (evaluating 't.NativeModules.LocaleDetector.locale')
    
    --------- beginning of crash
2019-08-26 00:13:09.451 20933-21025/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.docprime.partner, PID: 20933
    com.facebook.react.common.JavascriptException: null is not an object (evaluating 'n.IsAndroid'), stack:
    <unknown>@735:85
    h@2:1670
    <unknown>@734:196
    h@2:1670
    <unknown>@733:352
    h@2:1670
    <unknown>@732:85
    h@2:1670
    <unknown>@731:85
    h@2:1670
    <unknown>@727:395
    h@2:1670
    <unknown>@724:2026
    h@2:1670
    <unknown>@560:2204
    h@2:1670
    <unknown>@559:85
    h@2:1670
    <unknown>@386:252
    h@2:1670
    <unknown>@385:2152
    h@2:1670
    <unknown>@384:85
    h@2:1670
    <unknown>@383:331
    h@2:1670
    <unknown>@382:204
    h@2:1670
    <unknown>@379:67
    h@2:1670
    <unknown>@378:30
    h@2:1670
    <unknown>@377:177
    h@2:1670
    <unknown>@376:852
    h@2:1670
    <unknown>@375:1226
    h@2:1670
    <unknown>@373:240
    h@2:1670
    <unknown>@372:3102
    h@2:1670
    <unknown>@371:85
    h@2:1670
    <unknown>@370:579
    h@2:1670
    <unknown>@369:85
    h@2:1670
    <unknown>@12:156
    h@2:1670
    <unknown>@11:30
    h@2:1670
    d@2:868
    global code@1493:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
## Current behavior
---

## Expected Behavior
---
working fine in debug but not working in release mode 

## Possible Solution
---

## Steps to reproduce
---
on startup
# Environment details
---
sdk 2.2.2

**Comment by saghul** [comment] 2019-08-26 10:02
What are you building, the SDK to embed it in an app or Jitsi Meet (the app) itself?

How exactly are you building it?

**Comment by Rajivyadav** [comment] 2019-08-27 06:59
I am adding following in build.gradle 
   implementation ('org.jitsi.react:jitsi-meet-sdk:2.2.2') {

         exclude group: 'com.facebook.react', module:'react-native-google-signin'
     exclude group: 'com.facebook.react', module:'react-native-linear-gradient'
         transitive = true }
and I am using you maven repo :
   maven{
             url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
         }

It works fine in debug but in release mode, it's crashing every time.
I am not using pro guard.

**Comment by 733** [comment] 2019-08-27 08:01
Could you guys please stop emailing me? Thanks.

Pobierz aplikacje Outlook dla systemu Android<https://aka.ms/ghei36>

________________________________

**Comment by damencho** [comment] 2019-08-27 08:08
@733 There is a button watch/unwatch click it and configure it yourself.

**Comment by saghul** [comment] 2019-08-27 08:52
Can you create a small project which reproduces this issue? I cannot reproduce it.

**Comment by saghul** [comment] 2019-09-21 17:18
No follow-up, closing.

**Closed** 2019-09-22 13:21 UTC

**Comment by hasgardee** [comment] 2020-07-24 07:33
`react-native-codepush` was causing issues for me. try disabling it. codepush bundle name is different than app.bundle I guess. So, want to make both same to run codepush and react-native-jitsi-meet

**Comment by 1Ajay** [comment] 2020-11-26 13:58
Facing the same issue.

**Comment by hemant2capgemini** [comment] 2022-06-28 03:35
Same here, I am also not using the react-native-codepush but even though app is crashing for release build. Debug build works fine.
