### ISSUE TITLE
problem with the Jitsi servers

### ISSUE THREAD

**Issue by syepesb** [jitsi/jitsi-meet#5524] opened 2020-03-31 22:30 UTC
Hello, I am experiencing a problem with the Jitsi servers when trying to record a virtual conference. I begun the recording and successfully recorded 12 minutes, which saved to the dropbox. Unfortunately the service went down temporarily and I received an error message saying "recording stop". After, the program began recording again as I heard the "recording start" prompt but upon finishing the conference the content that had been recording didn't upload to the dropbox. Is there any way to recover this data? Thank you.

**Comment by Echolon** [comment] 2020-04-10 21:12
@syepesb  please review the community portal: https://community.jitsi.org

duplicate of:

meet.jit.si recording - no audio recorded #5403 

@damencho

**Closed** 2020-04-11 03:39 UTC
