### ISSUE TITLE
Invalid constraints error in Safari

### ISSUE THREAD

**Issue by joushx** [jitsi/jitsi-meet#6704] opened 2020-05-14 10:56 UTC
## Description
When opening jitsi web, getting the video streams fails in Safari

## Current behavior
There is a error log about the constraints beeing invalid

## Expected Behavior
The constraints should be accepted and a video stream should be returned by the browser to be used in Jitsi

## Possible Solution
Remove or add properties in constrains

## Steps to reproduce
Use safari to go to meet.jit.si

# Environment details
Safari 12.1.1

cc: @jallamsetty1

**Comment by jallamsetty1** [comment] 2020-05-14 16:44
Can you please attach the console logs containing the constraints that were passed and the error reported by Safari 12.1.1 ? Unfortunately I don't have 12.1.1 and I can't reproduce this with Safari 13.1.

**Comment by joushx** [comment] 2020-05-15 13:08
```text
[Warning] 2020-05-15T12:58:12.448Z – "[modules/RTC/RTCUtils.js]" – "Failed to get access to local media. Error: Invalid constraint [object Object] " (lib-jitsi-meet.min.js, line 10)
```

```javascript
{video: {height: {ideal: 720, max: 720, min: 240}, facingMode: "user"}, audio: false}
```

**Comment by jallamsetty1** [comment] 2020-05-15 14:04
Are you running Safari on an older model of macbook ? Please check out this webkit bug- https://bugs.webkit.org/show_bug.cgi?id=210932. Looks like it is the same issue, we will be closing this issue if that is the case.

**Comment by HelloWorldUser123** [comment] 2020-05-18 05:50
Thats weird because I now have the same problem and it worked with an older jitsi version

**Comment by joushx** [comment] 2020-05-18 07:01
Yes, but stable version `4047` still works in Safari on our test iPhones, but it appears to be broken in unstable `4107`.

**Comment by jallamsetty1** [comment] 2020-05-18 22:22
@joushx , will you be able to get the console log (i.e., constraints passed for gUM) for the working case with 4047 build ? We haven't changed the video constraints so its possible that its a safari bug.

**Comment by joushx** [comment] 2020-05-26 06:49
I'm currently not able to get the logs from an iPhone. However, Safari works now when removing the `min` and `max` properties.

**Comment by jallamsetty1** [comment] 2020-06-26 13:58
Looks like webkit will have a fix for this in the next STP as per https://bugs.webkit.org/show_bug.cgi?id=210932#c28

**Comment by jallamsetty1** [comment] 2020-07-09 15:03
This issue has been fixed on meet.jit.si. I am closing this issue, please feel free to reopen it if you still see the issue.

**Closed by jallamsetty1** 2020-07-09 15:03 UTC
Labels: browser-support, web
