### ISSUE TITLE
iOS and Android not providing Screen Sharing feature

### ISSUE THREAD

**Issue by JaspreetSingh1986** [jitsi/jitsi-meet#7990] opened 2020-10-28 08:50 UTC
Hi ,

We are not getting screen sharing feature in call in both iOS and Android. What should I need to do to enable Screen share feature.

Thanks in Advance.

**Comment by saghul** [comment] 2020-10-28 08:56
All you can do is wait. We are working on it.

**Comment by JoshuaDietz** [comment] 2020-11-10 22:54
Duplicate of  #5252

**Closed** 2020-11-11 08:44 UTC
Labels: android, feature-request, ios, mobile
