### ISSUE TITLE
web cam

### ISSUE THREAD

**Issue by giannny408** [jitsi/jitsi-meet#5492] opened 2020-03-30 16:26 UTC
non riesco ad aprire la webcam

**Comment by alexanderadam** [comment] 2020-03-31 08:06
1. Se possibile, dovresti comunicare in inglese.
2. Puoi provare https://test.webrtc.org/ e vedere che funziona lì?
3. Questo è probabilmente un duplicato di #5155

<hr>

1. If possible, try to communicate in English
2. Can you try whether your camera works at https://test.webrtc.org/?
3. This is probably a duplicate of #5155

/cc @saghul maybe it would make sense to make a sticky issue regarding Webcam issues? Otherwise all those duplicates will continue popping up…

**Comment by saghul** [comment] 2020-03-31 08:09
Good call @alexanderadam I had never used pinnedd issssues before. Pinned https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by alexanderadam** [comment] 2020-03-31 08:10
@saghul you also might want to add the missing 'o' in the title (non-w_o_rking) :wink:

**Comment by saghul** [comment] 2020-03-31 08:11
🤦‍♂

**Comment by alexanderadam** [comment] 2020-03-31 08:12
Perfect :+1:

**Comment by Echolon** [comment] 2020-04-10 20:22
@saghul I favor of #5425 I would also close all the listed issues to clean up the repo

**Closed** 2020-05-12 13:33 UTC
Labels: duplicate
