### ISSUE TITLE
resolution does not scale up under certain conditions

### ISSUE THREAD

**Issue by netFLOw95** [jitsi/jitsi-meet#14501] opened 2024-03-19 15:10 UTC
### Description:

If you are viewing a screen share and multiple cameras from other participants and pin the camera from the person who shares his screen, the resolution stays at 180p and doesn´t scale up. If you pin a camera from another participant (which is not sharing his screen) the resolution scales up.

### Steps to reproduce:

1. Start a meeting with three participants
2. One participant is sharing his screen and has hits camera enabled. The second participant only enables his camera.
3. If the third participant pins the camera from the screen share participant the resolution stays low
4. If the third participant pins the camera from the participant without screen share the resolution scales up

### Expected behavior:

Also scale up the resolution from the participant with screen share. This was also the case in the older versions.

### Actual behavior:

The resolution stays low when pinning the screen share participant.

![image](https://github.com/jitsi/jitsi-meet/assets/109732076/7eec98b7-f03f-4b52-b456-842c2276cee6)
![image](https://github.com/jitsi/jitsi-meet/assets/109732076/34b6c5ba-4712-4c6e-8ccd-925f86ad3d4c)

### Server information:

- Jitsi Meet version: 9364 (with VP8)
- Operating System: RHEL8

### Client information:

- Browser / app version: Chrome 122
- Operating System: Windows 10

### Additional information:

Only occurs with version 9364, VP8 and Chrome

**Comment by jallamsetty1** [comment] 2024-03-19 15:34
@netFLOw95 Can you please share the browser console logs for the participant sharing the screen? A fix for this issue was included in stable version 9364. I am not able to reproduce this issue.

**Comment by netFLOw95** [comment] 2024-03-20 09:00
[console.log](https://github.com/jitsi/jitsi-meet/files/14663953/console.log)

**Comment by jallamsetty1** [comment] 2024-03-20 14:10
```
Logger.js:155 2024-03-20T08:53:38.019Z [modules/RTC/TraceablePeerConnection.js] <rl._updateVideoSenderEncodings>:  TPC[id=1,type=JVB] setting max height=180,encodings=[{"active":true,"adaptivePtime":false,"networkPriority":"low","priority":"low","scaleResolutionDownBy":4,"maxBitrate":200000},{"active":false,"adaptivePtime":false,"networkPriority":"low","priority":"low","scaleResolutionDownBy":2,"maxBitrate":500000},{"active":false,"adaptivePtime":false,"networkPriority":"low","priority":"low","scaleResolutionDownBy":1,"maxBitrate":1500000}]
Logger.js:155 2024-03-20T08:53:27.698Z [modules/RTC/BridgeChannel.js] <Fa.sendSourceVideoTypeMessage>:  Sending SourceVideoTypeMessage with video type **31c9db58-v0: desktop**
Logger.js:155 2024-03-20T08:53:38.020Z [modules/RTC/BridgeChannel.js] <Fa.sendSourceVideoTypeMessage>:  Sending SourceVideoTypeMessage with video type **31c9db58-v1: camera**
```

It appears that the bridge is requesting only 180p for the camera track , source 31c9db58-v1 as seen in the logs above. Are you sure the camera tile is pinned on the receiver? Maybe there is something wrong with the receiver constraints sent by the participants viewing the share?

**Comment by netFLOw95** [comment] 2024-03-21 09:56
I know figured out, that the issue only occurs when you start screen sharing before enabling the camera.
So in summary:
- Sender enables screen sharing, sender enables camera, receiver is pinning the camera --> Problem
- Sender enables camera, sender enables screen sharing, receiver is pinning the camera --> No problem

**Comment by jallamsetty1** [comment] 2024-03-21 19:36
@netFLOw95 Unfortunately I don't reproduce the issue if the sender enables screensharing first.

**Comment by netFLOw95** [comment] 2024-03-22 08:49
I can know also reproduce it via https://meet.jit.si/DasIstEinTest#config.videoQuality.codecPreferenceOrder=["VP8"]&config.p2p.codecPreferenceOrder=["VP8"]

**Comment by jallamsetty1** [comment] 2024-03-22 15:45
Thanks, I am able to repro it now. Looking into it.

**Closed** 2024-03-22 19:37 UTC
