### ISSUE TITLE
transmission in youtube gives error repeatedly

### ISSUE THREAD

**Issue by midebort** [jitsi/jitsi-meet#6102] opened 2020-04-16 15:52 UTC
I tried to begin transmission in youtube and gives error repeatedly.
can this be solved?

If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.

**Comment by luixxiul** [comment] 2020-04-16 16:00
See #5403 and close this issue, if you find a duplicate there. If you cannot find, please provide additional information here so that the team could investigate. Steps to reproduce the issue is very appreciated.

**Closed** 2020-04-16 16:02 UTC
