### ISSUE TITLE
Mic doesn't work in Safari when muted while joining the room

### ISSUE THREAD

**Issue by jhartmann44** [jitsi/jitsi-meet#10276] opened 2021-10-28 06:57 UTC
Hello everyone!
When I use the option starWithAudioMuted and join the room with Safari, I can't enable the microphone. I can still klick the button to enable it and it also shows me that I'm unmuted but for everyone else I'm muted.
If I join the room without the startWithAudioMuted option and my mic is enabled from start on, everyone can hear me. It is also not possible to switch the mic, if I do so everyone else can't hear me again. 
You can only prevent this when your mic is enabled from start on.

I also found the same problem on mee.jit.si.
There is no startWithAudioMuted enabled but if you get to the prejoin page and mute yourself first and then join the session, you wont be able to activate your mic again.

Please fix this, it is really annoying, thank you!

**Comment by jallamsetty1** [comment] 2021-11-01 14:26
@jhartmann44 I followed the exact same steps on Safari 15.0 and macOS 11.6 and here is what I see
1. User joins audio muted in pre-join and unmutes themselves - works fine on meet.jit.si. Are you seeing this issue on meet.jit.si ? A fix was deployed recently to address this. If you still see it there, can you please let me know what mic you have selected ? A system default one or a non-preferred device ?
2. Join the call with audio unmuted and changing the mic during the call doesn't work - I am able to reproduce this. The browser is throwing a `A MediaStreamTrack ended due to a capture failure error` when we are trying to capture an audio stream from a different device. I will look into why this is happening.

**Comment by jallamsetty1** [comment] 2021-12-13 15:39
Closing this as it has been fixed/

**Closed by jallamsetty1** 2021-12-13 15:39 UTC
