### ISSUE TITLE
Don't always mute when a youtube video is playing

### ISSUE THREAD

**Issue by dani** [jitsi/jitsi-meet#6390] opened 2020-04-26 11:36 UTC
When sharing a youtube video, every participant gets muted. This makes sens to prevent feedback loop (see Bug #2540).

But while the video is playing, if a participant manually unmute its mic, it'll be backed to muted a few seconds later. This shouldn't be the case. For example, the youtube volume could be low enough to prevent feedback loop, or the participant could be using a headphone.

Muting when the video starts is the correct behavior, but it should be possible to unmute manually while a youtube video is playing.

**Comment by AndreasGassmann** [comment] 2020-05-09 22:13
I agree with this suggestion. If watching a video with a group of friends it's basically impossible for anyone to comment on what is happening. The whole youtube-watching-experience is weird overall (the video also seems to get muted if you unmute yourself?). The feedback loop shouldn't be a problem if people are using headphones.

**Comment by oxytu** [comment] 2020-05-10 05:34
I also agree, the current functionality is not useful (not to say distracting and not understandable from a user point of view) and I also would vote for people using their headphones. Muting for the first time might be a good thing to do though.

**Comment by cosmokak** [comment] 2020-05-25 03:37
Made a GitHub account just to chime in and let the Jitsi team that this needs to be fixed. I am using the browser version. Should be easy to add a setting to toggle on/off 'Auto mute mic during YouTube sharing' or something similar. This is an unfortunate drawback as it severely limits the usefulness of the YouTube streaming feature. What is the point of watching a video together in a conference if you're prohibited from speaking to each other about said video? Otherwise great platform.

More generally, it's 2020 - it should be the host's and participants' duty to manage feedback, not the software.

**Comment by luixxiul** [comment] 2020-05-25 04:30
> Should be easy to add a setting

Any contribution would be appreciated :-)

Seriously, the dev team is working on stuff based on priorities, and the fact that this issue has not been addressed tells that for the team this issue is a low-priority *compared to other issues*.

**Comment by cosmokak** [comment] 2020-05-25 05:04
> 
> 
> > Should be easy to add a setting
> 
> Any contribution would be appreciated :-)
> 
> Seriously, the dev team is working on stuff based on priorities, and the fact that this issue has not been addressed tells that for the team this issue is a low-priority _compared to other issues_.

Honored you have singled out this one comment on a seemingly widespread issue! 

I am sure there are many things to work on, but frankly that's not my problem. This issue is fixed by removing code that doesn't seem to be working as intended, which would seem to me the easiest of all bugs to fix.

**Comment by luixxiul** [comment] 2020-05-25 05:13
> that's not my problem.

Well, please wait then until the team eventually picks up the issue.

> This issue is fixed by removing code that doesn't seem to be working as intended, which would seem to me the easiest of all bugs to fix.

Well, developing a software does not work like that way, sorry.

**Comment by saghul** [comment] 2020-11-27 15:00
Closing, we consider this to be working as intended.

**Closed by saghul** 2020-11-27 15:00 UTC
Labels: web

**Comment by AndreasGassmann** [comment] 2020-11-28 00:13
@saghul Could you elaborate which aspect of this "feature" makes any sense?

This was the 6th most upvoted issue overall before it was closed, so it's clear that many people disagree with the way it currently works.

I can understand if it's not a priority for you or if you don't have the resources to work on it, but I can't understand a "working as intended" response. An overwhelming majority of people want this feature changed. In fact, there is not a single person/argument in this whole thread in support of the current behaviour.

To be quite frank, the youtube sharing feature is completely unusable at the moment. We stopped using it entirely and instead just share the link in the chat so everyone has to watch it by themselves.

**Comment by oxytu** [comment] 2020-11-28 07:40
I second the comment of @AndreasGassmann. For me this is the only annoying thing in a product that is really great, I use regularly and has (except this) every feature I want.

**Comment by northivanastan** [comment] 2020-12-19 20:48
Even if muting participants is intended (though I wouldn't understand why) I think there's definitely some odd behaviour with this feature:

1. I can unmute myself while a YouTube video is being presented, but it mutes the YouTube video, and then automatically mutes me again after a few seconds.
2. If I talk, the "You are muted" popup appears, and clicking Unmute there lets me talk over the video briefly, but I'm sometimes muted again after a few seconds.

If the intended behaviour is that participants should be completely unable to talk over a video - and again, that would not make any sense - then should that be reported as a separate bug?
