### ISSUE TITLE
Allow browser's Copy Link Address context menu to copy the Call Info Link

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2765] opened 2018-04-07 23:39 UTC
On https://meet.jit.si/... the circle i button shows Call Info: Link meet.jit.si...
1. Say http or https
2. Allow browser's Copy Link context menu to copy it.

**Comment by saghul** [comment] 2018-04-08 11:39
Sounds good to me. /cc @virtuacoplenny maybe?

**Comment by virtuacoplenny** [comment] 2018-04-08 15:31
The http/https part was removed by design. I'll add the Copy Link...

**Comment by saghul** [comment] 2018-04-10 07:42
Fixed in https://github.com/jitsi/jitsi-meet/pull/2770

**Closed by saghul** 2018-04-10 07:42 UTC
