### ISSUE TITLE
Share a PeerTube Video

### ISSUE THREAD

**Issue by rg-artcom** [jitsi/jitsi-meet#8130] opened 2020-11-21 15:40 UTC
Instead of "Share a Youtube Video" I would like to have a menu item "Share a Peertube Video"

See also https://joinpeertube.org/

**Comment by heikar** [comment] 2020-11-22 17:23
Many video producers also work with vimeo.
It would be nice, if there be an interface to add (in a config file) additional video platforms (e.g. PeerTube or vimeo).

**Comment by Aspie96** [comment] 2020-12-02 17:57
I agree, it would be great to support more platforms.

**Comment by saghul** [comment] 2020-12-02 19:07
Duplicate of #7601

**Closed** 2020-12-02 19:07 UTC
Labels: feature-request
