### ISSUE TITLE
Add a mute button to the Android app

### ISSUE THREAD

**Issue by sebastienaubry** [jitsi/jitsi-meet#7205] opened 2020-07-01 10:21 UTC
Hi,
I would like to see a "Mute" button to the Andoid app, in order, for instance, to be able to receive a phone call during a JitSi meeting.
Thanks

**Comment by Echolon** [comment] 2020-07-01 20:46
@sebastienaubry can you please provide a screenshot of your interface, because I have a mute button in my app.

**Comment by sebastienaubry** [comment] 2020-07-01 21:12
Here it is.[
![Screenshot_Jitsi Meet](https://user-images.githubusercontent.com/41120158/86292077-5755b000-bbf0-11ea-83fc-a60dc10ca938.jpg)
](url)

**Comment by Echolon** [comment] 2020-07-01 21:21
Okay thank you.

But there is a mute button? (the one with the microphone?)

**Comment by sebastienaubry** [comment] 2020-07-01 21:32
I do not want to mute myself; I want to mute the others (or the application sound), in order to be able to have several calls at the same time.

**Comment by Echolon** [comment] 2020-07-02 05:42
Okay I see and I understand now.

I have several thoughts why I think this is maybe out of scope for Jitsi:

- I think it is more or less not senseful (or polite) to switch between several meetings and calls at the same time. But okay - I don't want to interfere with our buisness.

- Still I think it is a bare case. Almost every user will not have that case often. You also may can call people back and just prioritize. At least thats what I do and I think is a common and accepted situation nowadays.

- I wonder if that must be an Android feature(?).

What do you think?
@damencho @saghul 

____
Community-support, not directly affiliated with Jitsi Meet.

**Comment by sebastienaubry** [comment] 2020-07-02 05:59
Hi,
Here is the use case:
* I am in a JitSi meeting
* I receive an incoming phone call
* I tell the JitSi meeting attendees that I have to answer this call and that I will get back quickly
* I mute my microphone in JitSi, get the call
* Then I hear both the JitSi meeting and the call :-(
* I have to leave the JitSi meeting in order to hear the call properly

This is why I would like to "pause" the JitSi meeting without leaving it.

Thanks

**Comment by wjbuys** [comment] 2020-07-07 00:33
I also have a use case for muting other participants locally. In the desktop/web interface, there is a volume slider to adjust the local volume of each participant, but in the Android and iOS apps, there is not.

My use case is using an extra mobile device as camera (without audio), while using the significantly higher quality audio from my desktop for a virtual piano lesson. In this case, if I'm unable to locally mute the audio from my desktop on my mobile device. Without the ability to mute locally, I get an echo or worse, howling feedback.

**Comment by saghul** [comment] 2020-07-07 07:00
What you are asking for is really call hold. We don't support that yet. We can only support that use case with ConnectionService integration. Alas, it proved to be quite buggy in practice (maybe because we used the self-managed version) so we had to disable it.

**Comment by sebastienaubry** [comment] 2020-07-07 07:16
We just want to be able to mute the audio from the application (make it silent), like we would on a Firefox tab for instance.

**Comment by saghul** [comment] 2020-07-07 08:26
We need to do this in a mobile native way, as I said above.

**Comment by TBG-FR** [comment] 2020-07-07 21:47
@saghul Any clue about how to support ConnectionService in a better way ? I'd be glad to contribute. I disabled it as well in my app, but I was pretty sure that kind of feature (and possibly some others) would be related to that integration, so if a better way to do it exist, I'd be glad to try

**Comment by TBG-FR** [comment] 2020-10-10 09:48
Still active, AFAIK.

**Comment by lma-gh** [comment] 2021-05-23 08:13
Although I am thankful for the existence of Jitsi Meet for Android, I am absolutely baffled regarding the lack of some IMHO very basic functionality (and the ... errr ... sub-optimal UI, but other bug reports already deal with (part of) that).
.
There are enough everyday use cases that need a solution on app level, not on Android level, and the same app solution is more than good enough for most cases where you suggested an Android level solution:

- User X has audio I don't want to hear (snoring, a loud coffee machine, sex sounds, a book or movie spoiler, ...). Solution: locally mute user X.

- User Y has posted a link to a short video in the chat, and I want to watch (and hear!) it without the other users' voices rendering the video's audio unintelligble. Solution: Deafen myself for the duration of the video.

- I'm in a conference in hands-free mode (using the devices loudspeaker), when suddenly the door opens and my roommate needs a question answered urgently, but we cannot concentrate on this real-life chat, because the conference participants are talking, too. Solution: Deafen myself shortly.

In above use cases where I deafen myself, I might still want to hear the sounds of my anti-tinnitus app in the background, because otherwise my tinnitus is too distracting. This means a "Deafen" button in the app, not something on Android level.
.
E.g. mumble offers both "deafen" and "locally mute others" (alongside "mute myself"), and both features are used regularly in my "mumble circles".

**Comment by chrysn** [comment] 2021-06-14 07:42
I'd like to add another class of use cases, and an implementatio point to this discussion:

I'm frequently in calls where two people in the same physical room participate in the same call but need distinct video feeds (because they can't sit next to each other because one has [confidential material](https://en.wikipedia.org/wiki/Dungeon_Master) on their screen). Having two audio devices in such a setup leads to the expected complications -- so one of the participating devices does audio with an omnidirectional mike, and the other mutes out.

Different but practically analogous setups occur too, eg. when I use a tablet for video in/out with the other participants, next to a laptop from which I share screen.

I agree with @Echolon that there *could* or even *should* be an Android feature to mute the device or even the app, but there ain't (at least on Android 7.1 (compatible; LineageOS)). Apps can't be muted selectively, and unlike the media volume (which can be turned down to zero), the in-call volume (through which Jitsi produces sound, which seems like the right decision in general) can not be turned to zero in Android. Thus, the app is the only practical place to introduce a "mute audio out" functionality.

Currently, I employ one of two workarounds:
* I use the web app on a PC rather than the Android app (which is a pity given that my Android tablet has the best video around) (there, tabs can be muted, and audio can be muted fully in the audio stack), or
* I insert a 3.5mm to 6.53mm TRS adapter into the Android device, tricking it to redirect audio. This is a crude hack.

**Comment by deliciouslytyped** [comment] 2021-08-15 21:29
Thanks for the TRRS suggestion, it was almost a workaround for me, until I realized I don't have a jack, nor do I have any USB-C earbuds.

I think the lack of this functionality is not a problem if you don't need it, but it's very painful when you do. I'm using two devices near each other and I can't stop the feedback.

Implementation-wise, unless there is something strange in the internals - why would you need to use an android API? "Just" add a speaker icon that gets crossed out when you are deafened, and zero the sound output or whatever. The cross-linked issue above has a nicer description.

**Comment by deliciouslytyped** [comment] 2021-08-16 18:44
I am currently six failure nodes deep in trying to mute my phone.

I went out to buy either a USB-C to TRRS adapter today, to do the above workaround.
I cycled around half the city and only found an adapter in one place.
The doesn't work, because it turns out a lot of androids are compiled without support for passive adapters.
Active adapters are more expensive, if you can even find one.
Some phones don't even report an error.
(Some do, which is how I managed to figure out what the problem is.)
USB C earbuds are also expensive.

**Comment by aymanayyad19** [comment] 2022-02-14 11:48
Device: Physical Device  
Android Version: 10
Used Service: Jitsi Meet SDK (Android)
Log Error :

E/JitsiMeetLogger: [modules/xmpp/moderator.js] Focus error, retry after 1000 { _nsMap: { '': 'jabber:client' },
E/JitsiMeetLogger:   attributes: 
E/JitsiMeetLogger:    { '0': 
E/JitsiMeetLogger:       { ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'xmlns',
E/JitsiMeetLogger:         name: 'xmlns',
E/JitsiMeetLogger:         namespaceURI: 'http://www.w3.org/2000/xmlns/',
E/JitsiMeetLogger:         specified: true,
E/JitsiMeetLogger:         localName: 'xmlns',
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 152,
E/JitsiMeetLogger:         nodeValue: 'jabber:client',
E/JitsiMeetLogger:         value: 'jabber:client',
E/JitsiMeetLogger:         ownerElement: [Circular] },
E/JitsiMeetLogger:      '1': 
E/JitsiMeetLogger:       { ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'type',
E/JitsiMeetLogger:         name: 'type',
E/JitsiMeetLogger:         namespaceURI: undefined,
E/JitsiMeetLogger:         specified: true,
E/JitsiMeetLogger:         localName: 'type',
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 173,
E/JitsiMeetLogger:         nodeValue: 'error',
E/JitsiMeetLogger:         value: 'error',
E/JitsiMeetLogger:         ownerElement: [Circular] },
E/JitsiMeetLogger:      '2': 
E/JitsiMeetLogger:       { ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'from',
E/JitsiMeetLogger:         name: 'from',
E/JitsiMeetLogger:         namespaceURI: undefined,
E/JitsiMeetLogger:         specified: true,
E/JitsiMeetLogger:         localName: 'from',
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 186,
E/JitsiMeetLogger:         nodeValue: 'focus.jitsi.ethelcare.com',
E/JitsiMeetLogger:         value: 'focus.jitsi.ethelcare.com',
E/JitsiMeetLogger:         ownerElement: [Circular] },
E/JitsiMeetLogger:      '3': 
E/JitsiMeetLogger:       { ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'id',
E/JitsiMeetLogger:         name: 'id',
E/JitsiMeetLogger:         namespaceURI: undefined,
E/JitsiMeetLogger:         specified: true,
E/JitsiMeetLogger:         localName: 'id',
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 217,
E/JitsiMeetLogger:         nodeValue: '4540509d-2dd2-4279-bf00-11dcb5d96e84:sendIQ',
E/JitsiMeetLogger:         value: '4540509d-2dd2-4279-bf00-11dcb5d96e84:sendIQ',
E/JitsiMeetLogger:         ownerElement: [Circular] },
E/JitsiMeetLogger:      '4': 
E/JitsiMeetLogger:       { ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'to',
E/JitsiMeetLogger:         name: 'to',
E/JitsiMeetLogger:         namespaceURI: undefined,
E/JitsiMeetLogger:         specified: true,
E/JitsiMeetLogger:         localName: 'to',
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 266,
E/JitsiMeetLogger:         nodeValue: '966c8872-69ce-43c7-a78c-51edf4994e08@jitsi.ethelcare.com/wh9dAodb',
E/JitsiMeetLogger:         value: '966c8872-69ce-43c7-a78c-51edf4994e08@jitsi.ethelcare.com/wh9dAodb',
E/JitsiMeetLogger:         ownerElement: [Circular] },
E/JitsiMeetLogger:      _ownerElement: [Circular],
E/JitsiMeetLogger:      length: 5 },
E/JitsiMeetLogger:   childNodes: 
E/JitsiMeetLogger:    { '0': 
E/JitsiMeetLogger:       { _nsMap: {},
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'error',
E/JitsiMeetLogger:         tagName: 'error',
E/JitsiMeetLogger:         namespaceURI: 'jabber:client',
E/JitsiMeetLogger:         localName: 'error',
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         previousSibling: null,
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 334,
E/JitsiMeetLogger:         firstChild: [Object],
E/JitsiMeetLogger:         lastChild: [Object] },
E/JitsiMeetLogger:      length: 1 },
E/JitsiMeetLogger:   ownerDocument: 
E/JitsiMeetLogger:    { implementation: { _features: {} },
E/JitsiMeetLogger:      childNodes: { '0': [Object], length: 1 },
E/JitsiMeetLogger:      doctype: null,
E/JitsiMeetLogger:      documentURI: undefined,
E/JitsiMeetLogger:      documentElement: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         ownerDocument: [Circular],
E/JitsiMeetLogger:         nodeName: 'body',
E/JitsiMeetLogger:         tagName: 'body',
E/JitsiMeetLogger:         namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger:         localName: 'body',
E/JitsiMeetLogger:         previousSibling: null,
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 1,
E/JitsiMeetLogger:         firstChild: [Circular],
E/JitsiMeetLogger:         lastChild: [Object] },
E/JitsiMeetLogger:      firstChild: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         ownerDocument: [Circular],
E/JitsiMeetLogger:         nodeName: 'body',
E/JitsiMeetLogger:         tagName: 'body',
E/JitsiMeetLogger:         namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger:         localName: 'body',
E/JitsiMeetLogger:         previousSibling: null,
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 1,
E/JitsiMeetLogger:         firstChild: [Circular],
E/JitsiMeetLogger:         lastChild: [Object] },
E/JitsiMeetLogger:      lastChild: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         ownerDocument: [Circular],
E/JitsiMeetLogger:         nodeName: 'body',
E/JitsiMeetLogger:         tagName: 'body',
E/JitsiMeetLogger:         namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger:         localName: 'body',
E/JitsiMeetLogger:         previousSibling: null,
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 1,
E/JitsiMeetLogger:         firstChild: [Circular],
E/JitsiMeetLogger:         lastChild: [Object] },
E/JitsiMeetLogger:      _inc: 35 },
E/JitsiMeetLogger:   nodeName: 'iq',
E/JitsiMeetLogger:   tagName: 'iq',
E/JitsiMeetLogger:   namespaceURI: 'jabber:client',
E/JitsiMeetLogger:   localName: 'iq',
E/JitsiMeetLogger:   parentNode: 
E/JitsiMeetLogger:    { _nsMap: 
E/JitsiMeetLogger:       { '': 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger:         stream: 'http://etherx.jabber.org/streams' },
E/JitsiMeetLogger:      attributes: 
E/JitsiMeetLogger:       { '0': [Object],
E/JitsiMeetLogger:         '1': [Object],
E/JitsiMeetLogger:         '2': [Object],
E/JitsiMeetLogger:         _ownerElement: [Circular],
E/JitsiMeetLogger:         length: 3 },
E/JitsiMeetLogger:      childNodes: { '0': [Circular], '1': [Object], '2': [Object], length: 2 },
E/JitsiMeetLogger:      ownerDocument: 
E/JitsiMeetLogger:       { implementation: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         doctype: null,
E/JitsiMeetLogger:         documentURI: undefined,
E/JitsiMeetLogger:         documentElement: [Circular],
E/JitsiMeetLogger:         firstChild: [Circular],
E/JitsiMeetLogger:         lastChild: [Circular],
E/JitsiMeetLogger:         _inc: 35 },
E/JitsiMeetLogger:      nodeName: 'body',
E/JitsiMeetLogger:      tagName: 'body',
E/JitsiMeetLogger:      namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger:      localName: 'body',
E/JitsiMeetLogger:      previousSibling: null,
E/JitsiMeetLogger:      nextSibling: null,
E/JitsiMeetLogger:      parentNode: 
E/JitsiMeetLogger:       { implementation: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         doctype: null,
E/JitsiMeetLogger:         documentURI: undefined,
E/JitsiMeetLogger:         documentElement: [Circular],
E/JitsiMeetLogger:         firstChild: [Circular],
E/JitsiMeetLogger:         lastChild: [Circular],
E/JitsiMeetLogger:         _inc: 35 },
E/JitsiMeetLogger:      lineNumber: 1,
E/JitsiMeetLogger:      columnNumber: 1,
E/JitsiMeetLogger:      firstChild: [Circular],
E/JitsiMeetLogger:      lastChild: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'iq',
E/JitsiMeetLogger:         tagName: 'iq',
E/JitsiMeetLogger:         namespaceURI: 'jabber:client',
E/JitsiMeetLogger:         localName: 'iq',
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         previousSibling: [Circular],
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 529,
E/JitsiMeetLogger:         firstChild: [Object],
E/JitsiMeetLogger:         lastChild: [Object] } },
E/JitsiMeetLogger:   previousSibling: null,
E/JitsiMeetLogger:   nextSibling: 
E/JitsiMeetLogger:    { _nsMap: { '': 'jabber:client' },
E/JitsiMeetLogger:      attributes: 
E/JitsiMeetLogger:       { '0': [Object],
E/JitsiMeetLogger:         '1': [Object],
E/JitsiMeetLogger:         '2': [Object],
E/JitsiMeetLogger:         '3': [Object],
E/JitsiMeetLogger:         '4': [Object],
E/JitsiMeetLogger:         _ownerElement: [Circular],
E/JitsiMeetLogger:         length: 5 },
E/JitsiMeetLogger:      childNodes: { '0': [Object], length: 1 },
E/JitsiMeetLogger:      ownerDocument: 
E/JitsiMeetLogger:       { implementation: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         doctype: null,
E/JitsiMeetLogger:         documentURI: undefined,
E/JitsiMeetLogger:         documentElement: [Object],
E/JitsiMeetLogger:         firstChild: [Object],
E/JitsiMeetLogger:         lastChild: [Object],
E/JitsiMeetLogger:         _inc: 35 },
E/JitsiMeetLogger:      nodeName: 'iq',
E/JitsiMeetLogger:      tagName: 'iq',
E/JitsiMeetLogger:      namespaceURI: 'jabber:client',
E/JitsiMeetLogger:      localName: 'iq',
E/JitsiMeetLogger:      parentNode: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'body',
E/JitsiMeetLogger:         tagName: 'body',
E/JitsiMeetLogger:         namespaceURI: 'http://jabber.org/protocol/httpbind',
E/JitsiMeetLogger:         localName: 'body',
E/JitsiMeetLogger:         previousSibling: null,
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         parentNode: [Object],
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 1,
E/JitsiMeetLogger:         firstChild: [Circular],
E/JitsiMeetLogger:         lastChild: [Circular] },
E/JitsiMeetLogger:      previousSibling: [Circular],
E/JitsiMeetLogger:      nextSibling: null,
E/JitsiMeetLogger:      lineNumber: 1,
E/JitsiMeetLogger:      columnNumber: 529,
E/JitsiMeetLogger:      firstChild: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: {},
E/JitsiMeetLogger:         ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'query',
E/JitsiMeetLogger:         tagName: 'query',
E/JitsiMeetLogger:         namespaceURI: 'http://jabber.org/protocol/disco#info',
E/JitsiMeetLogger:         localName: 'query',
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         previousSibling: null,
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 722 },
E/JitsiMeetLogger:      lastChild: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: {},
E/JitsiMeetLogger:         ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'query',
E/JitsiMeetLogger:         tagName: 'query',
E/JitsiMeetLogger:         namespaceURI: 'http://jabber.org/protocol/disco#info',
E/JitsiMeetLogger:         localName: 'query',
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         previousSibling: null,
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 722 } },
E/JitsiMeetLogger:   lineNumber: 1,
E/JitsiMeetLogger:   columnNumber: 142,
E/JitsiMeetLogger:   firstChild: 
E/JitsiMeetLogger:    { _nsMap: {},
E/JitsiMeetLogger:      attributes: { '0': [Object], _ownerElement: [Circular], length: 1 },
E/JitsiMeetLogger:      childNodes: { '0': [Object], '1': [Object], '2': [Object], length: 3 },
E/JitsiMeetLogger:      ownerDocument: 
E/JitsiMeetLogger:       { implementation: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         doctype: null,
E/JitsiMeetLogger:         documentURI: undefined,
E/JitsiMeetLogger:         documentElement: [Object],
E/JitsiMeetLogger:         firstChild: [Object],
E/JitsiMeetLogger:         lastChild: [Object],
E/JitsiMeetLogger:         _inc: 35 },
E/JitsiMeetLogger:      nodeName: 'error',
E/JitsiMeetLogger:      tagName: 'error',
E/JitsiMeetLogger:      namespaceURI: 'jabber:client',
E/JitsiMeetLogger:      localName: 'error',
E/JitsiMeetLogger:      parentNode: [Circular],
E/JitsiMeetLogger:      previousSibling: null,
E/JitsiMeetLogger:      nextSibling: null,
E/JitsiMeetLogger:      lineNumber: 1,
E/JitsiMeetLogger:      columnNumber: 334,
E/JitsiMeetLogger:      firstChild: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: {},
E/JitsiMeetLogger:         ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'not-acceptable',
E/JitsiMeetLogger:         tagName: 'not-acceptable',
E/JitsiMeetLogger:         namespaceURI: 'urn:ietf:params:xml:ns:xmpp-stanzas',
E/JitsiMeetLogger:         localName: 'not-acceptable',
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         previousSibling: null,
E/JitsiMeetLogger:         nextSibling: [Object],
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 355 },
E/JitsiMeetLogger:      lastChild: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: {},
E/JitsiMeetLogger:         ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'session-invalid',
E/JitsiMeetLogger:         tagName: 'session-invalid',
E/JitsiMeetLogger:         namespaceURI: 'http://jitsi.org/protocol/focus',
E/JitsiMeetLogger:         localName: 'session-invalid',
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         previousSibling: [Object],
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 458 } },
E/JitsiMeetLogger:   lastChild: 
E/JitsiMeetLogger:    { _nsMap: {},
E/JitsiMeetLogger:      attributes: { '0': [Object], _ownerElement: [Circular], length: 1 },
E/JitsiMeetLogger:      childNodes: { '0': [Object], '1': [Object], '2': [Object], length: 3 },
E/JitsiMeetLogger:      ownerDocument: 
E/JitsiMeetLogger:       { implementation: [Object],
E/JitsiMeetLogger:         childNodes: [Object],
E/JitsiMeetLogger:         doctype: null,
E/JitsiMeetLogger:         documentURI: undefined,
E/JitsiMeetLogger:         documentElement: [Object],
E/JitsiMeetLogger:         firstChild: [Object],
E/JitsiMeetLogger:         lastChild: [Object],
E/JitsiMeetLogger:         _inc: 35 },
E/JitsiMeetLogger:      nodeName: 'error',
E/JitsiMeetLogger:      tagName: 'error',
E/JitsiMeetLogger:      namespaceURI: 'jabber:client',
E/JitsiMeetLogger:      localName: 'error',
E/JitsiMeetLogger:      parentNode: [Circular],
E/JitsiMeetLogger:      previousSibling: null,
E/JitsiMeetLogger:      nextSibling: null,
E/JitsiMeetLogger:      lineNumber: 1,
E/JitsiMeetLogger:      columnNumber: 334,
E/JitsiMeetLogger:      firstChild: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: {},
E/JitsiMeetLogger:         ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'not-acceptable',
E/JitsiMeetLogger:         tagName: 'not-acceptable',
E/JitsiMeetLogger:         namespaceURI: 'urn:ietf:params:xml:ns:xmpp-stanzas',
E/JitsiMeetLogger:         localName: 'not-acceptable',
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         previousSibling: null,
E/JitsiMeetLogger:         nextSibling: [Object],
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 355 },
E/JitsiMeetLogger:      lastChild: 
E/JitsiMeetLogger:       { _nsMap: [Object],
E/JitsiMeetLogger:         attributes: [Object],
E/JitsiMeetLogger:         childNodes: {},
E/JitsiMeetLogger:         ownerDocument: [Object],
E/JitsiMeetLogger:         nodeName: 'session-invalid',
E/JitsiMeetLogger:         tagName: 'session-invalid',
E/JitsiMeetLogger:         namespaceURI: 'http://jitsi.org/protocol/focus',
E/JitsiMeetLogger:         localName: 'session-invalid',
E/JitsiMeetLogger:         parentNode: [Circular],
E/JitsiMeetLogger:         previousSibling: [Object],
E/JitsiMeetLogger:         nextSibling: null,
E/JitsiMeetLogger:         lineNumber: 1,
E/JitsiMeetLogger:         columnNumber: 458 } } }

**Closed** 2022-02-14 16:36 UTC
Labels: feature-request, mobile, confirmed, android, quality

**Comment by JonasGilg** [comment] 2022-03-27 09:24
I have another use case. Today we held a presentation, where one user gave a PowerPoint presentation on a desktop and I moderated the session from my tablet next to him. 

We wanted the audio output from the computer, since it has a better quality than my tablet speakers. Sadly I was unable to turn the sound on my tablet off and we didn't have anything to plug into the tablet for the workaround.

It is really annoying, since this is something we want to do more often.

**Comment by maksudur-rahman** [comment] 2023-06-19 11:25
> We need to do this in a mobile native way, as I said above.

@saghul can you provide any solutions regarding conference hold or mute audio of the conference, Because it's annoying to hear both the JitSi meeting and the call.

**Comment by saghul** [comment] 2023-06-19 11:33
We don't have a solution for that, sorry.
