### ISSUE TITLE
Unable to start meeting muted: startWithVideoMuted: true and startWithAudioMuted: true, options are ignored in latest build.

### ISSUE THREAD

**Issue by migonr77** [jitsi/jitsi-meet#8462] opened 2021-01-22 15:10 UTC
### Description:

Unable to start meeting muted.
startWithVideoMuted: true and startWithAudioMuted: true, options are ignored/not working properly  in latest build. With this options enabled, meetings should started with camera and microphone disabled for every one in room.

### Steps to reproduce:

enable options:

    startWithVideoMuted: true,
    startWithAudioMuted: true,

in example-config.js

### Expected behavior:

With this options enabled meetings are started with camera and microphone disabled for every one in room.

### Actual behavior:

Video a microphone is disabled only for second and next participants in order, NOT for the first one, who creates the room. If I set new introduced options:
    startAudioMuted: 1,
    startVideoMuted: 1,

behavior is the same. There is no way to start meeting with camera and microphone disabled for every one in room.

### Server information:

- Jitsi Meet version:
root@vmeet:/etc/jitsi/meet# dpkg -l|grep jitsi
ii  jitsi-meet                       2.0.5390-3                                 all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody               1.0.4628-1                                 all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver            1.0.4628-1                                 all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                   1.0.4628-1                                 all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config            1.0.4628-1                                 all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2               2.1-416-g2f43d1b4-1                        all          WebRTC compatible Selective Forwarding Unit (SFU)

- Operating System:
debian stable

### Client information:

- Browser / app version: all
- Operating System: all

### Additional information:

This change was introduced by 2.0.5390 update.

**Comment by amsnek** [comment] 2021-01-22 15:47
can confirm but duplicate of #8144

**Comment by damencho** [comment] 2021-01-22 16:25
Duplicate #8144

**Closed by damencho** 2021-01-22 16:25 UTC
