### ISSUE TITLE
no audio/video on selfhosted instance

### ISSUE THREAD

**Issue by Deshke** [jitsi/jitsi-meet#234] opened 2015-02-11 14:54 UTC
hey there, i've tried the quick-install from https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md with 
```bash
  echo 'deb http://download.jitsi.org/nightly/deb unstable/' >> /etc/apt/sources.list
  wget -qO - https://download.jitsi.org/nightly/deb/unstable/archive.key | apt-key add -
  apt-get update
  aptitude install jitsi-meet jitsi-videobridge 
``` 

but there is no video or audio from a second client (no matter if chrome beta/stable on any os), any idea? 

```bash
~: java -version
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)

~: cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
 
```

replaced my "server.tld" with "somehost"
```bash
==> prosody/prosody.log <==
Feb 11 15:44:49 mod_bosh	info	New BOSH session, assigned it sid 'bc047b3b-4e2e-4285-9fd4-a8a6d3d1ec5f'
Feb 11 15:44:51 boshbc047b3b-4e2e-4285-9fd4-a8a6d3d1ec5f	info	Authenticated as 8faa0554-b729-4e59-a673-ab42291ed04f@somehost

==> jitsi/jicofo.log <==
15:44:52.532 INFO: [37] org.jitsi.jicofo.xmpp.FocusComponent.handleIQSet().222 Focus request for room: someprefixpossiblybasedonpath@conference.somehost
15:44:52.533 INFO: [37] org.jitsi.jicofo.FocusManager.createConference().230 Created new focus for someprefixpossiblybasedonpath@conference.somehost@auth.somehost conferences count: 1 options:
    channelLastN: -1
    adaptiveLastN: false
    adaptiveSimulcast: false
    bridge: jitsi-videobridge.somehost
    enableFirefoxHacks: false
    openSctp: true
15:44:52.699 SEVERE: [40] org.jivesoftware.smack.PacketReader.notifyConnectionError() Closes the connection temporary
stream:error (host-unknown)
	at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:264)
	at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:45)
	at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:74)
15:44:57.549 SEVERE: [38] org.jitsi.jicofo.util.RegisterThread.run().42 net.java.sip.communicator.service.protocol.OperationFailedException: Failed to connect
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to connect
	at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.register(XmppProtocolProvider.java:161)
	at org.jitsi.jicofo.util.RegisterThread.run(RegisterThread.java:38)
Caused by: No response from the server.: 
	at org.jivesoftware.smack.NonSASLAuthentication.authenticate(NonSASLAuthentication.java:73)
	at org.jivesoftware.smack.XMPPConnection.login(XMPPConnection.java:217)
	at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.register(XmppProtocolProvider.java:156)
	... 1 more

==> prosody/prosody.log <==
Feb 11 15:45:02 mod_bosh	info	New BOSH session, assigned it sid '690b2649-223d-43e3-9fbd-60a8ea8b1cc7'
Feb 11 15:45:03 bosh690b2649-223d-43e3-9fbd-60a8ea8b1cc7	info	Authenticated as c0ce568a-54b9-4dcc-8501-0b5fea3a478d@somehost

==> jitsi/jicofo.log <==
15:45:04.114 INFO: [48] org.jitsi.jicofo.xmpp.FocusComponent.handleIQSet().222 Focus request for room: someprefixpossiblybasedonpath@conference.somehost
15:45:11.102 INFO: [18] org.jitsi.jicofo.FocusManager.expireLoop().458 Focus idle timeout for someprefixpossiblybasedonpath@conference.somehost
15:45:11.103 INFO: [18] org.jitsi.impl.protocol.xmpp.OperationSetColibriConferenceImpl.expireConference().334 Nothing to expire - no conference allocated yet
15:45:11.103 SEVERE: [18] org.jitsi.jicofo.JitsiMeetConference.leaveTheRoom().360 Chat room already left!
couldn't setup local SOCKS5 proxy on port 7777: Address already in use
15:45:11.253 INFO: [18] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.info() XMPP provider Jabber:focus@auth.somehost/focus3083935872941@localhost disconnected
15:45:11.254 INFO: [18] org.jitsi.jicofo.FocusManager.conferenceEnded().252 Disposed conference for room: someprefixpossiblybasedonpath@conference.somehost conference count: 0
```

**Comment by GonzaloAraujoC** [comment] 2015-02-22 09:41
Same here ... Ubuntu 14 ... did you solve this?
Thanks!

**Comment by GonzaloAraujoC** [comment] 2015-02-22 09:47
I can cconfirm that it's a bug in Ubuntu 14, i reinstall everything on Ubuntu 12 and work great! ... hope this help.

Gonzalo.

**Comment by neusdan** [comment] 2015-02-27 11:40
same probem here: 

from prosody.log:

```
Feb 27 12:31:38 jcpd399b0       info    Incoming Jabber component connection
Feb 27 12:31:38 jitsi-videobridge.jitsi.xxx.de:component     info    Component authentication failed for jitsi-videobridge.jitsi.xxx.de
Feb 27 12:31:38 mod_component   info    Disconnecting component, <stream:error> is: <stream:error><not-authorized xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Given token does not match calculated token</text></stream:error>
Feb 27 12:31:38 jcpd399b0       info    component disconnected: jitsi-videobridge.jitsi.xxx.de (false)

```

**Comment by Deshke** [comment] 2015-02-27 12:29
i solved this by using Oracle JDK and not the openJDK

**Comment by neusdan** [comment] 2015-02-27 13:42
does not help for me

i think this is maybe also the reason:

```
14:21:37.810 WARNING: [21] org.jitsi.impl.neomedia.codec.FMJPlugInConfiguration.warn() Codec org.jitsi.impl.neomedia.codec.audio.amrwb.JNIDecoder is NOT successfully registered
java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:260)
        at org.jitsi.impl.neomedia.codec.FMJPlugInConfiguration.registerCustomCodecs(FMJPlugInConfiguration.java:225)
        at org.jitsi.impl.neomedia.MediaServiceImpl.setupFMJ(MediaServiceImpl.java:1607)
        at org.jitsi.impl.neomedia.MediaServiceImpl.<clinit>(MediaServiceImpl.java:241)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:260)
        at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:118)
        at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:86)
        at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:163)
        at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:115)
        at org.jitsi.videobridge.Conference.getMediaService(Conference.java:928)
        at org.jitsi.videobridge.Content.getMediaService(Content.java:668)
        at org.jitsi.videobridge.RtpChannel.getMediaService(RtpChannel.java:748)
        at org.jitsi.videobridge.RtpChannel.initialize(RtpChannel.java:878)
        at org.jitsi.videobridge.Content.createRtpChannel(Content.java:275)
        at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:736)
        at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:548)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleColibriConferenceIQ(ComponentImpl.java:209)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQRequest(ComponentImpl.java:380)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:311)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:263)
        at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQGet(ComponentImpl.java:362)
        at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:511)
        at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
        at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
        at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
        at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Could not find FFmpeg decoder 0x12001!
        at org.jitsi.impl.neomedia.codec.audio.FFmpegAudioDecoder.assertFindAVCodec(FFmpegAudioDecoder.java:36)
        at org.jitsi.impl.neomedia.codec.audio.amrwb.JNIDecoder.<clinit>(JNIDecoder.java:25)
        ... 31 more

```

```
 Could not find FFmpeg decoder 
```

but i already installed ffmpeg and libavcodec packages

**Comment by bgrozev** [comment] 2015-02-27 14:04
@neusdan This exception is harmless, and ffmpeg and/or libavcodec are not needed.

**Comment by gpolitis** [comment] 2015-03-23 10:53
@Deshke  do you still have the problem?

**Comment by Deshke** [comment] 2015-03-23 11:22
nah, solved mine with the OracleJDK 1.7, maybe this should be standing in the requirements

**Comment by gpolitis** [comment] 2015-03-23 11:25
Thanks for the feedback. I don't think we've ever experienced any major problems with OpenJDK so I'm closing the issue. Please re-open it, if you wish to investigate further.

**Closed by gpolitis** 2015-03-23 11:25 UTC

**Comment by venkateshyella** [comment] 2017-01-09 11:59
Hi ,

We have issue in jitsi-meet : audio is not working if jitsi is in idle state for some hours 

Once i restart it is working fine but what is the permanent solution for this issue

We found below error in logs


Jicofo 2017-01-09 16:03:01.332 SEVERE: [99] org.jitsi.jicofo.ChannelAllocator.log() Failed to allocate channels for testvideocall@conference.10.0.0.150/sreeni-0ec2d3
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to allocate channels - no bridge configured
	at org.jitsi.jicofo.ChannelAllocator.allocateChannels(ChannelAllocator.java:372)
	at org.jitsi.jicofo.ChannelAllocator.createOffer(ChannelAllocator.java:307)
	at org.jitsi.jicofo.ChannelAllocator.discoverFeaturesAndInvite(ChannelAllocator.java:166)
	at org.jitsi.jicofo.ChannelAllocator.run(ChannelAllocator.java:135)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Jicofo 2017-01-09 16:03:01.333 SEVERE: [99] org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl.checkIfDisposed().148 Not doing expireConference - bridge not initialized
Jicofo 2017-01-09 16:03:01.407 INFO: [86] org.jitsi.jicofo.discovery.DiscoveryUtil.discoverParticipantFeatures().146 testvideocall@conference.10.0.0.150/venky-2a39f4, features: 
Jicofo 2017-01-09 16:03:01.407 INFO: [86] org.jitsi.jicofo.discovery.DiscoveryUtil.discoverParticipantFeatures().149 http://jabber.org/protocol/caps

**Comment by lhammond** [comment] 2017-01-16 14:45
venkateshyella, I'm seeing the same behavior.

I tried running a test over the weekend, but it didn't work.

To reproduce this, simply launch a test with multiple clients and let it run.


java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

**Comment by JuricaJaman** [comment] 2017-02-07 21:26
I have the same issue on debian 8 with java 8 when starting videobridge, i have java 8 jdk oracle installed. Anyone solve this?

**Comment by saghul** [comment] 2017-02-08 07:43
Could this be the fd leak @gpolitis ?

**Comment by gpolitis** [comment] 2017-02-09 16:58
> Failed to allocate channels - no bridge configured

You need to check if your JVB process is up and running and if it's configured correctly. 

On a side note, it would be nice to have a troubleshooting document somewhere with some common troubleshooting steps.

**Comment by JuricaJaman** [comment] 2017-02-09 19:16
for host unknown i solve it by adding or uncommenting line:
VirtualHost "localhost"

I still have error:
	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:17)
	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:220)
Caused by: java.lang.ClassNotFoundException: org.jitsi.impl.neomedia.codec.FFmpeg
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
JVB 2017-02-09 21:04:18.291 WARNING: [10] org.jitsi.impl.neomedia.codec.FMJPlugInConfiguration.log() Codec org.jitsi.impl.neomedia.codec.audio.amrwb.JNIEncoder is NOT successfully registered
java.lang.NoClassDefFoundError: org/jitsi/impl/neomedia/codec/FFmpeg
	at org.jitsi.impl.neomedia.codec.audio.FFmpegAudioEncoder.assertFindAVCodec(FFmpegAudioEncoder.java:49)
	at org.jitsi.impl.neomedia.codec.audio.amrwb.JNIEncoder.<clinit>(JNIEncoder.java:35)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)


Anyone had the same and solve it? I run out of ideas for this.

**Comment by damencho** [comment] 2017-02-10 08:34
Ignore this NoClassDefFoundError for now. This is known as we stripped ffmpeg out of the bridge, will be fixing it at some point, it is harmless.
