### ISSUE TITLE
Ghost user left in the room after kicking out participants - Android app (react-native)

### ISSUE THREAD

**Issue by jagannath-swarnkar** [jitsi/jitsi-meet#7304] opened 2020-07-14 11:31 UTC
### Description:
In jitsi meet - native app, after kicking out a participant, participant disconnects but ghost instance still left in moderators screen. 

### Steps to reproduce:

1. cloned the repo *jitsi-meet* and setup for React-native
2. installed packages and run the android app (react-native run-android)
3. connected two-three participants

### Expected behavior: 
on kick out participant should disappear

### Actual behavior:
I'm kicking out a participant and participant disconnects but that participant's ghost remains in moderators screen. it is not disappearing.

### Client information:

- Browser / app version: 20.3.0
- Operating System: for Android and ios

**Comment by AliKarpuzoglu** [comment] 2020-07-17 08:58
happened to me on iOS too.  Could this be due to the Lobby Feature? This bug was introduced in the last few months -  I had an up to date version on May 30th that did not have this issue

**Comment by saghul** [comment] 2020-07-17 14:26
Confirmed. A new app and SDK release if coming out. Thanks for the report folks!

**Comment by saghul** [comment] 2020-07-17 14:49
SDK 2.9.2 is out for both platforms with a fix for this. Cheers!

**Closed by saghul** 2020-07-17 14:49 UTC
Labels: android, ios, mobile, ui/ux

**Comment by HuskarHuang** [comment] 2020-09-14 01:52
@saghul Has the problem been solved? Which branch has or tag?

**Comment by HuskarHuang** [comment] 2020-09-14 07:00
It needs about 60 seconds，can we shorter the time to about 10 to 20 secods

**Comment by HuskarHuang** [comment] 2020-09-14 13:50
The ghost may exists，but when some one go into the room，could we remove the ghost，otherwise it is strange for the user because it is two users is the same but one has no video image
