### ISSUE TITLE
my app, implimenting jitsi meet Andriod pre-build sdk, do not work on sumsung andriod 5

### ISSUE THREAD

**Issue by yassineberradi** [jitsi/jitsi-meet#3940] opened 2019-03-02 15:58 UTC
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by yassineberradi** [comment] 2019-03-02 16:00
when running my app a get 
E/ReactNativeJS: Java exception in 'NativeModules'
    
    java.lang.NoClassDefFoundError: android.telecom.CallAudioState
03-02 15:30:02.363 23785-23820/com.example.myapplication E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
03-02 15:30:02.364 23785-23820/com.example.myapplication E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
03-02 15:30:02.405 23785-23821/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.example.myapplication, PID: 23785
    com.facebook.react.common.JavascriptException: Java exception in 'NativeModules'
    
    java.lang.NoClassDefFoundError: android.telecom.CallAudioState, stack:
    libcore.reflect.InternalNames.getClass@55
    java.lang.Class.getDexCacheType@476
    java.lang.reflect.ArtMethod.getDexCacheType@191
    java.lang.reflect.ArtMethod.getParameterTypes@136
    java.lang.reflect.Method.getParameterTypes@174
    java.lang.Class.getDeclaredMethods@769
    com.facebook.react.bridge.JavaModuleWrapper.findMethods@88
    com.facebook.react.bridge.JavaModuleWrapper.getMethodDescriptors@118
    android.os.Handler.handleCallback@739
    android.os.Handler.dispatchMessage@95
    com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage@29
    <unknown>@1043:340
    v@2:1483
    <unknown>@1042:276
    v@2:1483
    <unknown>@1041:194
    v@2:1483
    <unknown>@1040:85
    v@2:1483
    <unknown>@971:312
    v@2:1483
    <unknown>@970:85
    v@2:1483
    <unknown>@343:240
    v@2:1483
    <unknown>@12:184
    v@2:1483
    <unknown>@11:30
    v@2:1483
    d@2:866
    global code@1433:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:135)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)

**Comment by emilykag** [comment] 2019-03-15 11:44
Same problem here. I solved it by downgrading jitsi to 1.16.0

**Comment by saghul** [comment] 2019-03-15 11:49
Oops, we fixed this a couple of days ago. I'll push an update to 1.21. Sorry about that.

**Comment by emilykag** [comment] 2019-03-15 11:51
Thank you

**Comment by saghul** [comment] 2019-03-15 14:10
Duplicate of https://github.com/jitsi/jitsi-meet/issues/3933

**Closed by saghul** 2019-03-15 14:10 UTC

**Comment by calamatitech** [comment] 2019-04-04 21:28
Same problem building jitsi meet app for Android and running it on Android 5.0 (on Android >= 6.0 the app works well). How can I fix the source of embedded sdk (I presume android/sdk/ ....)?

**Comment by saghul** [comment] 2019-04-05 12:18
What version are you building? This is fixed now. You can chek the android-19.0.3 tag.

**Comment by calamatitech** [comment] 2019-04-05 12:48
I'm building the latest stable release, I'll try the current, waiting for the new stable release, with the new sdk. 
Thank you.

**Comment by saghul** [comment] 2019-04-05 13:13
The new SDK is out already, but the 19,.0.3 release should work on Android 5, we fixed that explicitly.

**Comment by calamatitech** [comment] 2019-04-05 14:13
Can you help me to find the right version of sdk? In maven repository there are the latest version, 2.0.0, and two older version, 1.16 e 1.21(only artifacts fixed).
Should I search the right sdk in jitsi meet repository? I didn't find any tag 19.0.3
Sorry, but I'm a little bit disoriented

**Comment by saghul** [comment] 2019-04-05 15:05
You said you were building the Jitsi Meet app, now you mentioned the SDK. I am also confused now :-)

Either way, this is fixed in both Jitsi Meet 19.0.3 and the SDK 2.0.0:

https://github.com/jitsi/jitsi-meet/releases/tag/android-sdk-2.0.0 (already on Maven, no need to build it)

https://github.com/jitsi/jitsi-meet/releases/tag/android-19.0.3

**Comment by calamatitech** [comment] 2019-04-05 16:50
Ok, thank you, I need the android release

**Comment by saghul** [comment] 2019-04-05 17:04
The android **what** release? Android app or Android SDK?

**Comment by calamatitech** [comment] 2019-04-05 20:22
The android-release-19.0.3 (app).
However, I'm thinking to patch the latest stable release I'm using (stable/jitsi-meet_3548) with the fix you suggested in commit 2b96c44dc56025f0428fc21948e7e7c66e4d370c
https://github.com/jitsi/jitsi-meet/pull/3967
"The android.telecom.CallAudioState class was only added in API level 23 (Android
M), so make sure we don't import it in lower versioned devices."

**Comment by saghul** [comment] 2019-04-05 21:07
Yes, applying that commit will solve the problem.

Now, when it comes to stable releases, 3548 is a stable release for the web. The mobile apps follow a different release cycle, and the latest stable release is 19.0.3.

**Comment by calamatitech** [comment] 2019-04-08 13:11
I did'nt understand this difference between web and Android.
What about IOS, is the same release cycle of Android, o shall I search for a IOS tag?
Many thanks for you support

**Comment by saghul** [comment] 2019-04-08 14:13
The web and mobile apps share the code base but are release at different intervals.

Android and iOS are usually released together but each has a different tag, since one platform may require a bug fix release which the other doesn’t.
