### ISSUE TITLE
Screen sharing on iPad

### ISSUE THREAD

**Issue by JoshuaDietz** [jitsi/jitsi-meet#6203] opened 2020-04-19 20:30 UTC
Hello,

I'd like to request a feature. According to your feature-request template:

**Is your feature request related to a problem you are facing?**
Since I use my iPad as "virtual paper" it would be really nice if it was possible to share the screen of the iPad. From a technical standpoint I think it should be possible since zoom (which I don't want to use) supports this feature on iPad as well.

**Describe the solution you'd like**
Having a button to start sharing the screen just like in the web version on PC would solve my problem. For it to make sense the screen sharing needs to keep running even when Jitsi Meet runs in the background (because obviously I don't want to share Jitsi but other apps)

**Describe alternatives you've considered**
Maybe a (really bad but better than nothing) alternative would be a digital whiteboard in Jitsi Meet to at least allow some kind of hand writing.

Thank you for your great work

Joshua

**Comment by saghul** [comment] 2020-05-13 14:45
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5252

**Closed by saghul** 2020-05-13 14:45 UTC
Labels: feature-request, ios
