### ISSUE TITLE
iOS Jitsi SDK compile error

### ISSUE THREAD

**Issue by edgar-j-b** [jitsi/jitsi-meet#8107] opened 2020-11-16 04:23 UTC
Im having issue on xcode 12.2. I already using pod 'JitsiMeetSDK', '~> 2.10.2' and i cant still build my app. the error was 

Failed to build module 'JitsiMeet' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

**Comment by AmineNac** [comment] 2020-11-16 11:37
Same issue since latest xcode 12.2 update

**Comment by sei-vsarvepalli** [comment] 2020-11-16 20:16
Looks like duplicate of Issue:  https://github.com/jitsi/jitsi-meet/issues/8106

**Closed** 2020-11-17 06:29 UTC
