### ISSUE TITLE
Openeing a room from 2.0.7210 Server in the Electron App on MAC OS - no controls in the alwaysOnTop view

### ISSUE THREAD

**Issue by salekseev73** [jitsi/jitsi-meet#11416] opened 2022-04-22 06:47 UTC
### Description:

I updated the self hostet jitsi server from 2.0.7.7001 to 2.0.7210. When opening a room in the Electron app, an empty window is displayed in the alwaysOnTop mode. First when video is activated, then the  video is displayed in the window, but without control buttons. Usually an avatar and the controls with buttons are displayed in this window.

Opening a room from the old instance (2.0.7.7001) in the same app works fine.

### Steps to reproduce:

1. Start electron App on MAC OS
2. Open a room from the 2.0.7.7001 jitsi server without video
3. Move electron to background just by using another program.
4. The small empty widow is shown

### Expected behavior:

In the alwaysOnTop window an avtar of the user and the control buttons are shown

### Actual behavior:

The latest version 2.0.7210:
<img width="341" alt="new-2 0 7210" src="https://user-images.githubusercontent.com/3920478/164618814-0d4514fa-07a3-43b7-9eb0-776666cea7e1.png">

The previous one 2.0.7.7001:
<img width="338" alt="previous-version-2 0 7210" src="https://user-images.githubusercontent.com/3920478/164618905-d10002ec-b16c-46a0-a7b1-1b270a56e93b.png">

### Server information:

- Jitsi Meet version:

```bash
dpkg -l | grep jitsi
ii  jitsi-meet                            2.0.7210-1                            all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                    1.0.6091-1                            all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                        1.0.6091-1                            all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                 1.0.6091-1                            all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                    2.1-665-g3a90ccdc-1                   all          WebRTC compatible Selective Forwarding Unit (SFU)
```

- Operating System: ubuntu

### Client information:
- app version: Electron-Client last stable
- Operating System: MAC OS

**Comment by salekseev73** [comment] 2022-04-22 09:31
I suspect that the change may have something to do with this commit 18 days ago:
https://github.com/jitsi/jitsi-meet/pull/11302

In the new version the alwaysOnTop window looks like:

```
<body style="app-region: drag;">
	<div id="react"></div>
	<video autoplay="" id="video"
		style="transform: scaleX(-1); display: block;" muted=""></video>
	<div class="dismiss"></div>
	<link rel="stylesheet"
		href="file:////jitsi-meet-electron/node_modules/@jitsi/electron-sdk/alwaysontop/render/alwaysontop.css">
</body>
```

In the previous version:

```
dy style="app-region: drag;">
	<div id="react">
		<div id="alwaysOnTop">
			<div class="toolbox-content-items always-on-top-toolbox fadeOut">
				<div aria-pressed="false" aria-disabled="false"
					aria-label="Audio mute" class="toolbox-button" tabindex="0"
					role="button">
					<div class="toolbox-icon   ">
						<div class="jitsi-icon jitsi-icon-default ">
							<svg height="22" width="22" viewBox="0 0 24 24">
								<path fill-rule="evenodd" clip-rule="evenodd"
									d="M16 6a4 4 0 00-8 0v6a4.002 4.002 0 003.008 3.876c-.005.04-.008.082-.008.124v1.917A6.002 6.002 0 016 12a1 1 0 10-2 0 8.001 8.001 0 007 7.938V21a1 1 0 102 0v-1.062A8.001 8.001 0 0020 12a1 1 0 10-2 0 6.002 6.002 0 01-5 5.917V16c0-.042-.003-.083-.008-.124A4.002 4.002 0 0016 12V6zm-4-2a2 2 0 00-2 2v6a2 2 0 104 0V6a2 2 0 00-2-2z"></path></svg>
						</div>
					</div>
				</div>
				<div aria-pressed="false" aria-disabled="false"
					aria-label="Video mute" class="toolbox-button" tabindex="0"
					role="button">
					<div class="toolbox-icon   ">
						<div class="jitsi-icon jitsi-icon-default ">
							<svg fill="none" height="22" width="22" viewBox="0 0 22 22">
								<path clip-rule="evenodd"
									d="M13.75 5.5H3.667c-1.013 0-1.834.82-1.834 1.833v7.334c0 1.012.821 1.833 1.834 1.833H13.75c1.012 0 1.833-.82 1.833-1.833v-.786l3.212 1.835a.916.916 0 001.372-.796V7.08a.917.917 0 00-1.372-.796l-3.212 1.835v-.786c0-1.012-.82-1.833-1.833-1.833zm0 3.667v5.5H3.667V7.333H13.75v1.834zm4.583 4.174l-2.75-1.572v-1.538l2.75-1.572v4.682z"></path></svg>
						</div>
					</div>
				</div>
				<div aria-disabled="false" aria-label="Hangup"
					class="toolbox-button" tabindex="0" role="button">
					<div class="toolbox-icon   hangup-button">
						<div class="jitsi-icon jitsi-icon-default ">
							<svg height="22" width="22" viewBox="0 0 32 32">
								<path
									d="M16 12c-2.125 0-4.188.313-6.125.938v4.125c0 .5-.313 1.063-.75 1.25a13.87 13.87 0 00-3.563 2.438c-.25.25-.563.375-.938.375s-.688-.125-.938-.375L.373 17.438c-.25-.25-.375-.563-.375-.938s.125-.688.375-.938c4.063-3.875 9.563-6.25 15.625-6.25s11.563 2.375 15.625 6.25c.25.25.375.563.375.938s-.125.688-.375.938l-3.313 3.313c-.25.25-.563.375-.938.375s-.688-.125-.938-.375a13.87 13.87 0 00-3.563-2.438c-.438-.188-.75-.625-.75-1.188V13c-1.938-.625-4-1-6.125-1z"></path></svg>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<video autoplay="" id="video"
		style="transform: scaleX(-1); display: block;" muted=""></video>
	<div class="dismiss"></div>
	<link rel="stylesheet"
		href="file:///jitsi-meet-electron/node_modules/@jitsi/electron-sdk/alwaysontop/render/alwaysontop.css">
</body>
```
The react div is empty

**Comment by saghul** [comment] 2022-04-22 09:32
Can you open the JS console and check for errors? (Same keyboard shortcut as in Chrome)

@robertpin any chance this is related to the buttons change?

**Comment by salekseev73** [comment] 2022-04-22 09:50
No, there are no error messages, just an info
```
/jitsi-meet-electron/node_modules/@jitsi/logger/lib/Logger.js:154 2022-04-22T09:47:42.453Z [AOT] <logInfo>:  [MAIN] handling aot-show state update from main process
/jitsi-meet-electron/node_modules/@jitsi/logger/lib/Logger.js:154 2022-04-22T09:47:44.649Z [AOT] <logInfo>:  [MAIN] handling aot-hide state update from main process
```

**Comment by salekseev73** [comment] 2022-04-22 09:54
Yes, I found in the second alwaysOnTop window an error message:

```
AudioMuteButton.js:72 Uncaught TypeError: pi.isStartSilent is not a function
    at hi.componentDidMount (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:291668)
    at hu (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:182956)
    at Al (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:199745)
    at t.unstable_runWithPriority (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:225203)
    at Hi (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:141968)
    at Rl (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:196484)
    at gl (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:192595)
    at fl (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:189726)
    at Xl (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:205810)
    at https://AudioMuteButton.js:72 Uncaught TypeError: pi.isStartSilent is not a function
    at hi.componentDidMount (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:291668)
    at hu (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:182956)
    at Al (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:199745)
    at t.unstable_runWithPriority (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:225203)
    at Hi (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:141968)
    at Rl (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:196484)
    at gl (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:192595)
    at fl (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:189726)
    at Xl (https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:205810)
    at https://meet.uni-frankfurt.de/libs/alwaysontop.min.js:2:207196/libs/alwaysontop.min.js:2:207196
```

**Comment by saghul** [comment] 2022-04-22 10:44
Can you reproduce this when connecting to meet.jit.si?

**Comment by salekseev73** [comment] 2022-04-22 11:49
No, it works fine with meet.jit.si. It works fine as well with our old instance

**Comment by salekseev73** [comment] 2022-04-22 12:03
I replaced  `/usr/share/jitsi-meet/libs/alwaysontop.min.js` on the new instance 2.0.7210 by the file from the old instance 2.0.7.7001. And it works now. As a workaround it is fine, but for the future updates, it must be fixed

**Comment by saghul** [comment] 2022-04-22 12:50
meet.jit.si is always a tad ahead of stable, so this means it's fixed already and the next stable release will contain the fix.

**Comment by salekseev73** [comment] 2022-04-22 12:58
OK, thank you

**Comment by damencho** [comment] 2022-04-22 13:27
> meet.jit.si is always a tad ahead of stable, so this means it's fixed already and the next stable release will contain the fix.

@saghul It is not the case this time. Because of some default config and the fact that deploy was broken because of prosody 0.12 we pushed a newer version to stable. So this needs addressing before we push new stable.

**Comment by robertpin** [comment] 2022-04-26 06:26
Looks like it has something to do with `isStartSilent`. @horymury can you take a look?

**Comment by horymury** [comment] 2022-04-26 08:50
> Looks like it has something to do with `isStartSilent`. @horymury can you take a look?

Yep, created PR with fix.

**Comment by csett86** [comment] 2022-05-13 10:44
This is fixed with https://github.com/jitsi/jitsi-meet-electron/pull/747 and released in https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2022.4.1, so this issue can be closed.

**Closed** 2022-05-13 10:49 UTC
