### ISSUE TITLE
Big video not shown

### ISSUE THREAD

**Issue by bgrozev** [jitsi/jitsi-meet#262] opened 2015-04-06 12:34 UTC
Sometimes the big video for a certain participant turns black and never recovers.

**Comment by gpolitis** [comment] 2015-04-28 11:23
This is nasty and difficult to debug (as #261 is). We should probably add special handling for this when we improve logging #275.

**Comment by hristoterezov** [comment] 2015-04-28 11:40
I think 667f673 fixes this issue. Is anybody able to reproduce it since that commit?

**Comment by gpolitis** [comment] 2015-04-28 11:46
I can't reproduce it right now, although that alone doesn't mean it's fixed as it only happens sometimes (from the original bug report). I'll keep an eye on it and report back if I repro it.

**Comment by hristoterezov** [comment] 2015-04-28 12:53
That commit fixes the following issue. When user mutes its video and then start it again the old video element was not removed from the thumbnail. That's how we end up with more than one video elements in the thumbnail. One of them is the correct one and the others have old "src" attributes and they are black. So when the participant is shown on the large video we are copying the "src" attribute from the video element and if the wrong video element is chosen the large video is black.

Maybe there are other issues that could cause the black large video.

**Comment by bgrozev** [comment] 2015-05-20 14:13
George and me were able to reproduce this on https://github.com/jitsi/jitsi-meet/commit/fb6ad8cffd1358c6fad08f38f6e9072c4a922c46 using these steps:
1. Open one tab in FF
2. Open two tabs in chrome
3. The chrome instances do not see FF's "big" video, and they have two "video" elements under one participant's "span".

I am not sure if this is related to firefox, or is just intermittent and we happened to only hit it with firefox.

**Comment by gpolitis** [comment] 2015-05-21 13:52
The issue described in the previous comment has been fixed with e3da472e7aff4b5a23f2eacf2068093cb6d3a23e. It's indeed a FF/Unified Plan handling specific issue.

**Closed** 2016-02-17 19:28 UTC
Labels: type:bug
