### ISSUE TITLE
[IOS] Mobile client does not refresh room after moderator starts the meeting

### ISSUE THREAD

**Issue by nowlnowl** [jitsi/jitsi-meet#9477] opened 2021-06-30 11:40 UTC
### Description:

If a I join a meeting which has not started yet (only moderators can start a meeting) I get a popup saying I can either login or wait for a moderator to start the meeting. If the moderator starts the meeting after the mobile client does not refresh and auto join.
I need to exit the meeting and manually join it again.
In android the client joins the newly opened meeting automatically

### Steps to reproduce:

1. Enter a room with IOS application (not moderator)
2. Enter same room on another device as moderator and start the meeting
3. See result on IOS client

### Expected behavior:

Auto join the meeting

### Actual behavior:

Seeing the popup waiting for the meeting to start

**Comment by csett86** [comment] 2021-12-05 21:24
This is a duplicate of #9477, and by now android is also affected (according to #9477).

**Comment by saghul** [comment] 2021-12-08 07:43
Continuing on #10211

**Closed by saghul** 2021-12-08 07:43 UTC
