### ISSUE TITLE
End call button doesn't work in portrait mode on Samsung Galaxy 2 ( other buttons function normally.)

### ISSUE THREAD

**Issue by hardlycode** [jitsi/jitsi-meet#8984] opened 2021-04-10 06:23 UTC
### Description:

End call button doesn't work in portrait mode on Samsung Galaxy View 2 ( other buttons function normally.)

(Works fine on my LG phone.)

### Steps to reproduce:

1. Start call.
2. Try to end call.
3. Reboot tablet because there is no way to end the call.

### Expected behavior:

Pushing the hang up button should work.

### Actual behavior:

Seriously...it doesn't work. No idea why.

**Comment by saghul** [comment] 2021-04-10 06:30
Any difference in landscape mode?

**Comment by hardlycode** [comment] 2021-04-10 06:32
Negative. I just tested it.

All the other buttons work normally, except the red "end call" button.

**Comment by xenonblaze** [comment] 2021-04-10 09:40
I have the same problem on an Android 7 tablet. After updating the app to version 21.0.0 from F-Droid the hang-up button does not work anymore.

**Comment by saghul** [comment] 2021-04-10 10:54
Can either of you provide an adb logcat?

**Comment by daniel-w00** [comment] 2021-04-10 14:24
[logcat.txt](https://github.com/jitsi/jitsi-meet/files/6289980/logcat.txt)
I have the same problem with a Samsung Galaxy Tab with Android 8. But if you click the End-Call-Button really often, it suddenly works sometimes. If you close Jitsi via the Recent Apps, the calls also ends.
I hope i did the logcat right

**Comment by roblefko** [comment] 2021-04-11 00:13
I'm having the same issue, and I think I know what the cause is.  I've attached a screenshot from my table ( Lenovo Smart Tab M8). Notice that the end-call button does not fit on the toolbar. The gray background for the toolbar ends just at the left edge of the button.  I have the same issue on my phone, a Google Pixel 3.
![Screenshot_20210410-180139](https://user-images.githubusercontent.com/71861893/114287883-c0e4d380-9a38-11eb-8354-ab352055c4af.png)

**Comment by saghul** [comment] 2021-04-11 06:43
We have fixed this in master, a meeting beta with a fix will be released early next week.

**Comment by xenonblaze** [comment] 2021-04-11 06:51
I can confirm this on my tablet. In landscape format the button is outside the toolbar background. I didn't notice it has a background at all because it's "almost black" on black which seems to be trendy nowadays. Maybe you could enhance the contrast a bit.

**Comment by martnaum** [comment] 2021-04-12 19:14
Confirmed on S4 and S5e tabs running latest Android.

**Comment by saghul** [comment] 2021-04-13 05:46
We're hoping to have a new beta out today.

**Comment by saghul** [comment] 2021-04-13 14:47
21.1.0 beta is out, can you please test?

**Comment by daniel-w00** [comment] 2021-04-13 14:53
Yes, it works again with latest beta

**Comment by saghul** [comment] 2021-04-13 15:04
Thanks for checking!

**Comment by lukaprincic** [comment] 2021-04-16 11:09
I'm hit by the same bug. How can I get the beta for android?

**Comment by biot** [comment] 2021-05-03 12:16
Version 21.1.0 build 211000 fixed the problem for me as well, thanks!

**Comment by saghul** [comment] 2021-05-03 15:09
Thanks for confirming! I'm closing this then.

**Closed by saghul** 2021-05-03 15:09 UTC

**Comment by subhra9326** [comment] 2021-06-22 17:46
Hi, There is no bug fixing for flutter.  ( jitsi_meet 4.0.0 "jitsi_meet: ^4.0.0"  Published Apr 13, 2021 )
Please fix this issue for flutter also. Thanks. I am using the OnePlus 5T with the latest Android OS.
