### ISSUE TITLE
config.js: startWithAudioMuted/startWithVideoMuted values seem to be ignored

### ISSUE THREAD

**Issue by cketti** [jitsi/jitsi-meet#8429] opened 2021-01-15 18:47 UTC
### Description:

Setting `startWithAudioMuted` and `startWithVideoMuted` to `true` in `config.js` seems to be ignored after the update to Jitsi Meet 2.0.5390-1 (Jitsi deb repo)

### Steps to reproduce:

1. Open browser's incognito/privacy mode
2. Join meeting
3. After granting access to microphone/webcam both audio and video are enabled automatically

### Expected behavior:

Audio/video should be disabled when joining a meeting.

### Actual behavior:

Audio/video is enabled automatically when joining a meeting.

### Server information:

- Jitsi Meet version: 2.0.5390-1 (Jitsi deb repo)
- Operating System: Debian

### Client information:

- Browser / app version: Chrome 87 / Firefox 84
- Operating System: Ubuntu

### Additional information:
This worked fine in the previous stable Jitsi Meet version.

Possibly related: #8144

**Comment by hristoterezov** [comment] 2021-01-16 00:06
Duplicate of https://github.com/jitsi/jitsi-meet/issues/8144.

**Closed by hristoterezov** 2021-01-16 00:06 UTC
Labels: duplicate
