### ISSUE TITLE
Setting to join a conference without the camera turned on

### ISSUE THREAD

**Issue by MiningPickaxe** [jitsi/jitsi-meet#5330] opened 2020-03-23 11:20 UTC
**Is your feature request related to a problem you are facing?**
Yes, when someone new joins the bandwith struggles for a few seconds before it calms down

**Describe the solution you'd like**
I'd like to be able to set a preference (either in the conference itself or each user individually in his browser) to join a room without the camera beeing turned on immediatly. This would prevent taking up too much bandwith for people with slow internet connections when new people join. And sometimes you don't want everyone to know how you look when you enter a room

**Describe alternatives you've considered**
Disabling the Camera in the browser Settings, this is a workaround but not really ideal. Gives you a warning you have to manually expand and click "ok" on.

**Comment by saghul** [comment] 2020-03-23 11:30
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5045

**Closed by saghul** 2020-03-23 11:30 UTC
