### ISSUE TITLE
external webcam problem with chrome

### ISSUE THREAD

**Issue by pasquale979** [jitsi/jitsi-meet#5120] opened 2020-03-09 10:59 UTC
if i use chrome, the external webcam does not work. if I use firefox it works instead. do I have to enable something?

**Comment by saghul** [comment] 2020-03-11 12:42
What webcam is it? Can you try https://test.webrtc.org/ and let us know if it works there?

**Comment by alexanderadam** [comment] 2020-03-25 11:23
Isn't this a duplicate of #5155?

**Comment by saghul** [comment] 2020-03-27 21:35
No follow-up, I'm closing this one.

**Closed by saghul** 2020-03-27 21:35 UTC
