### ISSUE TITLE
Rejoin now and duplicate user issue Android

### ISSUE THREAD

**Issue by soorajjaivas** [jitsi/jitsi-meet#7277] opened 2020-07-09 14:38 UTC
I am using jitsi latest sdk version 2.9.0 in my android app.I couldnot get the call backs of onConferenceTerminated while clicking stop call icon.Also while joining call,its showing rejoin now dialog box and closes window.
Another issue is duplicate users showing while joining call.

Please help me

**Comment by Echolon** [comment] 2020-07-09 16:33
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

If you think this is a bugreport, please fill out the template first, then I can reopen.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-07-09 16:33 UTC
Labels: android, mobile, question

**Comment by soorajjaivas** [comment] 2020-07-10 13:41
Hi,
I reported  bug issue.I couldnot join to video session cal.Following error getting
 E/JitsiMeetSDK: [features/analytics] Error(Error){"message":"No analytics handlers created!","stack":"Error: No analytics handlers created!\n    at anonymous (index.android.bundle:448:1252)\n    at f (index.android.bundle:111:155)\n    at anonymous (index.android.bundle:111:882)\n    at apply (native)\n    at anonymous (index.android.bundle:117:1783)\n    at y (index.android.bundle:117:661)\n    at C (index.android.bundle:117:1025)\n    at callImmediates (index.android.bundle:117:3100)\n    at value (native)\n    at anonymous (index.android.bundle:36:1283)\n    at value (index.android.bundle:36:2939)\n    at value (index.android.bundle:36:1253)\n    at value (native)"}

**Comment by saghul** [comment] 2020-07-10 14:00
That is a harmless error log. Which I will remove to avoid the confusion.

**Comment by soorajjaivas** [comment] 2020-07-20 12:23
oh ok, but sometimes duplicate issue happening while joing to a call.Sometimes Reonnecting now window shows and suddenly it closes when user joins call for first time. Could you please help on this
