### ISSUE TITLE
Screen sharing does not show the cursor/pointer

### ISSUE THREAD

**Issue by MarkWieczorek** [jitsi/jitsi-meet#5986] opened 2020-04-14 10:22 UTC
## Description
---
Jitsi meet works great on my system (macOS with firefox), and being able to share the screen is a very important feature for our research group that is now meeting on-line. However, when sharing the screen, everything works as expected with the exception that the cursor/pointer does not display on the other participants video stream. We have tried sharing the entire desktop, as well as a single application, with the same effect. Unfortunately, this is a deal-breaker for us...

**Comment by jallamsetty1** [comment] 2020-04-14 20:13
Hey there, thank you for the bug report. It appears that this is a Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1625694 that has been fixed. I have also verified that the issue is fixed in FF 76.

**Closed** 2020-04-14 21:06 UTC
