### ISSUE TITLE
JistiSDK crash issue

### ISSUE THREAD

**Issue by PinkeshGjr** [jitsi/jitsi-meet#4995] opened 2020-01-20 07:10 UTC
JitsiMeetSDK is keep crashing in iOS 13.3. It's working fine in iOS 12.

```
2020-01-20 12:35:32.109443+0530 XXXX[977:193742] [JitsiMeetSDK] [modules/xmpp/xmpp.js] P2P STUN servers:  [ { urls: 'stun:stun.l.google.com:19302' },
  { urls: 'stun:stun1.l.google.com:19302' },
  { urls: 'stun:stun2.l.google.com:19302' } ]
2020-01-20 12:35:32.121114+0530 XXXX[977:193742] [JitsiMeetSDK] [modules/xmpp/xmpp.js] (TIME) Strophe connecting:	 1579503932120
2020-01-20 12:35:32.122883+0530 XXXX[977:193744] [JitsiMeetSDK] NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]
2020-01-20 12:35:32.123203+0530 XXXX[977:193743] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]'
*** First throw call stack:
(0x18cc92a48 0x18c9b9fa4 0x18cce8360 0x18ccf16b4 0x18cb7f73c 0x18cb715d0 0x1036a5220 0x18cc98c20 0x18cb68d30 0x18cb69908 0x1035d645c 0x1035d856c 0x1035d82d0 0x1044457fc 0x104446bd8 0x10444db48 0x10444e6e4 0x104459adc 0x18c9aeb88 0x18c9b1760)
libc++abi.dylib: terminating with uncaught exception of type NSException

```

**BT**
```
* thread #11, queue = 'WebRTCModule.queue', stop reason = signal SIGABRT
  * frame #0: 0x000000018ca89ec4 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x000000018c9a51d8 libsystem_pthread.dylib`pthread_kill$VARIANT$mp + 136
    frame #2: 0x000000018c8f9844 libsystem_c.dylib`abort + 100
    frame #3: 0x000000018ca527d4 libc++abi.dylib`abort_message + 128
    frame #4: 0x000000018ca529c4 libc++abi.dylib`demangling_terminate_handler() + 296
    frame #5: 0x000000018c9ba258 libobjc.A.dylib`_objc_terminate() + 124
    frame #6: 0x000000018ca5f304 libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame #7: 0x000000018ca5f29c libc++abi.dylib`std::terminate() + 44
    frame #8: 0x000000018c9ba1dc libobjc.A.dylib`objc_terminate + 12
    frame #9: 0x0000000107a5ebec libdispatch.dylib`_dispatch_client_callout + 36
    frame #10: 0x0000000107a65b48 libdispatch.dylib`_dispatch_lane_serial_drain + 744
    frame #11: 0x0000000107a666e4 libdispatch.dylib`_dispatch_lane_invoke + 448
    frame #12: 0x0000000107a71adc libdispatch.dylib`_dispatch_workloop_worker_thread + 1324
    frame #13: 0x000000018c9aeb88 libsystem_pthread.dylib`_pthread_wqthread + 276`
```

**Comment by PinkeshGjr** [comment] 2020-01-20 10:27
@saghul  Would you please help me with this. That would be really helpful.

**Comment by saghul** [comment] 2020-01-20 10:33
Do you have a call scenario where you can reproduce it reliably? What SDK version are you currently using?

**Comment by PinkeshGjr** [comment] 2020-01-20 10:42
i am using Version 2.5.0. It's crashed every-time when i initialise JitsiMeetView. I am using custom frameworks instead of Pods. Let me know if you need more details.

**Comment by saghul** [comment] 2020-01-21 09:54
Can you reproduce the issue with the latest (2.5.3) pods?

**Comment by PinkeshGjr** [comment] 2020-01-21 10:10
It's strange. i tried to rebuild framework again Version 2.5.0 and it's working well. No crash at all.

**Comment by PinkeshGjr** [comment] 2020-01-22 12:00
@saghul Would you please help me. It's started crashing again.

**Comment by saghul** [comment] 2020-01-22 12:03
> Can you reproduce the issue with the latest (2.5.3) pods?

You haven't answered to this. We have not seen such crash in our builds AFAIK.

**Comment by PinkeshGjr** [comment] 2020-01-22 12:13
@saghul  as per project requirement i can't use Pods.

**Comment by saghul** [comment] 2020-01-22 13:26
Can you use these frameworks? https://github.com/jitsi/jitsi-meet-ios-sdk-releases/tree/master/Frameworks those are what's in the latest pods.

**Comment by PinkeshGjr** [comment] 2020-01-23 05:33
@saghul yes sure let me rebuild and get back to you.

**Comment by djorkaeffalexandre** [comment] 2020-02-17 23:37
> Can you use these frameworks? https://github.com/jitsi/jitsi-meet-ios-sdk-releases/tree/master/Frameworks those are what's in the latest pods.

It's working fine for me!
2.4 sometimes crash on iOS 13.3.
Thanks a lot @saghul .

**Comment by saghul** [comment] 2020-02-18 08:39
I'm going to tentatively close this since it doesn't seem to be reproducible on the latest version.

**Closed by saghul** 2020-02-18 08:39 UTC
