### ISSUE TITLE
I want to share my video conference thru youtube

### ISSUE THREAD

**Issue by apenaministries** [jitsi/jitsi-meet#5647] opened 2020-04-04 03:24 UTC
I am sorry I want to share my conference thru youtube can you tell me why is not working?

**Comment by Echolon** [comment] 2020-04-10 21:05
duplicate 
Feature request: YouTube sharing on Android #5367

@damencho

**Comment by spacehobo** [comment] 2020-05-17 15:33
#5367 has been marked as a duplicate of this, but it is not the same request.  That one is about sharing youtube videos in the meet (a feature that works flawlessly only so long as everyone is using Chrome), not about sharing meets via youtube live.

**Comment by l3d00m** [comment] 2020-05-17 16:43
Well @apenaministries if this is still occurring, please share details beyond "it doesn't work".

**Comment by Echolon** [comment] 2020-05-25 18:23
@l3d00m @luixxiul 

Are you sure this should be kept open? I really lags information and the author does not respond.

**Closed** 2020-06-04 09:50 UTC
Labels: info:feedback-needed
