### ISSUE TITLE
build error on xcode 11

### ISSUE THREAD

**Issue by ciufab** [jitsi/jitsi-meet#6113] opened 2020-04-16 22:18 UTC
Hi,
I'm new in ios development so I try to be clear in explaining the steps I've taken before the error presented.
I've installed Xcode 11 on catalina
I've installed homebrew, node and cocoapods(1.9.1)
I've installed the additionals dependencies as stated in the guide for the apps
I've downloaded the ios examples, opened a terminal and cd to the /ios/swift-pip/JitsiSDKTest directory here I've launced 'pod install' and obtained the pod directory
I open the workspace, set the 'always embed swift standard libraries' to yes and disabled bitcode.
When i click play I get 11 errors:
- one is Failed to load module 'JitsiMeet'
the others are like
../Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:72:21: 'PiPViewCoordinator' is not a member type of 'JitsiMeet' 

I'm pretty sure that I'm doing something wrong but can't figure out what...

Edit:
I've tried the same steps with the objc project and I'm able to compile the app and launch in simulator, once the conference starts I'm unable to see others video(I just see red flashing light) but I suppose it's normal?

**Comment by ankitjamuar** [comment] 2020-04-18 22:24
HI, I am getting exact same issue in XCode 11.4.
Please suggest.
Error: Total 10
Failed to load module 'JitsiMeet'
'PiPViewCoordinator' is not a member type of 'JitsiMeet'
and 8 more

**Comment by saghul** [comment] 2020-04-19 06:11
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5645

**Closed** 2020-04-19 06:11 UTC
