### ISSUE TITLE
Feature-Req: Invite Jitsi-client to conference / Join conference with Jitsi-client

### ISSUE THREAD

**Issue by jkrenzer** [jitsi/jitsi-meet#96] opened 2014-08-13 23:07 UTC
Hi!

Jitsi and Jitsi-Meet would be even more awesome if one could participate in a conference regardless of using the web- or Jitsi-client. Scenario: Conference with some moderators/speakers/employees using their trusty Jitsi/XMPP with all their preferences, LDAP, bells and whistles and an unknown number of (anonymous) visitors via web-client.

Kind regards,

Jörn

**Comment by pedro-nonfree** [comment] 2015-03-02 18:36
Hi.

It worked with gajim and my experimental server with jitsi-meet (is not working with meet.jit.si, perhaps disallowed).
Details:
Wizard: "I want to register for a new account"
Put "anonymous login" capability, and point to the server: jitsi.yourdomain.org

Join Group Chat / Join New Group Chat
Account: jitsi.yourdomian.org
nickname (need something)
room: room-you-want-to-join
server: conference.jitsi.yourdomain.org (by default is conference).


In jitsi cannot got it work because I need to have registered an account. An easy way...?

What is needed to do to improve jitsi client - jitsi meet. I have time.

**Comment by Wolf480pl** [comment] 2015-03-02 19:43
@pedro-nonfree did you get audio/video to work? or just text?

**Comment by pedro-nonfree** [comment] 2015-03-02 19:56
@Wolf480pl  /Obviously/ just text, because gajim does not have videobridge/webrtc (audio,video,...).

I would like to try with jitsi client, but I am not able to login in the server, so I cannot access a room.
It seems you know how to login with jitsi client.

**Comment by Wolf480pl** [comment] 2015-03-02 20:09
@pedro-nonfree you create an account on any other XMPP server, and use that to log in. Then you can join any conference room on any server. Just enter room-you-want-to-join@conference.jitsi.yourdomain.org as the room name.

Also, Gajim does have audio/video (but not on Windows, and requires python-farstream).

**Comment by jtsaitw** [comment] 2015-03-25 09:01
Thanks to Wolf480pl, I can do it from jitsi-client (myAccount@jappix.com)  to jitsi-meet (meet.jit.si) now. 
But I still can not find any way to "jitsi-meet ring to jitsi-client(other XMPP account), It is nice to have a friend list with photo, and elder user can ring to other XMPP account in the list.

**Comment by arthurlogilab** [comment] 2015-06-17 14:14
+1

**Comment by emcho** [comment] 2015-06-18 07:31
I am going to leave this open for now but it is very unlikely that someone would have the time to work on it in the foreseeable future.

**Comment by marclaporte** [comment] 2015-07-18 01:42
Full interoperability (video, screen sharing, etc) between Jitsi & Jitsi Meet is obviously a lot of work. But perhaps activity in a Jitsi Meet conference could nudge a Jitsi user via XMPP to join the action in Jitsi Meet with a modern browser? 

"Some activity has been detected in the Jitsi Meet room at https://meet.jit.si/test so please visit with your browser"

Thanks!

**Comment by zorbalaras** [comment] 2015-09-15 19:46
I definitely need the Jitsi & Jitsi Meet interoperability. I was able to check that chatting between a Jitsi client and a Jitsi Meet room just works fine out of the box. Can someone give me some hints/starting-point from a coding perspective to bring the audio/video interoperability? Marc, any idea?
Thanks!

**Comment by Wolf480pl** [comment] 2015-09-16 19:39
@zorbalaras according to my observations from half a year ago, the focus initiates a Jingle call to anyone who joins the MUC (seen it happen in Gajim, but should be the same for all clients, incl. Jitsi). Now, for some reason, the client isn't able to accept that call. A starting point would be to figure out why it 

However, some things may have changed since then.
Also, I'd love to see some info on this from the Jitsi team.

**Comment by MRYingLEE** [comment] 2015-12-07 07:36
This is a feature I am looking for.
1. @pedro-nonfree @Wolf480pl If my meeting link is https://meet.jit.si/test,  what's my MUC room name and server name if I access the MUC in an XMPP client.
2. Does somebody find such a web XMPP client to support user login and anonymous login for a MUC at the same time? If so, maybe we can integrate Meet.Jiti.si with the Web XMPP client together in a HTML page to implement this feature. 

Any comments?

**Comment by bgrozev** [comment] 2015-12-07 15:47
> 1. @pedro-nonfree @Wolf480pl If my meeting link is https://meet.jit.si/test, what's my MUC room name and server name if I access the MUC in an XMPP client.

In a default Jitsi-Meet installation with domain "example.com" the "test" conference would use the "test@conference.example.com" MUC. 

Note that conferences will not work out of the box with another client.

**Comment by MRYingLEE** [comment] 2015-12-08 00:28
@bgrozev I tried "test@conference.example.com" and "test@conference.jitsi.example.com" and met the error of "DNS resolution failed". 
So, I guess it is because the server settings that the built-in Prosody works only locally.

**Comment by bgrozev** [comment] 2015-12-08 00:45
[Yes](http://prosody.im/doc/components#dns). Also, s2s will currently not work (at least not on meet.jit.si).

**Comment by Wolf480pl** [comment] 2015-12-08 16:39
I'm pretty sure s2s used to work on meet.jit.si in the past.

Anyway, @MRYingLEE, you could either try connecting with an XMPP client in anonumous login mode to meet's XMPP server, like the webapp does, or running your own meet instance on localhost and creating a regular XMPP account in Prosody for testing purposes.

If you manage to join the MUC, try to see if the focus (jicofo) is trying to initiate a Jingle call with you, and if you can accept that call.

**Comment by singpolyma** [comment] 2015-12-17 15:43
+1

**Comment by dilagurung** [comment] 2016-09-03 13:18
can anybody help me to set up the jits-video bridge using open fire.. I followed the instruction given in respective site but of no avail... Add to that  what is the process of accessing videochat room???

**Comment by marclaporte** [comment] 2016-09-06 06:38
@dilagurung : http://wikisuite.org/How-to-install-Openfire-Meetings-on-ClearOS

**Comment by Wolf480pl** [comment] 2018-12-04 15:07
Is it wontfix only because nobody has time to work on it?
In that case I think closing the issue is not the best idea... maybe some day someone will want to make a pull request? And if they see it as wontfix, they'll think it is an undesirable feature and any pull request won't be accepted.

**Closed as completed** 2018-12-04 15:25 UTC
