### ISSUE TITLE
[BUG] Memory Leak on Linux during call on Firefox

### ISSUE THREAD

**Issue by franzcor** [jitsi/jitsi-meet#11962] opened 2022-08-03 17:34 UTC
### Steps to reproduce:

1. Start a Jitsi call on Firefox. Even just starting the call without any other partecipants, produces the problem. 
2. Doesn't matter if you enable microphone, webcam or screen sharing. The bug always appears.

### Expected behavior:

I expect to run a call without issues

### Actual behavior:

The RAM gets eaten by jitsi in less than 10-20 minutes. If you have 4GB of RAM, you reach almost 4GB of used RAM in that time.
I tried on several linux systems and several firefox versions.

### Server information:

- Jitsi Meet version: Webversion (meet.jit.si)
- Operating System:

### Client information:

- Browser / app version: Firefox ESR, Firefox SNAP (latest,kubuntu), Firefox Appimage (latest,Kubuntu)
- Operating System:  Linux Kubuntu 22.04 and Debian Testing

### Additional information:

This is not happening using chromium based browsers! Please fix this as it makes almost impossible to start a jitsi call on a firefox browser and it would be bad having jitsi only working properly on the most popular browser.
I hardly use chromium browsers and I have it only for this occasion.

On my desktop pc with 16GB of RAM, it take a looot more time to run out of memory on firefox ESR. But, eventually, you'll run out of memory there too. It took almost 40 minutes to fill 1 GB of RAM.

**Comment by keithdanielll** [comment] 2022-08-05 13:36
Is this happening server side or client side? I can't reproduce this on either.

**Comment by saghul** [comment] 2022-08-05 14:22
Did you use EST or the latest FF to test?

@franzcor Can you reproduce this on a recent FF version?

**Comment by keithdanielll** [comment] 2022-08-05 14:42
FF 103 ubuntu 20

**Comment by franzcor** [comment] 2022-08-05 21:23
> Is this happening server side or client side? I can't reproduce this on neither.

it should be client side

**Comment by franzcor** [comment] 2022-08-05 21:24
> Did you use ESR or the latest FF to test?
> 
> @franzcor Can you reproduce this on a recent FF version?

I tried on both Firefox ESR (Debian) and Latest FF Snap and Appimage(Kubuntu 22.04)
The bug appears on both

**Comment by saghul** [comment] 2022-08-06 08:42
What graphics card and drivers do you have? Can you repro the bug with video muted?

**Comment by franzcor** [comment] 2022-08-06 10:43
> What graphics card and drivers do you have? Can you repro the bug with video muted?

yes, the bug happens even only with mic active. Remind that Firefox on linux doesn't use hw accel like chromium so it's entirely using CPU AFAIK. In any case, the kubuntu pc has an intel 605 UHD integrated card and the desktop is an AMD rx550
both using mesa opensource drivers

**Comment by nekohayo** [comment] 2022-11-21 02:14
>  Firefox on Linux doesn't use hw accel like chromium so it's entirely using CPU AFAIK.

On the contrary, I've never seen hardware video codec acceleration work on anything _other_ than Firefox on Linux. [Fedora's guide](https://fedoraproject.org/wiki/Firefox_Hardware_acceleration) is pretty informative in that regard.

I tried meet.jit.si now on Fedora 106.0.4 on Intel Sandybridge graphics under X11/Xorg, being alone in a room (muted, video turned off) and there is no visible memory leak when looking at `about:performance` ; that jitsi tab stays at 20 MB of memory, and Firefox overall stays under 1 GB of RAM during that time.

**Comment by saghul** [comment] 2022-11-21 06:08
Thanks for the info! I'm going to tentatively close this.

**Closed by saghul** 2022-11-21 06:08 UTC
