### ISSUE TITLE
AirPods Pro: mic doesn't work

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#10086] opened 2021-10-02 15:37 UTC
### Description:

Mic doesn't work with AirPods Pro: other users don't hear me. Phone mic, without AirPods works fine.
Google meet and just audio notes works fine.

### Client information:
- App version: Jitsi 21.3.1 build 119
- Operating System: iOS 15.0

The report is filled from the words of @alexvanin

**Comment by alexvanin** [comment] 2021-10-02 17:04
It was related to https://github.com/jitsi/jitsi-meet/issues/10053
Can't reproduce in Jitsi 21.4.1 build 131.
Feel free to close the issue.

**Closed** 2021-10-02 17:06 UTC
