### ISSUE TITLE
captureLargeVideoScreenshot not working properly

### ISSUE THREAD

**Issue by network12** [jitsi/jitsi-meet#7942] opened 2020-10-20 14:08 UTC
Hello,

we have own instance of Jitsi meet (Ubuntu 20.04 LTS) and we want to use api call captureLargeVideoScreenshot as is described in this handbook: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe
So we have setuped this workload:

```
<div id="videocall-block"></div>
<div class="videocontroll-block `text-center">
  <button id="video-get-screenshot" class="btn-light">Capture video</button>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src='https://meet.jit.si/external_api.js'></script>
<script>
    $(function() {
        const recordButton = $('#video-get-screenshot');
        const domain = 'meet.xxxx.xx';
        const options = {
            roomName: '#roomName',
            parentNode: document.querySelector('#videocall-block'),
        };
        const api = new JitsiMeetExternalAPI(domain, options);
        recordButton.on('click', function() {
            api.captureLargeVideoScreenshot()
            .then(dataURL => {
                // handling image - POST send to server
            })
            .catch(err) {
                // catch has no effect actually
            }
        });
    });
</script>
```

When I am alone in room with enabled camera and mic - everything is working properly.
But when someone join the same room, after click on button, call fail:

![obrazek](https://user-images.githubusercontent.com/7238863/96596787-61a9d000-12ed-11eb-9eea-3ffd483ca90b.png)

Same issue is in situation when I am alone without enabled cam.

**Comment by jallamsetty1** [comment] 2020-10-21 14:30
I am able to repro the case when the remote or local video is muted, will add a fix for that but this shouldn't happen when the remote video is not muted.

**Comment by network12** [comment] 2020-10-21 15:55
> 
> 
> I am able to repro the case when the remote or local video is muted, will add a fix for that but this shouldn't happen when the remote video is not muted.

Hello, I did retest with mic and cam enabled on both sides and I wasn´t be able to capture screen. Imediately when one attende leave room, it works properly... So Iam not sure if problem is only within on/off cam...

**Comment by jallamsetty1** [comment] 2020-10-21 18:59
@network12, can you try to reproduce it with this example - https://github.com/jitsi/jitsi-meet/blob/master/doc/examples/api.html when the video is not muted ?

**Comment by network12** [comment] 2020-10-21 20:51
> 
> 
> @network12, can you try to reproduce it with this example - https://github.com/jitsi/jitsi-meet/blob/master/doc/examples/api.html when the video is not muted ?

You are absolutely right - when I setup parentNode: undefined - I am finaly able to do screenshot!
But within this setting iframe is being initialized in the end of page - is there any other way how to setup position without specify parentNode param?

**Comment by network12** [comment] 2020-10-22 19:22
Hello, I have new knowledge regarding behavior of this issue - Issue doesn´t depend on number of attende in the room, but on fact which video stream do you have on your screen. Eg if you have participant´s video, no way to get screenshot, if you have tile view, no way to get screenshot. But if you have own camera on the screen, everything works flawless...

**Comment by jallamsetty1** [comment] 2020-10-22 21:13
captureLargeVideoScreenshot takes a screenshot of the participant on the large video container, i.e., whatever participant is on the stage not in tile view. The error that you are getting when the remote participant is muted should be fixed after the above mentioned PR gets merged.

**Comment by network12** [comment] 2020-10-23 19:52
Hello,
finaly we found root of this issue. This issue is not depending on count of attendees or parentNode param, but simply on browser. When you use Firefox, you are able to do screenshot only your camera, but noone other from the room. When you switch to chrome (or other browser with chromium core), everything works flawless.

**Comment by jallamsetty1** [comment] 2020-10-23 23:29
> Hello,
> finaly we found root of this issue. This issue is not depending on count of attendees or parentNode param, but simply on browser. When you use Firefox, you are able to do screenshot only your camera, but noone other from the room. When you switch to chrome (or other browser with chromium core), everything works flawless.

Thank you for the update, re-opening the issue since I am reproduce the issue on Firefox.

**Closed** 2021-01-13 19:24 UTC
Labels: api, devices, quality

**Comment by thisisnkc** [comment] 2025-02-17 07:48
is this issue fixed? facing this currently, able to capture screen shot on firefox mobile only when the large video is of the local participant, if the large video is of any other participant, its fails to capture?
