### ISSUE TITLE
Add "say yes" and "say no" actions

### ISSUE THREAD

**Issue by hialvaro** [jitsi/jitsi-meet#6034] opened 2020-04-15 07:54 UTC
It would be great to have more actions on Jitsi-Meet. There's already a "Raise hand" action but what about "Say yes", "Say no" and others? This would be some good features for class/meetings and I think they're easy to implement: Just copying the "raise hand" option and changing text should do the job imo; maybe with a timeout for the notification so users don't have to deselect the "Say yes"/"Say no" button.

Also being able to open a poll where people can vote by just the "Say yes"/"Say no" button, for example would be nice. Or just an open poll.

**Comment by Echolon** [comment] 2020-05-13 20:04
@hialvaro may you provide a better title for the issue?

**Comment by hialvaro** [comment] 2020-05-17 11:17
> @hialvaro may you provide a better title for the issue?
Any suggestion?

**Comment by luixxiul** [comment] 2020-05-17 11:37
`Add "Say yes" and "Say no"`.

**Comment by hialvaro** [comment] 2020-05-18 10:14
@luixxiul Done!

**Comment by Echolon** [comment] 2020-05-25 18:51
I think this is actually a duplicate of:
**Option to receive responses to yes-no questions during a course?** #5796

But as the title is written a bit hard to search for, I understand that this create a duplicate :(

**Closed** 2020-08-04 09:36 UTC
Labels: duplicate, feature-request
