### ISSUE TITLE
Add screen sharing on iOS app

### ISSUE THREAD

**Issue by GodcraftPlata** [jitsi/jitsi-meet#6980] opened 2020-06-08 02:39 UTC
**Is your feature request related to a problem you are facing?**
It isn’t much of an issue for me, but for a lot of people it sure is. I also gotta make a presentation soon and I need to share the slides, so yeah, it’ll be nice if you can add it.

**Describe the solution you'd like**
The app is supposed to have [this code](https://developer.apple.com/documentation/replaykit/rpscreenrecorder?language=objc) or something to make it happen, but idk if it’s the approach you want.

**Describe alternatives you've considered**
There isn’t really an alternative solution, but dunno.

**Comment by saghul** [comment] 2020-06-08 07:31
Duplicate of #5945

**Closed** 2020-06-08 07:31 UTC
Labels: duplicate
