### ISSUE TITLE
Some community website content pages are broken

### ISSUE THREAD

**Issue by jackkinsella** [jitsi/jitsi-meet#5159] opened 2020-03-14 14:37 UTC
Not sure where the right place is to report this, but I guess someone reading this will know. The `community.jitsi.org` website is giving malformed HTML:

e.g. https://community.jitsi.org/t/jitsi-meet-failed-to-access-your-camera-microphone/17141
![Screen Shot 2020-03-14 at 15 36 37](https://user-images.githubusercontent.com/151206/76684127-a360f280-6609-11ea-8cdb-f5550202bc4c.png)

**Comment by saghul** [comment] 2020-03-14 14:42
I see the content just fine (ussing Firefox on macOS) what browser are you using?

**Comment by yuriyprysyazhnyuk** [comment] 2020-03-14 22:06
The same problem for me.

![Screenshot from 2020-03-14 23-05-22](https://user-images.githubusercontent.com/25881449/76691174-741da600-6648-11ea-894f-f47d90b4e529.png)
![Screenshot from 2020-03-14 23-04-17](https://user-images.githubusercontent.com/25881449/76691176-77b12d00-6648-11ea-8a35-41afc92d0381.png)

**Comment by saghul** [comment] 2020-03-15 09:15
We use a hosted Discourse instance for our community. There is not much we can do, alas. Have you tried using Firefox?

**Comment by jackkinsella** [comment] 2020-03-15 11:52
I'm using Google Chrome v80

Can confirm the issue does not occur in Firefox.

**Comment by simevo** [comment] 2020-03-16 10:34
This is unreproducible here on desktop Chromium and Firefox, but I have it on an iPad with iOS 12.4.5.

The screenshot is similar to that posted above, but not exactly the same:
![IMG_0842](https://user-images.githubusercontent.com/8254819/76747309-3ec4a580-6779-11ea-9c6f-b67f857a5716.PNG)

It stays there after repeated F5 and rebooting the device.

I run the remote inspector from MacOS Safari to see what is going on, this is a screenshot of the console:

![Schermata 2020-03-16 alle 11 17 18](https://user-images.githubusercontent.com/8254819/76747221-1a68c900-6779-11ea-9d28-bc3b8ac059c8.png)

and here is the text:
```
The source list for Content Security Policy directive 'script-src' contains an invalid source: ''report-sample''. It will be ignored.
Unrecognized Content-Security-Policy directive 'worker-src'.
Pagina ricaricata a 11:13:02
[DEPRECATION] `ember-addons/ember-computed-decorators` is deprecated. Please use `discourse-common/utils/decorators` instead. p — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:74206
[DEPRECATION] `ember-addons/ember-computed-decorators` is deprecated. Please use `discourse-common/utils/decorators` instead. p — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:74206
[DEPRECATION] `ember-addons/ember-computed-decorators` is deprecated. Please use `discourse-common/utils/decorators` instead. p — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:74206
[DEPRECATION] `ember-addons/ember-computed-decorators` is deprecated. Please use `discourse-common/utils/decorators` instead. p — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:74206
  exceptionHook — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:3855jQuery.Deferred exception: undefined is not a function (near '...l.replace...') (2)
  performEmojiUnescape — _pretty-text-bundle-b028b1d5eed228f191f4f25757a12c99d1209f6a9ce91f98c6d378dd3589df7d.js:324
  (funzione anonima) — _application-beb5fe40f48d0eb0c699224477104fb07f460b455d254e2d3c9fbda281c3d622.js:61469
  value — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:13471
  value — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:59854
  initialize — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:58965
  initialize — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:60203
  (funzione anonima) — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:60175
  evaluate — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:59374
  evaluateSyscall — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:62789
  evaluateInner — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:62735
  evaluateOuter — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:62727
  next — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:64859
  render — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:19073
  V — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:25920
  _renderRoots — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:19372
  _renderRootsTransaction — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:19410
  _renderRoot — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:19333
  _appendDefinition — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:19251
  appendOutletView — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:19237
  invoke — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:66278
  flush — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:66164
  flush — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:66372
  _end — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:66948
  end — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:66634
  _run — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:67003
  e — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:3571
  (funzione anonima) — _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:3639
  undefined
Failed to load resource: the server responded with a status of 404 () https://sjc5.discourse-cdn.com/try/assets/plugins/discourse-local-dates-b357ebdc27fa07ebb7aa74575132ca1dc8c76a7315801218013dffc3705c0356.js.map
Failed to load resource: the server responded with a status of 404 () https://sjc5.discourse-cdn.com/try/assets/plugins/discourse-checklist-4d8d1211e6834d312fb23fbceb481b59d30fb7ad666efcefea72f786e4cee402.js.map
TypeError: undefined is not a function (near '...l.replace...') _ember_jquery-3ed0ac532033dfeecf1ec0676df6716cd7076530930c656754ccf103d35b3e23.js:3864
Failed to load resource: the server responded with a status of 429 () https://community.jitsi.org/logs/report_js_error
```

**Comment by simevo** [comment] 2020-03-16 10:41
I researched on Discourse community website and these seem relevant:

- `ember-addons/ember-computed-decorators is deprecated. Please use discourse-common/utils/decorators`: https://meta.discourse.org/t/removal-of-ember-addons-ember-computed-decorators/132977
- `Failed to load resource: the server responded with a status of 429`: https://meta.discourse.org/t/understanding-logs-report-js-error-429/141744/3
- `The source list for Content Security Policy directive 'script-src' contains an invalid source: ''report-sample''. It will be ignored.` https://meta.discourse.org/t/update-from-2-4-0-beta9-to-2-4-0-beta10-yields-page-with-no-content-cloudflare-rocket-loader/139433

the latter seems the root issue; I suggest you get in touch with your Discourse forum hosting support

**Comment by saghul** [comment] 2020-03-17 20:12
I'm closing this since we use the Discourse in hosted mode, so it's up to them to fix. Sorry for the trouble!

**Closed by saghul** 2020-03-17 20:12 UTC
