### ISSUE TITLE
Call stays active

### ISSUE THREAD

**Issue by NoahSBG** [jitsi/jitsi-meet#7149] opened 2020-06-24 19:29 UTC
Description:
In the official Android App from the PlayStore the Call doesn't properly end when the red "hang up call" button is pressed and the app is closed by pressing the "home button" of the phone.
At least the audio gets send to other participants of the call without the users notice, receiving and playing the sound of active callers does't work on the "closed" app, so communication is not possible.

might be possible it's related to #7090
Only ends the call if the app is deleted from the lastr opened apps.

Steps to reproduce:

1. Have an active session with 2 participants
2. End the call by just pressing the red hang up symbol
3. one party rejoins the meeting and hears the sound from the other

Expected behavior:

Call is properly ended when pressing the red hang up symbol, no need to delete the app from last opened apps.

Actual behavior:

Meeting still ongoing in the background, without notice. possible to listen to the others device's microphone.
Call only ends when app is forced stopped from the app control panel or deleted from the last opened apps.

Client information:

both sides used the official app directly from the playstore

Additional information:

sounds somewhat similar to issue #7090

**Comment by franken300** [comment] 2020-09-28 11:27
This was not resolved as far as I know. However, I am unable to reproduce this issue. 
@NoahSBG Can your verify if this is still an issue?

**Comment by saghul** [comment] 2020-09-29 08:20
This might have been related to native call integration, which got disabled a few releases ago. Tentatively closing.

**Closed by saghul** 2020-09-29 08:20 UTC
Labels: android, mobile, privacy
