### ISSUE TITLE
Records on Jisti

### ISSUE THREAD

**Issue by kamiquase** [jitsi/jitsi-meet#6239] opened 2020-04-20 18:27 UTC
Hello, I will try to record a masterclass the 30 April and I wonder if is there any chance that the overcharge of records and streaming will still be busy by then.

**Comment by jacobgonzales20** [comment] 2020-04-20 19:24
no way of knowing, just make sure you start the recording early

**Comment by kamiquase** [comment] 2020-04-20 19:26
Ok. Thank you!

**Comment by campelo** [comment] 2020-04-22 00:07
Duplicate of #6257

**Closed** 2020-05-13 14:58 UTC
Labels: duplicate
