### ISSUE TITLE
Extremely slow on Motorola Moto G (2nd gen)

### ISSUE THREAD

**Issue by tobiasmuecksch** [jitsi/jitsi-meet#1814] opened 2017-07-24 09:35 UTC
I've testet the Jitsi Meet App (Version 1.6.46) on my android device and the video transmission is extremely slow. And I've observed that it even slows down more as time goes by.

Call Partner 1:  Motorola Moto G, 2nd gen, Android 6.0
Call Partner 2: Chrome 59, Mac OS 10.12.5
-> both connected to a WiFi with sufficient bandwidth (~3 mb/s - according to speedtest on both devices)

Do you need more information?

**Comment by saghul** [comment] 2017-07-24 11:43
While this may sound counter intuitive, does the situation improve if you add a third participant?

**Comment by tobiasmuecksch** [comment] 2017-07-24 12:41
@saghul Yes. It's improving with three participants. But I'm experiencing black screens from time to time. In chrome it's claimed that this has to do with a low bandwidth.

**Comment by saghul** [comment] 2017-07-24 13:23
> Yes. It's improving with three participants.

Dammit. This is most likely caused by the fact that we now (try to) use H264 for 1-1 calls. When there are at least 3 participants VP8 is used, which should perform worse, but I guess the H264 encoder / decoder is not as polished, oh well.

This is related to the phone itself, rather than the Android version, I'll update the title accordingly.

> But I'm experiencing black screens from time to time.

We are currently working on addressing this.

> In chrome it's claimed that this has to do with a low bandwidth.

If we don't detect enough bandwidth for all video streams (each HD stream could take between 1 and 2.5 Mbps) we suspend video from inactive participants, this is expected behavior.

**Comment by tobiasmuecksch** [comment] 2017-07-24 13:38
> This is related to the phone itself, rather than the Android version [...]

That's the big disadvantage of Android versus iOS devices. You never have the chance to know, that it will work on all devices, because there is such a wide range of completely different devices...

I will try it on another, newer android phone on Wednesday and report back then.

**Comment by saghul** [comment] 2017-07-24 14:25
Thanks!

**Comment by gpolitis** [comment] 2017-07-25 09:07
> But I'm experiencing black screens from time to time. In chrome it's claimed that this has to do with a low bandwidth.

This may also be caused by a bug in the bridge (https://github.com/jitsi/jitsi-videobridge/pull/503). A fix is merged but not released on https://meet.jit.si yet.

**Comment by tobiasmuecksch** [comment] 2017-07-26 08:09
In version 1.7.49 it works perfectly fine! What has changed ?!

**Comment by tobiasmuecksch** [comment] 2017-07-26 08:20
I have to clarify me previous statement. It's working perfectly under the following circumstances:
Caller 1: iPhone 6
Caller 2: Moto G (2nd gen)

But the performance extremely declines when Caller 3 joins the party.

Caller 1: iPhone 6
Caller 2: Moto G (2nd gen)
Caller 3: Google Chrome (60.x on Mac OS Sierra)

- OR -

Caller 1: Moto G (2nd gen)
Caller 2: Google Chrome (60.x on Mac OS Sierra)

performes poorly too. Chrome & iPhone performs good.

**Comment by tobiasmuecksch** [comment] 2017-07-26 08:34
@saghul 

I've tested a few more:

===
Caller 1: iPhone 6
Caller 2: iPad Air 2

-> Good performance
===

Caller 1: iPhone 6
Caller 2: iPad Air 2
Caller 3: Chrome

-> Good performance (but the transmission of the iPad is scrambled)

===

Caller 1: iPhone 6
Caller 2: iPad Air 2
Caller 3: Moto G (2nd gen)

 -> bad performance

**Comment by saghul** [comment] 2017-07-26 08:50
Thanks for your thorough analysis. I'll try to reproduce it locally.

**Comment by tobiasmuecksch** [comment] 2017-07-28 09:45
@saghul I've investigated this issue on a newer Android device.

Samsung Galaxy J5 (Model 2017)

The performance is better. In some 1-1 calls there were permanent black screens. Sometimes the video transmission from the J5 was slow and shifted in time. But overall in most cases the performance was satisfying.

*Interesting*
I've observed something very interesting! When the Samsung J5 joins a 1-1 call before the Moto G, the experience is perfect.
But when the Moto G joins the call first, it's very bad. I was able reproduce this behavior in 10 calls (same behavior in every call).

@saghul Do you have any idea why it's important who joins the call first?

**Closed** 2018-12-11 00:49 UTC
Labels: project:react-native, type:support, wontfix
