### ISSUE TITLE
Video and Screen Share issues on Safari 14.0 on Mac OS X

### ISSUE THREAD

**Issue by htcheng** [jitsi/jitsi-meet#7984] opened 2020-10-27 06:41 UTC
Possibly related to issue [https://github.com/jitsi/jitsi-meet/issues/7953] regarding Safari 14 on iOS, but this issue affects Macs running OS X Catalina, Big Sur and Mojave using Safari Version 14.0 (15610.1.28.1.9, 15610) and variants.

### Description:

Since Apple released Safari 14.0, we've noticed two issues with Jitsi Meet that were not present before with users running previous versions of Safari on Macintosh:

1) When some users are screen sharing, Safari 14 users will see a black screen in Speaker View but the screen sharing will be visible in Tile View. This only affects Safari 14 users, previous Safari versions worked as do Chrome and Firefox clients on Mac and Windows.
2) With some users of Safari 14, audio for all participants will be heard but some of the video feeds from other participants will not be visible (i.e. black screen with no video, but with the avatar).

### Steps to reproduce:

1. In a six person video conference (not 2 with P2P mode) with four participants using either Chrome Windows, Chrome Mac, or the Jitsi-Meet Electron client, if other participants join using Safari 14 (on OS X 10.14, 10.15 or 10.16), sometimes (not every time), when one of the non-Safari participants (e.g. Mac user on Chrome) starts sharing their screen in Jitsi, the Safari 14 users will see a Black Screen in Speaker View, but when they change to Tile View, the Screen Sharing will be see Tile View. None of the other browsers are affected.
2. We've tried this on meet.jit.si, beta.jit.si and alpha.jitsi.net and it is reproducible across all three platforms. We also tried it with a stock Jitsi VM built from source and all exhibit this behavior as of 10/26/20.
3. The behavior is not reproducible when two users are on Safari 14 and when two users on two different computers join a conference with Chrome and Safari 14 running on each computer (so 4 participants in a Jitsi room running from two computers, each with Chrome and Safari 14 joined as a participant), but manifests itself when more than 2 participants from more than 2 locations join.
4. A seemingly related issue is that when participants have their video turned on, Safari 14 users will see that the video is on from a participant in the filmstrip, but clicking on the participant doesn't show the video feed, but only a black screen with the participants avatar (like when video is off), but the participant is sharing their video and other participants can see the video feed - but Safari 14 users do not see the video either in Tile View or Speaker View.

### Expected behavior:

1) When a participant is sharing their screen, Safari 14 users should be able to see the screen share in both Speaker View and Tile View.
2) When a participant has their video feed turned on, Safari 14 users should be able to see a participant video feed.

### Actual behavior:

1. Safari 14 users see only a black screen when another participant is sharing their screen in Speaker View, but can see the screen share in Tile View.
2. when participants have their video turned on, Safari 14 users will see that the video is on from a participant in the filmstrip, but clicking on the participant doesn't show the video feed, but only a black screen with the participants avatar

### Server information:

- Jitsi Meet version: 2.0.5142-1 as well as versions on meet.jit.si, beta.jit.si and alpha.jitsi.net as of 10/26/20
- Operating System: Ubuntu 18.04LTS on GCP for the server compiled from Source

### Client information:

- Browser / app version: Safari Version 14.0 (15610.1.28.1.9, 15610) and variants
- Operating System: Mac OS X 10.14.x, 10.15.6, 10.16.x

### Additional information:

None at this time.

**Comment by beyondlevi** [comment] 2020-10-27 11:00
This is happening consistently for us. We tested with our deployment and alpha.jitsi

**Comment by MarkErik** [comment] 2020-10-29 13:17
I am also experiencing these issues with Safari 14 as described above.
e.g. Video feeds from other participants will not be visible (i.e. black screen with no video, but with the avatar)

**Comment by gh264367** [comment] 2020-10-30 18:00
Since this problem is known by Jitsi, is there an estimate time of when a fix for this will be available?

**Comment by jallamsetty1** [comment] 2020-11-09 16:23
Duplicate of #7953

**Closed** 2022-04-30 23:34 UTC
Labels: wontfix, web, quality, browser-support
