### ISSUE TITLE
add new language

### ISSUE THREAD

**Issue by TivanDev** [jitsi/jitsi-meet#7436] opened 2020-08-01 11:37 UTC
How can I add another language?
I want to add Persian language and RTL direction in jitsi meet
please share a way to add new language

**Comment by TivanDev** [comment] 2020-08-01 11:47
CLA Already signed

**Comment by Echolon** [comment] 2020-08-02 20:58
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

@TivanDev: Please checkout those two links: https://github.com/jitsi/jitsi-meet/issues/6751 and https://github.com/jitsi/jitsi-meet/tree/master/lang#translating-jitsi-meet. To my understanding it does not work at the moment.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-08-02 20:58 UTC
Labels: localization, question
