### ISSUE TITLE
Couldn't hold 3rd part conference

### ISSUE THREAD

**Issue by rachelxj** [jitsi/jitsi-meet#2211] opened 2017-11-24 03:46 UTC
Hi,
I deployed jitsi-meet by following the quick-start on local VM with fixed IP. When the third person joins the conference, the screen goes black, the audio is gone too. What happened? And I don't know how to restart jitsi-meet, from the detailed manual install guide, it talks about nginx, but I couldn't find nginx on my VM being installed. 

invoke-rc.d nginx restart
invoke-rc.d: unknown initscript, /etc/init.d/nginx not found.

**Comment by rachelxj** [comment] 2017-11-24 03:54
Here are the logs

Jicofo 2017-11-23 19:54:03.065 WARNING: [483] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
        at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1969)
        at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
        at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:312)
        at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1846)
        at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1655)
        at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:260)
        at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1086)
        at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1020)

**Comment by saghul** [comment] 2017-11-24 09:45
What do you see in the javascript console?

**Comment by damencho** [comment] 2017-11-24 15:02
How did you install? Using the quick-install method. 
The problem is that jicofo cannot connect to prosody, as prosody is not using a correct and valid certificate on the XMPP port. This is fixed in the Debian packages and should be fine after an upgrade.

**Comment by rachelxj** [comment] 2017-11-29 01:41
OK. thanks, let me try it

**Comment by classfiy** [comment] 2018-05-04 03:51
@rachelxj Have you solved your problem? I also met this problem; could you give me some help?

**Closed** 2018-12-12 09:35 UTC
Labels: wontfix
