### ISSUE TITLE
Can we link external sources of video and audio in jitsi

### ISSUE THREAD

**Issue by swapwaky** [jitsi/jitsi-meet#6266] opened 2020-04-21 11:13 UTC
i would like to know if any possibilities to used some external sources of video and audio in jitsi ?

**Comment by rcsarv** [comment] 2020-04-21 14:35
It's not possible to, you need to use self-hosted server

**Comment by rcsarv** [comment] 2020-04-21 14:37
Please explain, what you mean by the external source.  It's already supporting Youtube as an external source.

**Comment by swapwaky** [comment] 2020-04-21 14:44
External sources like multiple camera or any video if I want to directly
wanna show them.

**Comment by luixxiul** [comment] 2020-04-21 17:55
You can use screen sharing. Is it not enough?

**Comment by Echolon** [comment] 2020-05-13 20:22
I will close this with reference to this: #5146
See also: #5403

Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-05-13 20:22 UTC
