### ISSUE TITLE
Error obtaining microphone permission with chromium browser

### ISSUE THREAD

**Issue by jlegido** [jitsi/jitsi-meet#4455] opened 2019-07-17 09:29 UTC
## Description

An error "Error obtaining microphone permission" appears when accessing jitsy meeting from chromium browser.

## Current behavior

An error "Error obtaining microphone permission" appears when accessing jitsy meeting from chromium browser.

## Expected Behavior

First time a dialogue asking for granting permissions of mic should appear.

Subsequent accesses to the same conference URL should allow using the mic without asking for permissions (obviously if previously permission has been granted).

## Possible Solution

Manually force chromium to allow a URL accessing microphone.

## Steps to reproduce

1. Get the repo

git clone

2. Enter the directory

```
cd docker-jitsi-meet
```

3. Adjust env variables

```
cp env.example .env
```

4. Startup the environment

```
docker-compose up -d
```

5. Open chromium browser

6. Proceed to:

https://localhost:8443/test

7. Grant permissions to cam

# Environment details

Chromium version: Version 73.0.3683.75 (Developer Build) built on Debian buster/sid, running on Debian bullseye/sid (64-bit)

It works with Firefox (version 60.8.0esr (64-bit))

**Comment by jlegido** [comment] 2019-10-15 11:06
Hi there.

I'm still able to reproduce the issue, so adding a comment.

Thanks.

**Comment by jlegido** [comment] 2020-01-13 12:06
Hi there.

I'm still able to reproduce the issue, so adding a comment. Chromium version:

```
Version 76.0.3809.100 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)
```

Nobody else is able to reproduce this issue?

Thanks.

**Comment by saghul** [comment] 2020-01-14 09:40
Sorry about that @jlegido.  Can you reproduce the problem when accessing https://meet.jit.si/test123?

I think it might have to do with self-signed certificates.

I cannot reproduce this on Chromium 78 (Debian buster/sid build) when accessing meet.jit.si

**Comment by jlegido** [comment] 2020-01-14 09:44
Yes, I was able to reproduce it just clicking your link.

If nobody else is experiencing this issue I guess the root cause is local, so this issue can be closed.

Thanks (moltes gràcies) for your time @saghul.

**Comment by saghul** [comment] 2020-01-14 09:47
> Yes, I was able to reproduce it just clicking your link.

Hum, that's bad. Can you try this page? https://test.webrtc.org/ if it also fails there there must be something Chromium doesn't like about your system 😢

**Comment by jlegido** [comment] 2020-01-14 10:18
Very useful resource indeed, same issue.

I filled [this bug report](https://test.webrtc.org/)

**Comment by saghul** [comment] 2020-01-14 10:37
Thanks! I'll close this then, since there is nothing we can do on our side.

**Closed by saghul** 2020-01-14 10:37 UTC
