### ISSUE TITLE
Can't join meet for more than tow people?

### ISSUE THREAD

**Issue by kangzhe0000** [jitsi/jitsi-meet#2440] opened 2018-01-31 08:49 UTC
I set up a meet, but when third people join, there is no image.  Is the service need to connect to the Internet?  Now our service deploy on Lan.

**Comment by saghul** [comment] 2018-01-31 09:27
Can you share the logs in the JS console?

**Comment by slavakisel** [comment] 2018-01-31 15:34
@saghul Having similar issue here - for two people conference works without issues, as soon as the third person joins there video disappears and we can't hear each other. Logs:
[1st person](https://pastebin.com/T8s2YjPK)
[2nd person](https://pastebin.com/diccZF1h)
[3rd person](https://pastebin.com/JjwrcEnU)

**Comment by saghul** [comment] 2018-01-31 15:44
Hum I connected to your server myself and got the same result, but no errors... @paweldomas maybe you can cake a look if you have time?

@slavakisel What versions have you installed?

**Comment by damencho** [comment] 2018-01-31 15:49
@slavakisel Have you checked your jicofo logs? This is like there is no jicofo in the room.

**Comment by slavakisel** [comment] 2018-01-31 16:12
@damencho @saghul  I have installed everything via apt package `jitsi-meet`. Here is what I have:
- jicofo version 1.0-388-1
- jitsi-videobridge version 1011-1
- jitsi-meet version 1.0.2635-1

I've took a look at jicofo and videobridge logs, unfortunately I don't see any errors there

[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1682366/jicofo.log)
[videobridge.log](https://github.com/jitsi/jitsi-meet/files/1682367/videobridge.log)

**Comment by damencho** [comment] 2018-01-31 16:26
When you installed it, have you followed all the steps from:
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
As your jvb is behind NAT I see it advertises both ip-addresses, but have you forwarded 10000 udp and tcp 443 to the machine where jvb is running?

**Comment by saghul** [comment] 2018-01-31 17:04
@damencho Even if he didn't, shouldn't we have detected an ICE failure?

**Comment by slavakisel** [comment] 2018-01-31 17:43
I am not sure if it is applicable to my case... I am running jitsi on VPS with public IP address, no NAT involved

**Comment by kangzhe0000** [comment] 2018-02-02 03:21
I find the problem, stun pointed to a intranet IP. How can I modify this config?
![stun](https://user-images.githubusercontent.com/22000426/35715062-3d48758a-080b-11e8-8eb5-a793c915d3dc.png)

**Comment by saghul** [comment] 2018-02-02 07:37
Have you done what @damencho mentiomned here? https://github.com/jitsi/jitsi-meet/issues/2440#issuecomment-361987233

**Comment by kangzhe0000** [comment] 2018-02-02 07:40
I have ran the server in Internet,not in Lan.  Does it must do as @damencho mentiomned?

**Comment by saghul** [comment] 2018-02-02 07:41
If the server is on the public internet then you shouldn't need it, but you seem to be behind some NAT?

**Comment by kangzhe0000** [comment] 2018-02-02 07:54
Yes, I use NAT forwarding.  I will try it, thank you

**Comment by kangzhe0000** [comment] 2018-02-05 09:16
@damencho  10000 udp and tcp 443 to the machine is running， and localhost IP is also  configured. but the problem is still exist.

**Comment by kangzhe0000** [comment] 2018-02-05 09:37
stun server's destination is 192.168.10.190, how can I modify it, replace of another IP?

**Comment by kangzhe0000** [comment] 2018-02-05 11:45
I use wireshark to capture, and I find that there is no UDP  communication. The local video stream is not uploaded when the third person join.

**Comment by saghul** [comment] 2018-02-05 13:16
@kangzhe0000  Have you configured those ice4j parameters @damencho mentioned? If so, please share your config here.

**Comment by kangzhe0000** [comment] 2018-02-06 03:49
[jitsi.meet.txt](https://github.com/jitsi/jitsi-meet/files/1697681/jitsi.meet.txt)
[sip-communicator.txt](https://github.com/jitsi/jitsi-meet/files/1697682/sip-communicator.txt)

@saghul

**Comment by damencho** [comment] 2018-02-06 04:45
I just tested it and it works for me. Do you still see the problem?

**Comment by kangzhe0000** [comment] 2018-02-06 05:44
no error logs,but the local video stream is not uploaded when the third person join.

**Comment by woodsjail** [comment] 2018-02-17 00:15
I am also having this problem. Perfect video conference between two people, but then when a third person joins the entire room drops. I can still see people connected but there is no audio or video. Hosted on an Azure server with an open connection. Any help would be appreciated. I would also like to know where the logs are so that I may post them if needed. I have only tweaked a few things on the server as far as graphics and naming. Jigasi is also installed, but not currently working. Would that cause an issue? Please let me know thanks again!

**Comment by f987002856** [comment] 2018-02-24 09:27
@woodsjail I am also having this problem，Have you solved it?

**Comment by damencho** [comment] 2018-02-24 14:16
@woodsjail and @f987002856 Have you checked this: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration ?
Make sure ports are open and forwarded and correct ip addresses are there and jvb is restarted after the changes.

**Comment by f987002856** [comment] 2018-02-26 08:48
@damencho Thank you for your answer. I test it in the same inner network.
there are two options i can not understand:
1、you said "make sure ports are open",It refers to program deployment device port or public network port?
2、how to restart jvb? service jitsi-videobridge restart?
Looking forward to your reply.

**Comment by damencho** [comment] 2018-02-26 14:38
1. If your jvb is running on a machine with public address this refers to the firewall. If your jvb is behind nat(not running on a machine with a public address), these ports need to be open at the device/machine with the public address and forwarded to the jvb machine as it will receive the traffic.
2. /etc/init.d/jitsi-videobridge restart

**Comment by f987002856** [comment] 2018-02-26 15:43
@damencho thank you.
lf my jvb is behind nat and all of user in the same 
 Intranet,can I not open the port of the public network machine? In other words,do i have to open the port in the public address machine if more than two people come in?
Because of the public address machine belongs to company and my department has no right to amend it,so there has other way to resolve it?
i am looking forward to your answer,thank you!

**Comment by damencho** [comment] 2018-02-26 15:47
If the users can access directly the ip address of the jvb machine and its ports then you can do that, you don't have to setup the private and public address in the jvb config and leave it by default and your deployment will be usable only from your intranet.

**Comment by f987002856** [comment] 2018-02-27 10:06
@damencho I'm sorry to bother you again.
Today I tried to debug my service again,but the problem is still not solved.
I tried to access the service port by telnet ip port and found that these ports can be accessed such as 80,443,5222,5280. But the port 5347 and 4443 can not connect.
Then i use command netstat -an | grep 5347  and netstat -an | grep 443,the picture below is the result
![j 4alqe4sa cf u5dh7v_ c](https://user-images.githubusercontent.com/12999173/36722262-0a789e8c-1be8-11e8-9b21-9d2fa2dfdde8.png)
I want to know the port 5347 is normal? If not normal, how do I modify?
During debugging I found that jvb was not used at all.Is the port 5347 problem?
The below is my jvb config:
![czi1 kgl1 3 us _c zio](https://user-images.githubusercontent.com/12999173/36722584-d98275d6-1be8-11e8-847c-bfdacb172332.png)
Looking forward to your respond,Thank you again.

**Comment by damencho** [comment] 2018-02-27 14:22
So port 5347 is the default component port of prosody. I suppose jvb and prosody are on the same machine. By default jvb tries to connect to localhost:5347. 
You can check jvb logs for errors. 
When you were installing jitsi-meet you entered as a name for the service: 10.25.25.115, it this correct?

**Comment by f987002856** [comment] 2018-02-27 15:22
@damencho Yes,i entered the 10.25.25.115 when it let me enter the domain.please tell me how to check jvb logs,maybe i can find some useful
logs.Thank you!

**Comment by damencho** [comment] 2018-02-27 15:57
The logs are in /var/log/jitsi/jvb.log

**Comment by f987002856** [comment] 2018-02-28 09:03
@damencho Hi,thank you very much for your guidance!
I checked the jvb.log, but I did not find anything out there.I also checked the browser's console information.I found that when the third person entered the room, the console would have the following message,it said "Peer to Peer connection closed" and "Not adding remote JVB tracks - no session yet.Do you konw the reason?
![1519806211 1](https://user-images.githubusercontent.com/12999173/36778642-4d9d5372-1ca8-11e8-9771-4cde42fe54f6.jpg)

The below is the jvb.log message.All are the following information, no other information.please help me to see if there is a problem.
![vqhqw 1k6w7gkgrkp xwiq](https://user-images.githubusercontent.com/12999173/36778860-0428cbee-1ca9-11e8-9a25-74658f984e3d.png)
![_vk97i1m6cit wz6u nxp](https://user-images.githubusercontent.com/12999173/36778864-05f1487a-1ca9-11e8-8d67-233b1f8c1af1.png)
Thank you very much for your guidance again!

**Comment by damencho** [comment] 2018-02-28 13:51
Apparently the clients do not have any information for bridge ... What about jicofo logs?

**Comment by f987002856** [comment] 2018-02-28 14:52
@damencho. icofo log has error as. issues #2117. 
my service has no domain,only has ip address and use. /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh to create letsencrypt,but it said i used ip without domain,so can not create letsencrypt.
how can i resolve it?use custom ssl to instead of it?

**Comment by damencho** [comment] 2018-02-28 15:03
Have you touched the auth...domain settings or certificates?
The certificate used by jicofo is internal, generated and made as trusted on the local machine only. Has nothing todo with web or letsencrypt. 
Default installations mange those and you should not see that problem. You are basically running without jicofo at the moment.
I don't see the point of installing a certificate at all, you can continue using self signed anyway your deployment is internal and is not accessed by public address.

**Comment by f987002856** [comment] 2018-02-28 15:29
I don't setting anything,I install service by quick-install and enter my ip address,then run /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh.
But when i run /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh,it has error tells me can't create letsencrypt by ip and i ignore it.
you said my service running without jicofo,but if  i run /etc/init.d/jicofo stop,the service peer to peer will can't run normal.so i dont konw whether jicofo is running in.my service.if not,please tell me what should i do.thank you for your response

**Comment by damencho** [comment] 2018-02-28 16:28
@f987002856 
I just did a quick test. I've created a DO VM with ubuntu 16.04, installed jitsi-meet as said in the quick-install guide, entering the ip address of the machine, running the let's encrypt script I received the error "Requested name X.X.X.X is an IP address. The Let's Encrypt certificate authority will not issue certificates for a bare IP address.", restarted jvb as it seems it was stopped in the process of the let's encrypt script and due to the error was not started again and everything is working fine, I'm able to enter with 3 participants without a problem.
```
echo 'deb https://download.jitsi.org stable/' >> /etc/apt/sources.list.d/jitsi-stable.list
wget -qO -  https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
apt-get update
apt-get -y install jitsi-meet
/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
/etc/init.d/jitsi-videobridge restart
```
I also tried restarting jicofo and there is no problem with connecting to prosody. 
So something broke it on your side. 
Did you follow the same steps? What is your OS and version?

**Comment by f987002856** [comment] 2018-03-01 01:17
@damencho 
Thank you very much for your guidance.
My OS is ubuntu 16.04 and not install firewall. All my steps are the same as yours and I do nothing else.
The error that appear are the same as yours.
Now i will create new VM with ubuntu 16.04 by Oracle VM VirtualBox and install jitsi-meet as your guide.
I hope that there will be no problem again,haha.

**Comment by damencho** [comment] 2018-03-01 05:06
I will close this one, as it gathered too many different problems. Most of these come from wrong configuration or missed the steps about ports and addresses.

**Closed by damencho** 2018-03-01 05:06 UTC
