### ISSUE TITLE
IFrame API: Desktop Safari (13.1 od Ipad OS 13.5): TypeError: null is not an object (evaluating 'e.getAudioTracks') on Camera Activation 

### ISSUE THREAD

**Issue by informatikTirol** [jitsi/jitsi-meet#6865] opened 2020-05-26 06:51 UTC
On current Desktop Safari (13.1 od Ipad OS 13.5) I get an JS exception when I want to activate the camera. 

`TypeError: null is not an object (evaluating 'e.getAudioTracks')`

This error happens only if the room is all-ready created. If I am the first in the room, then the camera will be activated. 
When I join the room without the IFRAME API directly with the jitsi meet url, then it works. 
I have tested it with the latest nightly build (jitsi-meet_4649), the current stable version and the the public server https://meet.jit.si

Mobile Safari (IOS 13.5) works with IFrame API Setting
```
configOverwrite: {
 disableDeepLinking: true,
}
```

If the iframe api call is made on localhost, it is working... you have to deploy it to remote to see the error

**Comment by saghul** [comment] 2020-05-26 07:11
Ping @jallamsetty1

**Comment by jallamsetty1** [comment] 2020-05-29 14:42
Can you please check if you are still reproducing this on https://alpha.jitsi.net ?

**Comment by informatikTirol** [comment] 2020-05-30 04:21
I get the same error message on https://alpha.jitsi.net 

https://www.dropbox.com/s/lxkjovqcmv6m0aw/DbCC%201.jpg?dl=0

**Comment by informatikTirol** [comment] 2020-05-30 04:55
Safari gets unresponsive on https://alpha.jitsi.net when using the Aframe API (https://alpha.jitsi.net/libs/external_api.min.js)  
With the nightly build (jitsi-meet_4649) thats ok.

**Comment by informatikTirol** [comment] 2020-05-31 04:56
Important: if the iframe api call is made on localhost, it is working... you have to deploy it to remote   to see the error

**Comment by torreylyons** [comment] 2020-06-02 04:15
> Safari gets unresponsive on https://alpha.jitsi.net when using the IFrame API (https://alpha.jitsi.net/libs/external_api.min.js)
> With the nightly build (jitsi-meet_4649) thats ok.

Note the lockup on Safari is likely due to callstats.io being enabled on https://alpha.jitsi.net. As I noted at https://community.jitsi.org/t/safari-lockup-with-callstats-io/58863?u=torrey, this is a known issue with callstats.io and Safari. This lockup happens regardless of whether Jitsi Meet is in an iFrame or not.

**Comment by jallamsetty1** [comment] 2020-06-02 15:08
> Important: if the iframe api call is made on localhost, it is working... you have to deploy it to remote to see the error

Will you be able to share a link to your deployment so that I can try it there and see what is happening ?

**Comment by informatikTirol** [comment] 2020-06-03 04:46
I prepared a special testversion.

https://jitsi.informatik.tirol/

On the right upper corner you can switch between meet.jit.si and alpha.jitsi.net

**Comment by informatikTirol** [comment] 2020-06-03 05:02
The bug is also on IOS 13.5.1, Iphone X

**Comment by saghul** [comment] 2020-06-03 05:34
This is very helpful, thank you! I could reproduce the problem on an iPhone 7 Plus running latest iOS 13.

**Comment by informatikTirol** [comment] 2020-06-03 05:56
Glad that it helps. One note: The switch in the upper right corner does not change the external API, I have included https://alpha.jitsi.net/libs/external_api.min.js in the index.html

**Comment by jallamsetty1** [comment] 2020-06-03 12:15
Thank you, this is very helpful. I was able to reproduce the issue as well.

**Comment by jallamsetty1** [comment] 2020-06-04 15:21
I merged a fix to the master, it should be available in the next nightly build. Please give it a try and let me know if it fixes the issue for you, thanks !

**Comment by informatikTirol** [comment] 2020-06-05 07:39
It works, very cool, thank you! I have tested on IOS; IPAD OS and MAC OS

**Comment by luixxiul** [comment] 2020-06-05 07:41
@informatikTirol if the issue was confirmed to have been fixed and no issue left to be fixed, let's close the issue. thanks!

**Closed** 2020-06-05 07:42 UTC
Labels: api, browser-support, info:feedback-needed
