### ISSUE TITLE
Screen sharing

### ISSUE THREAD

**Issue by lweffer** [jitsi/jitsi-meet#2233] opened 2017-11-29 14:49 UTC
Everytime I try to share the screen it fails.

**Comment by damencho** [comment] 2017-11-29 14:51
Can you share more details?
Are you using meet.jit.si? Are you using custom deployment, was that deployment configured the desktop sharing? What is the error you have? Pasting js console logs will help to catch the problem.

**Comment by legalmat** [comment] 2017-12-02 13:10
Hi, this is a really weird tool meet.jit.si does not a single time do what is should nor what it is supposed to do. What a chaos. Completely unusable.am on Linux, KDE Neon, with latest stable Firefox , then I go to the address and want to share with someone and when I click screensharing it does this: https://prnt.sc/hi3s2j
Ok, my camera I can only see myself and the other party I can kick when I open the room or the other opened the room. But she was on a Mac. You know? haha. literally nothing works. And when I want to download meet also nothing starts... It seems to be server only tool
this is really very bad usability. sorry, I know its open source, but someone can explain how things work or not?

**Comment by damencho** [comment] 2017-12-02 15:37
What is the exact problem you are facing with meet.jit.si? Have you tried with chrome/chromium, Firefox is known to use a lot of CPU when doing webrtc calls.
The screenshot you have shown is how it is supposed to work, this is when you are showing the screen which you are sharing. The same will happen if you put a mirror in front of another mirror. When using screen sharing it is supposed that the user that is doing that is showing something on his screen, another application etc., not showing the conference itself, as the other participants are already seeing the conference.

This a video conferencing solution which involves several server-side components(jitsi-videobridge, jicofo, web server and prosody a xmpp server) and a webrtc javascript web application(jitsi-meet) which all are needed so it can operate. If you want to install it, the easiest way is to use Debian/Ubuntu machine and read the [guide](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md).
There is a very basic scheme of the components used and how they use the network [here](https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#network-description).

Other than that, you just open a page, copy the link and send it to another participant to open it in their browser and that's it, for the best experience we recommend using chrome or chromium.

**Comment by legalmat** [comment] 2017-12-02 16:19
Thank you for trying to help me. Look, I opened the URL in firefox cause it is my browser now after I left Chromium really disappointed. I used the meet.jit.si and wanted to show ANY window to the other but she, using safari on iMac couldnt see anything. The voice stuff was very bad, the whole fucntionality leaves me really wondering and then that when I want to present screen why should I see it in Big or nearly full view myself? I see my screen already on my real screen. get me?
Its is not like I oldnt use it, or? I just pressed the button. the other windows are not selectable. only when I open a second brower, but THIS second she could ALSO not see.
Now, what can someone do wrong about using this?
Lol
Pressing "screensharing" button in a wrong way, that is why this window mirrored itself?
Lol.
Sorry, but to be serious, it should ONLY display to the other pariticipants, or to me in small... but this mirroring... Not supposed to do.
I will make a screencast, then you can see.
And am only talking about the web conference, the rest did even not start at all.
Its sorry, to say, not well documented THERE where I download it on jitsi.org and to be true I expected a desktop application, not a server tool. So maybe my first idea is totally wrong.
But let me show you the screencast soon.

**Comment by damencho** [comment] 2017-12-02 16:47
No need for a screencast I know what you are talking about, we have discussed this a number of times. But we came to the same conclusion: this is physics, you cannot stop a mirror from displaying the view from the other mirror. And as I said earlier screen sharing is to be used with other tabs/windows/screens there is no point of showing your own conference screen, but if you want to do that, you know what is the result.

There is information about the desktop client and about jitsi-meet and the other projects on the website. I already send you a link to jitsi-meet installation guide. If you want to use the desktop client you need a service to use it with, xmpp or sip service you need to find and subscribe to it. But for best video experience we recommend using chrome and jitsi-meet. Browsers like Edge and Safari are in their early stage of using webrtc, and so we are working on adding support for them, but for example safari, for now, we only support audio there. I can continue explaining about browsers and problems they have, but there is no need to go in details, and these are stuff we cannot change, we can only try to adopt with them and give to the user the best possible experience, which is not always the best for them. 
If you want to try and have good experience try chrome/chromium.

**Comment by legalmat** [comment] 2017-12-02 17:41
Ok. The other tabs dont work, the only tab that is showing ANY kind of reaction is the one that records itself. I hoped to have a solution to present to foreign clients but maybe this is not the way to go

**Comment by damencho** [comment] 2017-12-02 17:58
What is the browser and its version that you are using? You are trying on meet.jit.si, right? There are numerous ways we can see what is the problem. For example, you can send me the link you were testing with and I can check what can be the cause of the problem.

**Comment by legalmat** [comment] 2017-12-02 18:08
I used firefox  57.0.1 on KDE neon
and my friend any (I suppose) up to date safari on iMac. thing is, why I was writing all this, that there on the meet.jit.si written easy and very general, that was not the case. you know? am a fan of usabily, develop websites also, use a lot wordpress and many other softwares and I just had not good experience with jitsi so far.

**Comment by damencho** [comment] 2017-12-02 18:14
Can you try with chrome/chromium? 
Yeah, maybe when opening with those browsers there should be a notification saying the experience will not be optimal... I agree this is something we can improve. I will bring it up to the other devs.

**Comment by legalmat** [comment] 2017-12-02 18:23
I can, yes. I also looked for app in chromium they had no effect. Let me see

**Comment by damencho** [comment] 2017-12-02 23:45
So for IE there was a support using a third-party plugin, but this soon will be removed and only Edge will be supported. Safari, for now, is audio only.
Thanks for the reports and we will discuss this and will take some action for at least warning the user.

**Comment by esbeeb** [comment] 2018-04-17 01:26
If Chrome/Chromium are the only web browsers that work well with the screensharing feature, then why not have a pop-up appear to the user (if they are **not** using Chrome/Chromium), that they would do well to use Chrome/Chromium instead, and **then** use the screensharing feature.  Let the tool be self-documenting!

**Comment by MurzNN** [comment] 2018-11-22 03:34
@esbeeb Firefox browser works well with Screen sharing, Chrome needs to install a separate extension. But in Chrome 70 version there are improvements with native screen sharing api: https://groups.google.com/forum/#!msg/discuss-webrtc/Uf0SrR4uxzk/uO8sLrWuEAAJ
So seems in future screen sharing in Chrome will be work natively without extension.

**Comment by damencho** [comment] 2018-11-22 17:11
https://github.com/jitsi/lib-jitsi-meet/commit/9f123f34264bea52feb6efe25fa2f6a5876f1116

**Comment by MurzNN** [comment] 2019-02-20 18:54
I test screen sharing on current https://meet.jit.si/ version in Chrome 71, is still want to install extension and not works without extension. As I understand, via `getDisplayMedia` this must works out-of-the-box without extension!

@damencho Maybe you implement `getDisplayMedia`, but don't disable extension checking?

**Comment by MurzNN** [comment] 2019-02-20 19:06
After upgrading to Chromium 72 it works, seems in 70 & 71 this feature is not enabled by default!
So, @lweffer - let's close this bug as `Fixed`?

**Comment by lpetigny** [comment] 2019-02-20 20:40
Monsieur, 
Vous êtes convoqué à une seance d'entrevue et de simulation qui se tiendra le jeudi 21 février 2018 au local TSE 713 d’après l’horaire suivant :
 

·         9h30 à 12h30 :      

·         13h30 à 16h30 :    CREÉ


    Le mercredi 20 février 2019 à 14:07:07 UTC−5, Alexey Murz Korepov <notifications@github.com> a écrit :  
 
 
After upgrading to Chromium 72 it works, seems in 70 & 71 this feature is not enabled by default!
So, @lweffer - let's close this bug as Fixed?

**Closed** 2019-05-28 21:04 UTC
Labels: type:support, wontfix
