### ISSUE TITLE
Incorret UI color for toogleVideo in toolbar when hide hangup button by api

### ISSUE THREAD

**Issue by miguelrcDEV** [jitsi/jitsi-meet#5509] opened 2020-03-31 11:52 UTC
## Description
When i remove the hangup button from TOOLBAR_BUTTONS like: 
```
TOOLBAR_BUTTONS: [
     'microphone', 'camera', 'closedcaptions', 'desktop', 
     'fullscreen', 'fodeviceselection', 'settings', 
     'profile', 'chat', 'recording', 'videoquality', 'filmstrip', 
     'stats', 'tileview', 'download', 'help', 'mute-everyone'
]
```
The toogleVideo button turns into hangup button style

## Current behavior
![Captura de pantalla 2020-03-31 a las 13 43 27](https://user-images.githubusercontent.com/17248343/78022965-1aaabc00-7356-11ea-94b2-dae4c683e8c0.png)

## Expected Behavior
![Captura de pantalla 2020-03-31 a las 13 48 14](https://user-images.githubusercontent.com/17248343/78023076-4ded4b00-7356-11ea-9374-be039c323362.png)

## Possible Solution
Now you add css by position.
![image](https://user-images.githubusercontent.com/17248343/78023275-a886a700-7356-11ea-99ce-c31c09ae7fd2.png)

You can put visibility hidden to excluded buttons, but I think it's better idea to give style by id.

## Steps to reproduce
 Set TOOLBAR_BUTTONS like: 
```
TOOLBAR_BUTTONS: [
     'microphone', 'camera', 'closedcaptions', 'desktop', 
     'fullscreen', 'fodeviceselection', 'settings', 
     'profile', 'chat', 'recording', 'videoquality', 'filmstrip', 
     'stats', 'tileview', 'download', 'help', 'mute-everyone'
]
```

# Environment details
Mac OSX v10.15.3 in Google Chrome v80

**Comment by saghul** [comment] 2020-03-31 12:29
Duplicate of https://github.com/jitsi/jitsi-meet/issues/5417

**Closed by saghul** 2020-03-31 12:29 UTC

**Comment by luixxiul** [comment] 2020-05-24 08:30
The color should be defined not on *where* the buttons appears, but on *what* they mean.
