### ISSUE TITLE
youtube livestreaming error: all streamers are currently busy

### ISSUE THREAD

**Issue by mrclean06** [jitsi/jitsi-meet#6265] opened 2020-04-21 10:42 UTC
hi 

When i try to stream on my youtube channel.. an error message will be appered : 
all streamers are currently busy

do you know how to stream my visionferency on my tv channel .. please

**Comment by AliKarpuzoglu** [comment] 2020-04-21 11:04
look at this issue: #5403

**Comment by rcsarv** [comment] 2020-04-21 14:38
These days jit.si facing huge traffic, and recording only possible one recording per instance so all servers are busy.
Try self-hosted server.

**Comment by campelo** [comment] 2020-04-22 00:03
duplicate of #6249

**Comment by luixxiul** [comment] 2020-05-12 03:23
Do you experience the issue yet?

**Closed** 2020-05-12 07:17 UTC
Labels: duplicate, info:feedback-needed
