### ISSUE TITLE
iOS SDK cannot join locked room

### ISSUE THREAD

**Issue by calvinckho** [jitsi/jitsi-meet#3861] opened 2019-02-02 12:29 UTC
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
--- Successfully deployed on iOS and can join conferences. But if the room is locked, the user cannot get pass the password prompt even with the right password. 

## Current behavior
--- The user gets stuck at the password prompt in iOS.

## Expected Behavior
--- The prompt would go away and allow the user to join.

**Comment by saghul** [comment] 2019-02-02 14:58
What SDK version are you using?

**Comment by calvinckho** [comment] 2019-02-06 05:52
Thanks for the response. It is 1.21.1.

**Comment by calvinckho** [comment] 2019-03-02 09:28
@saghul any update on fixing this issue? Thanks in advance for looking into it. It's a great SDK!

**Comment by saghul** [comment] 2019-03-02 11:52
Sorry, no news, I'm afraid this fell off my radar. I'll take a look next week!

**Comment by calvinckho** [comment] 2019-04-02 17:48
hey Saghul, I know the new iOS SDK just came out. I didn't upgrade it yet. Was it fixed in the new iOS SDK?

**Comment by saghul** [comment] 2019-04-03 06:23
We haven't released the new SDK yet, but it has landed in master. I could not reproduce the issue.

**Comment by saghul** [comment] 2019-04-03 14:38
SDK 2.0.0 is out now. Please try it out and report back if you run into problems. https://community.jitsi.org/t/jitsi-meet-sdk-2-0-0-for-android-and-ios-released/17485

**Closed by saghul** 2019-04-03 14:38 UTC

**Comment by calvinckho** [comment] 2019-04-03 17:57
@saghul thanks will try it out!
