### ISSUE TITLE
how to allow jitsi meeting on mobile browser using webview? I am Externel jitsi api.

### ISSUE THREAD

**Issue by jeetvirani** [jitsi/jitsi-meet#5773] opened 2020-04-08 04:26 UTC
When i am running in desktop it is working fine. But when i am trying into Mobile browser or webview it is giving this error: 
**You need the Jitsi Meet mobile app to join this meeting on your phone.**
Can anyone help me?

**Comment by Entretoize** [comment] 2020-04-08 09:00
Same question, it works by loading the computer version on mobile so why are they forcing using the app ? It must have a workaround as it just checks user agent.

**Comment by Entretoize** [comment] 2020-04-08 09:07
Just found a way, just add that in your index.html after the first `<script>`:
Object.defineProperty(navigator, 'userAgent', {
    get: function () { return 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36'; }
});

You'll have to update css to be fine on mobile.

**Comment by alariej** [comment] 2020-04-08 16:06
Hi @Entretoize, your solution looks promising but doesn't work for me unfortunately, I still can't get the Jitsi Meet API to load on Webview Android (react-native-webview@5.12.1). I don't get passed the warning to install the Jitsi app. I tried various user agents, no luck. Are you using more or less the same script as in https://github.com/jitsi/jitsi-meet/blob/master/doc/examples/api.html? If not, any chance you can post your script? Perhaps other settings also influence the environment detection in the Jitsi API...

**Comment by Entretoize** [comment] 2020-04-08 16:12
My solution is for a mobile web browser. It could work in a webview, with that user agent, but with the right permissions and some javascript trick maybe I remember the webview needs some javascript custom handling.
I'm using jitsi "as is" on debian, I used the quick install guide.

**Comment by alariej** [comment] 2020-04-08 16:19
I see. Yes I think it will be difficult and perhaps impossible to trick react-native-webview via navigator.userAgent :-(

**Comment by dmelechow** [comment] 2020-04-09 09:13
@Entretoize I took code from an example, and I tried your approach but it doesn't work for me

**Comment by saghul** [comment] 2020-04-09 09:18
Try this:

```
configOverwrite: {
    disableDeepLinking: true
},
```

Note that this won't work on iOS because we need to make some Safari fixes and last I checked web viewss don't have WebRTC support.

**Comment by Entretoize** [comment] 2020-04-09 09:54
> @Entretoize I took code from an example, and I tried your approach but it doesn't work for me

I'm not using the external api, I installed jitsi-meet on my own server.

**Comment by dmelechow** [comment] 2020-04-09 10:15
@saghul Thanks, It helped, but it lost the ability to turn on audio/video, is it a bug or I need to add something extra?

[
![Screenshot 2020-04-09 at 13 13 45](https://user-images.githubusercontent.com/11187627/78884698-0ce6ec00-7a64-11ea-8207-5aadd47f2ef4.png)
](url)

**Comment by alariej** [comment] 2020-04-09 15:01
@saghul On Android, Webview (from v36) has WebRTC support:

https://developer.chrome.com/multidevice/webview/overview#does_the_new_webview_have_feature_parity_with_chrome_for_android_

Not quite sure about WKWebView on iOS.

**Comment by saghul** [comment] 2020-04-09 15:20
@dmelechow You are using `filmStripOnly: true` was that intentional? Remove that it should just work.

**Comment by dmelechow** [comment] 2020-04-10 10:38
@saghul Unfortunately, this approach doesn't work too, I removed `filmStripOnly: true` and used this `configOverwrite: {
    disableDeepLinking: true
},` but whatever I can't turn on audio/video and I got some warning message
![2020-04-10 13 37 03](https://user-images.githubusercontent.com/11187627/78985032-703e5000-7b30-11ea-9fc8-c094ab8f872f.jpg)

**Comment by Entretoize** [comment] 2020-04-10 11:44
If you are building a android app, maybe permission are missing in manifest or not clearly asked to user. Or you are using an iframe ?

**Comment by dmelechow** [comment] 2020-04-10 12:08
@Entretoize I tried to build the web application with 
`  <script src="https://meet.jit.si/external_api.js"></script>`

**Comment by alariej** [comment] 2020-04-11 17:41
@dmelechow I just tested the Jitsi Meet external API on Android Webview and I can confirm that it fails to access the camera and microphone. The problem is that the API serves Jitsi Meet inside an **iframe**, which for some reason fails to obtain the permissions given to the Webview. If you just pass the Jitsi Meet URL (`https://meet.jit.si/<someConferenceID>#config.disableDeepLinking=true`) to the Webview, instead of the API, then everything works fine: The Webview requests the camera and microphone permissions, and you get video and sound.

One problem with the iframe could be that the Jitsi Meet API server does not pass the `"Access-Control-Allow-Origin":"*"` CORS header. AFAIK, this would be required for Jitsi Meet to access hardware permissions behind an iframe. @saghul, can you confirm this?

**Comment by Entretoize** [comment] 2020-04-11 19:04
I already succeded in using jitsi-meet in an iframe with that code:

<iframe src="https://example.com" allow="camera;microphone"></iframe>

**Comment by alariej** [comment] 2020-04-11 19:40
But was the source https://meet.jit.si, or a self-hosted version? As I wrote above, it probably works only if the web server for the source provides the `"Access-Control-Allow-Origin":"*"` CORS header. I believe the Jitsi Meet API already provides the `allow="camera;microphone"` directive in the iframe, so that should not be the problem.

**Comment by Entretoize** [comment] 2020-04-12 08:15
It was on the self hosted version, but I just tried in an android webview with the meet.jit.si and the camera and microphone works and are streamed.
I added the following permissions in the manifest:
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.MICROPHONE" />
	<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
And needed to request permission from the user:
        Manifest.Permission.RecordAudio

**Comment by alariej** [comment] 2020-04-12 09:22
I use the exact same permission settings. Do you pass `https://meet.jit.si` as a URL parameter to the Webview, or are you building the HTML using `<script src="https://meet.jit.si/external_api.js"></script>`?

**Comment by Entretoize** [comment] 2020-04-12 12:19
I just pass https://meet.jit.si.
EDIT: I just tried with your code:

```
<head>
  <meta charset="utf-8">
  <meta http-equiv="content-type" content="text/html;charset=utf-8">
</head>

<body>

 <script src="https://meet.jit.si/external_api.js"></script>

  <script>
    var domain = "meet.jit.si";
    var options = {
      roomName: "JitsiMeetAPIExample1221121212",
      width: 700,
      height: 500,
      parentNode: undefined,
      configOverwrite: {},
      interfaceConfigOverwrite: {
        filmStripOnly: true
      }
    }
    var api = new JitsiMeetExternalAPI(domain, options);
  </script>
</body>

</html>
```

And it worked too.

**Comment by alariej** [comment] 2020-04-12 17:35
Yes I think that is the difference. Your web server must somehow provide the required CORS header (https://tecadmin.net/enable-cors-apache/), while the https://meet.jit.si server does not.

Webview has both a `source.html` parameter and a `url` parameter. You can put the Jitsi Meet API code in the `source` parameter, and leave the `url` parameter empty.

In React Native, it would be:
```
const html =
`<head>
  <meta charset="utf-8">
  <meta http-equiv="content-type" content="text/html;charset=utf-8">
</head>
<body>
  <script src="https://meet.jit.si/external_api.js"></script>
  <script>
    ...
  </script>
</body>
</html>`;
```
then call the Webview like this:
```
<WebView
  source={{
    html: html,
  }}
  mediaPlaybackRequiresUserAction={ false }
  allowsInlineMediaPlayback={ true }
/>
```

**Comment by dmelechow** [comment] 2020-04-12 17:41
@Entretoize I'm doing a web project with RactJs, in my .HTML file I inserted `<script src="https://meet.jit.si/external_api.js"></script>
`

**Comment by dmelechow** [comment] 2020-04-12 18:15
@Entretoize I don't have any mobile apps, I only use jitsi in my ReactJs project in desktop and mobile browser, on desktop everything is working perfectly, but in a mobile browser, there are problems 1. You need to use native jitsi app 2. `configOverwrite: { disableDeepLinking: true }` when I use this I can't turn on the audio, for simplicity I was trying to the code from doc in the pure .HTML file

**Comment by alariej** [comment] 2020-04-14 13:05
@Entretoize I tried the Jisti Meet API HTML code in a static web page, which I call in the Android Webview using the URL parameter. This works perfectly well and I now have access to video and sound in the Webview, with no failed access error. I am not quite sure anymore why calling the same HTML directly in the Webview doesn't work. Is it a CORS issue, a security feature in Webview, a bug?

I also tested my web page on Chrome and Firefox on Android and it works well. The UI design of Jitsi Meet is not yet well adapted for mobile devices, but I think this will get better eventually.

Unfortunately, things don't look as good on iOS. Chrome doesn't even have access to camera or microphone permissions at all. With Safari, I can access the microphone, but the video only shows a static image. I haven't tried yet the Webview on iOS, but it doesn't look like it supports WebRTC yet.

**Comment by SumitBando** [comment] 2020-04-21 15:23
The JS code may be checking for user agent, and refusing to work if the agent indicates a mobile browser, and demanding app download.

On my macbook, a web page with the simplest embed works in Chrome.
Unfortunately, if I have the developer tool set to emulate a phone, it fails to work, with this screen.

<img width="299" alt="Screen Shot 2020-04-21 at 8 39 08 PM" src="https://user-images.githubusercontent.com/248569/79883823-fc465680-8411-11ea-98f3-05d8b816164d.png">

This was an enormous waste of time for me, and likely others.
If this is by design, it should at least be documented.

**Comment by iresharma** [comment] 2020-05-23 23:35
> Try this:
> 
> ```
> configOverwrite: {
>     disableDeepLinking: true
> },
> ```
> 
> Note that this won't work on iOS because we need to make some Safari fixes and last I checked web viewss don't have WebRTC support.

This worked perfectly
On an iPhone too


I mean I'm not really sure I used a simulator so I check back on iPhone and reply tomorrow

**Comment by saghul** [comment] 2020-05-24 05:14
The option should now work fine.

In fact, we have landed open in browser support in master now.

Closing.

**Closed** 2020-05-24 05:14 UTC
Labels: api, mobile, question

**Comment by tdrp** [comment] 2020-05-28 22:29
@iresharma @alariej  - were you able to get this to work on a real iPhone? I am running into the same problem as other users where it is not letting me enable the camera or microphone. Works fine on Android though, but not on iOS.

**Comment by iresharma** [comment] 2020-05-28 22:41
> @iresharma @alariej  - were you able to get this to work on a real iPhone? I am running into the same problem as other users where it is not letting me enable the camera or microphone. Works fine on Android though, but not on iOS.



In my case sometimes it worked sometimes it didn't, I still wrapping my head around how to fix it

The worst part is some guy closed this issue stating it's fixed so I pushed to deployment and now my client is complaining again and again.

**Comment by ShubhGar** [comment] 2020-07-04 12:54
Hi, I try https://jitsinew.tinda.app/test with wkwebview ios but it unable to access camera and Microphone

**Comment by shijilspark** [comment] 2020-08-11 10:28
Has anyone has the issue of turning off/on camera in mobile browser after enabling disableDeepLinking: true ?

I can mute/unmute mike though. 

Any help would be appreciated.

**Comment by PRAVEENKUMARRAJENDRAN** [comment] 2020-08-31 09:26
I'm also facing same issue

**Comment by amirkhattak** [comment] 2020-09-24 21:52
hi there i am i am facing issue on mobile i am using external jitisi site api using iframe in a box for my site but on mobile device its says download app wevview is not working any 1 can help me p
![Uploading 79883823-fc465680-8411-11ea-98f3-05d8b816164d.png…]()
ls?

**Comment by marcelomf** [comment] 2021-09-05 09:33
for external api, try:

```
      let domain = "meet.jit.si";
      let options = {
          roomName: 'test123',
          width: '100%',
          height: '100%',
          userInfo: {
            // email: 'email@jitsiexamplemail.com',
            displayName: 'test321'
          },
          configOverwrite: {
            requireDisplayName: false,
            prejoinPageEnabled: false,
            disableDeepLinking: true,
          },
          interfaceConfigOverwrite: {
            MOBILE_APP_PROMO: false,
          },
          // parentNode: meetElement
      }
      let api = await new JitsiMeetExternalAPI(domain, options)
```

**Comment by amirkhattak** [comment] 2021-09-05 20:20
thank you

**Comment by paudeldileep** [comment] 2022-02-07 04:28
unable to join the meeting from react-native-webview . What might be the problem. 
![image](https://user-images.githubusercontent.com/64344997/152724530-02ebc5f9-09ba-4a2a-b171-083f8113b5c9.png)

**Comment by saghul** [comment] 2022-02-07 07:00
Not sure what the question is. What problem are you facing?

**Comment by paudeldileep** [comment] 2022-02-08 14:06
> Not sure what the question is. What problem are you facing?

I solved the issue but is there way for going back to previous screen on react native after call ends

**Comment by paudeldileep** [comment] 2022-02-08 14:07
I have a web view screen for conference and I want each user to be redirected back to previous page when meeting ends

**Comment by paudeldileep** [comment] 2022-02-08 14:10
![image](https://user-images.githubusercontent.com/64344997/153003673-ad3c8f8f-cf2b-4185-80d4-ad8ae8ea578d.png)

**Comment by saghul** [comment] 2022-02-08 15:44
You'd need to detect the URL changes I think.
