### ISSUE TITLE
getUserMediaWithConstraints fails when device has only a back camera

### ISSUE THREAD

**Issue by calamatitech** [jitsi/jitsi-meet#2720] opened 2018-04-03 19:00 UTC
I builded the android app Jitsi Meet cloning the branch master and tried it on smart glass (only back camera), smartphone (back and front camera), android emulator with only a back camera, android emulator with only a front camera.
**In both (virtual and real) devices with only a back camera,** **getUserMediaWithConstraints fails**:
04-01 09:57:24.958  2846  2886 W ReactNativeJS: '[modules\\RTC\\RTCUtils.js]', '<n>: ', 'Failed to get access to local media. Error ', { name: null,
04-01 09:57:24.958  2846  2886 W ReactNativeJS:   message: 'Failed to create new track',
04-01 09:57:24.958  2846  2886 W ReactNativeJS:   constraintName: undefined }, { audio: false,
04-01 09:57:24.958  2846  2886 W ReactNativeJS:   video:
04-01 09:57:24.958  2846  2886 W ReactNativeJS:    { mandatory: {},
04-01 09:57:24.958  2846  2886 W ReactNativeJS:      optional: [ { facingMode: 'user' } ],
04-01 09:57:24.958  2846  2886 W ReactNativeJS:      facingMode: 'user' } }
The Android version of the four devices is 6.0.
Instead the Jitsi Meet app downloaded by Play Store works great on the smart glass.
In attachment the logs of the smart glass and smartphone.

[smart_glass_log.txt](https://github.com/jitsi/jitsi-meet/files/1872935/smart_glass_log.txt)
[smartphone_log.txt](https://github.com/jitsi/jitsi-meet/files/1872936/smartphone_log.txt)

 Here is the code of getUserMediaWithConstraints, extracted from node_modules\lib-jitsi-meet\modules\RTC\RTCUtils.js

    getUserMediaWithConstraints(
            um,
            successCallback,
            failureCallback,
            options = {}) {
        const constraints = getConstraints(um, options);

        logger.info('Get media constraints', constraints);

        return new Promise((resolve, reject) => {
            try {
                this.getUserMedia(
                    constraints,
                    stream => {
                        logger.log('onUserMediaSuccess');
                        setAvailableDevices(um, stream);

                        if (successCallback) {
                            successCallback(stream);
                        }

                        resolve(stream);
                    },
                    error => {
                        setAvailableDevices(um, undefined);
                        logger.warn(
                            'Failed to get access to local media. Error ',
                            error, constraints);
                        const jitsiTrackError
                            = new JitsiTrackError(error, constraints, um);

                        if (failureCallback) {
                            failureCallback(jitsiTrackError);
                        }

                        reject(jitsiTrackError);
                    });
            } catch (e) {
                logger.error('GUM failed: ', e);
                const jitsiTrackError
                    = new JitsiTrackError(e, constraints, um);

                if (failureCallback) {
                    failureCallback(jitsiTrackError);
                }

                reject(jitsiTrackError);
            }
        });
    }

**Comment by calamatitech** [comment] 2018-04-03 19:15
For completeness of the information provided above, here is the code of getUserMediaWithConstraints, extracted from node_modules\lib-jitsi-meet\modules\RTC\RTCUtils.js, with the warning bolded

    getUserMediaWithConstraints(
            um,
            successCallback,
            failureCallback,
            options = {}) {
        const constraints = getConstraints(um, options);

        logger.info('Get media constraints', constraints);

        return new Promise((resolve, reject) => {
            try {
                this.getUserMedia(
                    constraints,
                    stream => {
                        logger.log('onUserMediaSuccess');
                        setAvailableDevices(um, stream);

                        if (successCallback) {
                            successCallback(stream);
                        }

                        resolve(stream);
                    },
                    error => {
                        setAvailableDevices(um, undefined);
                        **logger.warn(**
                            '**Failed to get access to local media. Error** ',
                            **error, constraints);**
                        const jitsiTrackError
                            = new JitsiTrackError(error, constraints, um);

                        if (failureCallback) {
                            failureCallback(jitsiTrackError);
                        }

                        reject(jitsiTrackError);
                    });
            } catch (e) {
                logger.error('GUM failed: ', e);
                const jitsiTrackError
                    = new JitsiTrackError(e, constraints, um);

                if (failureCallback) {
                    failureCallback(jitsiTrackError);
                }

                reject(jitsiTrackError);
            }
        });
    }

**Comment by saghul** [comment] 2018-04-03 19:38
I think the problem is here: https://github.com/jitsi/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java#L157-L181

That code needs to fallback do the first available camera, if the requested one is not available. FTR, we do this in iOS.

**Comment by saghul** [comment] 2018-04-03 19:38
@guusdk you might be interested in this as well.

**Comment by calamatitech** [comment] 2018-04-03 20:26
Can it be useful to force facingMode = 'environment'? How can I do it?

**Comment by saghul** [comment] 2018-04-04 08:42
@calamatitech You can try changing the constant here: https://github.com/jitsi/jitsi-meet/blob/d93782af8a1d2b166cbd04808b0dc91bffeb1915/react/features/base/tracks/actions.js#L99 and set it to `CAMERA_FACING_MODE.ENVIRONMENT`. (https://github.com/jitsi/jitsi-meet/blob/d93782af8a1d2b166cbd04808b0dc91bffeb1915/react/features/base/media/constants.js#L6)

Let me know how that goes!

**Comment by calamatitech** [comment] 2018-04-04 10:49
Same error, because fascingMode is still 'user'.
See attached log
[log.txt](https://github.com/jitsi/jitsi-meet/files/1875374/log.txt)

**Comment by saghul** [comment] 2018-04-04 11:40
You'll need to dig deeper, alas I'm swamped right now and cannot look into it myself, sorry.

**Comment by calamatitech** [comment] 2018-04-04 12:13
Ok, I tried to set 
export const CAMERA_FACING_MODE = {
    ENVIRONMENT: 'environment',
    USER: 'environment'
};
and
                        facingMode:
//                            options.facingMode || CAMERA_FACING_MODE.USER,
                            CAMERA_FACING_MODE.ENVIRONMENT,
same error;

**Comment by calamatitech** [comment] 2018-04-04 12:54
You are right!
Modifying GetUserMediaImpl.java in this way:
        // Otherwise, use facingMode.
        boolean isFrontFacing;
        if (facingMode == null) {
            facingMode = "user";
            isFrontFacing = true;
	/////// PLEASE FIX ME //////
            isFrontFacing = false;
	////////////////////////////
        } else {
            isFrontFacing = !facingMode.equals("environment");
	/////// PLEASE FIX ME //////
            isFrontFacing = false;
	////////////////////////////
        }

**Comment by guusdk** [comment] 2018-04-05 12:29
Thanks for finding this! Am I right to conclude that this can be made to work without changes to React Native WebRTC? The Jitsi Meet application (from the Android store) does not suffer from this problem, which suggests it can be worked around in code.

**Comment by saghul** [comment] 2018-04-05 13:37
@guusdk I'm not sure, TBH. The fix should be in the Java code I linked. We (react-native-webrtc really) should return the first available camera if none match the facingMode.

**Comment by guusdk** [comment] 2018-04-05 14:48
For what it's worth - I'm reproducing the issue with the Jitsi Meet for Android code, when I run that from Android Studio. Applying a fix as shown by @calamatitech does make that go away. I was puzzled to find that the running from code behaves differently from the app that is in the store. Is it based on older code?

**Comment by saghul** [comment] 2018-04-05 14:58
@guusdk I have the same feeling. My suspicion is that `enumerator.isFrontFacing(name)` works differently on the simulator vs the real hardware.

I'd say what needs to happen is that we pick the first camera available if the one matching our desired facingMode is not found.

A PR is more than welcome at jitsi/react-native-webrtc :-)

**Comment by calamatitech** [comment] 2018-04-05 15:13
I tried the fix on two real devices, smart glass (back camera only) and smart glass (front and back camera).
Now the app builded by myself works as the app from the Android store.
But I can't find where getUserMedia is called with the constraint facingMode = 'user' .... I would like to change the default camera to back, in place of front

**Comment by saghul** [comment] 2018-04-05 15:53
> But I can't find where getUserMedia is called with the constraint facingMode = 'user' .... I would like to change the default camera to back, in place of front

That's not really a good solution. Look at my comment above.

**Comment by ajaydata** [comment] 2018-04-05 15:58
We were able to built successfully and actually add much capability in videomeet app, which is now available on app store.. 

If you want to try videomeet session let me know..

Thanks..

On April 5, 2018 8:18:17 PM GMT+05:30, Guus der Kinderen <notifications@github.com> Wrote:
>For what it's worth - I'm reproducing the issue with the Jitsi Meet for
>Android code, when I run that from Android Studio. Applying a fix as
>shown by @calamatitech does make that go away. I was puzzled to find
>that the running from code behaves differently from the app that is in
>the store. Is it based on older code?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jitsi/jitsi-meet/issues/2720#issuecomment-378962469

राजमेल - राजस्थान सरकार की फ्री ईमेल सेवा

**Comment by calamatitech** [comment] 2018-04-05 18:47
saghul, I know that the solution is to fix the code you linked.
Setting the default camera to "back" is an extra, I want that the behaviour of the smart glass and smartphone be the same: at the start of the app, they immediately streams video of the "environment".

**Comment by guusdk** [comment] 2018-04-06 08:04
@calamatitech I'd argue that the primary purpose of Meet is to have a video conference, and that therefor, the default camera should be the one facing the user. In any case, I think it's an issue unrelated to this one (perhaps open a new issue for this?)

**Comment by saghul** [comment] 2018-04-06 09:29
@calamatitech I personally find that quite a corner case, so I'm not sure we'll ever get around doing it ourselves. Patches are of course welcome, and if you make a good case for it, it could be incorporated. But as @guusdk pointed out, that's a different issue.

**Comment by guusdk** [comment] 2018-04-06 10:07
Do you guys want a PR made to your fork, the upstream Oney repo, or both?

**Comment by calamatitech** [comment] 2018-04-06 12:06
I think it is correct that the default camera is the front camera, because jitsi meet is a videoconference app.
Perhaps the row of code that force facingMode to 'user' is 
const facingMode = options.facingMode || CameraFacingMode.USER;
contained in the funcion getConstraints in node_modules\lib-jitsi-meet\modules\RTC\RTCUtils.js.
If I want to make the change, I will set npm to work with a local copy of lib-jitsi-meet, modified to set facingMode to CameraFacingMode.ENVIRONMENT

**Comment by calamatitech** [comment] 2018-04-06 12:37
Sorry for my poor English. I'm trying to say that I will try to modify my local copy of the node module lib-jitsi-meet to set the default camera to back.
For the purpose of videoconference, I can say the app works correctly with the default camera set to front.
My intention is different: I want stream to a remote desktop what I see, by mean of a smart glass or a smart phone. Many thank to you and to saghul for your collaboration.

**Comment by saghul** [comment] 2018-04-09 10:14
This is fixed by latest master, please update and give it a shot. All credit goes to @guusdk for making the patch 🎉 🎉 

We tested it on a RealWear HMT-1.

**Closed by saghul** 2018-04-09 10:14 UTC
