### ISSUE TITLE
Logitech Orbit camera not recognized

### ISSUE THREAD

**Issue by jbrooksmartin** [jitsi/jitsi-meet#5430] opened 2020-03-27 19:20 UTC
USB camera not recognized by Jitsi to mic or video capture.  Any suggestions?

**Comment by saghul** [comment] 2020-03-27 21:06
Does it work on test.webrtc.org ?

**Comment by alexanderadam** [comment] 2020-03-31 08:13
Duplicate of #5425

**Comment by jbrooksmartin** [comment] 2020-04-01 02:18
It works in some of the tests, but not all.  I tried the VDC fix at that #5425 issue, and I didn't find it.  Should I just post my test results there?  is this a new pop-up issue?

**Comment by saghul** [comment] 2020-04-01 21:26
We think we have found the problem and an update will be rolling out shortly.

**Comment by jbrooksmartin** [comment] 2020-04-03 04:34
Awesome. Thank you.

**Closed** 2020-05-12 13:32 UTC
Labels: duplicate
