### ISSUE TITLE
How to set password using Jitsi-meet iOS sdk

### ISSUE THREAD

**Issue by iDev-ymakhija** [jitsi/jitsi-meet#7792] opened 2020-09-28 05:33 UTC
Can someone help me how we can set set password for the meeting, using iOS and Android SDK? and if we can't set it using SDK is there any other way?

**Comment by Echolon** [comment] 2020-09-29 16:29
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-09-29 16:29 UTC
Labels: question
