### ISSUE TITLE
Participants do not see video of other participants imediately

### ISSUE THREAD

**Issue by Zalmoxisus** [jitsi/jitsi-meet#277] opened 2015-04-24 14:33 UTC
It happens for a new participant with no webcam or if a participant denies access to the webcam. In this case such a participant receives only audio of other participant, and only after 1:30 - 2 minutes receives (sees) video stream.
Tested with last master and on meet.jit.si.

**Comment by gpolitis** [comment] 2015-04-28 11:16
Replicating my comment in #274. This could be a bug in the WebRTC engine, like not requesting PLIs for receiving channels if audio/video is disabled. You could try to disable bundle and rtcp-mux and see if it changes anything.

**Comment by Kidav** [comment] 2015-04-29 18:29
Seems disable bundle and rtcp-mux does not help.
This bug relates to the closed https://github.com/jitsi/jitsi-meet/issues/32 .
I am just looked to the https://github.com/jitsi/jitsi-meet/blob/master/modules/xmpp/JingleSession.js
At the end of file
```javascript
var isVideo = data.stream.getVideoTracks().length > 0;
    // an attempt to work around https://github.com/jitsi/jitmeet/issues/32
    if (isVideo &&
        data.peerjid && this.peerjid === data.peerjid &&
        data.stream.getVideoTracks().length === 0 &&
        APP.RTC.localVideo.getTracks().length > 0) {
        window.setTimeout(function () {
            sendKeyframe(self.peerconnection);
        }, 3000);
    }
```
this snipet wont work in the any case because conditions data.stream.getVideoTracks().length > 0 and data.stream.getVideoTracks().length === 0 conflicting

video not appears even if I run sendKeyframe code in the browser console 
```javascript
var pc = APP.xmpp.getConnection().jingle.activecall.peerconnection;
pc.setRemoteDescription(pc.remoteDescription,function () {
            pc.createAnswer(
                function (modifiedAnswer) {
                    pc.setLocalDescription(modifiedAnswer,function () {},function () {});
                }
            );
        }
);
```

I think this lines causes such problems 
```javascript
    // FIXME:
    // this was a hack for the situation when only one peer exists
    // in the conference.
    // check if still required and remove
    if (sdp.media[0])
        sdp.media[0] = sdp.media[0].replace('a=recvonly', 'a=sendrecv');
    if (sdp.media[1])
        sdp.media[1] = sdp.media[1].replace('a=recvonly', 'a=sendrecv');
```
this is pice of code from _modifySources function in the same file

**Comment by Zalmoxisus** [comment] 2015-06-01 16:01
It happens for any participant, not only without webcam.

Steps to reproduce:
1. Open https://meet.jit.si/
2. Open in other window the same url (participant 2).
3. Click "stop camera" icon for both participants.
4. Start camera of the Participant 2.
The Particiapant 1 will not be able to see the Participant 2 for about 2 minutes.

The bug is related to WebRTC or to JVB as the currentTime of the video is 0 for this interval.

**Comment by Zalmoxisus** [comment] 2015-06-01 17:10
@Kidav, removing those lines doesn't help. 

Excluding the line [1] solves this, but, of course, not in case when the participant is without webcam.

Checked in Firefox too, it's the same.

[1] https://github.com/jitsi/jitsi-meet/blob/master/modules/RTC/LocalStream.js#L61

**Comment by idcmp** [comment] 2015-07-15 21:00
FWIW +1, experiencing this too (local install Ubuntu 14, Oracle JDK 8, Chrome Linux Version 43.0.2357.134 (64-bit))

**Comment by Kidav** [comment] 2015-07-22 15:55
For now (when Chrome 44 released) similar, but more serious problem is that after turning video Off and On it is not possible to see others participants video. Any suggestions described above does not help - reproduced on freshness installation of jitsi-meet and on meet.jit.si. Maybe issue https://github.com/jitsi/jitsi-meet/issues/320 is more related

What is interesting is that if I use http instead https this bug is not appears

**Comment by paweldomas** [comment] 2015-07-28 11:37
The issue is caused by the fact that Chrome is using SSRC=1 in PLI requests when it has no local video configured. JVB is dropping these packets, so clients without local video are not able to request keyframes. A workaround could be to make Jicofo configure video SSRC=1 for them.

**Comment by paweldomas** [comment] 2015-08-05 14:10
Can be fixed with https://github.com/jitsi/jitsi-videobridge/commit/b6622988f8109310b5d84519ce43fdeecb0c6350

**Comment by paweldomas** [comment] 2015-08-07 11:01
Fixed in https://github.com/jitsi/jitsi-meet/commit/fb875423a909e4f7eccb43bc4526d13f3b84ce67

**Closed by paweldomas** 2015-08-07 11:01 UTC
Labels: type:bug
