### ISSUE TITLE
Does Jitsi supports E2EE for android and iOS?

### ISSUE THREAD

**Issue by xaldarof** [jitsi/jitsi-meet#14639] opened 2024-04-16 13:41 UTC
E2EE works on web, but it doesn't work on android and iOS.

**Comment by saghul** [comment] 2024-04-16 13:45
No, it doesn't. Closing as a duplicate of https://github.com/jitsi/jitsi-meet/issues/8148

**Closed by saghul** 2024-04-16 13:45 UTC
Labels: feature-request
