### ISSUE TITLE
Add feature graphic and screenshots for fastlane

### ISSUE THREAD

**Issue by PanderMusubi** [jitsi/jitsi-meet#4588] opened 2019-09-03 06:18 UTC
Please add a feature graphic and screenshots for smartphone and tablet to the fastlane directory for the Android app.

This will enable that these images are uploaded automatically to all app stores, being Google Play and F-Droid.

See also the following https://gitlab.com/fdroid/fdroiddata/issues/1413#note_193403754 where F-Droid promotes all this metadata to be upstream. Benefit is one point of control for screenshots which are distributed to all app strores automatically and identically.

**Comment by PanderMusubi** [comment] 2019-09-03 06:23
Location to add these images (according to a certain format) is https://github.com/jitsi/jitsi-meet/tree/master/android/fastlane

**Comment by PanderMusubi** [comment] 2019-09-03 06:26
Some additional info is in https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

**Comment by saghul** [comment] 2019-09-03 06:49
Thanks for bringing this up! Alas I'm not sure we have all the assets since the move, but I'll check it out.

**Comment by PanderMusubi** [comment] 2019-11-25 09:14
Do you have an update? Jitsi Meet is nog also on F-Droid and those assets would now be used there too.

**Comment by saghul** [comment] 2019-11-26 08:57
Sorry, no updates.

**Comment by PanderMusubi** [comment] 2019-11-27 07:17
Can I help out with this? Or are they in a repo I don't have access to?

**Comment by saghul** [comment] 2019-11-27 08:26
I don't think you can, because I don't know where those assets are to begin with :-/

**Comment by PanderMusubi** [comment] 2019-12-06 08:08
I see screenshots in https://play.google.com/store/apps/details?id=org.jitsi.meet Does that help locating them?

**Comment by saghul** [comment] 2019-12-06 08:10
I got ahold of them! I'll be putting them in the fastlane directory shortly.

**Comment by PanderMusubi** [comment] 2019-12-06 08:19
Super! Note you can use `optipng` to reduce the file size of PNG images for faster loading.

**Comment by saghul** [comment] 2020-03-05 09:00
Oops, forgot to close this one. They are here now: https://github.com/jitsi/jitsi-meet/tree/master/android/fastlane/screenshots

**Comment by PanderMusubi** [comment] 2020-03-05 11:44
Thanks. Here is optimization, reduction from 37 MB to 30 MB https://github.com/jitsi/jitsi-meet/pull/5107 This is important for people with a minimal data plan on their mobile device as app store website and app store apps distribute these images.

**Comment by PanderMusubi** [comment] 2020-03-05 11:51
Additional question, best is to use only one feature graphic, i'd sugest https://github.com/jitsi/jitsi-meet/blob/master/android/fastlane/screenshots/Feature-Graphic-1024x500-1-1.png

@IzzySoft do you have any further suggestions?

**Comment by saghul** [comment] 2020-03-05 13:05
This has become the source for us storing all images we have, so we may have extras, that's ok. I guess F-Droid can pick just one?

**Comment by PanderMusubi** [comment] 2020-03-05 14:07
F-Droid (and Google Play) expects the files to be found in a top-lever directory according to a certain naming scheme, see for example https://github.com/y20k/transistor/tree/master/metadata/en-US

**Comment by saghul** [comment] 2020-03-05 14:13
Ah, good to know! I'll get that done for the next update then.

**Comment by IzzySoft** [comment] 2020-03-05 20:35
@saghul for an easy reference, see my snippet: [Fastlane file structure](https://gitlab.com/snippets/1895688). The current directory (forgive me) is just a mess. Contents need to be split. From what I see, there are `phoneScreenshots`, `sevenInchScreenshots` and maybe more. Going by my linked snippet, it should be easy to sort out.

**Comment by saghul** [comment] 2020-03-06 06:49
Thanks for the pointer!

As mentioned before, we don’t and won’t use fast lane to upload the metadata. I dumped it there so F-Droid can pick it up though.

**Comment by IzzySoft** [comment] 2020-03-06 07:22
@saghul F-Droid doesn't "pick manually", it's an automated process sticking to the definitions. Hence, what is not in the expected place is ignored. Which means the `fastlane` directory must be at top-level of your repo, and have the structure pointed out in my snippet. F-Droid picks the elements it finds there (so no mandatory ones – but it it's empty, the F-Droid listing won't even have summary or description; I'd say those two (`full_description.txt` and `short_description.txt`) are the minimum, with the screenshots strongly recommended).

**Comment by saghul** [comment] 2020-03-06 09:13
Thanks for clarifying. I'm afraid we have a problem then.

> Which means the `fastlane` directory must be at top-level of your repo,

We cannot do this. Our repo contains both the Android and iOS codebases (in addition to the web codebase, because they are all built from the same JS sources), and each has their own Fastlane config. Is there a way to specify a subdirectory?

> PS: the binaries in the fastlane root (`Appfile` & `Fastfile`) are only needed if you want to use Fastlane to deploy to Play Store (e.g. `fastlane android deploy`), F-Droid doesn't need them. So feel free to drop the two (with their `README.md`) when restructuring.

That's literally the only thing we use Fastlane for.

**Comment by PanderMusubi** [comment] 2020-03-06 09:14
@saghul you can also create a `metadata` top-level directory and don't use Fastlane. This directory will be picked up by F-Droid.

**Comment by saghul** [comment] 2020-03-06 09:16
@PanderMusubi I don't want to put Android only things outside of our android/ top-level directory. Is there no way around it?

**Comment by PanderMusubi** [comment] 2020-03-06 09:18
Not that I know. Most projects have separate repositories for Android, iOS and web. And they often all use a fourth shared repo.

As you also have a `debian` directory in top-level, using this approach would work here too https://github.com/y20k/transistor/tree/master/metadata

**Comment by saghul** [comment] 2020-03-06 09:41
I'll think about it, thanks for all the help folks!

**Comment by IzzySoft** [comment] 2020-03-06 19:38
@saghul Fallback: [Triple-T file structure](https://gitlab.com/snippets/1901490) (another snippet of mine). Not as "stable" with F-Droid, but should work. Goes inside the application tree (in your case, the top-level Triple-T directory would be directly in [`android/app/src/main/`](https://github.com/jitsi/jitsi-meet/tree/master/android/app/src/main) then. And what would be mainly needed by F-Droid would be `play/listings/*` – there especially short/full description and your graphics sorted into the `graphics/` sub-tree.

**Comment by jwsp1** [comment] 2020-10-07 08:49
On F-Droid there is also no changelog when an update arrives...

**Comment by IzzySoft** [comment] 2020-10-07 09:51
@jwsp1 as long as `fastlane` is not a top-level directory, F-Droid cannot use it at all – so of course there won't be any per-release changelog either.

@saghul If you take a look at https://fastlane.tools/ it says Fastlane covers ios as well. I'm not familiar with ios at all – but seeing for Android we use `fastlane/metadata/android/*` I'd conclude there's `fastlane/metadata/ios/*` for that. You've got a lot of resources outside the OS specific directories – so would one more really hurt that much? I'd even go as far as to say it would make your deployment easier if you can use Fastlane for Play, F-Droid and Apple :wink:

**Comment by saghul** [comment] 2020-10-07 12:15
Sorry @IzzySoft I just don't have the time bandwidth to deal with this right now. We have a system that works, and changing it requires we verify our build system keeps on working, etc.

We have no plans to put the changelogs as part of the repo. They live here: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-APPS.md

**Comment by IzzySoft** [comment] 2020-10-07 13:07
OK, understood the time & bandwidth part (so maybe if someone prepares that as PR, it might be acceptable?). As for build: It's just metadata. Like placing a `foo.txt` in the root, placing the `fastlane` directory there should not affect the build at all (unless your build process walks every directory in the root and wants to do womething with it).

Again: no pressure. I was just pointing out the correct locations again and mentioning possible advantages. Up to you whether you want to support this or not. F-Droid would definitely welcome it – but if it's not there, there are simply no screenshots etc at F-Droid, no other "consequences".

Thanks for looking at it – and all the best for the project!

**Comment by PanderMusubi** [comment] 2021-07-21 05:51
This is still a valid issue.

**Comment by PanderMusubi** [comment] 2022-01-09 07:01
This is still a valid issue.

**Comment by saghul** [comment] 2022-01-09 09:08
Our graphics are not screenshots but generated with mock-ups now, closing.

**Closed by saghul** 2022-01-09 09:08 UTC
Labels: feature-request

**Comment by PanderMusubi** [comment] 2022-01-09 09:45
Thanks for the explanation. ☺

**Comment by IzzySoft** [comment] 2022-01-09 11:23
Just as a note: You've placed the `fastlane` directory inside `android`. It won't be found there by F-Droid, which requires it to be at the top-level (i.e. the "root" of the repo). So the issue is not yet solved concerning the "for F-Droid" aspect – as F-Droid won't pick it up from its current location.
