### ISSUE TITLE
startWithVideoMuted does not work anymore

### ISSUE THREAD

**Issue by afle** [jitsi/jitsi-meet#8632] opened 2021-02-17 08:46 UTC
### Description:

Since upate to jitsi-meet 2.0.5390-3 video muted does not work anymore.

### Steps to reproduce:

/etc/jitsi/meet/config.js
```
    // Every participant after the Nth will start video muted.
    startVideoMuted: 0,

    // Start calls with video muted. Unlike the option above, this one is only
    // applied locally. FIXME: having these 2 options is confusing.
    startWithVideoMuted: true,
```

### Expected behavior:

Video should be muted when joining a conference.

### Actual behavior:

Every participiant of a conference starts with enabled camera and video.

### Server information:

- Jitsi Meet version: 2.0.5390-3
- Operating System: Debian 10

### Client information:

- Browser / app version: Chrome 88
- Operating System: Windows 10

**Comment by saghul** [comment] 2021-02-17 12:23
Duplicate of https://github.com/jitsi/jitsi-meet/issues/8144

**Closed by saghul** 2021-02-17 12:23 UTC
