### ISSUE TITLE
How do I change bandwidth / resolution

### ISSUE THREAD

**Issue by TheNomad11** [jitsi/jitsi-meet#1313] opened 2017-02-13 00:43 UTC
Is there a way to change the bandwidth used during a video call? The currently used bandwidth is too high for my shaky connection. I was digging around the code but could not find any settings. Is there a way to do use less bandwidth? Thanks!

**Comment by saghul** [comment] 2017-02-13 08:05
Hi! The is currently son setting for this. It adjusts dynamically based on network conditions and will grow to about 3.2Mbps upstream for a 720p stream. Downstream is even harder to predict, but will be generally limited by 2.5Mbps + 0.2Mbps * numberOfThumbnails.

**Comment by TheNomad11** [comment] 2017-02-13 11:00
Hi and thanks for your reply. Any chance that there will be a setting in the future? For example on 3G I might have a good connection here most of the time. But that does not mean that I'd like to burn my whole monthly data on a single video call. I installed Jitsi because it says it is low bandwidth, but this does not seem to be the case?

**Comment by saghul** [comment] 2017-02-13 11:13
Thanks for your feedback. The mobile applications are still in their infancy, so this is something we might consider to add along the way.

**Comment by TheNomad11** [comment] 2017-02-13 12:25
Thanks, good to know. I'd prefer a server side implementation, though, rather than an app setting. The connections in the region where I am are not always that stable, so for these cases, a setting with a maximum bandwidth as suggested on the default jitsi meet start page would be better:

> Multi-party video conferences work with as little as 128Kbps. Screen-sharing and audio-only conferences are possible with far less.

**Comment by pastk** [comment] 2017-03-08 22:24
I second that.
I just tried jitsi video conferencing while on mobile connection and it uses too much data so that I can't afford it for regular use on my data plan. Resolution / quality control like e.g. implemented in google hangouts would be a nice addition.

**Comment by bubomancer** [comment] 2017-04-14 06:15
I would also like this option.  Perhaps a workaround would be to manipulate the network quality signals (which would then in turn adjust the resolution and quality), but I am not sure if that is possible.

**Comment by Gummikavalier** [comment] 2017-05-04 14:19
@saghul Looks like that latest from the testing repo has enabled automatic bandwidth limitation.
Is it possible to change limits manually in the code or config somewhere?

Trouble is that by default Firefox has approximately 2.5 times higher bandwidth usage than Chrome (higher resolution and higher fps I think), and the limitation now kicks in with Firefox regardless of capacity of networks.

Stable version has no issues.

**Comment by gpolitis** [comment] 2017-05-04 16:19
> Trouble is that by default Firefox has approximately 2.5 times higher bandwidth usage than Chrome (higher resolution and higher fps I think), and the limitation now kicks in with Firefox regardless of capacity of networks.

Are you talking about overall bandwidth usage for the call? Are you talking about outbound or inbound traffic? How are you testing this? I'm asking all these questions because FF and Chrome outbound traffic should be comparable. However, FF doesn't support simulcast, so calls with FF will tend to consume more overall bandwidth than Chrome.

**Comment by Gummikavalier** [comment] 2017-05-05 05:15
> Are you talking about overall bandwidth usage for the call? Are you talking about outbound or inbound traffic? How are you testing this? I'm asking all these questions because FF and Chrome outbound traffic should be comparable. However, FF doesn't support simulcast, so calls with FF will tend to consume more overall bandwidth than Chrome.

Ok. Lack of simulcast could be very well be the most significant part of the problem...

For the measuring I was just using the bit-rate counter directly in the interface of jitsi-meet. If that counter should be trusted, Firefox and LG 720p webcam creates traffic ranging from 2 Mbps up to 4 Mbps, per direction. Both inbound and outbound bit-rate counters show approximately this same figure.

I'll check directly from the server what it shows as the total figure, first with Chrome and then Firefox, and report back.

**Comment by Gummikavalier** [comment] 2017-05-05 11:03
@gpolitis 

Here are 'dstat -n' values looking from our testing server.

Dstat shows in KBytes, converted to Kbits by multiplying it by 8 (--bits parameter didn't work).
Microphones were muted in web UI to prevent looping sound.
One on one sessions. No other use on the server. New p2p features are off.

```
**Jitsi-meet 1.0.2049-1 (testing)**

Firefox 53 to Firefox 53
On one client message: "video has been turned off to save bandwidth" appeared.
Note that this end shows 
-net/total-
 recv  send
 345k  298k	= 2760 Kbps / 2384 Kbps
 343k  291k
 357k  302k
 355k  306k
 338k  304k

During testing I saw that usage spiked to 3440 Kbps according to jitsi-meet bit-rate, but it does not always get cut with "save bandwidth message" when that happens.

Chrome 58 to Chrome 58
-net/total-
 recv  send
 237k  190k	= 1896 Kbps / 1520 Kbps
 227k  181k
 238k  191k
 243k  192k
 230k  184k
```

Jitsi-meet 1.0.1622-1 (stable) values are comparable, but only testing cuts the video to save bandwidth.

**Comment by gpolitis** [comment] 2017-05-05 15:30
I trust dstats more than the stats in our UI: It looks like FF receivers show the wrong values in the UI. We don't know whether the problem is in FF reporting the wrong values or in our code messing the values up somehow.

About the "video has been turned off to save bandwidth", sorry about that, that's yet another issue with FF. Recently we've enabled adaptive bandwidth control which shapes what the bridge is sending to the connected endpoints, based on the available bandwidth towards a specific endpoint. The problem is that FF doesn't react to our bandwidth probing, so once the bandwidth estimation in the bridge drops, it doesn't ramp back up. We're going to disable this functionality in FF, until we figure out what's wrong.

**Comment by Gummikavalier** [comment] 2017-05-08 08:02
Good to know and thanks! I'll keep testing new versions... :)

**Comment by saghul** [comment] 2017-05-08 08:43
FWIW, @TheNomad11 @pastk @bubomancer the mobile apps now have an audio-only mode, which will save bandwidth since no video will be sent / received. You can enable this mode with the telephone looking icon on the side toolbar.

**Comment by gi11es** [comment] 2017-05-09 09:54
Having control over the quality you send, like hangouts does, is an essential feature. At the WMF we do a lot of hangout calls and it's very common for us to ask a participant to lower their quality because they're choppy. Going audio-only is the last resort.

Today I gave Jitsi Meet a spin with a couple of colleagues and we were desperately looking for that feature because we were running into that exact problem. One of us was coming up choppy to others and there was nothing we could do about it, besides that person going audio-only.

The automated quality management is fine, up to a point. You need a way to manually override it on the spot for these situations.

**Comment by MariasStory** [comment] 2017-05-09 11:17
Hi @gi11es, try https://conf-huugl.rhcloud.com
I am interested to know your experience.
Sorry, no turn for free ;-).

**Comment by Gummikavalier** [comment] 2017-05-24 14:42
@gpolitis Reporting back that I haven't had problems with Firefox showing overly high bitrates or cutting the video with any of the versions after Jitsi-meet 1.0.2049-1.

Server end shows the same dstat figures as earlier, but Firefox/Jitsi-meet stays at ~1300 Kbps.

Thanks for the save bandwidth button too. :)

**Comment by redgrasss** [comment] 2017-11-20 12:43
Being able to set the bitrate would be awesome! If I have would ingest a high quality video feed for the host it would be great to set a suitable bitrate!

**Comment by jacq0123** [comment] 2018-01-14 10:27
Hi all,
I have another question related to bandwidth saving as well. 
As of now, if a user is connected to the meeting, via the mobile App, the camera of the mobile device stays ON during screen-sharing and a huge amount of bandwidth is wasted. This is contrary to the "Low Bandwidth" declaration of far less than 128 kbps for screen-sharing.
Is it possible to configure Jitsi in a way that it will automatically turn OFF the cameras on  participants' mobile devices, when the screen-sharing is activated, and will turn them back ON when the screen-sharing is over?
Thanks

**Comment by saghul** [comment] 2018-01-15 08:39
> As of now, if a user is connected to the meeting, via the mobile App, the camera of the mobile device stays ON during screen-sharing and a huge amount of bandwidth is wasted. This is contrary to the "Low Bandwidth" declaration of far less than 128 kbps for screen-sharing.
> Is it possible to configure Jitsi in a way that it will automatically turn OFF the cameras on participants' mobile devices, when the screen-sharing is activated, and will turn them back ON when the screen-sharing is over?

I'm not sure I follow. The mobile apps don't implement screen-sharing, they can of course see one, but not share their own. Why would you want to tun off your camera when another user is sharing their screen?

**Comment by jacq0123** [comment] 2018-01-15 09:08
Hi,

I had one connection to the meeting using the Android App and another connection from the desktop. During screen sharing, the download bandwidth from the server to the desktop was about 1600 kbps. When I turned the camera OFF on the Android App, that download bandwidth became 24 kbps. My point is that the extra bandwidth, consumes by the video of the mobile App, not needed/viewed during screen sharing, is a wasted bandwidth. So, is there a way to auto prevent transmitting the video, from mobile App, during screen sharing?

Thanks.

________________________________

**Comment by saghul** [comment] 2018-01-15 09:52
> My point is that the extra bandwidth, consumes by the video of the mobile App, not needed/viewed during screen sharing, is a wasted bandwidth.

That's just your opinion :-) I might be sharing a window or a full screen, but I could see you in a different screen, to see if you were paying attention or not.

> So, is there a way to auto prevent transmitting the video, from mobile App, during screen sharing?

No, there isn't. And since we cannot guess what the user really wants, I don't think we'd implement it.

**Comment by jacq0123** [comment] 2018-01-15 10:03
Thanks for the information. You do have an option for the moderator to mute a given participant or kick him/her out. Could the option to turn OFF the video been added to that as well?

Thanks again.

________________________________

**Comment by saghul** [comment] 2018-01-15 10:27
It could! Are you up for writing a patch?

**Comment by jacq0123** [comment] 2018-01-15 10:34
I'm not capable of doing it. If I had the knowledge I will be glad to.


________________________________

**Comment by jacq0123** [comment] 2018-01-18 09:31
HI Saghul,
For my applications, I don't need/want the videos of non moderator users to transmit during screen sharing.  Do you know who I can pay to write a patch to turn OFF the cameras (App included) of all the users, except the moderator, when he/she is sharing the screen?

**Comment by saghul** [comment] 2018-01-18 10:35
Sorry, I don't.

**Comment by saghul** [comment] 2018-01-18 10:37
I think it's time to close this. We currently have automatic bandwidth management, with the ability of doing manual intervention by using the quality control slider.

Anything other than this should be opened as a new issue.

**Closed by saghul** 2018-01-18 10:37 UTC
Labels: project:react-native
