### ISSUE TITLE
Unable to access my camera

### ISSUE THREAD

**Issue by Marce2020** [jitsi/jitsi-meet#5448] opened 2020-03-28 18:05 UTC
Unable to access my camera when I start a video conference

**Comment by neilzone** [comment] 2020-03-28 20:10
I doubt there's much anyone can do with this as it stands — if you were to list:

 - browser and version
 - operating system
 - any errors showing in your browser's console

that might help.

**Comment by alexanderadam** [comment] 2020-03-31 08:11
Most probably a duplicate of #5425.
Please test it on https://test.webrtc.org and report your at #5425.

**Closed** 2020-05-12 13:32 UTC
Labels: duplicate
