### ISSUE TITLE
install-letsencrypt-cert.sh fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by msplival** [jitsi/jitsi-meet#6502] opened 2020-04-30 17:59 UTC
I am following instructions from README.md to install Jitsi on my server.

I am using Ubuntu 20.04 as a host.

When I try to run /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh, as per suggestions, I get this error:

Package python-virtualenv is not available, but is referred to by another package.

E: Package 'python-virtualenv' has no installation candidate

**Comment by luixxiul** [comment] 2020-05-01 04:58
I think you should avoid the script since it depends on the old `certbot` and it would not be able to make it renew the certificate later when you'll need to do so. Instead I would use the official package.

Since you are on Ubuntu, you would follow https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04 to set up Nginx with Let's Encrypt on Ubuntu 18.04.

If you use apache, see: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-18-04

These are the script you could use on *Debian*:

````
sudo printf "deb http://deb.debian.org/debian stretch-backports main contrib non-free\n" | sudo tee -a /etc/apt/sources.list > /dev/null
sudo printf "deb-src http://deb.debian.org/debian stretch-backports main contrib non-free" | sudo tee -a /etc/apt/sources.list > /dev/null
sudo apt update && sudo apt install -y python-certbot-nginx -t stretch-backports
sudo apt install --only-upgrade python3-acme
sudo certbot --nginx -d example.com
````

Replace `example.com` with your own domain.

Finally, please make sure to run `sudo certbot renew --dry-run` to see if your certificate will be renewed when it should be.

**Comment by msplival** [comment] 2020-05-01 10:46
Yup, thank you for the info. I tried 18.04, and I run into the same issue.
It's not a problem to configure letsencript 'mnually', it's that the documentation is misleading - hence me opening this issue :)

**Comment by luixxiul** [comment] 2020-05-01 12:15
> I tried 18.04, and I run into the same issue.

it might not be able for me to help you fix the issue, but would you please paste the error message?

**Comment by revathskumar** [comment] 2020-05-09 11:57
Linking this comment here. https://github.com/certbot/certbot/issues/7941#issuecomment-619177149

I had the same issue and installed `certbot` via `sudo apt install -y certbot`

Then made changes to the script. 

commented out this part of downloading the `certbot-auto`

```sh
#if [ ! -f certbot-auto ] ; then
#  wget https://dl.eff.org/certbot-auto
#  chmod a+x ./certbot-auto
#fi
```

and replaced `./certbot-auto` with `certbot`.

**Comment by groodle** [comment] 2020-05-15 13:09
I have been looking at this and the issue is not with Jitsi. The issue is that there is no .deb file for python-virtualenv in the Ubuntu repository. You can see the package entry here:

https://launchpad.net/ubuntu/+source/python-virtualenv/20.0.17-1

It has an entry but no installable .deb file. This halfway state is causing the following conditional check in the `certbot-auto` script to succeed even through there is no package to install:

`  
 if apt-cache show python-virtualenv > /dev/null 2>&1; then
    virtualenv="$virtualenv python-virtualenv"
 fi
`

This is because the command `apt-cache show python-virtualenv ` fails with the following error:

`
# apt-cache show python-virtualenv
N: Can't select versions from package 'python-virtualenv' as it is purely virtual
N: No packages found
`
But returns successful status code of "0". I have opened a ticket with Ubuntu about this so hopefully the package will get added to their repo soon and resolve this issue.

**Comment by msplival** [comment] 2020-05-15 15:56
There is nothing to fix with ubuntu, python-virtualenv package is no more, python3-virtualenv replaces it. Also, installing just 'virtualenv' will install python3-virtualenv.

This is all related to Ubuntu 20.04, as there is no python2 there in main repositories (there is python2.7 from 'universe' repositories, though)

I was wrong regarding Ubuntu 18.04: there is python-virtualenv package there, which defaults to python2.7. 

So, I'd say the simplest way is to fix documentation :)

**Comment by luixxiul** [comment] 2020-05-27 02:19
Duplicate of https://github.com/jitsi/jitsi-meet/issues/6341

**Closed by luixxiul** 2020-05-27 02:19 UTC
Labels: packaging

**Comment by themeix** [comment] 2020-07-05 05:45
> I had the same issue and installed `certbot` via `sudo apt install -y certbot`
Perfect.. It worked for me too
