### ISSUE TITLE
Android Camera device no longer alive

### ISSUE THREAD

**Issue by qinyuanmao** [jitsi/jitsi-meet#2123] opened 2017-10-31 08:58 UTC
I will get this error "E/org.webrtc.Logging: Camera2Session: Error: Failed to start capture request. android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): createDefaultRequest:788: Camera device no longer alive" when I close meeting many times.

**Comment by qinyuanmao** [comment] 2017-10-31 09:04
And than I cannot connect to the camera. After kill the process I can connect to the camera again.

**Comment by saghul** [comment] 2017-10-31 10:21
What Android version and device do you have?

**Comment by qinyuanmao** [comment] 2017-10-31 13:46
My phone is OnePlus3T with Android7.1 and Huawei Mate8 with Android 7.0

**Comment by saghul** [comment] 2017-10-31 15:37
It fails on both of them? Did you grant camera permissions when prompted? Do you see video on the welcome page?

**Comment by qinyuanmao** [comment] 2017-11-01 01:10
yes it fails on both, I use it as a sdk.aar in the project, when I close the meeting sometime and I cant see the video again, the app crash with the error "E/org.webrtc.Logging: Camera2Session: Error: Failed to start capture request. android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): createDefaultRequest:788: Camera device no longer alive"

**Comment by qinyuanmao** [comment] 2017-11-02 06:48
```
view.setListener(new JitsiMeetViewListener() {
            @Override
            public void onConferenceFailed(Map<String, Object> data) {
//                Toast.makeText(MecpMeetActivity.this, "onConferenceFailed", Toast.LENGTH_SHORT).show();
            }
            @Override
            public void onConferenceJoined(Map<String, Object> data) {
//                Toast.makeText(MecpMeetActivity.this, "onConferenceJoined", Toast.LENGTH_SHORT).show();
            }
            @Override
            public void onConferenceLeft(Map<String, Object> data) {
//                Toast.makeText(MecpMeetActivity.this, "onConferenceLeft", Toast.LENGTH_SHORT).show();
                finish();
            }
            @Override
            public void onConferenceWillJoin(Map<String, Object> data) {
//                Toast.makeText(MecpMeetActivity.this, "onConferenceWillJoin", Toast.LENGTH_SHORT).show();
            }
            @Override
            public void onConferenceWillLeave(Map<String, Object> data) {
//                Toast.makeText(MecpMeetActivity.this, "onConferenceWillLeave", Toast.LENGTH_SHORT).show();
            }
            @Override
            public void onLoadConfigError(Map<String, Object> data) {
//                Toast.makeText(MecpMeetActivity.this, "onLoadConfigError", Toast.LENGTH_SHORT).show();
            }
        });
```
I use finish() at the onConferenceLeft, is that right?

**Comment by saghul** [comment] 2017-11-02 09:20
> I use finish() at the onConferenceLeft, is that right?

Yes, that shouldn't be a problem. Are you using the welcome page or do you have your own?

**Comment by qinyuanmao** [comment] 2017-11-03 00:56
I dont use the welcome page.I use your aar have the same problem on android 7.0.  I try it on android 5.1.1 it is running rigth without the problem.

**Comment by paweldomas** [comment] 2017-11-03 13:42
@saghul I can reproduce that by joining Jitsi Meet through the link "Join conversation" link in Chrome on Android (One Plus 5). But this will happen only if the app is killed. I'm trying to figure out what goes wrong, because even if the camera gets disconnected then it kind of recovers and prints camera FPS even though the local video preview is black. Also there is "Cannot read property 'parentNode' of undefined" printed in the JS console which suggests that React/RN has crashed.

**Comment by paweldomas** [comment] 2017-11-03 13:51
I think the problem is that when we're creating local video the Android  is not yet convinced that we're in the foreground and throws the disconnected error. If it happend just amoment later then things seem to work and recover from that error (not https://github.com/jitsi/webrtc/blob/062207d2f69776f11a54654c47109012986c8a17/webrtc/sdk/android/src/java/org/webrtc/Camera2Session.java#L181, but from the onDisconnected callback).

**Comment by paweldomas** [comment] 2017-11-03 15:45
It turns out we're calling GUM for video twice in that case

**Comment by saghul** [comment] 2017-11-03 16:00
Thanks for looking into it @paweldomas!

**Comment by qinyuanmao** [comment] 2017-11-08 01:04
@saghul hello,do you finish the promble?

**Comment by paweldomas** [comment] 2017-11-08 01:14
still working on it

**Comment by paweldomas** [comment] 2017-11-09 22:10
Opened a PR (almost ready): https://github.com/jitsi/jitsi-meet/pull/2149

**Comment by qinyuanmao** [comment] 2017-11-13 02:57
@paweldomas still unwork

**Comment by paweldomas** [comment] 2017-11-13 15:01
@qinyuanmao have you tried with that PR ? because it has not been merged yet to the master

**Comment by qinyuanmao** [comment] 2017-11-13 15:10
I merge the code on local，the issue is complete.thank you very much.

**Closed** 2017-11-16 14:36 UTC
Labels: project:react-native

**Comment by rajatkdhamija** [comment] 2019-04-08 20:24
how to solve it? facing it on one plus 6

**Comment by paweldomas** [comment] 2019-04-08 20:32
@rajatkdhamija what do you mean ? Those fixes mentioned above are already in the master and have been release long time ago. What app/version are you seeing this issue with ?

**Comment by rajatkdhamija** [comment] 2019-04-08 20:36
i have cloned the code about a week ago.. When i open the call screen for first time it works fine but when i disconnect the call and try re entering i see a white screen and logs show 

 E/org.webrtc.Logging: Camera2Session: Error: Failed to start capture request. android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): createDefaultRequest:1274: Camera device no longer alive

**Comment by rajatkdhamija** [comment] 2019-04-08 21:10
sorry bothering you but worked fine now...you did not mention that we need not add a jitsimeetview by ourself ..used code from you example open source and now its working fine. Thanks

**Comment by 1Ajay** [comment] 2020-12-02 07:00
I am not using the welcome page I created on my own.
I facing this issue can anyone help.

E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): cancelRequest:423: Camera device no longer alive
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:728)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1112)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:526)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:737)
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:237)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.os.ServiceSpecificException: cancelRequest:423: Camera device no longer alive (code 4)
        at android.os.Parcel.createException(Parcel.java:1956)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:393)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:93)
