### ISSUE TITLE
Very bad screen sharing quality when only two participants ( on the same network )

### ISSUE THREAD

**Issue by artknight** [jitsi/jitsi-meet#8008] opened 2020-10-29 17:14 UTC
### Description:

Screensharing has been very blurry lately, even with only two participants on the same network ( no latency )

### Steps to reproduce:

1. Run a self-hosted instance on your local network. 
2. Have two participants on the same network join a call and try to screenshare.

### Expected behavior:

The screensharing should be cristal clear given the participants and the jitsi instance are on the same network

### Actual behavior:

Screensharing has been very blurry. ( https://www.youtube.com/watch?v=6J368HqsJQE )

### Server information:

- Jitsi Meet version: 2.0.5142
- Operating System: Ubuntu Server 20.04 LTS

### Client information:

- Browser / app version: Chrome Version 86.0.4240.111
- Operating System: MacOS Catalina 10.15.6

### Additional information:

Here is a link to the thread in the jitsi community ( https://community.jitsi.org/t/bad-video-quality-of-one-way-screen-sharing-in-latest-jvb-2-0/31748 )

Is there a solution to this? I really need to get this resolved ASAP!!!

Thanks, Art

**Comment by Echolon** [comment] 2020-10-31 11:14
Please fill-out the issue template.

ASAP does not work here...

**Comment by artknight** [comment] 2020-11-02 01:26
@Echolon Would you please let me know where i can find this issue template at?

**Comment by cweiske** [comment] 2020-11-02 10:36
When you create a new bug, then the issue description is pre-filled with the template

**Comment by cweiske** [comment] 2020-11-02 10:37
Related to #6409.

**Comment by artknight** [comment] 2020-11-02 12:38
@Echolon @cweiske I have updated the description in accordance with the issue template. 

How soon as this be investigated and solved? 

PS: I am told and I quote `ASAP does not work here` ... so what does?

**Comment by heikar** [comment] 2020-11-03 13:24
I had the same problem:
A meeting with two participants in different networks with self hostet jitsi.
The audio quality was ok but the shared screen was sometimes a little bit blurry.

### Server information:
Jitsi Meet version: 2.0.4857
Operating System: Ubuntu Server 20.04 LTS

### Client information:
#### Participant 1:
Browser: Chrome
Operating System: MacOS
#### Participant 2:
Browser: Microsoft Edge (With Chrome)
Operating System: Windows 10

**Comment by pgenderson** [comment] 2020-11-06 16:24
@artknight there's no point is saying the issue needs to be resolved 'ASAP'. It's redundant info as everyone knows it needs to be resolved, if the problem isn't caused by you.

**Comment by artknight** [comment] 2020-11-06 18:41
@pgenderson I politely disagree as some issues could prioritized differently and not get resolved for months.

**Comment by jallamsetty1** [comment] 2020-11-09 16:18
This issue has been fixed on https://meet.jit.si and will available in the next release of the stable builds. Please feel free to re-open the ticket if you still see the issue after updating your deployments.

**Closed by jallamsetty1** 2020-11-09 16:18 UTC
Labels: info:feedback-needed, quality

**Comment by artknight** [comment] 2020-11-24 15:19
@jallamsetty1 do you know if the commit has been merged into master already?

**Comment by jallamsetty1** [comment] 2020-11-24 22:47
> @jallamsetty1 do you know if the fix has been merged into master already?

Yes, this has been fixed on meet.jit.si. If you are deploying your own instance, jitsi meet version 2.0.5283 should have the fix.

**Comment by umerf52** [comment] 2020-12-30 00:10
@jallamsetty1 has the fix been deployed on Docker as well?
Latest release on Docker repo is `stable-5142-4`.

**Comment by falkowich** [comment] 2021-01-19 12:13
@umerf52 Did you get any clarity in this question?

**Comment by umerf52** [comment] 2021-01-19 17:46
> 
> 
> @umerf52 Did you get any clarity in this question?

I was able to get somewhat better quality by switching to VP9 and using min:1 and max:5 for frame rate.
