### ISSUE TITLE
"startWithAudioMuted" does not work anymore

### ISSUE THREAD

**Issue by Aly-ve** [jitsi/jitsi-meet#8901] opened 2021-03-28 13:03 UTC
Good morning,

### Description:

Just updated Jitsi Meet on one of my VPS, meeting rooms stopped to begin with microphone muted by default for everyone.

### Expected behavior:

Rooms should start muted for everyone.
In my `/etc/jitsi/meet/xxx-config.js`:

```javascript
var config = {
    // ...
    startWithAudioMuted = true,
}
```

### Actual behavior:

Meeting begins with microphone activated.

### Server information:

- Jitsi Meet version: 2.0.5390-3
- Operating System: Debian 10.9

### Client information:

- Browser / app version: Firefox, Chrome, Opera, ...
- Operating System: GNU/Linux, macOS and Windows 10.

### Additional information:

Just upgrated to Debian 10.9 with a Jitsi Meet update.
It worked fine before, I checked the official documentation but nothing found about this. 

Thank you. 🙂

**Comment by saghul** [comment] 2021-03-28 13:26
Duplicate of https://github.com/jitsi/jitsi-meet/issues/8144

**Closed by saghul** 2021-03-28 13:26 UTC

**Comment by Aly-ve** [comment] 2021-03-28 13:54
Sorry, thank you @saghul
