### ISSUE TITLE
Android SDK (2.2.2) crashes when rotating screen during video call

### ISSUE THREAD

**Issue by calvinckho** [jitsi/jitsi-meet#4847] opened 2019-11-12 22:05 UTC
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
In video call, Android SDK crashes when rotating screen

## Current behavior
Rotating it in any direction will crash the app. Tried starting the call on both portrait and landscape. Then when rotating the screen, it crashes the SDK.

## Expected Behavior
It should rotate the call without any issue

## Possible Solution
---

## Steps to reproduce
I'm testing it on a Samsung S7 phone. Rotate the Android device screen from portrait to landscape during video call will crash the Activity.

# Environment details
2019-10-08 22:26:51.050 5803-5803/com.restvo.app E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.restvo.app, PID: 5803
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:139)
at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35)
at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135)
at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35) 
at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114) 
at android.os.Handler.handleCallback(Handler.java:790) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6494) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
at org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView(JitsiMeetActivity.java:105)
at org.jitsi.meet.sdk.JitsiMeetActivity.leave(JitsiMeetActivity.java:121)
at org.jitsi.meet.sdk.JitsiMeetActivity.finish(JitsiMeetActivity.java:94)
at com.capacitor.jitsi.plugin.JitsiActivity$1.onConferenceTerminated(JitsiActivity.java:64)
at java.lang.reflect.Method.invoke(Native Method) 
at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135) 
at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35) 
at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114) 
at android.os.Handler.handleCallback(Handler.java:790) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6494) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by saghul** [comment] 2019-11-13 07:32
I believe this got fixed in SDK 2.4.0, which was released a few days ago. Can you please update and test?

**Comment by calvinckho** [comment] 2019-11-13 18:29
Thanks for the quite response. I am curious, if I upgrade the android SDK to 2.4.2, does it mean I also have to migrate my project from android support to androidx?

**Comment by saghul** [comment] 2019-11-13 19:17
I think so, yeah. You can use jettifier if any dependencies you have are not compatible yet.

**Closed** 2019-11-20 23:20 UTC

**Comment by danielreuther** [comment] 2020-04-16 20:53
I received an error report with the above exception from an Android 10 device on SDK 2.7. Unfortunately, I can't tell whether it was related to screen orientation change or not since I can't reproduce the issue myself, yet.

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:139)
	at org.jitsi.meet.sdk.ListenerUtils.access$000(ListenerUtils.java:35)
	at org.jitsi.meet.sdk.ListenerUtils$1.run(ListenerUtils.java:114)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8147)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at org.jitsi.meet.sdk.ListenerUtils.runListenerMethodOnUiThread(ListenerUtils.java:135)
	... 9 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jitsi.meet.sdk.JitsiMeetView org.jitsi.meet.sdk.JitsiMeetFragment.getJitsiView()' on a null object reference
	at org.jitsi.meet.sdk.JitsiMeetActivity.getJitsiView(JitsiMeetActivity.java:106)
	at org.jitsi.meet.sdk.JitsiMeetActivity.leave(JitsiMeetActivity.java:122)
	at org.jitsi.meet.sdk.JitsiMeetActivity.finish(JitsiMeetActivity.java:95)
	at org.jitsi.meet.sdk.JitsiMeetActivity.onConferenceTerminated(JitsiMeetActivity.java:220)
	... 11 more
```
