### ISSUE TITLE
I added a new attribute to Conference and added setter but doesn't seem to change for remote users

### ISSUE THREAD

**Issue by MisMagJr** [jitsi/jitsi-meet#7414] opened 2020-07-28 07:41 UTC
I tried different ways including firing events but even the event seems to be fired only for the current user.

**Comment by Echolon** [comment] 2020-07-29 15:53
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-07-29 15:53 UTC
Labels: config, question
