### ISSUE TITLE
Unfortunately, Something Went Wrong - After following Quick Install Guide

### ISSUE THREAD

**Issue by jerrybopara** [jitsi/jitsi-meet#2184] opened 2017-11-16 14:06 UTC
Hello Friends,

I've installed Jitsi-Meet as per Quick Install Guide. I've installed it with proper subdomain & correct SSL Certificates. but when I'm trying to start meeting I'm getting an error.
                     Error - Unfortunately, Something Went Wrong.

Please have a look at Screenshot - https://www.dropbox.com/s/nnbfdt31fq2jqkq/webrtc.png?dl=0

=> As our server is running at AWS, So I've updated below parameters 
     FILE -  /etc/jitsi/videobridge/sip-communicator.properties
      org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.webrtc.ajdevdemos.com/.*
      org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=<172.31.58.181>
      org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<34.225.31.115>

Server Details: 
URL    - https://webrtc.ajdevdemos.com/
OS      - Ubuntu 14.04.5 LTS 
Server Type - AWS EC2 Instance
Followed Quick Install Guide - https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md 

Please help me to get this fixed, I'm totally new in Jitsi Setups. 
Thanks,
Jerry

**Comment by damencho** [comment] 2017-11-16 15:53
If you open the js console you will see "CONFERENCE FAILED: conference.videobridgeNotAvailable". Check why there is no bridge, is it running, is it connected. Maybe it failed healthcheck for some reason and was removed from the pool of bridges, these are stuff that can be checked in the logs.

**Comment by Ark74** [comment] 2017-12-28 04:51
Maybe be a duplicate of #1390

**Comment by twoprops** [comment] 2018-02-24 05:48
I am having the exact same symptoms as OP; sad that there's no resolution. I installed on a new, clean server by slavishly following the instructions at 
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md 
and installed an existing SSL certificate. (It should be noted that I already have other instances running that I installed a couple of years ago.)

The home page opens fine, but when I try to enter a room I get endless repetitions of the enormously informative "Something went wrong." error screen. The JS console shows repeated "CONFERENCE FAILED: conference.focusDisconnected focus.meet.sacmedoasis.com". The jitsi and nginx logs aren't helpful. In the prosody log I get repeated "Disconnecting component, <stream:error> is: <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>focus.ok does not match any configured external components</text></stream:error>" errors.

The only difference I can see between this and my working installs is that I am on Debian Jessie and the others are on Ubuntu xenial, but my feeble brain cannot figure out the problem.

Any ideas?

**Comment by damencho** [comment] 2018-02-24 06:02
Apparently, there is not jicofo, have you checked jicofo logs?

**Comment by twoprops** [comment] 2018-02-24 06:10
Thanks for the quick comment!

The jicofo log is a steady stream of "host-unknown" errors:

````
Jicofo 2018-02-23 22:04:58.128 WARNING: [1104] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve auth.ok</text></stream:error>
````
Alas, that means nothing to me: I don't know which host is "unknown," particularly as the DNS configuration is exactly the same as on a working install.

**Comment by damencho** [comment] 2018-02-24 06:22
Jicofo tries to connect to prosody using domain auth.yourdomain and it fails as prosody answers host-unknown. 
The domain used by jicofo is in /etc/jitsi/jicofo/config (JICOFO_AUTH_DOMAIN=) and you can check in your prosody config /etc/prosody/conf.d/yourdomain.cfg.lua is there such a virtual domain defined.

**Comment by twoprops** [comment] 2018-02-24 06:38
Ah! For some reason, JICOFO_AUTH_DOMAIN was "auth.ok" and it should have been "auth.meet.sacmedoasis.com". The domain was correctly defined for prosody. I didn't see any errors during the install, so I'm not sure why it wasn't configured correctly. JICOFO_HOSTNAME was also set to "ok" instead of "meet.sacmedoasis.com".  Once I fixed those, everything seems to be working.

After I get some sleep, I'll see if I can figure out where the install failed.

Thanks so much for your help!

**Closed** 2018-02-24 14:19 UTC
