### ISSUE TITLE
og proprieties not working - https://ogp.me/

### ISSUE THREAD

**Issue by Sx3** [jitsi/jitsi-meet#6450] opened 2020-04-29 06:17 UTC
When we post our jitisi meet server url on a chat like (rocket-chat) is is not showing the **og:image** property correctly (https://ogp.me/) also same for https://meet.jit.si/ url too
Also for our server it is showing _"TURN Server (https admin connection)"_ instead of the **og:description**

![image](https://user-images.githubusercontent.com/3599933/80565751-ea1a7880-8a0e-11ea-83db-5529eb4895cb.png)

any directions ?

**Comment by felix-voicehub** [comment] 2020-04-29 07:54
You would have to check the `og:PROPERTY` properties in the header of that page. It seems like the favicon is linked with the wrong type (missing `type="image/x-icon"`). In any case, https://github.com/jitsi/jitsi-meet/blob/master/index.html is the file you want to modify. See https://ogp.me/ for a list of all properties.

**Comment by luixxiul** [comment] 2020-05-17 18:01
It seems Rocket.Chat fetches the icon image that is referred to the root of its own, not that of Jitsi instance.

![Clipboard01](https://user-images.githubusercontent.com/3362943/82155961-f7858e80-9867-11ea-8d2e-902fa6590305.png)

And see:

https://github.com/jitsi/jitsi-meet/blob/f94db0da2cc429e62fdbcb879b0f1acf2b45a8d4/title.html#L3
https://github.com/jitsi/jitsi-meet/blob/f94db0da2cc429e62fdbcb879b0f1acf2b45a8d4/title.html#L8

**Comment by luixxiul** [comment] 2020-05-17 18:49
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fmeet.jit.si

> Provided og:image URL, images/jitsilogo.png?v=1 was not a valid URL.

Also see: https://stackoverflow.com/a/9858694

So this is a bug of Jitsi.

**Comment by luixxiul** [comment] 2020-05-23 06:34
I'm going to close this as duplicate of https://github.com/jitsi/jitsi-meet/issues/6031.

**Closed by luixxiul** 2020-05-23 06:34 UTC
Labels: confirmed
