### ISSUE TITLE
Add official support for Matomo

### ISSUE THREAD

**Issue by ludovicm67** [jitsi/jitsi-meet#6411] opened 2020-04-27 12:19 UTC
**Is your feature request related to a problem you are facing?**
For the moment only Google Analytics and Amplitude are supported for analytics purposes, because it's the ones that are/was used in the meet.jit.si instance (see https://github.com/jitsi/jitsi-meet/issues/4170#issuecomment-489046092).
One other solution that is commonly used is [Matomo](https://matomo.org).

**Describe the solution you'd like**
It could be nice to have an implementation to support Matomo for analytics, as suggested in some comments in #4590 and #4170.
The implementation should expose following API [react/features/analytics/handlers/AbstractHandler.js](https://github.com/jitsi/jitsi-meet/blob/master/react/features/analytics/handlers/AbstractHandler.js).

Examples of already implemented analytics solutions:
 - Google Analytics: [react/features/analytics/handlers/GoogleAnalyticsHandler.js](https://github.com/jitsi/jitsi-meet/blob/master/react/features/analytics/handlers/GoogleAnalyticsHandler.js)
 - Amplitude: [react/features/analytics/handlers/AmplitudeHandler.js](https://github.com/jitsi/jitsi-meet/blob/master/react/features/analytics/handlers/AmplitudeHandler.js)

**Comment by saghul** [comment] 2020-04-27 15:37
We don’t have the intention to use Matomo ourselves at least for now, but a PR adding support for it would be most welcome!

**Comment by ludovicm67** [comment] 2020-04-27 20:28
@saghul I'm working on a implementation and will do a PR soon for that.

**Comment by MagicFab** [comment] 2020-05-06 14:13
@ludovicm67 is there any progress  ? I'd be interested in testing this and I can help with documentation and localization too.

**Comment by ludovicm67** [comment] 2020-05-06 14:54
@MagicFab yes, my [PR](https://github.com/jitsi/jitsi-meet/pull/6434) was merged ~1h ago.

The Matomo endpoint and the Matomo site id needs to be configured here:

https://github.com/jitsi/jitsi-meet/blob/bdd129b9a2c6d98d384e6e53eeb2e33ec8a183cf/config.js#L374-L376

Will have some more additional work to do to make it customizable using environment variables when using docker images (see https://github.com/jitsi/docker-jitsi-meet/issues/529).

**Comment by saghul** [comment] 2020-05-06 15:50
Oops, forgot to close this one. Thanks @ludovicm67 for the work!

**Closed by saghul** 2020-05-06 15:50 UTC

**Comment by tcurdt** [comment] 2020-12-16 23:05
Is there some further documentation on this?

I've configured the Matomo endpoint and the site but I am seeing

```
Logger.js:154 2020-12-16T22:38:37.726Z [JitsiMeetJS.js] <Object.init>:  Analytics disabled, disposing.
Logger.js:154 2020-12-16T22:38:37.726Z [modules/statistics/AnalyticsAdapter.js] <Object.dispose>:  Disposing of analytics adapter.
Logger.js:154 2020-12-16T22:38:37.736Z [modules/statistics/AnalyticsAdapter.js] <Object.dispose>:  Disposing of analytics adapter.

```
in the console.

Could this caused by `disableThirdPartyRequests`?
