### ISSUE TITLE
Jitsi meet chat button

### ISSUE THREAD

**Issue by sriranjani18** [jitsi/jitsi-meet#6994] opened 2020-06-09 16:41 UTC
Would like to customize chat button behavior... Where can I find the code for chat button listener, that opens the sliding panel? 
Thank you

**Comment by Echolon** [comment] 2020-06-09 18:56
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

We have a high income of new issues and need to manage this. Therefore I will close this issue.

Anyway we are very happy about contributions!

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-06-09 18:56 UTC
Labels: quality

**Comment by sriranjani18** [comment] 2020-06-10 03:46
Thank you
