### ISSUE TITLE
Can not invoke a special subdirectory in /usr/share/jitsi-meet

### ISSUE THREAD

**Issue by woweil** [jitsi/jitsi-meet#7529] opened 2020-08-14 11:48 UTC
Hallo everyone;

I want to use on the same machine owncloud.
So I extracted the owncloud-archive in /usr/share/jitsi-meet/owncloud
This is the Document_root from the regarding config file.
But jitsi interprets the expression as a new room.
Can I prevent this behaviour. If yes, how can I create a new room by an alternative way?

Man thanks and regards!
Wolfram

**Comment by woweil** [comment] 2020-08-14 12:15
I have found a solution for preventing to create new rooms in a restricted way:
https://community.jitsi.org/t/can-i-prevent-creation-of-rooms-other-than-a-pre-authorised-list/25041
But I cannot invoke the subdirectory owncloud. I only see a white page.
So I ask, if there is a solution, to invoke subdirs in the rootdir.

Regards
Wolfram

**Comment by Echolon** [comment] 2020-08-14 17:36
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-08-14 17:36 UTC
Labels: packaging, question
