### ISSUE TITLE
Toggling screen sharing multiple times makes it impossible to disable

### ISSUE THREAD

**Issue by Gkleinereva** [jitsi/jitsi-meet#7818] opened 2020-09-30 22:22 UTC
### Description:

Turning screensharing on, turning it off, then turning it back on again results in the user no longer being able to turn screensharing off or start their camera in the current https://meet.jit.si/ instance.

### Steps to reproduce:

1. Navigate to https://meet.jit.si/ and begin a new meeting
2. Turn on screensharing, wait to see your screen
3. Turn off screensharing, wait to see your face
4. Turn on screensharing
5. You will now not be able to turn off screensharing, and you won't be able to turn on your camera in the corner.  Each time you try to turn off screensharing, you will get the console error shown below

### Expected behavior:

Screensharing should be togglable by all users on a meeting at all times

### Actual behavior:

Screensharing cannot be turned off after it is turned on a second time in a meeting by a single user.  This console error appears each subsequent time the user presses the 'Share Screen' button:
![JitsiConsoleError](https://user-images.githubusercontent.com/23621633/94745058-df05a480-032e-11eb-9c6a-3c5c22de5624.png)

Additionally, the user will be unable to start their camera after this happens.

### Server information:

- Jitsi Meet version: I believe 4425.1043.  It's the version meet.jit.si is operating as of me writing this
- Operating System: meet.jit.si instance

### Client information:

- Browser / app version: Reproduced in Chrome and Edge
- Operating System: Windows

### Additional information:

My colleague and I have been using meet.jit.si for years, and this is the first time we are encountering this problem.  We screenshare frequently, so I'm positive it's a relatively new issue.  Though I can't pinpoint an exact date, yesterday was the first day we observed the problem and I'm almost positive screensharing was working correctly as of ~2 weeks ago.

**Comment by saghul** [comment] 2020-10-01 08:00
Ping @jallamsetty1

**Comment by jallamsetty1** [comment] 2020-10-01 14:14
@Gkleinereva, I am not able to reproduce this on Windows 10 with Chrome and Edge. What version of Chrome are you using and also is there a specific application window that reproduces this issue reliably ?

**Comment by Gkleinereva** [comment] 2020-10-01 16:40
Hey Jaya @jallamsetty1 - thanks for looking into this!  In hindsight, I think it is likely an issue with my camera.  I was not able to reproduce the issue on my laptop.  This started when my partner mentioned "Screen sharing sometimes doesn't work", and in my research I encountered the problem.  She is also unable to reproduce this exact issue on her machine, but has experienced some inconsistent behavior with screen sharing.  If we find a specific reproducible issue across machines, I'll open another issue.  Sorry to bother you!  I've included answers to your questions below for reference, but I think we can close this.

#### Chrome Version
I'm using the Official 64-bit build of 85.0.4183.121

#### Specific Application Window
I'm not exactly sure what you mean by this question?  I have a meet.jit.si link open in a chrome tab (e.g. https://meet.jit.si/ElderlyPacksGuideOnly), and the issue happens consistently on both my machine and my partner's.

**Comment by jallamsetty1** [comment] 2020-10-01 19:17
> Hey Jaya @jallamsetty1 - thanks for looking into this! In hindsight, I think it is likely an issue with my camera. I was not able to reproduce the issue on my laptop. This started when my partner mentioned "Screen sharing sometimes doesn't work", and in my research I encountered the problem. She is also unable to reproduce this exact issue on her machine, but has experienced some inconsistent behavior with screen sharing. If we find a specific reproducible issue across machines, I'll open another issue. Sorry to bother you! I've included answers to your questions below for reference, but I think we can close this.
> 
> #### Chrome Version
> I'm using the Official 64-bit build of 85.0.4183.121
> #### Specific Application Window
> I'm not exactly sure what you mean by this question? I have a meet.jit.si link open in a chrome tab (e.g. https://meet.jit.si/ElderlyPacksGuideOnly), and the issue happens consistently on my machine (Windows 10, custom build, 64 bit, chrome, USB camera, dual monitor).

Thank you, I was trying to understand your setup and if it happens with a specific application that you are trying to share. Are you trying to share the entire screen, application window or a tab ? Also is this window on a monitor different from where the conference is running ?

**Comment by Gkleinereva** [comment] 2020-10-01 19:30
#### >Entire screen, application window, or tab
Ahh I see.  Originally, I only observed the issue was when I was sharing an entire screen.  I just tried with a chrome tab and with a specific application.  I hit the same issue once just now when I was sharing an application (VS Code), but I could NOT reproduce the issue again with screen sharing (despite reproducing it ~15 times consistently yesterday and earlier today).  Who knows...maybe a glitch in the matrix.

#### >Which monitor
I reproduced it on both monitors consistently yesterday and this morning.  As I said, I'm not seeing it now so who knows.

**Comment by jallamsetty1** [comment] 2020-10-01 20:26
Next time when this happens, will you be able to grab the full console logs for us ? Thanks !

**Comment by Gkleinereva** [comment] 2020-10-01 20:36
Yes, can do!  I'll make a habit of doing that if I notice anything else wonky as well.  Thanks for your help Jaya  :)

**Comment by Gkleinereva** [comment] 2020-10-09 16:40
Hey Jaya - we've been experiencing quality issues with meet.jit.si and I want to run a few ideas by you if you don't mind.  

The call quality issues appear to be intermittent and occur even when both participants have (ostensibly) good internet connections.  Oftentimes, Jitsi reports my estimated upload bandwidth in the range of ~200 kbps even though a charter speed test reports an upload speed of ~11000 kbps.  I'm typically talking to my friend/colleague Tracy who lives on the opposite side of the country, but also has a good internet connection.  She observes similar inconsistencies with call quality, strongly correlated with the current upload bitrate reported by Jitsi.  Often times, the resolution drops too low to productively share screens.  Yesterday it was bad enough for us to switch to zoom where we did not experience the same issues with call quality

We're using the meet.jit.si instance (iframe API), and for the reasons above, I have a haunch that the bottleneck is the server(s) for the public instances.  Does that sound right to you?  Thus, we're thinking we should stand up our own instance of Jitsi to have better consistent call quality.  I know there are a ton of factors in play here (few of which I thoroughly understand), but I wanted to see if you thought having a dedicated server would solve our problems.  

I've attached the console log from a call today where we were experiencing similar problems, as well as a log downloaded from the 'Save logs' button under Tracy's connection information tab if they're of any assistance.  Thanks for your help/patience  :)
[jitsiCallInfoLog.log](https://github.com/jitsi/jitsi-meet/files/5356283/jitsiCallInfoLog.log)
[jitsiLog.log](https://github.com/jitsi/jitsi-meet/files/5356285/jitsiLog.log)

**Comment by Gkleinereva** [comment] 2020-10-09 16:42
We were also curious what the optimal upload bitrate is for 720p video.  I saw the zoom/jitsi comparison video, and it looks like jitsi performs well with an upload bitrate of 500 kbps.  Do you know what jitsi would consider 'optimal'?

**Comment by Gkleinereva** [comment] 2020-10-14 17:30
Hey Jaya @jallamsetty1 - Any chance you have a moment to consider this course of action?  I don't mean to bother you and I know I'm being a choosing beggar, but we'd really like to resolve our jitsi issues soon.  Thanks!

**Comment by jallamsetty1** [comment] 2020-10-14 20:31
Hi @Gkleinereva, I was out the last 2 days and hence the delay :) If you are doing 2 person conferences on Chrome, then you will be bypassing JVB and won't be affected by load on meet.jit.si unless your clients are sitting behind a firewall and are not able to discover each other, in that case media will be routed through our TURN servers. Please note that, when Firefox and Safari clients are involved, the media is routed through the JVB always, even for 2 participant calls. So there is a chance that your 2 person calls can be affected by the load on meet.jit.si. I would definitely recommend you to host your own dedicated server.
We have configured a max. bitrate of 1500 Kbps for 720p streams on our infrastructure which should be optimal for HD video. Browser automatically adjusts the quality of the video uploaded based on the uplink b/w available, you will start seeing drop in framerate or quality at around 500 Kbps and browser will start switching to a lower resolution when uplink is less than that value.
Thank you for the logs but I didn't anything out of the place that would explain the issues with video quality. In a direct call, it is up to the browser to estimate the b/w between the sender and receiver and we have no control over that.

**Comment by Gkleinereva** [comment] 2020-10-14 21:58
Thank you so much @jallamsetty1.  Sorry to bother you while you were gone.  We'll start work on standing up our own server.  I don't remember if the call that I screenshotted below was having quality issues, but it looks like it was indeed marked p2p.  I'll keep an eye on that indicator when we have issues in the future.  Thanks again!

![ESKJitsiCallConnectionInfo](https://user-images.githubusercontent.com/23621633/96049594-185d0a80-0e2d-11eb-81ec-a0c4d53633bd.png)

**Comment by jallamsetty1** [comment] 2021-01-13 20:51
Closing the issue since the issue hasn't been seen since the initial report. Please feel free to reopen if its still happening.

**Closed by jallamsetty1** 2021-01-13 20:51 UTC
Labels: meet.jit.si, ui/ux
