### ISSUE TITLE
Brave iOS toolbars don't collapse when the webpage is scrolled

### ISSUE THREAD

**Issue by iccub** [jitsi/jitsi-meet#9340] opened 2021-06-04 23:05 UTC
### Steps to reproduce:

1. join a together.brave.com call with 8+ people
2. Scroll down and up
3. Notice that toolbars don't hide

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by stephendonner** [comment] 2021-06-08 01:14
Do you happen to still have a screenshot of this you can attach, @iccub?  Also, you say Brave iOS toolbars, so are we sure this is an issue for the Jitsi / 8x8 team?  (Unfortunately, it apparently takes a conference call of quite a few people, as you note, to be able to reproduce this issue.)

**Comment by iccub** [comment] 2021-06-08 09:36
Sample screenshot
![IMG_7185](https://user-images.githubusercontent.com/6950387/121161475-50e2a600-c84d-11eb-9f37-00469294060a.PNG)

the toolbars hide fine on other websites when you scroll down, i didn't check with other mobile browsers

**Comment by stephendonner** [comment] 2021-06-11 05:30
Thanks, @iccub - the 8x8 team said they're working on this, and your other filed issues 👍

**Comment by saghul** [comment] 2021-08-25 13:12
This has been fixed already. I'm not 100% sure it got deployed already, but it not, it'll be part of the next one, since the fix(es) got merged a while ago: https://github.com/jitsi/jitsi-meet/commit/9ee75038b69bb473755ecf078922a437d11b992e https://github.com/jitsi/jitsi-meet/commit/2209394d094452b22c8d33ec05d4493195164cc7

**Closed by saghul** 2021-08-25 13:12 UTC
Labels: brave

**Comment by stephendonner** [comment] 2021-09-10 18:51
Verified `FIXED` using 1.30.1 on iOS public beta 15

![Image from iOS](https://user-images.githubusercontent.com/387249/132903038-c70e206f-1434-4cec-bb66-1bae7b98ce41.png)
