### ISSUE TITLE
Mobile bug

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#3132] opened 2018-06-13 01:53 UTC
When there is a web user in the room and the room is named in Chinese, the mobile terminal cannot enter the room for the first time, but it can enter the room again through historical records. How to solve this bug?

**Comment by lyubomir** [comment] 2018-08-27 14:31
This issue sounds like a duplicate of https://github.com/jitsi/jitsi-meet/issues/3107 to me.

**Closed by lyubomir** 2018-08-27 14:31 UTC
Labels: project:react-native
