### ISSUE TITLE
Setting a custom URL does not work - iOS SDK 

### ISSUE THREAD

**Issue by amorixpod** [jitsi/jitsi-meet#7409] opened 2020-07-27 20:29 UTC
Hello there, 

Currently I'm facing an issue with the iOS SDK which is that I can't set jitsi to use my server. the only way to use my server is open the app and then change it from the inside, but I want to code it in, which I did by typing in 
        builder.serverURL = URL(string: "serverurl")
But this for some reason doesn't work! I was able to implement this perfectly on android, so I'm almost certain that I'm doing something wrong and would like your help! 
Im using the latest SDK (2.10.0 on the .plist file) and I've tried multiple SDKS and also the sample SDK implementations and none seem to work

**Comment by Echolon** [comment] 2020-07-29 15:50
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-07-29 15:50 UTC
Labels: ios, mobile, question
