### ISSUE TITLE
Event Listner

### ISSUE THREAD

**Issue by amalafortunate** [jitsi/jitsi-meet#7102] opened 2020-06-19 18:32 UTC
**How to Get the Participant name after they Join the meet.**
I am using jitsi external API, I need to get the participant name while it triggers the event listener

`api.on("participantJoined", ()=>{ });`

**Comment by Echolon** [comment] 2020-06-19 20:21
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org
Unfortunately, therefore I will close this issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-06-19 20:21 UTC
Labels: api, quality

**Comment by amalafortunate** [comment] 2020-06-20 06:06
Yeha sorry for posting there.
Ive got answer for the question myself thank you
