### ISSUE TITLE
Jitsi behaving in unexpected manner

### ISSUE THREAD

**Issue by atb00ker** [jitsi/jitsi-meet#2345] opened 2018-01-01 21:02 UTC
I have having a terrible time setting up jitsi-meet.

**Server Information**
- uname -a
    - Linux e2e-33-82.e2enetworks.net.in 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- cat /etc/lsb-release
    - DISTRIB_ID=Ubuntu
    - DISTRIB_RELEASE=16.04
    - DISTRIB_CODENAME=xenial
    - DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

**What happened?**
I did manual setup, it failed with too many errors, i tried to clean up, and found the quick setup, it didn't work. After a lot of cleaning and purging, hours later, it worked!
I connected my phone (android) and laptop (Note: They are on the same WiFi) and i was getting both video and audio. Awesome!
Next, I made a call to a superior in order to show the setup works, call connects, we are on the same call room, we can talk over messages but no call or video but as soon as everyone disconnects and it's just my laptop and phone, it starts working, when someone else connects, it fails.

I thought maybe i set it up wrong and it'll work only for two people.
So i disconnected my phone and asked someone to connect (now my laptop and the other person is not on the same WiFi), now, it fails.

But if i connect my phone and laptop again, It Works!

**logs**
Logs don't look pretty either.
prosody.log : https://hastebin.com/kebocoyari.sql
jicofo.log : https://hastebin.com/ikitesalof.nginx (Not complete trimmed due to document size limit)
I would be happy to provide any other log/information if needed.

**Note** 
I understand that this might not be the place for this, i don't completely understand the mail system, i am sending a copy of this issue to `users@jitsi.org`, please close the issue if this is not the correct place.

**Comment by damencho** [comment] 2018-01-01 21:49
For the described problem, usually the reason for it is that jvb is running on a machine without public address and/or port forwarding hasn't been setup.
Checkout https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by damencho** [comment] 2018-01-01 21:54
Will edit the manual installation instructions to warn that they are not recommended and can easily be confusing for users and that the quick install is the recommended way for doing deployments

**Comment by damencho** [comment] 2018-01-01 22:01
I just saw the jicofo logs (sorry on mobile) and I see some certificate errors 
The note about nat is valid if not configured.
But you also face the problem with jicofo, when you have 2 devices, they connect p2p, for more than two you need jicofo and the bridge, so you need to fix the jicofo errors. Manual install and then quick install can lead to problem with the auth.domain certificate. You need to check it and probably clear the trusted certs for java and update them again ... When I'm in front of a pc can give you more details.

**Comment by atb00ker** [comment] 2018-01-02 11:47
> For the described problem, usually the reason for it is that jvb is running on a machine without public address and/or port forwarding hasn't been setup.
> Checkout https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
> > Documentation here says if the machine is behind NAT, this is not the case for me. It's a static IP for the server, It is not behind NAT.
> >`sudo lsof -i` output : https://hastebin.com/ozewetaxok.rb
> > `sudo netstat -tulpn` output : https://hastebin.com/uconajekef.rb // Mosh Entry removed.
> > About the ports, According to documentation 4443 TCP port and 10000 UDP port also need to be open, i don't see them in the here, so, it this the issue? I googled and found that i need to "bind" the protocol to application, how can i do that for jvb?

**Comment by atb00ker** [comment] 2018-01-02 12:14
> You need to check it and probably clear the trusted certs for java and update them again...
> > I am a little confused, do you mean the file at `/etc/jitsi/videobridge/sip-communicator.properties` If yes, then that files seems to have the correct domain name, `org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=auth.MY_SERVER_DOMAIN_NAME/.*` Although, I don't know how would i update. If no, could you guild me to the file, please?
 
> When I'm in front of a PC can give you more details.
> > That would be very useful, thank you. :)

**Comment by atb00ker** [comment] 2018-01-02 12:27
Also, This might be useful, I noticed a file named prosody.err containing the following line: `Jan 02 00:37:16 portmanager     error   Failed to open server port 5347 on ::1, Cannot assign requested address`

**Comment by damencho** [comment] 2018-01-02 14:52
You need to change the port of prosody and also setup this in jvb and jicofo.
The listening ports you may not see them till you made a conference attempt.

**Comment by atb00ker** [comment] 2018-01-02 16:44
Do you think removing everything and reinstalling will cause the same issues again?

**Comment by damencho** [comment] 2018-01-02 19:53
Now do jicofo and jvb connect successfully on the component port ?

**Comment by damencho** [comment] 2018-01-02 19:55
If prosody is not listening on 5347 because of some other service, reinstalling will not result anything different.

**Comment by atb00ker** [comment] 2018-01-15 16:09
Apologies for late reply, I got busy with other projects, i did try to work on this, however, my problem is still unsolved, i have made some advancement, jvb is working without errors, but jicofo isn't working!

```
Jicofo 2018-01-15 20:51:58.472 SEVERE: [26] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: The followi
ng addresses failed: 'localhost:5222' failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connection refused (Conn
ection refused)
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'localhost:5222' failed because: localhost/12
7.0.0.1 exception: java.net.ConnectException: Connection refused (Connection refused)
        at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:618)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:890)
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:379)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:248)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$000(XmppProtocolProvider.java:57)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:229)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:224)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)  
Jicofo 2018-01-15 20:51:58.472 SEVERE: [26] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: The followi
ng addresses failed: 'localhost:5222' failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connection refused (Conn
ection refused)
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'localhost:5222' failed because: localhost/12
7.0.0.1 exception: java.net.ConnectException: Connection refused (Connection refused)
        at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:618)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:890)
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:379)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:248)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$000(XmppProtocolProvider.java:57)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:229)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:224)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)  

```
This is the first error from the top in jicofo.log; I think the problem is with connection of prosody and jicofo, but i am very unsure.
I am linking the output of various files i find will help you understand the problem.
If i am correct, then please guide me which password to change, otherwise, please explain the error, and how can i solve it.
Thank you!
**Outputs:**
**debconf-get-selections | grep jitsi: ** https://hastebin.com/diheqaveka.vbs
**prosody.log:** https://hastebin.com/udegetobeh.sql
**jicofo.log:** https://hastebin.com/kajipisibi.pl [TRIMMED!]
**jvb.log:** https://hastebin.com/bijehoziyu.scala
**myserver.cfg.lua:** https://hastebin.com/axulahogam.lua
**prosody.cfg.lua:** https://hastebin.com/vixowowebe.lua
**jicofo config:** https://hastebin.com/xaliduqezi.ini
**jvb config:** https://hastebin.com/qesakurena.ini

**Comment by damencho** [comment] 2018-01-15 20:11
The problem is later in the log, the connection refused is maybe prosody restarting, once it is up you can see you still have the problem with the certificates ... 
I will try testing it tomorrow to find some easy workaround...

**Comment by damencho** [comment] 2018-01-17 17:25
update-ca-certificates -f
Should fix the problem.

**Comment by atb00ker** [comment] 2018-01-17 18:51
I did `update-ca-certificates -f`, now jicofo seems to work! Thank you for that.
But while jicofo & prosody stopped throwing errors, jvb is now throwing errors.
`[921] util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[IceUdpTransportManager connect thread,5,main] and message was: java.net.UnknownHostException: e2e-33-82.e2enetworks.net.in: e2e-33-82.e2enetworks.net.in: Name or service not known`

Here are the SEVERE errors in log file of jvb: https://hastebin.com/fakisadoma.vbs
Please note that on the Archive of the mailing list, i found issues on `IceUdpTransportManager` but people facing those issues have to setup sip-communicator for NAT, In my case that is not applicable because my server has a static IP and is not behind NAT.

**Comment by damencho** [comment] 2018-01-17 19:38
Is this the jvb machine e2e-33-82.e2enetworks.net.in? Do you have an entry in hosts for it on the machine itself?

**Comment by atb00ker** [comment] 2018-08-31 10:40
Sorry, I never got around to solve the issue.
Jitsi was installed in another server for the organisation & this server is no more in that state.

**Comment by saghul** [comment] 2018-08-31 10:49
I'm going to close this then, since it has been well over a year.

**Closed by saghul** 2018-08-31 10:49 UTC
