### ISSUE TITLE
jigasi configuration for jwt

### ISSUE THREAD

**Issue by SriramScorp** [jitsi/jitsi-meet#7418] opened 2020-07-29 06:29 UTC
Jigasi dial-in, which was working with 'Secure Domain' setup, broke after switching to token authentication. What is the additional configuration required to make it work? Can you provide working example for prosody (if another virtualhost is required), jicofo (if 'org.jitsi.jicofo.auth.URL=' needs to be configured) and jigasi (whether I should add a token or use xmpp authentication)?

**Comment by Echolon** [comment] 2020-07-29 15:58
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-07-29 15:58 UTC
Labels: question
