### ISSUE TITLE
Android keyboard is overlapping the input field

### ISSUE THREAD

**Issue by sophie-kuehn** [jitsi/jitsi-meet#10128] opened 2021-10-08 09:19 UTC
### Description:

The Android keyboard is overlapping the input field.

### Steps to reproduce:

1. Join a call
2. Open the chat

### Expected behavior:

Chat input field should be visible fully.

### Actual behavior:

Chat input field is blocked.

![Screenshot_20211008-110850_1](https://user-images.githubusercontent.com/6147076/136531430-a41e280c-9f94-4e1d-847d-3594c2d0824c.png)

### Client information:

- Jitsi Meet version: 21.3.0
- Operating System: Android 11 (build RQ3A.210905.001) 
- Device: Google Pixel 5

**Comment by AjayShivanagol** [comment] 2021-10-10 04:19
when we open any default gifs or emojis then also it will completely get hidden.

![1](https://user-images.githubusercontent.com/29257275/136681802-ed945081-a930-47f9-a62e-69723cc13710.jpeg)
![2](https://user-images.githubusercontent.com/29257275/136681803-1025dfc2-bffb-49d9-a3d7-73cb8d7c536c.jpeg)

**Comment by Calinteodor** [comment] 2021-10-21 07:41
@AjayShivanagol can you test now and let us know if the issue is still present? Thank you!

**Comment by Calinteodor** [comment] 2021-12-06 13:22
No follow up, closing.

**Comment by sophie-kuehn** [comment] 2021-12-06 13:48
No new version was released to check this. Issue persists.

**Comment by saghul** [comment] 2021-12-06 14:22
Beta has been out for a while, it's currently in review.

**Comment by sophie-kuehn** [comment] 2021-12-06 20:30
Version 21.4.1 build 214010
Issue persists.

**Comment by saghul** [comment] 2021-12-07 02:37
Beta is 21.5

**Comment by sophie-kuehn** [comment] 2021-12-07 11:31
The play store was not offering me an update event though i joined the beta. Anyhow. I reinstalled the app. No change in 21.5 build 9222825.

![Screenshot_20211207-122902](https://user-images.githubusercontent.com/6147076/145021633-d115f340-2940-4bb3-bb4a-ea090d8359a8.png)

**Comment by saghul** [comment] 2021-12-07 13:49
What device and keyboard is that?

@Calinteodor PTAL when you can.

**Comment by sophie-kuehn** [comment] 2021-12-07 14:54
Operating System: Android 11 (build SP1A.211105.003)
Device: Google Pixel 5
Stock keyboard

**Comment by saghul** [comment] 2021-12-07 14:56
Thanks!

**Comment by sophie-kuehn** [comment] 2021-12-07 20:05
Made a mistake. It's Android 12 by now. Build number is correct.

**Comment by sreerags96** [comment] 2022-01-04 06:43
Issue still persists.
keyboard is overlapping the chat input field.

version: 21.5.0
build: 9488412

OS: Android 11 and 12

**Comment by AjayShivanagol** [comment] 2022-01-07 09:51
is this fixed?

**Comment by saghul** [comment] 2022-01-07 11:02
Not, it isn't. It doesn't happen on all devices so it's a tricky one to fix.

**Comment by sophie-kuehn** [comment] 2022-02-19 11:29
Looks good in 22.0.0

![Screenshot_20220219-122611](https://user-images.githubusercontent.com/6147076/154798945-c6414e9c-d9de-4204-924f-9d0283bb006c.png)

**Comment by saghul** [comment] 2022-02-19 15:09
Great work @Calinteodor !

**Comment by saghul** [comment] 2022-02-19 15:10
Hanna for confirming @sophie-kuehn , we'll be making a new release soon.

**Closed by saghul** 2022-02-19 15:10 UTC
