### ISSUE TITLE
Boken: sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh

### ISSUE THREAD

**Issue by x011** [jitsi/jitsi-meet#6878] opened 2020-05-26 20:31 UTC
`sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh`

is broken on Ubuntu 20.04

```
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
```

**Comment by yodaphone** [comment] 2020-05-26 21:54
jitsi is not yet ready for 20.04 . Please use 18.04

there are a few things that break as of now.

your problems has been solved. 
please check https://www.linuxbabe.com/ubuntu/install-jitsi-meet-ubuntu-20-04 step 3

there has been a lot of discussions around 20.04. its not worth the time installing and putting band-aids for now

https://community.jitsi.org/search?q=ubuntu%2020.04
if you use secure domain you might encounter a prosody authentication error.

**Comment by saghul** [comment] 2020-05-26 22:12
> jitsi is not yet ready for 20.04 & i dont think its a supported OS. Please use 18.04

What exactly makes you think that? The fact that a Let'ss Encrypt script doesn't work? certbot-auto doesn't work on Ubuntu 20.04, but that's about it. You can use certbot yourself no problem.

**Comment by luixxiul** [comment] 2020-05-27 02:17
Duplicate of https://github.com/jitsi/jitsi-meet/issues/6502

**Closed by luixxiul** 2020-05-27 02:17 UTC
Labels: info:feedback-needed, packaging

**Comment by luixxiul** [comment] 2020-05-27 02:18
Duplicate of https://github.com/jitsi/jitsi-meet/issues/6341
