### ISSUE TITLE
Not recording audio to YouTube livestream

### ISSUE THREAD

**Issue by ece106** [jitsi/jitsi-meet#3694] opened 2018-12-17 20:49 UTC
## Description
---
After clicking Start Live Stream & entering youtube key, the video from everyone on the livestream records to Youtube, but none of the audio from anyone's mic records to youtube. This has been a problem for several weeks.

## Current behavior
---
Audio is not sent to Youtube

## Expected Behavior
---
Audio should be sent to Youtube recording

## Steps to reproduce
---
Click 3 dots in lower right corner of live viewer
Select Start Live Stream
Enter youtube key,
Select Start Live Stream

# Environment details
---
Happens on Linux, Mac; Chrome, Firefox, and probably everything else

**Comment by virtuacoplenny** [comment] 2018-12-18 02:56
I wonder if this has to do with Chrome's latest changes about autoplay. Recording works by a fake participant joining the conference, and it could be that because the participant hasn't interacted with the site (not interacting with gum) that audio does not play. I can reproduce this in a new chrome guest session window by joining a meeting, denying getUserMedia, and reloading the page.

@bbaldino

**Comment by geekgonecrazy** [comment] 2018-12-18 18:12
This seems to also happen in the dropbox recording functionality.  Recorded a whole hour long meeting of bobbling heads 😄 

I too was using chrome, though sounds like may be something on the fake participant end not actually the regular participants?

**Comment by virtuacoplenny** [comment] 2018-12-18 19:11
If the problem is chrome's autoplay policy, and there is no confirmation so far that being the case, it really won't matter what browser you use to initiate recording. The fake participant uses chrome to join the meeting and record everything.

**Comment by ece106** [comment] 2018-12-18 20:06
No. It is definitely not chrome. We recorded on Firefox, watched on Firefox, had no chrome connected and still no audio.

**Comment by geekgonecrazy** [comment] 2018-12-18 23:45
Did some digging to understand the stack better.

As @virtuacoplenny said the recording component uses chrome.

Called jibri here is a snippet from the reader on that repo:

> Jibri provides services for recording or streaming a Jitsi Meet conference.

> It works by launching a Chrome instance rendered in a virtual framebuffer and capturing and encoding the output with ffmpeg. It is intended to be run on a separate machine (or a VM), with no other applications using the display or audio devices. Only one recording at a time is supported on a single jibri.

**Comment by virtuacoplenny** [comment] 2018-12-18 23:57
This might be fixed now in latest jibri. https://github.com/jitsi/jibri/pull/167. Someone (or me) will probably let you know (somewhere) if it has truly been fixed. I think the new version has to be built, deployed, probably verified, and some other work.

**Comment by ece106** [comment] 2018-12-19 00:02
Well I was going to try recording, but getting All streams are currently busy" again...

**Comment by virtuacoplenny** [comment] 2018-12-19 00:04
That's being worked on now from what I know. Has to do with some issues with not communicating properly with some infra hooks for scaling.

**Comment by virtuacoplenny** [comment] 2018-12-20 01:00
Okay, the audio recording issue should be fixed. It was due to chrome’s change in audio policy not being accounted for. There should also be fewer errors of recorders being busy; that fix I don’t know the details of but I think the reporting of recorder/jibri status improved so the infra has better handling of available recorders.

**Comment by ece106** [comment] 2018-12-20 02:01
It works! Thank you. You guys/ladies do fabulous important work.

**Closed** 2018-12-20 08:19 UTC
