### ISSUE TITLE
nginx vhost not correctly configured for ipv6 on port 80

### ISSUE THREAD

**Issue by gbonfiglio** [jitsi/jitsi-meet#5209] opened 2020-03-17 16:37 UTC
I'm running a full dual stack server, and in addition to https://github.com/jitsi/jitsi-meet/issues/5000 I've noticed the nginx virtual host created by default at setup time is not listening on port 80 over ipv6 - but the default one is.

This causes requests coming to the hostname I've configured over IPv4 to be correctly routed to jitsi's virtual host, requests coming over IPv6 (same hostname) going to the default one.

Fixed by adding a v6 listener in /etc/nginx/sites-enabled/DOMAIN.conf:

```
    listen 80;
    listen [::]:80;
```

**Comment by saghul** [comment] 2020-03-17 20:01
Sounds like a sensible thing to do indeed. Any chance you could submit a PR?

**Comment by gbonfiglio** [comment] 2020-03-17 20:23
I'd really love to but I spent a good 30 mins trying to understand the installer logic and could not figure it out.

Can you point me in the right direction for what's generating both nginx.conf and the vhost file in sites-enabled?

**Comment by damencho** [comment] 2020-03-17 22:12
This is nginx template we use https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example
We also do some changes dynamic when we install and config turnserver https://github.com/jitsi/jitsi-meet/blob/2dd5d0a1801eece4b74fe618fee7cdf1b486a823/debian/jitsi-meet-turnserver.postinst#L99

**Comment by gbonfiglio** [comment] 2020-03-17 22:40
thankyou - created https://github.com/jitsi/jitsi-meet/pull/5216 which fixes this one and https://github.com/jitsi/jitsi-meet/issues/5000

**Comment by ACCakut** [comment] 2020-03-27 13:16
Please put this information into the quick install readme until it is published in all packages.

**Comment by damencho** [comment] 2020-03-27 15:19
That is already in latest unstable and very soon will hit stable

**Comment by 70rc** [comment] 2020-04-04 20:51
I'm late to the party, but as the issue is still open I thought I'm gonna put this here. The fix is in place in the current stable Ubuntu/Debian package, but it seems to solve the problem only partially. After a fresh installation I still don't have IPv6 connectivity according to https://ipv6-test.com/validate.php and https://www.ssllabs.com/ssltest/ . This seems to be related to the TURN server installation. As far as I can tell, the fix correctly treats the IPv6 listeners in jitsi-meet-turnserver.postinst. However, this script also installs an additional nginx module that contains the new nginx stream listener: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.conf As can be seen in line 21, this only listens on IPv4. Adding an IPv6 listener here solves the issue for me.

Apologies if my terminology is a bit fuzzy. This is the first time I work with nginx. I'm happy to submit a PR if that helps.

**Closed** 2020-04-07 02:27 UTC
