### ISSUE TITLE
Audio slider disappears if you mute a user with the slider

### ISSUE THREAD

**Issue by fipski** [jitsi/jitsi-meet#8777] opened 2021-03-11 13:24 UTC
### Description:

If you mute a user with the volume slider, the slider disappears and you can't unmute him again.

### Steps to reproduce:

1. start conference on meet.jit.si
2. mute remote user with volume slider
3. and it's gone

### Expected behavior:

Turn the volume back up again.

### Actual behavior:

No volume slider, but microphone mute status and audio indicators still working.

### Server information:

- Jitsi Meet version: meet.jit.si

### Client information:

- Browser / app version: Version 89.0.4389.23 (Official Build) beta (64-bit)
- Operating System: Ubuntu 20.04

### Additional information:

![image](https://user-images.githubusercontent.com/37374368/110793598-1a5cb580-8275-11eb-92af-d2d96d54e8f5.png)
![image](https://user-images.githubusercontent.com/37374368/110793651-2a749500-8275-11eb-8eb1-07c1b9ffedf4.png)

**Comment by saghul** [comment] 2021-03-11 13:37
Duplicate of https://github.com/jitsi/jitsi-meet/issues/8761

**Closed by saghul** 2021-03-11 13:37 UTC

**Comment by fipski** [comment] 2021-03-11 13:42
Sorry, I only searched for open issues...
