### ISSUE TITLE
meet.jit.si: Chrome & Brave grey screen after allowing Camera / Mic access - FireFox OK

### ISSUE THREAD

**Issue by philiprhoades** [jitsi/jitsi-meet#9728] opened 2021-08-17 00:44 UTC
I am assuming this is a problem with the server source code at meet.jit.si ?

### Steps to reproduce:

1. Go to meet.jit.si
2. Start meeting
3. Click to allow access to PC's camera and microphone

### Expected behavior:

The Jitsi Meet screen is displayed

### Actual behavior:

A blank, grey screen is displayed

### Server information:

?

### Client information:

- Browser / app version:  Chrome / Brave
- Operating System:  Fedora 34

### Additional information:

Using F12 shows an empty HTML Body except for a message that JavaScript needs to be enabled (which it already is of course) - see attachment.
![2021-08-17_10-31-08](https://user-images.githubusercontent.com/1153703/129646266-647c7964-494e-43bc-a876-405bea8df7a4.png)

Happy to help debugging of course . .

**Comment by saghul** [comment] 2021-08-17 05:54
What do you see in the console tab?

**Comment by therob84** [comment] 2021-12-02 18:33
I can confirm same behaviour on **Firefox 94.0** on Linux Mint 20.2. While just seeing a grey screen the camera LED is showing up and Camera and Mic symbols are shown as actively used in Firefox.

Also with same screen of debug window as above:
![grafik](https://user-images.githubusercontent.com/15350793/144481116-a3fdda7c-4a4a-4695-a3c0-48e8fa306a7d.png)


You asked for console tab - i only show errors and warnings:
![grafik](https://user-images.githubusercontent.com/15350793/144480725-e59f0402-22b6-41c5-a706-e68423bf654f.png)

Screenshots are taken after I already disabled for this site: privacy/Aktivitätenverfolgung in Firefox shield symbol, disabled all Add-ons: FirstpartyIsolation, NoScript, µBlockOrigin. No change.

Same behaviour in **Firefox 94 and Windows 10**.

Using **Ungoogled Chromium (Version 95**.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-Bit)) everything is working as expected, but from time to time (10-30 minutes of conference) the tab is not responding anymore and has to be restartet (tested various times with https://meet.scheible.it/.)

Any hope to find the error?

**Comment by therob84** [comment] 2022-01-05 17:30
Today I again checked functionality of https://meet.scheible.it/ with Firefox **95.0.1 (64-Bit) on Linux Mint 20.2** - and **it worked!** (exactly Version of jitsi I don't know, maybe this helps (striped off the page source code?): `<script src="libs/lib-jitsi-meet.min.js?v=5675"></script>`.

Any comments why it now works? Is this issue now solved?

**Comment by saghul** [comment] 2022-01-06 09:00
Yep it must have been fixed in a later stable version. We've made a few since the original report.

**Closed by saghul** 2022-01-06 09:00 UTC
