### ISSUE TITLE
IOS SDK won't connect the conference while the containing app is in background

### ISSUE THREAD

**Issue by softavail** [jitsi/jitsi-meet#12821] opened 2023-01-24 06:43 UTC
### Description:

I use Jitsi SDK into my IOS application. 
I integrated the SDK via CocoaPods.
When my app is in background or killed, and I receive VoIP push, answer and try to connect into the conference, there is no audio in both directions.
I load JitsiMeetView into a controller and present. In viewDidLoad I configure options and invoke join with the option configured
I pass the following feature flags as well:
"prejoinpage.enabled" set to false
"call-integration.enabled" set to false

### Steps to reproduce:

- Put the app in background / kill
- Lock the screen
- Receive call via VoIP push
- Register incoming push with CallKit. Call starts ringing 
- Answer the call
- Create parent view controller containing JitsiMeetView7. 
- In controller's viewDidLoad, invoke jitsiMeetView.join( joinOptions)

### Expected behavior:

The conference to be joined and the user is able to hear remote audio and broadcast his/her local audio

### Actual behavior:

The app does not receive nor send any audio. Other can't hear me nor I can hear others

Now if I unlock the phone by clicking CallKit's Launch App button, my app brings up back in foreground 
and I immediately see that the app starts connecting into the conference. Looks like while the app is in background, the SDK doesn't even try to connect and waits for the app to enter foreground. Once this happens the conference starts connecting

### Client information:

- IOS SDK version: IOS SDK 7.0.1
- Operating System: IOS 16.1

### Additional information:
I notice that when the app is in background the JitsiMeetView's parent view controller is properly loaded and it's viewDidLoad, viewWillAppear, viewDidAppear methods are called. The SDK doesn't try to start joining the conference until the app is put on foreground.
I do not use JMCallKitProxy nor JMCallKitListener 

### Logs
I enabled SDK's logs and here are how they look like

- While the app is in background and the user answers the call I can only see the following log entries:
```
[JitsiMeetLog] '2023-01-22T13:23:47.309Z', '[modules/browser/BrowserCapabilities.js]', 'This appears to be react-native, ver: 0.68.5'
[JitsiMeetLog] Running "App
```
- After the app is put on foreground I immediately see the following log entries
```
[JitsiMeetLog] RCTStatusBarManager module requires that the UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO
[JitsiMeetLog] RCTStatusBarManager module requires that the                 UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO
[JitsiMeetLog] [features/app] appNavigate to https://dev-jitsi.myserver.com/DB93EDAE-F5D6-4E3B-846F-9B19D284EEAC#config.startWithVideoMuted=false&config.subject=%22Jitsi%20Conference%22
[JitsiMeetLog] [features/base/connection] No connection found while disconnecting.
[JitsiMeetLog] [features/app] Loaded SDK 7.0.1
[JitsiMeetLog] [features/base/net-info] Network changed {"isOnline":null,"details":{"subnet":"255.255.255.0","isConnectionExpensive":false,"ssid":null,"bssid":null,"ipAddress":"192.168.1.179"},"networkType":"wifi"}
[JitsiMeetLog] [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: null }
[JitsiMeetLog] [AudioMode] Route changed, reason: 3
[JitsiMeetLog] [features/base/net-info] Network changed {"isOnline":true,"details":{"subnet":"255.255.255.0","isConnectionExpensive":false,"ssid":null,"bssid":null,"ipAddress":"192.168.1.179"},"networkType":"wifi"}
[JitsiMeetLog] [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
[JitsiMeetLog] [features/base/lib-jitsi-meet] Config loaded from https://dev-jitsi.qamyjitsi.com/config.js?room=db93edae-f5d6-4e3b-846f-9b19d284eeac
[JitsiMeetLog] [features/base/config] Extending config with: {"startWithVideoMuted":false,"subject":"jitsi Conference"}
[JitsiMeetLog] [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
[JitsiMeetLog] [modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
[JitsiMeetLog] [features/analytics] Initialized 0 analytics handlers
[JitsiMeetLog] [features/base/media] Start muted:
[JitsiMeetLog] [features/base/media] Start audio only set to false
[JitsiMeetLog] [features/base/connection] Using service URL https://dev-jitsi.qamyjitsi.com/http-bind
[JitsiMeetLog] [modules/xmpp/xmpp.js] P2P STUN servers:  [ { urls: 'stun:meet-jit-si-turnrelay.jitsi.net:443' } ]
[JitsiMeetLog] [modules/xmpp/xmpp.js] Source-name signaling is enabled
[JitsiMeetLog] [modules/xmpp/xmpp.js] Receiving multiple video streams is enabled
[JitsiMeetLog] [modules/xmpp/xmpp.js] (TIME) Strophe connecting:     2521023848.296708
[JitsiMeetLog] [modules/RTC/RTCUtils.js] Got media constraints: {"video":false,"audio":{"autoGainControl":true,"echoCancellation":true,"noiseSuppression":true}}
[JitsiMeetLog] [modules/RTC/RTCUtils.js] Got media constraints: {"video":{"height":{"ideal":720,"max":720,"min":180},"width":{"ideal":1280,"max":1280,"min":320},"facingMode":"user"},"audio":false}
[JitsiMeetLog] [modules/RTC/RTCUtils.js] list of media devices has changed: [ { groupId: '',
[JitsiMeetLog] [modules/RTC/RTCUtils.js] Available devices:  [ { groupId: '',
[JitsiMeetLog] [modules/RTC/RTCUtils.js] onUserMediaSuccess
[JitsiMeetLog] [modules/RTC/JitsiLocalTrack.js] Setting new MSID: 6f0898d5-8ae8-5de8-d11d-62e52ef873b8 15555FCF-5390-49F7-A8A3-7024996C7818 on LocalTrack[undefined,audio]
[JitsiMeetLog] [VideoCaptureController] Capture will start
[JitsiMeetLog] [VideoCaptureController] Capture started
[JitsiMeetLog] [modules/RTC/RTCUtils.js] onUserMediaSuccess
[JitsiMeetLog] [modules/RTC/JitsiLocalTrack.js] Setting new MSID: d3381c27-001c-785c-15a8-f0b748d547f8 BB35DD5A-B004-4968-8CDB-B5447F5BAB06 on LocalTrack[undefined,video]
[JitsiMeetLog] [features/base/lastn] There is no active conference, not updating last N
[JitsiMeetLog] [features/base/redux] redux state persisted. 287197863c9e50620acff1db522f2505 -> 09478b3bd0f9e4e1c9c48446e9f2783b
[JitsiMeetLog] [modules/xmpp/XmppConnection.js] Stream resume enabled, but WebSockets are not enabled
[JitsiMeetLog] [modules/xmpp/strophe.ping.js] XMPP pings will be sent every 10000 ms
[JitsiMeetLog] [modules/xmpp/xmpp.js] (TIME) Strophe connected:     2521025254.226291
[JitsiMeetLog] [modules/xmpp/xmpp.js] My Jabber ID: b9531a01-c9db-42a4-a2e6-f124ce0321e9@dev-jitsi.qamyjitsi.com/CZgyTvDG0OLX
[JitsiMeetLog] [modules/RTC/CodecSelection.js] Codec preferences for the conference are JVB: vp8,
[JitsiMeetLog] [modules/xmpp/xmpp.js] JID b9531a01-c9db-42a4-a2e6-f124ce0321e9@dev-jitsi.qamyjitsi.com/CZgyTvDG0OLX using MUC nickname b9531a01
[JitsiMeetLog] [modules/statistics/AvgRTPStatsReporter.js] Avg RTP stats will be calculated every 15 samples
[JitsiMeetLog] [JitsiConference.js] backToP2PDelay: 5
[JitsiMeetLog] [modules/videosipgw/VideoSIPGW.js] creating VideoSIPGW 
... etc
```

**Comment by saghul** [comment] 2023-01-24 12:46
This is a duplicate of https://github.com/jitsi/jitsi-meet/issues/12303

A workaround was proposed, but nobody has dug to find the actual source of the problem.

**Closed by saghul** 2023-01-24 12:46 UTC

**Comment by softavail** [comment] 2023-01-24 15:47
@saghul Thank you for referring the original ticket. The workaround fixes the case where I pass the VoIP push as a video call, because in this case upon answer the OS unlocks the device and brings the app in foreground. By applying the workaround, unlocking happens, the app is put in foreground and the conference joins. 
Unfortunately when I receive an audio only call, I pass it to the CallKit with isVideo set to false, and in this case upon answer the IOS doesn't even try to unlock the device and the app stays in background until the user click launch app button in the call kit. While the app is in background, the Jitsi SDK does not try to connect the conference (may be waiting for the app state to become active which happens only if the user clicks launch app button )
Can you advice please

**Comment by saghul** [comment] 2023-01-24 18:05
Excellent, thank you! If there is a way to simulate this with a small sample app that would really help.

**Comment by isnaenimus** [comment] 2023-01-31 05:21
> @saghul you can ignore my last comment for audio call. I realised the problem by reading to the end #12303. I will try to put the log lines you refer, and will contribute. Let's try to understanding the real root cause. Thanks!

Hello @softavail, is there a way to simulate this with a small sample app? it helps a lot if you give an example. thanks
